### ISSUE TITLE
[Bug]: 可以评论，但是无法显示评论数，浏览量

### ISSUE THREAD

**Issue by qianyan98** [walinejs/waline#1010]
### 问题描述 | Describe the bug

为了使用waline管理页面上的用户管理，将waline客户端升级到3.0.1版本后，导致博客评论数与浏览量消失

### 问题网站 | Website URL

https://makiru.top/blog/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
serverURL 的配置需要增加 `https://` 开头
