### ISSUE TITLE
[Bug]: 环境变量IPQPS设置无效

### ISSUE THREAD

**Issue by AsahiKou** [walinejs/waline#1013]
### 问题描述 | Describe the bug

看描述服务端设置IPQPS为0是可以关闭提交等待，但配置了不起作用。

比如我匿名提交了一个评论，再次提交，还是会出现“Comment too fast”提示，且等待时间未知。

如果有这样需求，考虑提示加入多久后才可以再次评论。

![](https://s2.loli.net/2022/05/05/UrIClsBSVMk1jfX.jpg)

### 问题网站 | Website URL

https://blog-comments-asahikou.vercel.app/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

MySQL

**Comment by lizheming** [comment]
确认下是否是时区问题~ 参考 https://github.com/walinejs/waline/issues/482 https://github.com/walinejs/waline/issues/737
