### ISSUE TITLE
[Bug]: 评论会出现弹框

### ISSUE THREAD

**Issue by qianyan98** [walinejs/waline#1015]
### 问题描述 | Describe the bug

![image](https://user-images.githubusercontent.com/34894295/166915355-ce70d84c-37a3-4212-bbd6-569b810cbfb8.png)

评论可以成功，刷新后会显示评论，手机端评论出现弹框后，叉掉弹框会出现重复评论两次的情况

### 问题网站 | Website URL

https://makiru.top/blog/guestbook/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
same with #1012
