### ISSUE TITLE
[Feature]: 安全建议

### ISSUE THREAD

**Issue by cyrus0w** [walinejs/waline#1018]
### 功能概述 | Describe the feature

能不能增加lencloud的acl控制呢，现在的Comment和Users表没有一点acl限制，拿到了key和id就能随便操作数据

**Comment by lizheming** [comment]
现在 LEAN_KEY 和 LEAN_ID 是在服务端存储的，不会暴露给用户。新增数据是需要 LEAN_MASTER_KEY 才行的，不是所有用户可以新增数据。修改数据的话后续可能会开放用户编辑已发布的评论的功能，暂时不好加这个权限限制。而且这样你都 LEAN_KEY 和 LEAN_ID 暴露了，那感觉限制修改数据意义不大。

**Comment by cyrus0w** [comment]
> 现在用户 LE_KEY LE ID 是在服务端存储用户的，不会编辑功能已经暴露给。添加数据是 LEAN_MA_KEY 才行的，不是所有数据。用户可以添加数据发布可能会开放评论的修改，暂时不好加这个权限限制。而且这样你都暴露了 LEAN_KEY 和 LEAN_ID 了，那感觉限制修改数据意义不大。

好吧，主要我发现很多博客的js直接能看到key和id（其他页面模块泄露的）

**Comment by lizheming** [comment]
那个是 Valine，不是 Waline 哈，可以看下这篇文章 https://waline.js.org/advanced/why.html

**Comment by cyrus0w** [comment]
> 那个是 Valine，不是 Waline 哈，可以看下这篇文章 https://waline.js.org/advanced/why.html

刚又看了一次，确实waline没有泄露，是hexo的主题next泄露的

**Comment by lizheming** [comment]
你应该是之前用过 Valine 然后配置没删除直接切换到 Waline 了吧

**Comment by cyrus0w** [comment]
> 你应该是之前用过 Valine 然后配置没删除直接切换到 Waline 了吧

不是的，之前没用过valine，是next主题里面的leancloud_visitors功能泄露，它有个阅读次数统计

**Comment by lizheming** [comment]
https://waline.js.org/guide/client/pageview.html#%E5%92%8C%E8%AF%84%E8%AE%BA%E4%B8%80%E8%B5%B7%E4%BD%BF%E7%94%A8 可以直接使用 Waline 的浏览量统计功能

**Comment by cyrus0w** [comment]
> > 你应该是之前用过 Valine 然后配置没删除直接切换到 Waline 了吧
> 
> 不是的，之前没用过valine，是next主题里面的leancloud_visitors功能泄露，它有个阅读次数统计

这个功能其实next也给出了安全措施，但那个安全模块太久没更新了，现在用不了了，我也不是前端开发，大概看了下源码，后面也知道咋改

**Comment by cyrus0w** [comment]
> https://waline.js.org/guide/client/pageview.html#%E5%92%8C%E8%AF%84%E8%AE%BA%E4%B8%80%E8%B5%B7%E4%BD%BF%E7%94%A8 可以直接使用 Waline 的浏览量统计功能

恩恩，我试试
