### ISSUE TITLE
[Bug]: SMTP 邮件通知不能显示发件人名字

### ISSUE THREAD

**Issue by leirock** [walinejs/waline#1019]
### 问题描述 | Describe the bug

已经设置了环境变量  `SENDER_NAME`， 但是通知的发件人显示的依然是邮箱前缀，这个变量设置无效。

举个例子，发件邮箱假设是 `abc@example.com`，设置了发件人 `SENDER_NAME: 'Blog Notify'`。那么收到的通知邮件里，发件人只会显示 `abc`，而不是 `Blog Notify`。即使在邮箱的 web 端账户设置中指定发件人名字依然不行。

目前使用过 163 邮箱、QQ 邮箱、Outlook 邮箱通过 SMTP 发送通知邮件都有这个问题。

### 问题网站 | Website URL

https://cmt.pinlyu.com

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

SQLite

**Comment by lizheming** [comment]
有定义 SEND_EMAIL 吗？

**Comment by leirock** [comment]
刚刚设置了 `SENDER_EMAIL` 以后就可以了，看来之前是因为只设置了 `SMTP_USER`，漏了 `SENDER_EMAIL`。

thx
