### ISSUE TITLE
[Bug]: 客户端登录后的默认头像没有遵循服务器配置

### ISSUE THREAD

**Issue by tyadan** [walinejs/waline#1029]
### 问题描述 | Describe the bug

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/13864360/167756482-2918eb41-c98e-4fc6-9ac2-fd784e3b7d33.png">
如图所示，客户端在登陆后，评论框的头像没有遵循服务器的avatar配置，而是使用了默认的worker.dev，导致无法打开

### 问题网站 | Website URL

https://jayshao.com/use-waline-system/

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

MySQL

**Comment by lizheming** [comment]
自己设置下 `AVATAR_PROXY=false`，我们还在观察 `worker.dev` 的情况，预计下周切换下默认配置。

**Comment by tyadan** [comment]
我目前就是这么设置的，列表中的其他头像都遵循了我的设置，但是评论框的头像没有遵循

**Comment by tufu9441** [comment]
我是发现管理后台的用户管理界面中，列表中用户的头像显示没有遵循服务器的设置，而是固定使用了https://sdn.geekzu.org/avatar/

**Comment by taotework** [comment]
> 我是发现管理后台的用户管理界面中，列表中用户的头像显示没有遵循服务器的设置，而是固定使用了https://sdn.geekzu.org/avatar/

# 希望尽快修复

没错，我也发现了，这是个很低级错误的问题
来自：`packages/admin/src/pages/manage-comments/utils.js`
```js
export function buildAvatar(email = '', avatar = '') {
  if (avatar) {
    return avatar;
  }

  if (typeof email !== 'string') {
    email = '';
  }

  return `https://sdn.geekzu.org/avatar/${md5(email)}?s=40&r=G&d=`;
}
```
![image](https://github.com/walinejs/waline/assets/148311282/eec37288-a081-4276-bd4c-fcefa9e832b5)

@lizheming @cjh0613 

同时我发现这个代码来自 #259 的合并提交中

如果有最新进展，请联系我大号 @taotecode ，同时我创建了一份新的issues #2125
