### ISSUE TITLE
[Bug]: 通知中的 @username 部分直接显示为 markdown 格式

### ISSUE THREAD

**Issue by akuraito** [walinejs/waline#1030]
### 问题描述 | Describe the bug

如图

![image](https://user-images.githubusercontent.com/51032369/167763296-37bcd0f5-1bbf-43a9-b12f-857cfa3db48e.png)

### 问题网站 | Website URL

https://comment.404gle.cn/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by tufu9441** [comment]
服务端更新1.18.5之后，评论内容里直接显示html代码了，如下图：

![image](https://user-images.githubusercontent.com/6790361/168139043-247149cf-e8e9-45c2-b01a-ad918724cb58.png)
