### ISSUE TITLE
[Bug]: 无法切换表情包

### ISSUE THREAD

**Issue by LxnChan** [walinejs/waline#1031]
### 问题描述 | Describe the bug

感觉像是下面的元素在编辑框上面导致把编辑框的表情组件挡上了，没法切换表情包和点击下面的表情包。
![image](https://user-images.githubusercontent.com/46388610/167867302-a06951ff-eee1-4f97-b14f-3efe2c967d69.png)

版本2.4.0

### 问题网站 | Website URL

https://lxnchan.cn/super-resolution.html

### 服务部署在哪里？ | Where your waline deploy?

CloudBase

### 数据存储在哪里？| Where your comment data store?

CloudBase

**Comment by Mister-Hope** [comment]
Obviously waline style is covered by some other styles, I took 5 minutes, but failed to found out the reson, try dig out the reason by your own.
