### ISSUE TITLE
[Bug]: Error on creating table wl_comment in waline.pgsql

### ISSUE THREAD

**Issue by gfremex** [walinejs/waline#1033]
### 问题描述 | Describe the bug

CREATE TABLE wl_comment (
  id int check (id > 0) NOT NULL DEFAULT NEXTVAL ('wl_comment_seq'),
  user_id int DEFAULT NULL,
  comment text,
  insertedAt timestamp(0) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ip varchar(100) DEFAULT '',
  link varchar(255) DEFAULT NULL,
  mail varchar(255) DEFAULT NULL,
  nick varchar(255) DEFAULT NULL,
  pid int DEFAULT NULL,
  rid int DEFAULT NULL,
  sticky boolean DEFAULT NULL,
  status varchar(50) NOT NULL DEFAULT '',
  like inc DEFAULT NULL,
  ua text,
  url varchar(255) DEFAULT NULL,
  createdAt timestamp(0) with time zone NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp(0) with time zone NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ;

2022-05-13 04:28:10.906 UTC [2249] ERROR:  syntax error at or near "DEFAULT" at character 481

### 问题网站 | Website URL

https://xxx.xxx.railway.app

### 服务部署在哪里？ | Where your waline deploy?

Railway.app

### 数据存储在哪里？| Where your comment data store?

PostgreSQL

**Comment by lizheming** [comment]
感谢反馈，是语法有点问题，已经更新，请重新尝试一下~
