### ISSUE TITLE
[Feature]: 适配hexo-theme-stellar主题

### ISSUE THREAD

**Issue by panoshu** [walinejs/waline#1039]
### 功能概述 | Describe the feature

主题已经适配了valine，是否可以针对这个主题增加一个waline的适配插件。
主题仓库：[hexo-theme-stellar](https://github.com/xaoxuu/hexo-theme-stellar)

**Comment by tufu9441** [comment]
@panoshu 这种事难道不是应该主题自己来做吗

**Comment by lizheming** [comment]
https://github.com/xaoxuu/hexo-theme-stellar/pull/79
https://github.com/xaoxuu/hexo-theme-stellar/pull/80 
已经有两个 PR 了……等主题作者合并吧

**Comment by panoshu** [comment]
@tufu9441 我是看到waline手册里面提到了可以提issue，以及官方也有发布如next主题的插件，就提了一个。
