### ISSUE TITLE
[Bug]: 使用waline在手机浏览器打开网页右边会出现空白

### ISSUE THREAD

**Issue by panoshu** [walinejs/waline#1044]
### 问题描述 | Describe the bug

博客主题：next
客户端版本：v2.5.0
css：https://unpkg.com/@waline/client@v2/dist/waline.css
表现：在next主题配置中开启了评论模块的懒加载，**在手机浏览器打开网页后waline还没有加载的时候**，页面显示正常（可以占满横向的宽度）如图；
![正常显示](https://s2.loli.net/2022/05/20/eOG4HZfhXSbPUaC.png)
**等拉到页面底部，waline加载出来之后**，页面右边缘和屏幕的右边之间会出现一个空白条。
![异常显示](https://s2.loli.net/2022/05/20/UnXk5V8zASoYNOH.png)

对前端不了解，手机上也没法调试，在chrmoe的devtools中模拟手机显示也可以复现。

### 问题网站 | Website URL

https://blog.panoshu.top/posts/9db7e29f.html

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by panoshu** [comment]
刚试了下，直接访问vercel上部署的页面地址，chrom的devtools里面尺寸选择某个手机型号后，页面显示也会出现这种情况

**Comment by lizheming** [comment]
GIF 搜索框的问题，后续等 @Mister-Hope 老师优化后会解决

**Comment by Sansui233** [comment]
我也遇到了。挂载的容器上relative定位, `.wl-gif-popup` width 改成 100%，解决了。网页设计中里不建议对任何盒子的宽度使用绝对宽度单位。

**Comment by lizheming** [comment]
@San 问题已修复，请升级到 `@waline/client@2.5.1`
