### ISSUE TITLE
[Bug]: 请求 emoji 图片时无 referer

### ISSUE THREAD

**Issue by edgexyz** [walinejs/waline#1047]
### 问题描述 | Describe the bug

如题，添加了自己使用的 emoji 后发现无法正常加载，检查 request header 后发现 waline.min.js 加载 emoji png 时不会包含 referer header，而本人的反盗链策略要求 referer 必须包含 本地测试或者自身域名，因而出现 403。

目前的缓解方式是允许无 referer 直链也可以请求。

### 问题网站 | Website URL

icesh.me

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by Mister-Hope** [comment]
我觉得这是一个edge case，emoji本身不应该加refer，从而给表情包provider提供追踪的机会，另外诸如邮件通知等场景也并非含有原网站refer。所以我不认为这里是一个bug，同样我不认为很有必要提供一个额外选项控制开启refer

**Comment by inkss** [comment]
他可以在邮件模块里加 `img.wl-emoji {display: none !important}`，（坏笑
