### ISSUE TITLE
[Bug]: Hexo Next 主题插件会重复发送请求

### ISSUE THREAD

**Issue by zhangnew** [walinejs/waline#1059]
### 问题描述 | Describe the bug

Hexo Next 主题插件，`comment` 和 `article` 接口会连续发送两个一样的请求，发送请求的代码看起来是在这一部分：
`watchEffect` 函数也触发了一次请求

https://github.com/walinejs/waline/blob/938733637c96c96bd6bd99bec5f7dbc846942ad2/packages/client/src/init.ts#L84-L90

看起来是新版的问题，比如： [link 1](https://zhangnew.com/isso-to-waline.html) [link 2](https://qianfanguojin.github.io/2022/01/20/Hexo%E5%8D%9A%E5%AE%A2%E8%BF%9B%E9%98%B6%EF%BC%9A%E4%B8%BA-Next-%E4%B8%BB%E9%A2%98%E6%B7%BB%E5%8A%A0-Waline-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F/)
这个旧版本的没问题：[link 3](https://finisky.github.io/hexowaline/)

连续发送两个请求还会导致 Counter 表数据重复，为同一个 url 创建两条记录

### 问题网站 | Website URL

https://zhangnew.com/isso-to-waline.html

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

SQLite

**Comment by Mister-Hope** [comment]
Nice catch
