### ISSUE TITLE
[Bug]: waline.visitor 访问量显示和评论数在首页显示不生效

### ISSUE THREAD

**Issue by qigedandan** [walinejs/waline#1061]
### 问题描述 | Describe the bug

 waline.visitor 访问量显示和评论数在首页显示不生效
![image](https://user-images.githubusercontent.com/80624768/170224331-7dc92b88-21d7-4d19-9ef8-a057636dae1e.png)
![image](https://user-images.githubusercontent.com/80624768/170224461-6268c3d1-dbbf-4b0f-822f-629ba261df7a.png)

### 问题网站 | Website URL

qgdd.vercel.app

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by Mister-Hope** [comment]
Are you sure you are using it correctly?
