### ISSUE TITLE
cdn更换

### ISSUE THREAD

**Issue by Fgaoxing** [walinejs/waline#1068]
### 问题描述 | Describe the bug

如何更换cdn？

### 问题网站 | Website URL

https://waline.yt-blog.top

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
https://github.com/volantis-x/hexo-theme-volantis/blob/dev/_config.yml#L422-L423 自己改下主题的配置
