### ISSUE TITLE
[Bug]: waline官方网站打开一片空白

### ISSUE THREAD

**Issue by cyicz123** [walinejs/waline#1080]
### 问题描述 | Describe the bug

输入https://waline.js.org/ 后，打开一片空白。已用移动端和PC端测试。F5查看网站源代码，html也只有短短几行。
![image](https://user-images.githubusercontent.com/44216455/171570236-5e644ed3-bf41-4016-af13-8c386ade604f.png)
### 问题网站 | Website URL

https://waline.js.org/

### 服务部署在哪里？ | Where your waline deploy?

Other

### 数据存储在哪里？| Where your comment data store?

Deta Base

**Comment by Mister-Hope** [comment]
Fixed
