### ISSUE TITLE
[Bug]:   引入js报错

### ISSUE THREAD

**Issue by zhouchangen** [walinejs/waline#1094]
### 问题描述 | Describe the bug

使用v1报错， Unexpected token < in JSON at position 0，表情点击无法展示表情包的下拉列表  [https://unpkg.com/@waline/client@1.6.0/dist/Waline.min.js](url)

v2直接是Waline is not a constructor [https://unpkg.com/@waline/client@2.5.1/dist/waline.js](url)

### 问题网站 | Website URL

https://waline-institute-zdjtcmcom.vercel.app/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

MySQL

![b](https://user-images.githubusercontent.com/30683958/172095259-a4e91d3d-05ec-4ac4-92d9-6de21b264f1e.png)

**Comment by lizheming** [comment]
1. 1.x 默认从 jsdelivr 载入表情包，目前该 CDN 国内方案有问题，可自行更改其它的 CDN 
2. 2.x 默认的初始化方式有变化，需要将原来的 `new Waline` 修改成 `Waline.init()`

**Comment by zhouchangen** [comment]
多谢大佬
