### ISSUE TITLE
[Bug]: 设置多个 emoji 空间不足

### ISSUE THREAD

**Issue by AnzhiZhang** [walinejs/waline#1111]
### 问题描述 | Describe the bug

当设置多个 emoji 时，挤到第二行的表情没有背景。

![image](https://user-images.githubusercontent.com/37402126/172852678-0accf0e5-dc57-4176-9faf-6d4e33242a57.png)

使用的 emoji 列表：
```text
    'https://cdn.jsdelivr.net/gh/walinejs/emojis/bilibili',
    'https://cdn.jsdelivr.net/gh/walinejs/emojis/qq',
    'https://cdn.jsdelivr.net/gh/walinejs/emojis/tw-body',
    'https://cdn.jsdelivr.net/gh/walinejs/emojis/tw-food',
    'https://cdn.jsdelivr.net/gh/walinejs/emojis/tw-natural',
    'https://cdn.jsdelivr.net/gh/walinejs/emojis/tw-object',
    'https://cdn.jsdelivr.net/gh/walinejs/emojis/tw-symbol',
    'https://cdn.jsdelivr.net/gh/walinejs/emojis/tw-people',
    'https://cdn.jsdelivr.net/gh/walinejs/emojis/tw-sport',
    'https://cdn.jsdelivr.net/gh/walinejs/emojis/tw-time',
    'https://cdn.jsdelivr.net/gh/walinejs/emojis/tw-travel',
    'https://cdn.jsdelivr.net/gh/walinejs/emojis/tw-weather',
    'https://cdn.jsdelivr.net/gh/walinejs/emojis/tw-flag'
```

### 问题网站 | Website URL

未上线，使用 hexo + fluid 主题部署博客

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by AnzhiZhang** [comment]
![image](https://user-images.githubusercontent.com/37402126/173229040-5d825976-bc77-4726-970a-5ef370e5bce4.png)
![2022-06-12 18 35 14](https://user-images.githubusercontent.com/37402126/173229233-44bf4ac2-03a2-4f1d-8859-269d0ab3b56e.png)
我更新到博客发现，vertical 的空间似乎不太够，纵向滚动条是预期的行为吗？不知道是不是分辨率适配问题或博客适配问题，我尝试了两个屏幕和移动设备都有这个问题
在 https://blog.zhanganzhi.com/2022/06/b583a6838537/ 可以复现

**Comment by Zengzzhao** [comment]
> ![image](https://user-images.githubusercontent.com/37402126/173229040-5d825976-bc77-4726-970a-5ef370e5bce4.png) ![2022-06-12 18 35 14](https://user-images.githubusercontent.com/37402126/173229233-44bf4ac2-03a2-4f1d-8859-269d0ab3b56e.png) 我更新到博客发现，vertical 的空间似乎不太够，纵向滚动条是预期的行为吗？不知道是不是分辨率适配问题或博客适配问题，我尝试了两个屏幕和移动设备都有这个问题

为啥在emoji配置中引入你这些表情（官方给的https://waline.js.org/guide/features/emoji.html#%E9%A2%84%E8%AE%BE）不行？
