### ISSUE TITLE
[Feature]: 自己维护邮件服务商（SMTP_SERVICE）列表

### ISSUE THREAD

**Issue by AnzhiZhang** [walinejs/waline#1113]
### 功能概述 | Describe the feature

当前使用的 [列表](https://github.com/nodemailer/nodemailer/blob/master/lib/well-known/services.json) 作者停止维护，提交新 PR 模板提示 frozen，只接受 bug fix 不接受 feature。目前打开的两个 PR 也一直未接受。

例如阿里邮件推送 `smtpdm.aliyun.com` 不在该列表中，是否有必要考虑自行维护列表？

**Comment by Mister-Hope** [comment]
我的建议是，你自己研究一下 SMTP 发件和收件服务器与端口号，然后在讨论区的 "Show and Tell" 里开一个帖子，描述阿里云要怎么配置就好了。

**Comment by Mister-Hope** [comment]
或者更直观点说，我坚持这类问题应该在 node-mailer 处解决，而不是 waline 这边。你可以向这边提的建议可以找到一个还在维护，并且与 node-mailer 相比有优势的其他包来替换。
