### ISSUE TITLE
[Help Wanted or Bug]: 编辑普通用户个人资料

### ISSUE THREAD

**Issue by AnzhiZhang** [walinejs/waline#1116]
## /ui 无限跳转

#869 有提到，直接跳到 /ui/profile 可能会减少非前端进入用户页面看到无限跳转产生的迷惑

## 无法编辑个人资料

在个人资料页无法修改头像、资料和密码。修改后按钮变灰之后无任何反应，请求返回为

```json
{
    "errno": 1000
}
```

![image](https://user-images.githubusercontent.com/37402126/172881414-1504f7c7-0955-4da0-9e1b-c6c2cef6116e.png)

应该不是安全域名（`SECURE_DOMAINS`）问题，因为管理员可以修改，不知道是否是我的配置问题，如果是希望得到帮助。

**Comment by AnzhiZhang** [comment]
已修改

**Comment by lizheming** [comment]
本周略忙，相关问题下周会进行处理
