### ISSUE TITLE
[Bug]: 在React中报VUE的错误。。。

### ISSUE THREAD

**Issue by pincman** [walinejs/waline#1146]
### 问题描述 | Describe the bug

使用docusaurus启动，能正常运行，但是爆出如下错误
```
__VUE_OPTIONS_API__, __VUE_PROD_DEVTOOLS__ are not explicitly defined
runtime-core.esm-bundler.js?65e8:38 [Vue warn]: Invalid prop: type check failed for prop "rootId". Expected String with value "4", got Number with value 4. 
```
老版本是没问题的，2.x就报错

### 问题网站 | Website URL

https://pincman.com

### 服务部署在哪里？ | Where your waline deploy?

VPS, VirtualHost

### 数据存储在哪里？| Where your comment data store?

MySQL

**Comment by Mister-Hope** [comment]
I did not see a single line of code, also do no see reproduction repo.
