### ISSUE TITLE
[Bug]: 可以发空评论

### ISSUE THREAD

**Issue by SlimeNull** [walinejs/waline#1152]
### 问题描述 | Describe the bug

填几个空格, 然后发送评论, 居然能成功

### 问题网站 | Website URL

https://waline.js.org/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by Mister-Hope** [comment]
这有什么问题么？

如果你非得说有，那我要问了，发个句号是不是空评论？发个中文空格，零宽空格算不算空评论？发个其他符号算不算？

**Comment by lizheming** [comment]
我也觉得，空格情况太多了，还有中文空格的，还有各种零宽字符……意义不是很大。如果你觉得空格这种有问题的话可以自行在 `preSave()` 钩子进行处理 https://waline.js.org/reference/server.html#presave-comment
