### ISSUE TITLE
[Feature]: 评论可选按时间或热度排序

### ISSUE THREAD

**Issue by AnzhiZhang** [walinejs/waline#1162]
### 功能概述 | Describe the feature

建议增加评论的更多种排序方式，类似这样
![image](https://user-images.githubusercontent.com/37402126/176928432-0ea454db-a5ec-46b9-8254-99ade566622c.png)
热度的计算可以通过喜欢的数量和回复量综合计算，或仅计算点赞量

**Comment by tb0513** [comment]
https://tb0513.github.io/jump

**Comment by AnzhiZhang** [comment]
> https://tb0513.github.io/jump

@Mister-Hope Spam here

**Comment by AnzhiZhang** [comment]
@Mister-Hope Spam here

**Comment by lizheming** [comment]
`@waline/client@2.7.0` 已实现，欢迎体验
