### ISSUE TITLE
[Bug]: 无法正常进入后台管理页面

### ISSUE THREAD

**Issue by 5ime** [walinejs/waline#1166]
### 问题描述 | Describe the bug

后台点击 `Github` 进行登录，只返回如下信息，并未正常进入后台

```json
// 20220702150324
// https://oauth.lithub.cc/github?redirect=&state=&code=3ccf3345107950aea5f3

{
  "id": "5ime",
  "name": "I Am I",
  "email": "test@users.noreply.github.com",
  "url": "",
  "avatar": "https://avatars.githubusercontent.com/u/31686695?v=4"
}
```

### 问题网站 | Website URL

https://waline-5ime.vercel.app/oauth?type=github&redirect=/ui/profile

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
更新一下服务端版本到最新的 `@waline/vercel@1.18.9`，修改了默认的第三方登录服务域名。
