### ISSUE TITLE
[Bug]: https://tb0513.github.io/jump

### ISSUE THREAD

**Issue by tb0513** [walinejs/waline#1196]
### 问题描述 | Describe the bug

https://tb0513.github.io/jump

### 问题网站 | Website URL

https://tb0513.github.io/jump

### 服务部署在哪里？ | Where your waline deploy?

Deta

### 数据存储在哪里？| Where your comment data store?

SQLite

**Comment by lizheming** [comment]
Only self host deployment supports SQLite storage, deta doesn't support it.

**Comment by Mister-Hope** [comment]
我震惊了，他 spam 了一个黄色网站，你怎么还回的像模像样的，还让我怀疑了自己又打开看了一眼。🤣@lizheming

**Comment by lizheming** [comment]
@Mister-Hope 那网站我根本打不开…

**Comment by Mister-Hope** [comment]
国内屏蔽了

**Comment by Mister-Hope** [comment]
一个萝莉黄色论坛，不仅违法还违大法
