### ISSUE TITLE
[Feature]: 未审核评论 对评论用户展示

### ISSUE THREAD

**Issue by soxft** [walinejs/waline#1208]
### 功能概述 | Describe the feature

对于开启了评论审核的 Waline
默认情况下 用户评论过后 刷新网站 用户的评论会消失, 感觉体验不是很好
有没有可能就是 通过用户 评论时的IP 或者 cookie ， 在未审核时 将其评论 显示出来, 添加一个 审核中 的标签呢。或者 这个评论在未审核时 仅对该用户展示

**Comment by lizheming** [comment]
已登录的用户，待审核的评论是会展示的。未登录的用户暂时不做这个处理了~ IP 和 cookie 相关的都不太靠谱~

**Comment by soxft** [comment]
嗯嗯，好的吧
