### ISSUE TITLE
重新加入QQ头像API

### ISSUE THREAD

**Issue by MCSeekeri** [walinejs/waline#123]
在MiniValine之前的版本里加入了对QQ头像的支持,不过之后因为安全原因被删除了。
不过我觉得既然已经有了Waline那么应该就不需要顾虑安全问题了（
所以这个很赞的功能也许可以重新加入到Waline中（

**Comment by lizheming** [comment]
@MCSeekeri 嗯，可以考虑，不过后期会考虑加上用户头像上传的功能（或者指定头像地址）来支持这块的需求，这样做能更具有通用性一点。

**Comment by MCSeekeri** [comment]
那么考虑去不图床吗（
https://7bu.top
由杜老师开发的一个很不错的图床,已经被Artitalk设成默认图床了（

**Comment by lizheming** [comment]
@MCSeekeri 你好，之前我已经回复过杜老师这块的问题。Waline 是支持自定义上传图片逻辑的，通过自定义 uploadImage 方法，我们是可以支持任何图床的。所以适配去不图床其实非常简单，下面是一个示例，你可以参考一下：

new Waline({
  serverURL: 'xxx',
  uploadImage: function(file) {
      const formData = new FormData();
      formData.append('image', file);
      
      return fetch('https://7bu.top/upload/upload.html', {
        method: 'POST',
        body: formData
      }).then(resp => resp.json()).then(resp => resp.data.url);
    }
  }
});

**Comment by MCSeekeri** [comment]
感谢,那么下面我就静候QQAPI的回归了（

**Comment by lizheming** [comment]
目前可以使用 https://github.com/walinejs/waline/issues/532 这个 issue 中的方法返回 QQ 头像地址
