### ISSUE TITLE
[Bug]: Deta+Deta Base部署，评论者IP全部定位为Amazon

### ISSUE THREAD

**Issue by website-pages** [walinejs/waline#1243]
### 问题描述 | Describe the bug

Deta+Deta Base部署，评论者IP全部定位为Amazon，如图。
![image](https://user-images.githubusercontent.com/103917160/182031978-712fcf06-e168-43c3-a1db-d271c4012f4a.png)
![image](https://user-images.githubusercontent.com/103917160/182032005-58798a40-ba1d-42d4-9cf4-5297122260d5.png)
已确认不是本机问题，且有其他用户遇到了同样的问题。

### 问题网站 | Website URL

imwzx.deta.dev

### 服务部署在哪里？ | Where your waline deploy?

Deta

### 数据存储在哪里？| Where your comment data store?

Deta Base

**Comment by Lete114** [comment]
关于 IP : https://github.com/orgs/deta/discussions/282
