### ISSUE TITLE
[Feature]: 能不能有个举报的功能

### ISSUE THREAD

**Issue by w0oo** [walinejs/waline#1244]
### 功能概述 | Describe the feature

# 功能概述 | Describe the feature
![](https://camo.githubusercontent.com/dfcba8f800b3dd2a7ba710ca2c84d0a7e9f90c243cfc7ab86999e106fee5f3db/68747470733a2f2f696d672e61667161712e636f6d2f696d616765732f323032322f30372f32342f313635383634333932353832362e706e67)

**Comment by so1ve** [comment]
你自己删了不就行了
