### ISSUE TITLE
[Bug]: postgres 数据库查询报 error: column "COUNT(*) as count" does not exist

### ISSUE THREAD

**Issue by asadahimeka** [walinejs/waline#1286]
### 问题描述 | Describe the bug

用的是 Supabase 的数据库

![image](https://user-images.githubusercontent.com/31837214/184939987-d10f0c7c-5031-4abb-bdc5-c0d5199ad7c6.png)

### 问题网站 | Website URL

https://waline-ss-server.vercel.app

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

PostgreSQL

**Comment by lizheming** [comment]
https://github.com/walinejs/waline/discussions/1269 看下是不是这个问题

**Comment by asadahimeka** [comment]
> #1269 看下是不是这个问题

删除 `LEVELS` 变量后不再报错
