### ISSUE TITLE
[Feature]: 支持滚动到评论区时再加载的lazyload

### ISSUE THREAD

**Issue by appotry** [walinejs/waline#1295]
### 功能概述 | Describe the feature

init或者再添加一个新函数，例如lazyInit只是初始化最基本功能，这时还没有开始加载评论

到支持滚动到评论区时，调用另一个函数开始加载评论，例如startCommon

启用计数功能，也是用一个函数开关，例如startCount

想过，外部IntersectionObserver API 方式的lazyload，但是这样计数功能就不能用了，而pageview一般在页面开头，所以计数，和加载评论函数启动分开

**Comment by lizheming** [comment]
是不是可以外部自己实现？滚动到视野区再执行 `Waline.init()` 就UI那个？

**Comment by appotry** [comment]
> 是不是可以外部自己实现？滚动到视野区再执行 `Waline.init()` 就行？

计数功能似乎没有单独出来，文档中计数的js测试没有成功，Waline完全版计数才开启成功

文档这部分太简略了，没看明白。


<script src="https://unpkg.com/@waline/client/dist/pageview.js"></script>

pageview这个插件要怎么配置才能使用？

由于启用的waline pageview功能，所以外部滚动到视野区再执行 Waline.init() 就会导致文件头部的计数没法用了

如果计数可以单独配置使用，那么可以外部实现lazyload

**Comment by appotry** [comment]
如果pageview.js 和waline.js 同时使用会不会有冲突？

**Comment by appotry** [comment]
@lizheming 另外，管理面板数据导入导出是不是有bug？
数据导入提示504错误

**Comment by lizheming** [comment]
PageView 是可以独立使用的功能，不会和 `Waline.init()` 本身冲突，如果已经独立使用了 PageView 就不要再给 `Waline.init()` 设置 `pageview` 属性了，会有不必要的重复请求。

鉴于 PageView 单独使用不是标准的使用方法，所以这块如何使用没有在文档中说明。PageView 的初始化可以参考下 https://github.com/walinejs/waline/blob/main/packages/client/src/init.ts#L71-L76 其实就是传几个参数。

所以我理解这个 issue 问题已经解决。关于导入导出数据的问题建议另外开个 issue 然后提供下数据给我我看下会比较好，谢谢。

**Comment by Mister-Hope** [comment]
不不不不不，劳资的文档写的不可能遗漏任何用户可能需要的内容。

https://waline.js.org/reference/client.html#pageviewcount

请仔细阅读文档。

https://waline.js.org/reference/client.html#pageview init 函数默认不会启用浏览量统计功能，除非你显式配置，所以为什么你会觉得它俩会冲突？
