### ISSUE TITLE
[Bug]: 读者相互评论，审核通过后无邮件通知

### ISSUE THREAD

**Issue by xs314** [walinejs/waline#1313]
### 问题描述 | Describe the bug

![image](https://user-images.githubusercontent.com/55978649/186090432-257119de-ffac-4a2f-b2e6-1e548df075c8.png)
USERB回复了USERA后，按理USERA应该收到邮件通知实际上并没有，outlook也无发信记录

Vercel日志：
```
[2022-08-23T06:44:48.594] [9] [INFO]
 - SQL: SELECT * FROM `wl_Comment` WHERE ( `id` = '101' ), Time: 5ms
[2022-08-23T06:44:48.603] [9] [INFO]
 - SQL: UPDATE `wl_Comment` SET `status`='approved' WHERE ( `id` = 101 ), Time: 8ms
```

相同问题： #865

### 问题网站 | Website URL

https://blog.shiyunhong.com/hexo-css-do-not-work

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

MySQL

**Comment by qystudio0** [comment]
这似乎不是bug，应该是需求

**Comment by xs314** [comment]
> 这似乎不是bug，应该是需求

https://github.com/walinejs/waline/issues/865#issuecomment-1079568480

并不是
