### ISSUE TITLE
[Bug]: 评论留QQ邮箱会泄露QQ号，这样不太好

### ISSUE THREAD

**Issue by lbroot** [walinejs/waline#1314]
### 问题描述 | Describe the bug

自动获取QQ邮箱用户的头像，就是把页面的图片地址设置为 `https://q1.qlogo.cn/g?b=qq&nk=YOUR_QQ_NUMBER@&s=100`
直接右键复制图片地址就可以看到用户的QQ号了，不安全。

改进这个缺陷，我有如下想法：   
1. 提供一个变量，允许站长在他的站点禁用掉QQ头像的获取，只用 Gravatar 头像。
2. 保存QQ头像的加密地址，可以参考这样的文章（我随手搜的，很多文章）https://www.oschina.net/question/924485_157919
3. （推荐）把用户的QQ头像缓存到服务器上，使用随机的名称来保存图片。

**建议首先提供一个关闭的方法。**   
然后，关于第二个方法，值得注意的一点是，目前尚不知道这个加密头像地址是怎么加密的，为了避免日后有大佬找到逆向的方法了，建议直接使用方法三。

### 问题网站 | Website URL

https://waline.js.org/

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

MySQL

**Comment by lizheming** [comment]
头像地址输出本来就是可配的，建议参考 https://github.com/walinejs/waline/issues/532 反向操作一下即可。之前我们是默认提供 Gravatar 的，后来需要 QQ 头像的同学实在是太多了，才把这个 issue 的配置改成了默认的。
