### ISSUE TITLE
[Bug]: 2022年8月26日起，不开梯子无法加载评论

### ISSUE THREAD

**Issue by linhaii** [walinejs/waline#1318]
### 问题描述 | Describe the bug

2022年8月26日起，不开梯子无法加载评论列表。

无论是否绑定自己的域名，均有这种情况。即便是waline官网的评论框也有这个问题。

### 问题网站 | Website URL

https://waline.js.org

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by linhaii** [comment]
评论框可以显示，评论列表无法加载。

**Comment by rockbenben** [comment]
绑定域名后，暂时正常

**Comment by lizheming** [comment]
群里了解了下，应该是 *.vercel.app 域名被 DNS 污染了，按照楼上说的绑定自定义域名，或者去其它服务上部署解决吧。

**Comment by elkan1788** [comment]
可以考虑使用免费域名+LeanCloud国际版本的部署方案，但就是速度慢一些，但服务还是正常的使用。

- 方案及效果： [使用自定义域名激活Vercel部署的Waline服务](https://lisenhui.cn/blog/use-custom-domain-active-vercel-waline.html)

**Comment by updowncity** [comment]
我也遇到了同樣的情況(Vercel+LeanCloud國際版)，儘管已經配置了個人域名(域名未備案,也沒被牆)，但是在不開梯子的情況下還是無法加載Waline評論(管理端同樣無法訪問)。

**Comment by lizheming** [comment]
@updowncity 实测并没有问题
![image](https://github.com/walinejs/waline/assets/424491/f96d5a73-3d01-441b-95cf-b84f1f51b9a9)

**Comment by leonardo110** [comment]
没有更简单的方法了吗？只能更换到其他托管平台 或者 自定义域名 ？？？
