### ISSUE TITLE
[Bug]: 导入数据后并未将"wl_comment"表的id计数重设为导入后的值，导致创建评论时出现主键约束冲突

### ISSUE THREAD

**Issue by wsndshx** [walinejs/waline#1319]
## 复现步骤
在发现该BUG之前，曾经进行过如下操作

- 在容器因额度耗尽被暂停，重启容器后，顺手升级了版本，期间遇到的问题可见 #1317 
- 虽然通过给数据库插入缺少的列解决了问题，但为了避免潜在的问题因此导出了数据
- 重新根据[Railway 部署 | Waline](https://waline.js.org/guide/server/railway.html)重新部署了一次
- 部署完成后使用导入功能将之前的数据导入（虽然提示导入数据为空但却正常导入了）
- 在文章下发发表新评论

便得到如下图所示的错误信息

![image](https://user-images.githubusercontent.com/7829265/187013983-884652dc-bea8-43c4-bd01-3db58b8b9cd7.png)

查看后台日志发现提示主键约束冲突错误

![image](https://user-images.githubusercontent.com/7829265/187014019-13a9da42-12a0-445c-9526-c8bc89303e33.png)

查看数据库日志可见其在存储评论时使用的id为从1开始自增的

![image](https://user-images.githubusercontent.com/7829265/187014053-46350dbb-caf0-4f80-91b7-55c90e02405f.png)

## 临时的解决方案

- 可通过不断进行评论，使得自增id超过旧数据，之后便可以进行正常评论
- 数据库执行查询 `select setval('wl_comment_id_seq',(select max(id) from wl_comment));`

## 可能的修复方案

在导入数据后分别执行查询修正各表的`id_seq`值为该表的id最大值，因为其他的表可能也存在同样的问题。

### 问题网站 | Website URL

https://blog.fishfish.date/2022/02/09/Hexo%E5%AE%89%E8%A3%85Waline%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E8%B8%A9%E5%9D%91/

### 服务部署在哪里？ | Where your waline deploy?

Railway.app

### 数据存储在哪里？| Where your comment data store?

PostgreSQL

**Comment by lizheming** [comment]
fix by #1311
