### ISSUE TITLE
[Bug]: 评论失败

### ISSUE THREAD

**Issue by rmf2** [walinejs/waline#1338]
### 问题描述 | Describe the bug

这几天都是这样子
![image](https://user-images.githubusercontent.com/109793336/187644314-068820c2-9bb2-4b01-8832-d02e9cb13641.png)

### 问题网站 | Website URL

https://ws.zjyz.ml/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
https://forum.leancloud.cn/t/2022-8/25408 需要 LeanCloud 上绑下域名用 serverURL 配一下
