### ISSUE TITLE
[Bug]: 评论区下拉按钮卡顿

### ISSUE THREAD

**Issue by Mereithhh** [walinejs/waline#1352]
### 问题描述 | Describe the bug

评论区的下拉按钮拖动的时候有些卡顿，不太流畅。

我看了一下项目主页的评论区也是这样，用的 Chrome 浏览器。我用无痕模式关闭所有插件也是这样。

![image](https://user-images.githubusercontent.com/22872368/188302011-981e46e9-774c-45cc-8deb-b1e5daa248fd.png)

### 问题网站 | Website URL

https://waline.js.org/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
因为配置了 `transition` 加了动效，暂时不修复了，如果特别介意的话可以自己写 CSS 覆盖处理一下。

**Comment by Mereithhh** [comment]
妙。
