### ISSUE TITLE
[Bug]: 部署后出现如下提示？

### ISSUE THREAD

**Issue by flight025** [walinejs/waline#1355]
### 问题描述 | Describe the bug

我的waline评论出现如下提示：Unauthorized. [401 GET [](https://ohh9dzzy.api.lncldglobal.com/1.1/classes/Comment]，这是什么错误，有什么解决办法呢？
![捕获](https://user-images.githubusercontent.com/65944944/188340723-8e178d47-f819-4e3c-b0e5-c4ea5e7b2606.PNG)

### 问题网站 | Website URL

www.zaqizaba.xyz

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

GitHub

**Comment by lizheming** [comment]
1. 你确定你是用 GitHub 存储么，这是 LeanCloud 的报错信息（另外不建议初学者使用 GitHub 存储）
2. 如果使用 LeanCloud 存储的话记得 LEAN_ID, LEAN_KEY, LEAN_MASTER_KEY 三个写完整

**Comment by flight025** [comment]
你好，这三个LEAN_ID, LEAN_KEY, LEAN_MASTER_KEY环境变量设置是完整的。
![Uploading 捕获.PNG…]()

**Comment by flight025** [comment]
![捕获](https://user-images.githubusercontent.com/65944944/188409069-9db7bb2d-10e8-4b6f-8034-af1d34b42258.PNG)

**Comment by lizheming** [comment]
重新部署过了没有

**Comment by lizheming** [comment]
close with long inactivite.
