### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by pencilqaq** [walinejs/waline#1358]
### 问题描述 | Describe the bug

首次注册抛出500错误
![image](https://user-images.githubusercontent.com/36183335/188424234-d0a7d154-80b6-48db-88f5-927843ab46e5.png)
![image](https://user-images.githubusercontent.com/36183335/188424273-c74cf9e7-133d-4c94-857d-6f09ea704f19.png)

### 服务部署在哪里？ | Where your waline deploy?

VPS, VirtualHost

### 数据存储在哪里？| Where your comment data store?

Deta Base

**Comment by lizheming** [comment]
1. https://github.com/walinejs/waline/issues?q=is%3Aissue+is%3Aclosed+Not+initialized Not initialized 是 LeanCloud 没有初始化的报错，自行搜索一下可以
2. 如果你确认是要存储在 Deta Base 上的话需要设置相关的环境变量，怎么设置环境变量可以参考这个 discussion: https://github.com/walinejs/waline/discussions/694
