### ISSUE TITLE
[Bug]: 留言按倒序可以显示出来，按照正序和热度显示刷新且一直无法刷新显示

### ISSUE THREAD

**Issue by franktly** [walinejs/waline#1370]
### 问题描述 | Describe the bug

留言按倒序可以显示出来，按照正序和热度显示刷新且一直无法刷新显示, Hexo 博客复现地址：http://www.taolingyang.com/2021/07/14/C++%E8%99%9A%E5%87%BD%E6%95%B0%E8%A1%A8%E5%BD%92%E5%B1%9E/

### 问题网站 | Website URL

www.taolingyang.com

### 服务部署在哪里？ | Where your waline deploy?

Railway.app

### 数据存储在哪里？| Where your comment data store?

PostgreSQL

**Comment by lizheming** [comment]
`@waline/vercel@1.20.1` 已修复，感谢反馈

**Comment by franktly** [comment]
已更新版本验证现在正常了 谢谢

**Comment by franktly** [comment]
> `@waline/vercel@1.20.1` 已修复，感谢反馈

更新版本验证现在功能正常了 谢谢

**Comment by ayakasuki** [comment]
1.31.2复现
