### ISSUE TITLE
[Bug]: Fix linter for admin package

### ISSUE THREAD

**Issue by Mister-Hope** [walinejs/waline#1376]
### 问题描述 | Describe the bug

The admin source is using some unknown properties.

### 问题网站 | Website URL

Not related

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
which unknown properties?

**Comment by Mister-Hope** [comment]
https://github.com/walinejs/waline/runs/8211113072?check_suite_focus=true

**Comment by lizheming** [comment]
close by #1387
