### ISSUE TITLE
[Bug]: pageview 和 commentCount 计数对于path 最后有没有一个/ 是做两个path，其实应该是一个

### ISSUE THREAD

**Issue by appotry** [walinejs/waline#1400]
### 问题描述 | Describe the bug

问题：
https://blog.17lai.site/posts/9912bd5d
https://blog.17lai.site/posts/9912bd5d/

这两个链接都应该对应同一个path计数才对，但实际上，这两个链接的计数差异极大，猜测是作为两个path分别计数的！

并且，两个链接的评论都是分开的！一个链接获取不到另一个链接的评论

期望结果：
这两个链接，获取到的pageview 和commentcount 都应该是同一个
评论也应该指向同一个列表

### 问题网站 | Website URL

https://blog.17lai.site/posts/9912bd5d

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by appotry** [comment]
看来以前犯了个错误， path 不应该直接填写 window.location.pathname

应该对最后面的字符进行处理再填入，正则替换去掉/比添加/容易

**Comment by lizheming** [comment]
从 URL 规范来说 `/posts/9912bd5d` 这个文件资源，`/posts/9912bd5d/` 代表的是这个文件夹，这两者就是不一样的。
Waline 使用的 `path` 只是作为页面的唯一标识，如果你认为这两个是一个页面，那你就搞一个同样的唯一标识就可以了，而不是强迫我们改默认的行为。建议你直接使用 `9912bd5d` 作为唯一 ID 或者传入 `path` 的时候前置处理 `/` 的问题
