### ISSUE TITLE
[Bug]: sticky数据类型与数据库不匹配，500错误

### ISSUE THREAD

**Issue by ZvonimirSun** [walinejs/waline#1405]
### 问题描述 | Describe the bug

@waline/client v2.9,1 内数据类型与后端数据库不匹配，置顶功能500错误

![image](https://user-images.githubusercontent.com/22871764/190869153-1693ed44-a5b1-43fd-898d-e0a90a24a438.png)

![image](https://user-images.githubusercontent.com/22871764/190869176-e55db0e6-eaf0-4733-ba64-af3f3cde176c.png)

### 问题网站 | Website URL

https://wl.iszy.xyz

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

PostgreSQL

**Comment by lizheming** [comment]
https://github.com/walinejs/waline/issues/564#issuecomment-925425939 老表的话参考下这个改一下

**Comment by ZvonimirSun** [comment]
https://github.com/walinejs/waline/blob/d8f5832547c27802dd68f8d8e745806acdf45e18/assets/waline.pgsql#L15

那这边建库语句也要改下，这边还是旧的
