### ISSUE TITLE
[Bug]: 配置recaptcha之后，未登录提示Forbidden

### ISSUE THREAD

**Issue by StarWEB890** [walinejs/waline#1418]
### 问题描述 | Describe the bug

![msedge_3CWQDsFpfH](https://cdn.staticaly.com/gh/StarWEB890/TuChuang@master/images/msedge_3CWQDsFpfH.6ualnjhqly40.webp)
F12提示：
![msedge_OBh1xONfSk](https://cdn.staticaly.com/gh/StarWEB890/TuChuang@master/images/msedge_OBh1xONfSk.2hvxqw603o40.webp)

### 问题网站 | Website URL

https://wle.pl.xsnetw.ga/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
fixed at https://github.com/walinejs/waline/commit/7e696b672f9b4c8807d192e26cb51ee6d5611502
