### ISSUE TITLE
[Feature]: 宽泛意义上的评论： 文章点赞，文章评分功能

### ISSUE THREAD

**Issue by appotry** [walinejs/waline#1419]
## 背景

这个**宽泛**点讲也可以算是文章评论的一部分

写文字太累，不想，又想表示看过，评论一下。

那么，点赞，评分，就是文字评论的替代选择！

### 点赞

可以分为顶，踩，可以只允许登录用户，至于数据库是否记录点赞meta信息，可以只记录最终结果

### 评分

5分或者10分满分，看愿意给几分

是记录完整评分记录，方便追溯，或者节约空间，只记录最终结果

## 显示

能在文章列表界面显示出来更好

那么，为了节约体积，加载速度，可以考虑单独的js文件，类似 pageview

**Comment by appotry** [comment]
一种减少复杂度的方法，每条评论内容都记录为本次评分和上一条评论内容评分的某种加权算法的值，把这个值作为内容保存

以后每一条点赞，评分都这样记录。既能快速查找，又能追溯以往记录

内容和加权可以保存，总评分累计求和，评分人数，本次评分，这次评分之后评分值等等，即使想删除其中某一条评分，结合记录节点前后评分记录，也可以在某个后台计算并逐级修正所有评分

**Comment by Mister-Hope** [comment]
我个人认为评分大可不必了。如果想的话，我们可以实现一下Giscus的reaction
