### ISSUE TITLE
[Bug]: `MONGO_OPT_SSL` is in docs, but not found in actual code

### ISSUE THREAD

**Issue by Mister-Hope** [walinejs/waline#1434]
### 问题描述 | Describe the bug

.

### 问题网站 | Website URL

Not related

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
https://github.com/walinejs/waline/blob/main/packages/server/src/config/adapter.js#L50-L56
