### ISSUE TITLE
[Bug]: GIF search render abnormal

### ISSUE THREAD

**Issue by lizheming** [walinejs/waline#1449]
### 问题描述 | Describe the bug

GIF search render nothing while request has responded data.

### 问题网站 | Website URL

https://waline.js.org

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/193437080-7da26b7a-c0c7-4124-a2db-2f7f7aece040.png)

What do you mean by render abnormal? Are you sure you are using a proxy? I can not access tenor api v1 without proxy here.

**Comment by Mister-Hope** [comment]
Oh I got you, changing search word quickly does have issues.

**Comment by Mister-Hope** [comment]
Fixed in https://github.com/walinejs/waline/commit/2b4bc1cb433d12bb7bb2b1951e97471d8a722c0b
