### ISSUE TITLE
[Feature]: Reaction configure

### ISSUE THREAD

**Issue by Mister-Hope** [walinejs/waline#1451]
### 功能概述 | Describe the feature

Currenly reaction api is absolutely not complete enough for users.

We should give users ability to change reaction and adjust their position.

## possible solution

We should let users bind a key with the reaction:

E.g.:

```js
[
  ['happy', 'https://example.com/happy.png'],
  ['sad', 'https://example.com/sad.png'],
]
```

So that users can:

- change their position
- replace some reactions
- add removed reactions back while holding the counter when reaction is removed

**Comment by lizheming** [comment]
I'm not sure I have got you meaning.
- change theire position: use flex order property can easily achieve it.
- replace some reactions: just replace reaction image and locale text.
- add removed reactions back while holding the counter when reaction is removed: append new reaction into reaction property and use css `display:none` to remove old reaction. 

At the beginning of the design, I want reaction is light weight. So I use `reaction[0-9]` to  represent them. If we use a meaningful key to represent it, it will lose some extensibility.

**Comment by Mister-Hope** [comment]
We just ignore css tricks's difficulty you meation above to noob users.

The solution you provided here, means users can use maxium to 9 reactions from time to time. If they already have 9 reactions used( removed or currenly using) but they want one more reactions, they will have no idea.

I think that people would perfer a `reaction name => reaction counter` map stored, so that they can configue each reaction with id and images they want in their own order.

**Comment by Mister-Hope** [comment]
However, if you do think that holding a reaction map in database have issues comparing with 9 subject with number, I can add some new code to provide builtin support, something like:

(id only support 0-9)

```js
[
  {id: 4, img: 'https://example.com/happy.png'},
  {id: 2, img: 'https://example.com/sad.png'},
]
```

I don't think we should expect users to do the tricks like `flex with order` and `hide reactions`

**Comment by lizheming** [comment]
> The solution you provided here, means users can use maxium to 10 reactions from time to time. If they already have 10 reactions used( removed or currenly using) but they want one more reactions, they will have no idea.

This is not correct, user can use `reaction<number>` without 10 limit, just config reaction map image list.

**Comment by Mister-Hope** [comment]
But the built-in table only have reaction0 - reaction9. 

Our dicussion centrl point is actually choosing from:

- some reaction columns with number stored with speed and structure benifit in database, but confusing "id number" to users at frontend and tricky things to provide sorting and hiding.
- a reaction\<name-counter\> map stored with json, but much more better understanding using string id in configurations. Also the client doesn't need any tricky css, and users can have better locale settings.

**Comment by Mister-Hope** [comment]
Obvoiusly I prefer the second one

**Comment by Mister-Hope** [comment]
I ask some feedback from my theme QQ group, and they all confused about the options, and I adready met users simply adjust the reaction array images, and ask why the counter is incorrect and what he should do.

**Comment by lizheming** [comment]
> But the built-in table only have reaction0 - reaction9.

Code can't express unlimited by a limit map. So I use a number which may be satisfied much user. And will give unlimited solution answer when user take a issue or discussion.


> I ask some feedback from my theme QQ group, and they all confused about the options, and I already met users simply adjust the reaction array images, and ask why the counter is incorrect and what he should do.

Please let them make a new issue in waline, I'll answer them. and I'm not ready change the reaction api right now, so it won't make user update confused.

**Comment by Mister-Hope** [comment]
So dear users, I failed to convince lizheming. Here is an example

If you want `[f, b, c, d]` after you set `[a,b,c,d,e]`, do the following thing:

```js
{
  reactions: [
     // maintain them
     'https://example.com/a.png',, // a was set but no longer wanted
     'https://example.com/b.png',
     'https://example.com/c.png',
     'https://example.com/d.png',
     'https://example.com/d.png',, // e was set but no longer wanted
     // add your new reactions at the end
     'https://example.com/f.png',
   ]
}
```

```css
// hide a as it's first chind
.wl-reaction > li:nth-child(1) {
  display: none
}

// hide e as it's 5thchind
.wl-reaction > li:nth-child(5) {
  display: none
}

// sort f as first
.wl-reaction > li:nth-child(6) {
  order: 1;
}
```

**Comment by sysiocn** [comment]
Click to pop up, how to modify, and use hugo.
![image](https://github.com/walinejs/waline/assets/169319943/3171eef9-7de8-49e4-a3b8-91c18394c204)
