### ISSUE TITLE
data部署，添加环境变量后提示未初始化

### ISSUE THREAD

**Issue by weaving-dreams** [walinejs/waline#1452]
### 问题描述 | Describe the bug

data部署，添加环境变量后提示未初始化

### 问题网站 | Website URL

https://spt5wx.deta.dev/

### 服务部署在哪里？ | Where your waline deploy?

Deta

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
配置了 LeanCloud 环境变量了么，`Not initialized` 就是没有配置
