### ISSUE TITLE
[Bug]: 无法取消置顶

### ISSUE THREAD

**Issue by ZvonimirSun** [walinejs/waline#1493]
### 问题描述 | Describe the bug

![image](https://user-images.githubusercontent.com/22871764/194741305-edb222d4-3f1b-4c57-8463-30d6fbb1c61b.png)

- 数据库里sticky字段为numeric类型
- 镜像为刚拉的最新的 lizheming/waline:alpine
- 页面使用最新的hexo-next包，页面引用waline.js版本2.13.0
- `/comment`接口返回的sticky类型为string类型，有可能因为这个导致前端判断置顶逻辑存在问题

![image](https://user-images.githubusercontent.com/22871764/194741394-e0f5231b-524c-40b8-8b94-5c80a6f7ba67.png)

### 问题网站 | Website URL

https://wl.iszy.xyz

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

PostgreSQL

**Comment by kjcy8** [comment]
我的置顶了 还是会掉下来。

**Comment by ZvonimirSun** [comment]
> 

我那边看是正常置顶的，就是不能取消置顶，你那边不能置顶是不是加载的@waline/client不是最新的。

**Comment by kjcy8** [comment]
底下显示是最新版 Powered by Waline v2.13.0

**Comment by ZvonimirSun** [comment]
> 底下显示是最新版 Powered by Waline v2.13.0

我也这么显示，不过是能正常置顶的，应该是你的用户没有权限在我这边置顶，只有管理员才能执行

**Comment by lizheming** [comment]
@kjcy8 如果是你自己那边有问题，无法置顶，可以再开一个 issue 咨询一下。
