### ISSUE TITLE
[Bug]: 文章反应表情计数无法正常显示

### ISSUE THREAD

**Issue by zhonger** [walinejs/waline#1508]
### 问题描述 | Describe the bug

如下图所示，当启用文章反应功能，发现刷新页面表情右上角的数字无法正常显示。
![image](https://user-images.githubusercontent.com/12064158/196038376-f45d52bb-845b-40eb-a989-167013f3b766.png)

查看了一下 deta 的 Counter 表里的数据，如下所示：

![image](https://user-images.githubusercontent.com/12064158/196038495-fdc1c4e3-2c3e-4246-bbc2-921481510e58.png)

同一页面时无论点哪个表情，都是 time +1。

### 问题网站 | Website URL

https://h2o-ac.lisz.me/tech/new-theme-h2o-ac.html

### 服务部署在哪里？ | Where your waline deploy?

Deta

### 数据存储在哪里？| Where your comment data store?

Deta Base

**Comment by lizheming** [comment]
Reaction 功能需要升级 Waline 服务端到 >= 1.23.0 才可正常实用，你现在是 1.18.5 的版本，升级一下吧。
