### ISSUE TITLE
[Bug]: 更新阅读统计数API接口报错

### ISSUE THREAD

**Issue by mbsky1213** [walinejs/waline#1510]
### 问题描述 | Describe the bug

如图所示，更新阅读统计数API  `POST /article`  报错  
参数为 `{ "path":"/blog/articles/63426cb91b4967a650f3d4c0" }`

![image](https://user-images.githubusercontent.com/69257067/196148144-4e200b2a-312a-493c-8bef-da67874b552d.png)

其他API正常运行

### 问题网站 | Website URL

https://comment.mbsky.tk/article

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

MongoDB

**Comment by lizheming** [comment]
`@waline/vercel@1.24.1` 已修复，感谢反馈
