### ISSUE TITLE
[Bug]: 无法绑定推特

### ISSUE THREAD

**Issue by NichtsHsu** [walinejs/waline#1512]
### 问题描述 | Describe the bug

在账号管理界面，点击绑定推特按钮：

![image](https://user-images.githubusercontent.com/35688135/196322586-2a70ad9e-ce1b-4ff8-8660-0746931aec5e.png)

打开一个新页面，显示：

![image](https://user-images.githubusercontent.com/35688135/196322632-ada7ba7b-e39f-432e-9286-e732d061fea9.png)

```json
{"errno":403,"message":"403 - \"<?xml version='1.0' encoding='UTF-8'?><errors><error code=\\\"415\\\">Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings</error></errors>\""}
```

### 问题网站 | Website URL

https://waline.nihil.cc/ui#

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by NichtsHsu** [comment]
另外一方面，我打开 https://waline.nihil.cc/ui# （自定义域名）总是会自动跳转到 https://waline.nihil.cc/ui/profile ，如果用 https://myblog-comments.vercel.app/ui# （原始域名）就不会，不知道为什么。

**Comment by lizheming** [comment]
1. Twitter 第三方登录目前有问题
2. 跳转 profile 可能是登录账户非管理员的原因

**Comment by NichtsHsu** [comment]
> 跳转 profile 可能是登录账户非管理员的原因

我看出来了，我当时注册管理员账号用的是 nichtsvonchaos@gmail.com，然后在自定义域名里用的是 Github 登录的，登录进去显示 NichtsVonChaos@gmail.com，不是同一个账号了

**Comment by Mister-Hope** [comment]
这个之前在其他回答讨论过，根据Email的最初bfc，没有任何规定email用户名是不区分大小写的。换言之它可以区分大小写，也就是A和a作为不同用户名是合法的。所以一个行之有效的解决办法就是如果你使用的邮箱不区分大小写，均修改为相同的大小写格式。

**Comment by lizheming** [comment]
Twitter 登录已处理，登录问题已回复。
