### ISSUE TITLE
[Bug]: 在shadowDOM 环境中无法唤起表情选择的popup

### ISSUE THREAD

**Issue by canyuegongzi** [walinejs/waline#1516]
### 问题

详细展示  [示例](https://wu-component.github.io/component-plus/Complex/Comment.html)

该页面中有两个使用实例，一个未启用 shadowDOM  的webcomponent 组件可以正常唤起表情选择器，另外一个开启 shadowDOM 的情况下无法选择表情，想咨询下作者 walinejs 内部对点击逻辑是不是又特殊处理。

### 关于为什么封装WebComponent
*. 更加便捷的接入使用评论组件，如普通 HTML 标签一般，也可以做到更好的样式隔离。

### 问题网站 | Website URL

https://wu-component.github.io/component-plus/Complex/Comment.html

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
看了下代码，好像没做什么特别的逻辑，onclick 的时候直接就是修改状态 https://github.com/walinejs/waline/blob/main/packages/client/src/components/CommentBox.vue#L99

**Comment by Mister-Hope** [comment]
我不认为 Waline 代码有什么问题，最近比较忙，建议自查封装代码并确认跨域问题没有影响组件运行。

**Comment by Mister-Hope** [comment]
另外我们本身也计划过提供 WebComponents，但是因为涉及到非可序列化的属性（部分属性是函数），就搁置了。有兴趣可以提一个 PR（你可能不能直接使用 Vue 提供的自定义组件能力，需要自己封装一个 wrapper 并通过为 property 创建 proxy 或 getter/setter 来处理那几个函数属性。）
