### ISSUE TITLE
[Bug]: 通知邮件内容显示出错

### ISSUE THREAD

**Issue by website-pages** [walinejs/waline#1524]
### 问题描述 | Describe the bug

如图
![image](https://user-images.githubusercontent.com/103917160/197346662-41096ff6-86ee-4d25-8788-1c6a4858da72.png)

### 问题网站 | Website URL

waline.wzxabc.eu.org

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
`@waline/vercel@1.25.0` 已修复，感谢反馈。
