### ISSUE TITLE
[Bug]: 评论查看者时区与服务端时区不一致时，评论相对时间错误

### ISSUE THREAD

**Issue by ghost** [walinejs/waline#1539]
### 问题描述 | Describe the bug

评论服务器时区、评论者时区、查看评论者时区均为 GMT+1100 (Australian Eastern Daylight Time)
评论后显示 x 秒之前，刷新后变为 3小时前，正好为我所在的时区和 UTC+8 的差值。

### 问题网站 | Website URL

https://waline.hertz.zone

### 服务部署在哪里？ | Where your waline deploy?

VPS, VirtualHost

### 数据存储在哪里？| Where your comment data store?

SQLite

**Comment by lizheming** [comment]
服务器时区辛苦截图 check 一下，以及对应的评论 sqlite 数据库里存储的时间截图提供一下，还有就是发布评论的时候，后台程序在终端上也有一些日志的数据，里面有时间，辛苦也一并提供一下，感谢。

**Comment by HertzYang** [comment]
`ENV TZ Asia/Shanghai`

🤔 原来是服务端 Docker 容器内的时间是 CST。
但是应该还是有问题？F12 看它回复的时候就是给了一个时间字符串，不应该是给一个时间戳让浏览器按照本地时间自行计算吗。

**Comment by lizheming** [comment]
这个之后我处理下
