### ISSUE TITLE
[Bug]: 文档网站写错了

### ISSUE THREAD

**Issue by alca7raz** [walinejs/waline#1548]
### 问题描述 | Describe the bug

cloudbase写成clodbase

### 问题网站 | Website URL

https://github.com/walinejs/waline/blob/abe74f4ee6b404540483b7c2070d01ecbf209806/README_CN.md?plain=1#L33

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

CloudBase

**Comment by Mister-Hope** [comment]
PR welcome. It will be easy to fix it.
