### ISSUE TITLE
[Bug]: 重新导入数据后数据异常

### ISSUE THREAD

**Issue by skyreeves** [walinejs/waline#1575]
### 问题描述 | Describe the bug

我的hexo博客使用 `abbrlink` 插件优化了文章的链接，导致文章之前的评论丢失，于是我将评论数据导出手动修改涉及到的`"url":` ，然后在后台重新导入，而每次导入快成功就显示500错误。在后台的`评论`里能看到所有数据都在，而在博客上看只有新的评论，给评论的回复都没了。之后我去vercel重新部署发现问题依旧，去leancloud删掉了所以评论以及用户数据，再到waline后台导入，问题依旧。
涉及到我修改`"url":` 的只在文章里面，而主页**关于**页面的对话也异常了

此waline.json删掉了用户部分，其余未做更改：

### 问题网站 | Website URL

https://skyreeves.cn

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
`@waline/admin@0.23.1` 已修复该问题，请等待 CDN 版本生效并清楚浏览器缓存确保前端代码最新。
