### ISSUE TITLE
[Bug]: 打开文章后文章反应计数的显示不正确

### ISSUE THREAD

**Issue by meicha** [walinejs/waline#1576]
### 问题描述 | Describe the bug

问题站点：https://yuanmoe.com/
使用主题：vuepress-theme-hope
站点仓库地址：https://github.com/yuanmoe/blog
复现方法：从主页选择一篇文章，点击进入，此时显示的文章反应计数不是正确的
[错误计数截图](https://user-images.githubusercontent.com/48853590/200999423-1d4721d1-7a22-47de-a197-0d8825db8de5.jpeg)
刷新当前页面能够显示的是正确计数
[刷新后显示正确计数截图](https://user-images.githubusercontent.com/48853590/200999478-df6b569a-e072-423a-9f82-8cac14333dd1.jpeg)
我跪了

### 问题网站 | Website URL

https://yuanmoe.com/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
群里帮忙排查了下，这个是因为主题在切换路由的时候 Waline 拿到的 path 还是上一级的 path 导致 Reaction 获取的还是上一级页面的数据的原因。该问题和 Waline 关系不大，已让 issuer 自行处理主题的问题。

**Comment by Mister-Hope** [comment]
This is a bug of \@waline/client. cc @lizheming .

I think that Reaction component is written by you, however, the component is not "reactive" with config, when we use Waline.instance to update path (and maybe other things), it will not refresh itself.
