### ISSUE TITLE
[功能]：关闭后台用户注册功能以及专属标签的功能建议

### ISSUE THREAD

**Issue by yuanmoe** [walinejs/waline#1580]
### 功能概述 | Describe the feature

注册用户发布评论和管理员一样头像显示绿对钩，还可以自定义专属标签。
很容易让别人误认为是博主。(我要独享绿对勾和传输标签)

**Comment by yuanmoe** [comment]
如果管理员可以设置是否让部分用户有头像绿对勾和专属标签也挺好

**Comment by yuanmoe** [comment]
然后还希望专属标签可以自定义文字颜色和方块的背景颜色

**Comment by lizheming** [comment]
https://github.com/walinejs/waline/issues/858
