### ISSUE TITLE
[Bug]: 网页显式将您重定向的次数过多。HTTP 308 状态码。

### ISSUE THREAD

**Issue by shaoyaoqian** [walinejs/waline#1581]
### 问题描述 | Describe the bug

使用vercel提供的域名能正常访问，使用自定义域名之后无法访问。

### 问题网站 | Website URL

https://waline.pengfeima.cn/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by shaoyaoqian** [comment]
我使用的是cloudflare的域名解析，使用代理会出现这个错误，如果不使用就不会出现错误。

![image](https://user-images.githubusercontent.com/115222128/201823278-2a1805fb-5859-42b8-9554-df7e8396d7a3.png)

**Comment by lizheming** [comment]
很有可能是因为 Vercel 本身也是走了 CF 代理的原因，既然不代理能正常那就别代理了吧。

**Comment by 8bytes-code** [comment]
在使用cloudflare部署之后，我也遇到了网页重定向308的问题，并且关闭代理状态没有解决问题，后面我发现需要将cloudflare的 SSL/TLS 的加密模式设置为完全（Full）才解决了问题。估计也是因为vercel发布的项目有自己的ssl证书吧，不需要用cloudflare的
