### ISSUE TITLE
[Bug]: UnauthorizedError: Unauthorized

### ISSUE THREAD

**Issue by niliovo** [walinejs/waline#1583]
### 问题描述 | Describe the bug

UnauthorizedError: Unauthorized

    at Object.throw (/app/node_modules/koa/lib/context.js:97:11)

    at module.exports.putAction (/app/node_modules/@waline/vercel/src/logic/comment.js:250:28)

    at /app/node_modules/think-logic/index.js:51:37

    at processTicksAndRejections (node:internal/process/task_queues:95:5)

### 问题网站 | Website URL

https://waline.808688.xyz/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by niliovo** [comment]
> 

可是我另一个部署在docker上，试了mysql和sqlite都是这种情况，不知道是怎么了

**Comment by shaoyaoqian** [comment]
昨天还好好的

**Comment by skyreeves** [comment]
我将数据库从国际版leancloud迁到国内版之后问题依旧。

**Comment by lizheming** [comment]
设置了 `LOGIN=force` 了？看下配置的变量。

**Comment by niliovo** [comment]
没有添加，还是很久之前的配置

发自我的iPad


------------------ Original ------------------
From: Austin Lee ***@***.***&gt;
Date: Wed,Nov 16,2022 7:38 PM
To: walinejs/waline ***@***.***&gt;
Cc: niliovo ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [walinejs/waline] [Bug]: UnauthorizedError: Unauthorized (Issue#1583)





 
设置了 LOGIN=force 了？看下配置的变量。

**Comment by Azad-sl** [comment]
我也是，今天一早就不行了

**Comment by shaoyaoqian** [comment]
我明天也弄一个博客，再弄个友链嘿嘿

**Comment by Yuumi0221** [comment]
我也是，刚刚还能评论的，突然就不行了呜呜呜

**Comment by Mister-Hope** [comment]
Closed by https://github.com/walinejs/waline/pull/1586
