### ISSUE TITLE
[Bug]: 表情包搜索禁用无效

### ISSUE THREAD

**Issue by yuanmoe** [walinejs/waline#1592]
### 问题描述 | Describe the bug

设置了 search: false, 搜索框依然在
![image](https://user-images.githubusercontent.com/117996224/202591988-7f4bb2e2-d803-46e9-add9-dd50f6aeb8c8.png)
![屏幕截图 2022-11-18 085434](https://user-images.githubusercontent.com/117996224/202591869-81a94d77-2782-4fe4-bda6-2baa387fd217.png)

### 问题网站 | Website URL

https://yuanmoe.com/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by Mister-Hope** [comment]
https://github.com/walinejs/waline/commit/ede9a8aa74fc4b633de2230c4be21b7ab1771c8b
