### ISSUE TITLE
[Bug]: Installing English as default

### ISSUE THREAD

**Issue by shinokada** [walinejs/waline#1623]
### 问题描述 | Describe the bug

When I installed waline on Deta, the language is Chinese.
Is there any way I can change the default language as English?

![image](https://user-images.githubusercontent.com/147320/204672287-c0f5ac74-fcc3-4a78-bdbc-be0beb9b5b39.png)

### 问题网站 | Website URL

https://tcs1qs.deta.dev/

### 服务部署在哪里？ | Where your waline deploy?

Deta

### 数据存储在哪里？| Where your comment data store?

Deta Base

**Comment by lizheming** [comment]
Thank you for your report, I'll fix it later.

Right now, https://tcs1qs.deta.dev/?lng=en you can use `lng` parameter to change the language. 

PS. Waline also support Japanese language https://tcs1qs.deta.dev/?lng=jp . 

And the homepage is for debug usage. You can ignore it. You should use `@waline/client` when you inject waline to your site https://waline.js.org/en/guide/get-started.html#assign-domain-optional . Then you can use `lang` props to change language https://waline.js.org/en/reference/component.html#lang .
