### ISSUE TITLE
[Feature]: Add "Edit on GitHub" button to Docs

### ISSUE THREAD

**Issue by candideu** [walinejs/waline#1630]
### 功能概述 | Describe the feature

Hello! I would like to help with editing the English docs. Would it be possible to add a "Edit this page on GitHub" button to help with this? Here are some Vuepress docs that might be relevant: https://vuepress.vuejs.org/theme/default-theme-config.html#git-repository-and-edit-links

**Comment by Mister-Hope** [comment]
![Screenshot_2022-12-03-02-34-35-98_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/33315834/205362554-7c0a4d5c-ea54-4326-bb50-62c2f56cd56a.jpg)

What's this?

**Comment by candideu** [comment]
Oops, I see that it's there. Didn't notice it initially
