### ISSUE TITLE
[Bug]: sqlite升级到1.24.1和1.25.1等版本无wl_Users表，用户注册不成功

### ISSUE THREAD

**Issue by YYQHoro** [walinejs/waline#1647]
### 问题描述 | Describe the bug

```
docker run -d \
  -e SQLITE_PATH=/app/data \
  -e JWT_TOKEN=xxxxx \
  -e SECURE_DOMAINS=https://hiyyq.cn \
  -e AVATAR_PROXY=robohash \
  -p 127.0.0.1:xxxxx \
  -v /home/yyq/blog/data:/app/data \
  --restart always \
  lizheming/waline:1.24.1
```
![image](https://user-images.githubusercontent.com/8943323/206866938-fe5f91db-b582-44ec-9588-dd8e77220c90.png)

而且老版本sqlite文件已存在的情况下，这个新版本一部署就把老数据干掉了，我哭死，升级前恰好这次忘记备份了。。

试了1.24.1和1.25.1版本，均存在此问题

### 问题网站 | Website URL

hiyyq.cn

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

SQLite

**Comment by lizheming** [comment]
我试了下没有这个问题，你看下是不是你自己的 docker volume 映射没映射成功导致 sqlite 还在 docker 容器里，而没有到映射到本地。听你的情况感觉比较像这个问题。

**Comment by YYQHoro** [comment]
已经映射到本地了，所以才会把本地的清空。部署脚本都是同一个，只是改了镜像tag名。我是从最老的版本一下子升上来的，忘记以前是多少了。。至少是2021年的版本了。本地的waline.sqlite没有后来新增的那些表，这会不会是导致问题的原因
![image](https://user-images.githubusercontent.com/8943323/208248124-dd4bd590-947b-45bf-86fc-f1e17e55dcc9.png)

**Comment by YYQHoro** [comment]
thinkjs是会自动升级本地的sqlite数据库表结构到最新的版本吗？从代码上似乎没看到升级sql的地方，每次数据库的相关PR都是修改sql和修改sqlite文件

**Comment by lizheming** [comment]
目前不会自动升级表结构，表结构需要自己自行对齐一下。涉及到表结构的修改我应该都会在更新通知里说明的，可以关注一下。
