### ISSUE TITLE
reaction的bug

### ISSUE THREAD

**Issue by qystudio0** [walinejs/waline#1680]
### 问题描述 | Describe the bug

点一下会+1再点一下就会-1，不停点可以点成0

### 问题网站 | Website URL

waline.js.org

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by qystudio0** [comment]
![261bbae0576777ee.jpg](https://user-images.githubusercontent.com/78479629/208820883-ffb201c6-3b9e-4297-ac5b-26901c1c3128.jpg)
![3163bb18133860bd.jpg](https://user-images.githubusercontent.com/78479629/208820903-ed4a17a5-b49d-4704-bbd1-d7c96f11e9ed.jpg)

**Comment by Mister-Hope** [comment]
https://github.com/walinejs/waline/commit/ab4fee485f6fe082190289c4c9929528e5c4cb9f
