### ISSUE TITLE
[Feature]: Netlify的部署

### ISSUE THREAD

**Issue by cloudw233** [walinejs/waline#1684]
### 功能概述 | Describe the feature

如题，vercel目前在中国大陆难以访问，想要将评论系统部署到netlify，将example文件夹部署到netlify，
build command和vercel设置的一致，仍然无法访问。添加此功能，谢谢
谢谢

**Comment by cloudw233** [comment]
我并没有JS方面的基础，无法进行移植，对不起。
恳请您对netlify进行适配

**Comment by XiaMoHuaHuo-CN** [comment]
dns解析改为 `cname-china.vercel-dns.com` 就完事了

**Comment by lizheming** [comment]
已支持 https://waline.js.org/guide/deploy/netlify.html
