### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Steven-WZH** [walinejs/waline#1685]
### 问题描述 | Describe the bug

评论上传图片发送后，表情按钮消失，直接使用表情代码也不行
![image](https://user-images.githubusercontent.com/113268133/209106996-51141758-ad54-45f9-8a60-ccbdb0c7f3d9.png)

### 问题网站 | Website URL

https://blog.steven.tk

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by Mister-Hope** [comment]
Hi bro I am getting COVID-19 and I will rest in the comming days, so checks and fix will probably get delayed.

**Comment by Steven-WZH** [comment]
That's fine.Have a good rest!

**Comment by Mister-Hope** [comment]
Shoudl be fixed in v1.24.4
