### ISSUE TITLE
[Bug]: ip2region 默认采用的 IP 数据库偏老

### ISSUE THREAD

**Issue by greenhat616** [walinejs/waline#1714]
### 问题描述 | Describe the bug

![图片](https://user-images.githubusercontent.com/41122242/210481489-9130e382-e81e-4a55-88ec-25c5b4d0e69c.png)
![图片](https://user-images.githubusercontent.com/41122242/210481553-bafbbb8f-6cc0-4b7f-a5e7-f0002970a948.png)

* 很多比较新的 IP 段不能准确识别，尤其是移动的
* 官方宣称不再支持 IPV6 —— 这意味着 IPV6 无法识别

### 问题网站 | Website URL

https://i.a632079.me/posts/youre-not-late-youre-not-early/

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

MySQL

**Comment by Mister-Hope** [comment]
I am expecting issues like this contains a proper solution.

**Comment by greenhat616** [comment]
> I am expecting issues like this contains a proper solution.
@Mister-Hope 如果只解析 ipv4 的话，也许我们可以采用`纯真 IP 库 社区版`的数据源？我不太了解 `ip2region` 的数据库 `xdb` 的工作原理，不知道该怎么做他们之间数据库的转换。


有关 ipv6 方面，我也没有太大的建议。貌似现有的国内常用的 IP 查询脚手架都没支持的计划，因此这应该算一个 `feature request`
不过 ipv6 的基本数据库也许可以从下面入手？不过就是不知道能不能精确到地区：
[Maxmind-GeoLite](https://dev.maxmind.com/geoip/geolite2-free-geolocation-data?lang=en)
[DB-IP](https://db-ip.com/db/lite.php)
[IP2Location](https://lite.ip2location.com/ip2location-lite)

**Comment by lizheming** [comment]
`@waline/vercel@1.26.3` 增加了 `IP2REGION_DB` 环境变量能够自定义 IP 数据库配置，可以参考 https://github.com/lionsoul2014/ip2region

**Comment by nanqic** [comment]
@lizheming 请问`IP2REGION_DB` 环境变量在vercel部署的是不是没法用？

顺便提个想法，我想整合 https://github.com/yumeiqiang/dy-node-ip2region 和 https://github.com/yumeiqiang/dy-node-ip2region，当遇到ipv6地址时掉用后者的解析，v4的不变？是否欢迎提交pr？

https://github.com/walinejs/waline/blob/db932b2f860a4246c2e2efa690fa335e21c70398/packages/server/src/extend/think.js#L73

是不是只适配 `regionSearch.btreeSearch( )`就可以了
