### ISSUE TITLE
[Bug]: 使用Hexo + Butterfly主题布置博客无法显示侧边栏最新评论

### ISSUE THREAD

**Issue by wq-ls** [walinejs/waline#1739]
### 问题描述 | Describe the bug

我先查看f12查看了报错。
<img width="944" alt="image" src="https://user-images.githubusercontent.com/50230939/211726967-bf004852-f99e-414f-b0bf-f88dde131618.png">
发现其指向（https://app-production-2ffc.up.railway.app//comment?type=recent&count=6&lang=zh-CN）
查看railway详细信息，显示"NotFoundError: url //comment not found."
![image](https://user-images.githubusercontent.com/50230939/211727224-4992b868-48f0-46d7-9c9d-b1c1e7504f3a.png)
另外部署日志也显示了报错，但是我的评论系统可以正常评论和显示，就是博客主页显示最新评论有问题。
![image](https://user-images.githubusercontent.com/50230939/211727375-3de6d77c-b3ad-4645-ada5-1efa93a2bb6b.png)

### 问题网站 | Website URL

https://wq-ls.github.io/     https://app-production-2ffc.up.railway.app/

### 服务部署在哪里？ | Where your waline deploy?

Railway.app

### 数据存储在哪里？| Where your comment data store?

PostgreSQL

**Comment by wq-ls** [comment]
已经解决，“serverURL:” 配置的问题，URL最后不要加“/”

**Comment by musnows** [comment]
> 已经解决，“serverURL:” 配置的问题，URL最后不要加“/”

抱歉，我只搜索了跨域访问相关的issue，没有看到这个。目前问题已解决！
