### ISSUE TITLE
博主标志显示重复了好像

### ISSUE THREAD

**Issue by yangblaze** [walinejs/waline#1740]
### 问题描述 | Describe the bug

![image](https://user-images.githubusercontent.com/93808587/212143543-49599e67-af1d-49a5-9239-6a46513812bf.png)

### 问题网站 | Website URL

https://yangblaze.github.io

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by Mister-Hope** [comment]
你确定你自己没画蛇添足地给自己加了个同名的自定义头衔？

**Comment by lizheming** [comment]
博主可以单独在客户端设置标签，不用在后台用户那设置标签~
