### ISSUE TITLE
[Bug]: waline数据迁移导入数据报错:NOT NULL constraint failed,响应:500: Internal Server Error

### ISSUE THREAD

**Issue by krau** [walinejs/waline#1747]
### 问题描述 | Describe the bug

尝试使用waline后台的导入导出数据功能，将服务端由vercel迁移为自部署。
导出数据正常，将导出后的json文件导入到自部署的后端时，弹出 500: Internal Server Error，无法完成导入。

![图片](https://user-images.githubusercontent.com/71133316/212457059-4e11b669-e687-45e6-807d-0ff56a6defc8.png)

后台日志报错: 
[Error: SQLITE_CONSTRAINT: NOT NULL constraint failed: wl_Comment.status] {
  errno: 19,
  code: 'SQLITE_CONSTRAINT'
}
![图片](https://user-images.githubusercontent.com/71133316/212457122-db7d5376-0d7e-4d49-80f7-79a67c276cfe.png)

---
补充：
我原先的服务端是部署在vercel上，数据库存储使用的 leancloud
现在我想迁移到自己的主机上，用docker部署，并使用本地sqlite作为数据库

自己排查的时候，在自部署的waline中发了测试评论并导出，发现和原先部署在vercel的导出的数据结构有一定的不同。不知道是否是这个原因导致的。对比截图如下，右为原先的导出数据
1. comment 
![图片](https://user-images.githubusercontent.com/71133316/212457408-6818e1e4-f27d-473f-ac55-fddc84e4548a.png)
2. Users
![图片](https://user-images.githubusercontent.com/71133316/212457485-d44031b5-0692-4ba9-846a-a04068a9da90.png)

### 问题网站 | Website URL

如有需要我可以提供我后台的管理账户以供复现

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

SQLite

**Comment by lizheming** [comment]
是不是包含了历史的 Valine 的数据，看下导出的 comment 数据，是不是有 `status` 不为 `approved`, `waiting`, `spam` 或者不包含 `status` 字段的数据，自己修改下导出的数据补全下再试试。

**Comment by krau** [comment]
> 是不是包含了历史的 Valine 的数据，看下导出的 comment 数据，是不是有 `status` 不为 `approved`, `waiting`, `spam` 或者不包含 `status` 字段的数据，自己修改下导出的数据补全下再试试。

确实是这个问题，将所有comments都添加上status后可以正常导入
