### ISSUE TITLE
[Feature]: 评论通知对 WebHook 方式的支持

### ISSUE THREAD

**Issue by Candinya** [walinejs/waline#1752]
### 功能概述 | Describe the feature

现有的[评论通知](https://waline.js.org/guide/features/notification.html)功能基于平台进行适配，但是对于一些小众的平台（例如 matrix.org ），如果继续需求兼容会导致项目不必要的臃肿；可以在通知模块中推出一个 webhook 的通用方式，在用户需要自定义平台的通知服务时可以自己写中间件兼容，以实现通知定制的目的，并降低维护成本

例如可以在环境变量里指定逗号分隔的 webhook 串，当发生评论通知事件时将具体的参数（包括评论者是否为站点管理员之类的可用于中间件过滤的参数）以 POST json 的方式依次提交给各个需要的接口，由接口来处理模板的创建和消息的分发

**Comment by Mister-Hope** [comment]
模块化永远是一个好的idea，但是我觉得每个平台的代码大小应该可以接受吧。。。。。

**Comment by Candinya** [comment]
> 模块化永远是一个好的idea，但是我觉得每个平台的代码大小应该可以接受吧。。。。。

对的，单看一个平台问题不大，但如果各种小众平台提一个支持一个的话，像环境变量和模板之类的东西容易糊成一团，文档也会变长；所以就想一个通用支持方案（即使用不上也不会占用太多资源），这样就算之后有什么接口需要调整的时候也就不需要麻烦主仓库改来改去了

**Comment by lizheming** [comment]
https://waline.js.org/reference/server/env.html#%E9%AB%98%E7%BA%A7%E9%85%8D%E7%BD%AE 很早就支持了的功能

**Comment by Candinya** [comment]
啊好的，谢谢 🙏
