### ISSUE TITLE
[Feature]: 关于图床配置安全性的建议

### ISSUE THREAD

**Issue by Inetgeek** [walinejs/waline#1755]
## 存在的问题
目前如果设置了第三方图床API，假设开启了强制登录功能，则访问者在评论区可以直接上传图片，且请求信息里泄露了第三方图床的API地址和token，这样会导致自己付费购买的图床服务的token暴露给其他用户而导致被滥用自己的图床。
## 建议
- 在开启强制登录的情况下点击图片上传功能不可以上传图片，防止该接口被滥用导致数据库被攻击或第三方图床被滥用；
- 希望在管理端可以设置第3放图床的API信息，可以自定义图床API请求表单的字段和类型（一般是File类型，字段可能是img/image/file），可自定义header及body的请求参数及参数类型，可自定义返回数据的url提取地址，例如`data.url`。
- 希望后端可以设置一个上传图片的路由，用来隐藏和控制未登录情况下的图片上传功能的非法使用，例如：
> 假设waline的域名为`https://waline.example.com`，则管理端为`https://waline.example.com/ui`，前端图片上传处调用`https://waline.example.com/upload`路由，再由后端来完成对第三方API的调用或写入base64图片到数据库，这样既保证了token不会被泄露在前端，也保证了图片上传功能不会被滥用。

谢谢

**Comment by lizheming** [comment]
1. 登录的成本不是很高，即使限制了登录才能上传也并没有办法做到完全杜绝滥用
2. 转发第三方接口方案过于定向了，极其依赖第三方存储，扩展性不高且治标不治本
3. 如果你真的需要这么一个接口，其实可以考虑 DIY 一下，Vercel 分配个路由映射过去，之后在客户端配上 `imageUploader` 即可

```json
{
  "name": "comment",
  "github": {
    "silent": true
  },
  "builds": [
    {
      "src": "index.js",
      "use": "@vercel/node@2.5.10"
    },
    {
      "src": "upload.js",
      "use": "@vercel/node@2.5.10"
    },
  ],
  "routes": [
    {
      "src": "/upload",
      "dest": "upload.js"
    },
    {
      "src": "/(.*)",
      "dest": "index.js"
    }
  ]
}
```

```js
// upload.js
module.export = function(req) {
    const file = req.body.file;
   // 这里添加你的上传操作
   return { url: 'xxx' };
}
```

**Comment by Inetgeek** [comment]
作者能给一个稍详细一点的DIY教程么？我对Waline的修改不是很熟orz

**Comment by Inetgeek** [comment]
假设第三方图床是https://xxx.com/api/upload，token是放在请求体里，携带了参数名为image的File类型的formdata表单数据进行提交，这样的话怎么写？

**Comment by Mister-Hope** [comment]
> 在开启强制登录的情况下点击图片上传功能不可以上传图片

图片上传功能本身就是可以禁用的

**Comment by Mister-Hope** [comment]
> 在开启强制登录的情况下点击图片上传功能不可以上传图片

图片上传功能本身就是可以禁用的

> 假设waline的域名为https://waline.example.com，则管理端为https://waline.example.com/ui，前端图片上传处调用https://waline.example.com/upload路由，再由后端来完成对第三方API的调用或写入base64图片到数据库，这样既保证了token不会被泄露在前端，也保证了图片上传功能不会被滥用。

目前登录也只是邮箱验证，用户如果想刷你的图床，直接注册之后post你接口也一样的。

**Comment by Inetgeek** [comment]
> 

但感觉开启强制登录了还能在未登录情况下上传图片不太安全，如果没有开启强制登录确实可以上传。

**Comment by Inetgeek** [comment]
我其实想单纯的不想把token暴露在前端页面里[:害羞]，因为不熟悉node.js，大佬能给一个upload.js和前端的demo代码吗？[:期待]

**Comment by lizheming** [comment]
@RamSong https://waline.js.org/reference/client/props.html#imageuploader

**Comment by RamSong** [comment]
> @RamSong https://waline.js.org/reference/client/props.html#imageuploader

谢谢啦之前也看到了这个

我的意思是服务端禁止，前端禁止不也能通过特定url上传吗？

**Comment by lizheming** [comment]
@RamSong 什么叫做特定的 URL 上传？Waline 本身就没有上传的服务。
