### ISSUE TITLE
[Bug]:  回复评论时代码段起手不会正常显示，与预览结果不同

### ISSUE THREAD

**Issue by zywvvd** [walinejs/waline#1757]
### 问题描述 | Describe the bug

回复评论时代码段起手不会正常显示，与预览结果不同
这是在 Waline 官网主页评论栏的测试效果，觉得可以证明问题确实存在
![](https://101.43.39.125/HexoFiles/vvd_file_mt/202301191152998.jpg)
我的博客上用的 2.5.1 的版本，也是这个问题
https://www.zywvvd.com/notes/hexo/theme/fluid/fluid-build-pvuv-statistics/build-pvuv-statistics
大佬们看看要不要考虑修一修 ~ 

### 问题网站 | Website URL

https://www.zywvvd.com/notes/hexo/theme/fluid/fluid-build-pvuv-statistics/build-pvuv-statistics

### 服务部署在哪里？ | Where your waline deploy?

CloudBase

### 数据存储在哪里？| Where your comment data store?

MongoDB

**Comment by Mister-Hope** [comment]
#1649
