### ISSUE TITLE
[Bug]: 后台注册不成功，但是lc数据库有未验证用户

### ISSUE THREAD

**Issue by inju0524** [walinejs/waline#1762]
### 问题描述 | Describe the bug

![Screenshot_2023-01-20-22-32-11-709_com microsoft emmx](https://user-images.githubusercontent.com/57057343/213729810-e3b0f445-0076-4dd1-b552-475c1dcc4209.jpg)
![Uploading IMG_20230120_230002.jpg…]()

如标题所示，这是报错日志，请求解决

### 问题网站 | Website URL

https://pinglun.inju.top

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by inju0524** [comment]
![Uploading IMG_20230120_230002.jpg…]()

**Comment by inju0524** [comment]
![-1a2a1dce9aa238ba](https://user-images.githubusercontent.com/57057343/213730721-ce4eb1bd-c492-482d-9acf-401ced652a3b.jpg)
![-122dd8fb18628b18](https://user-images.githubusercontent.com/57057343/213730729-6a11e783-2315-431b-a818-d1f86817b2dc.jpg)
这是我的环境

**Comment by inju0524** [comment]
![Uploading 6b6ddf975a81d1b7.jpg…]()

**Comment by inju0524** [comment]
错误代码550

**Comment by inju0524** [comment]
![Uploading 6b6ddf975a81d1b7.jpg…]()

**Comment by inju0524** [comment]
![Uploading IMG_20230120_230704.jpg…]()

**Comment by inju0524** [comment]
我排除出来了是sender_name的问题。我写的值是INJU银烛，一加这个变量就会出现那个报错问题，请问是怎么回事

**Comment by lizheming** [comment]
这个是因为你定义了 SENDER_EMAIL 的原因，163 邮箱好像不支持配置 SENDER_EMAIL，你去掉应该就可以了
