### ISSUE TITLE
[Bug]: hexo中keep主题无法适应暗黑模式

### ISSUE THREAD

**Issue by DonTequilaaa** [walinejs/waline#1763]
### 问题描述 | Describe the bug

我在 Hexo 的 Keep 主题上启动了黑暗模式，但是Waline评论区的字体颜色却是深色的，导致看不清文字。

### 问题网站 | Website URL

https://dontequilaaa.github.io/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
https://waline.js.org/guide/features/style.html#%E6%9A%97%E9%BB%91%E6%A8%A1%E5%BC%8F%E6%94%AF%E6%8C%81
