### ISSUE TITLE
[Bug]: mysql 5.5 不支持两个timestamp字段同时为CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by gobiking** [walinejs/waline#1765]
### 问题描述 | Describe the bug

mysql 5.5 不支持两个timestamp字段同时为CURRENT_TIMESTAMP，请在业务层写入时间

### 问题网站 | Website URL

http://waline.waline.49535.cn-hangzhou.fc.devsapp.net/

### 服务部署在哪里？ | Where your waline deploy?

Aliyun FC

### 数据存储在哪里？| Where your comment data store?

MySQL

**Comment by xiyki** [comment]
我的解决方法是把mysql 5.5卸载，安装了mysql 5.6，之后就能支持两个timestamp字段同时为CURRENT_TIMESTAMP

**Comment by gobiking** [comment]
> 我的解决方法是把mysql 5.5卸载，安装了mysql 5.6，之后就能支持两个timestamp字段同时为CURRENT_TIMESTAMP

我有几个2011年白嫖的阿里云的免费RDS，现在还能用，唯一的就是不给版本升级了

**Comment by lizheming** [comment]
你可以改下数据库结构，把`createdAt` 和 `updatedAt` 这两个字段的 CURRENT_TIMESTAMP 去掉，实际上这两个字段基本也没什么用，对 Waline 的功能不受影响。

**Comment by gobiking** [comment]
> 你可以改下数据库结构，把`createdAt` 和 `updatedAt` 这两个字段的 CURRENT_TIMESTAMP 去掉，实际上这两个字段基本也没什么用，对 Waline 的功能不受影响。

是的我看了下源码，所以把CURRENT_TIMESTAMP给了insertedAt
