### ISSUE TITLE
[Bug]: deta 部署的waline服务端评论跳转链接拼接错误？

### ISSUE THREAD

**Issue by appotry** [walinejs/waline#1787]
### 问题描述 | Describe the bug

deta 部署中的waline评论跳转链接是下面这样的

[/posts/4d8a0b22/](https://waline.17lai.site/'https://blog.17lai.site'/posts/4d8a0b22/)

现在最新版本的waline服务端跳转链接是下面这样的
```
https://waline.17lai.site/'https://blog.17lai.site'/posts/4d8a0b22/
```

正确跳转链接应该是
```
https://blog.17lai.site/posts/4d8a0b22/
```

前段时间使用vercel部署的时候没发现这里有问题

刚测试最新的vercel部署，同样的leancloud数据库后端，vercel部署的waline就没有这个问题  https://cfwaline.17lai.site/

### 问题网站 | Website URL

https://waline.17lai.site/

### 服务部署在哪里？ | Where your waline deploy?

Deta

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
你的 SITE_NAME 和 SITE_URL 环境变量都多打了单引号了，自己处理下吧。
