### ISSUE TITLE
[Bug]: 使用Vercel + TiDB Cloud部署后在管理面板使用GitHub登录提示"can not find service: storage/tidb"

### ISSUE THREAD

**Issue by y2-Whyto** [walinejs/waline#1788]
### 问题描述 | Describe the bug

按照官网教程部署了vercel和tidb cloud之后，访问评论管理面板（/ui），点击使用GitHub登录后提示 500 "can not find service: storage/tidb"，如下图所示：

<img width="358" alt="图片" src="https://user-images.githubusercontent.com/42339192/216814394-ffc1266b-465c-471b-b208-e3f40875de4f.png">

已经按照教程设置了环境变量：

<img width="944" alt="图片" src="https://user-images.githubusercontent.com/42339192/216814432-515d8c84-d586-4856-b138-308812edfcb6.png">

<img width="682" alt="图片" src="https://user-images.githubusercontent.com/42339192/216814474-de11c144-4073-474f-8d63-e3bf8cfa8046.png">

数据库已建立：

<img width="839" alt="图片" src="https://user-images.githubusercontent.com/42339192/216814457-7d1338dc-a728-403b-bb26-2ad239a4885a.png">

不知原因是什么，应该如何解决？

### 问题网站 | Website URL

https://cadmin.new.whyto.net/ui

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

TiDB Cloud

**Comment by lizheming** [comment]
`@waline/vercel@1.26.1` 已修复，感谢反馈
