### ISSUE TITLE
[Bug]: Vercel + TiDB Cloud部署后使用GitHub登录管理页面时提示ER_ACCESS_DENIED_ERROR

### ISSUE THREAD

**Issue by y2-Whyto** [walinejs/waline#1790]
### 问题描述 | Describe the bug

书接上回（ #1788 ），刚刚在Vercel上redeploy之后，登录管理界面，还是点击GitHub登录，这次提示的错误变成了"ER_ACCESS_DENIED_ERROR: Access denied for user 'k9PStBACSwkjk8o.root'@'10.0.99.54' (using password: NO)"：

<img width="833" alt="图片" src="https://user-images.githubusercontent.com/42339192/216820666-464656dd-b272-4fad-8297-ba0c437308c5.png">

参见 #1788 ，我已经按照教程进行了配置，其中 `TIDB_PASSWORD` 还专程重置了一次，重新填写环境变量再部署，依然是这个提示。不知道是什么原因导致的。

### 问题网站 | Website URL

https://cadmin.new.whyto.net/ui

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

TiDB Cloud

**Comment by CATOOILG** [comment]
问题描述 | Describe the bug
按部就班顺着教程部署好waline后，首次启动发现和楼主一样的issue: ER_ACCESS_DENIED_ERROR: Access denied for user '4PQe24bpa4KdPyQ.root'@'10.0.99.54' (using password: NO)
在使用tidb提供的demo以及navicat均可以正常链接上访问waline - wl_Comment表，故提出疑问，感谢解答。

问题网站 | Website URL
https://waline.new.whyto.net/ui

服务部署在哪里？ | Where your waline deploy?
阿里云函数FC

数据存储在哪里？| Where your comment data store?
TiDB Cloud
