### ISSUE TITLE
[Bug]: 浏览器类型显示不正常

### ISSUE THREAD

**Issue by neila-a** [walinejs/waline#1799]
### 问题描述 | Describe the bug

使用手机Microsoft Edge发送时会识别为Chrome，但电脑不会（Android和Linux）
![图片](https://img1.imgtp.com/2023/02/11/UQH9dP3x.jpg)

### 问题网站 | Website URL

https://waline.js.org

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by Mister-Hope** [comment]
We use `ua-parser-js` to parse users ua, if you think there are any issues, fire an issue at their repo.
