### ISSUE TITLE
[Bug]: 迁移数据导入报500错误

### ISSUE THREAD

**Issue by Nemo1166** [walinejs/waline#1807]
### 问题描述 | Describe the bug

原先前端独立部署，数据库使用MySQL。现迁移到vercel + leancloud。从原站管理后台导入到新站时报如下错误。

![image](https://user-images.githubusercontent.com/38162382/219444202-a3f8bbc1-44ae-4fa0-bebe-7a2147654154.png)

控制台输出如下：

![image](https://user-images.githubusercontent.com/38162382/219444977-3579d03d-0f10-4797-9a6b-19684f4d486b.png)

两边均已更新至最新版；导出的json导入回原站点可以正常导入，新站点导入时报错。

![image](https://user-images.githubusercontent.com/38162382/219445679-149dc5f1-081e-4092-8ef0-1c7b90b2062d.png)

新站点导出的json导入回去也是500，

### 问题网站 | Website URL

如有需要可提供管理后台账密

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
提供下导出的文件，我们测试一下

**Comment by appotry** [comment]
@lizheming 遇到同样的报错，准备从vercel +lc 转移到docker 版本的waline 同样500报错 

给个邮箱，发文件给你

**Comment by Nemo1166** [comment]
> 提供下导出的文件，我们测试一下

@lizheming 已发送至邮箱[i@imnerd.org](mailto:i@imnerd.org)

**Comment by lizheming** [comment]
`@waline/admin@0.23.3` 针对 case 优化了下，后台更新下浏览器缓存后可以再试试。

**Comment by Nemo1166** [comment]
> `@waline/admin@0.23.3` 针对 case 优化了下，后台更新下浏览器缓存后可以再试试。

全新部署的服务端直接导入会报 404：LeanCloud 数据库中无 Comment 类。随便创建一条评论后可以正常导入了。

感谢 debug.
