### ISSUE TITLE
[Feature]: display Windows 10 as Windows 10/11

### ISSUE THREAD

**Issue by Ayx03** [walinejs/waline#1836]
### 功能概述 | Describe the feature

Because Windows 11 will also show up as Windows 10, and it seems that there's no way to differ Windows 11 from Windows 10 in a browser
related: #1834 
![](https://user-images.githubusercontent.com/75155322/222659908-dcdce696-6b19-4912-a42b-2a215c2a6805.png)

**Comment by lizheming** [comment]
I don't think it's a good approach, and the copy will get stinky and long when Windows is updated with a new version.

In fact, I found a solution that can better distinguish Windows 11, maybe you can take a look: https://github.com/walinejs/waline/pull/1838

**Comment by lizheming** [comment]
`@waline/client@2.14.8` and `@waline/vercel@1.26.4` has add `Windows 11` support, please try it~
![image](https://user-images.githubusercontent.com/424491/222885784-b86d4aca-f4f8-40ed-bf83-6f35e442ff6a.png)

It only compatible with some browsers like Edge or Chrome.
