### ISSUE TITLE
[Bug]: Amazon SES Emails Notifications are Not Working

### ISSUE THREAD

**Issue by ilovefreesw** [walinejs/waline#1862]
### 问题描述 | Describe the bug

After configuring the SMTP credentials, the emails are not being sent.

I have configured these ENVs:

AUTHOR_EMAIL: admin@xyz.com
SMTP_SERVICE: SES
SMTP_USER: *********
SMTP_PASS: *********

Ref: https://github.com/nodemailer/nodemailer/blob/master/lib/well-known/services.json

![image](https://user-images.githubusercontent.com/77317006/225261485-0c768403-f13d-49d5-bf92-7a1218282b31.png)

### 问题网站 | Website URL

https://walineilfs.vercel.app/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

MySQL

**Comment by Mister-Hope** [comment]
Check your logs, as well as this feature is working well for some people, then the issue is likely not on our side.

If you are setting auth issues in logs, then it's either your issue, or a problem with node mailer, or SES is failing to provide a standard smtp service.

**Comment by ilovefreesw** [comment]
There is nothing in the logs. No error/warning is shown. SES is working with the same SMTP settings in my other app. I have also tried SendPulse and that doesn't work either.

**Comment by lizheming** [comment]
Enter the Vercel background according to the operation in the screenshot, and then send a comment, and you can see the log. You can send us a screenshot to check.
![image](https://user-images.githubusercontent.com/424491/225357050-68f57bcd-9ef6-4dc0-bd1b-dc4ca6d11408.png)

**Comment by ilovefreesw** [comment]
In Logs I saw this error:

`501 Invalid MAIL FROM address`

After looking at here: https://github.com/walinejs/waline/blob/065797f888f43aa0cb80e8545ffa8e4bfa4febca/packages/server/src/controller/user.js

I found out that `SENDER_NAME` is required. I only had only configured `SENDER_EMAIL` environment variable.

So. It works now. Thanks for your help.

**Comment by ilovefreesw** [comment]
One more question.

Can it send email notification to all the admins? Because I have added multiple users in the comment management and set their role as administrator. But only the first user (which is me) is receiving the email notifications.

**Comment by lizheming** [comment]
@ilovefreesw Currently not supported, you can send a message to the mail group to solve this problem. Long-term solutions welcome PRs.
