### ISSUE TITLE
[Bug]: wl_counter 表不会更新 updatedAt 字段

### ISSUE THREAD

**Issue by liziwl** [walinejs/waline#1886]
### 问题描述 | Describe the bug

POST /article 这个接口并不会更新 wl_counter  表的 updatedAt 字段，应该是不符合预期。

Docker + MySQL 部署

### 问题网站 | Website URL

https://waline-api.liziwl.cn/article

### 服务部署在哪里？ | Where your waline deploy?

Other

### 数据存储在哪里？| Where your comment data store?

MySQL

**Comment by lizheming** [comment]
目前 updateAt 字段是冗余字段，项目中并没有使用。不过也欢迎 PR 添加修改。
