### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by suyin-long** [walinejs/waline#190]
1. 希望在评论里可以增加类似“管理员”、“新朋友”、“小伙伴”这样的标签
![2](https://user-images.githubusercontent.com/49554285/113736738-f1262c80-972f-11eb-9626-d511b118ebd3.png)
2. 希望可以对深色模式加以优化，或者增加深色模式选项，亦或者设置成跟随系统也行
3. 希望可以增加根据ip获取定位的功能
![3](https://user-images.githubusercontent.com/49554285/113736782-fedbb200-972f-11eb-8f12-5faa822eb5ad.png)
4. 希望增加取消显示评论数的按钮，且把“Waline”显示为“评论数”
5. 希望可以增加qq登录评论的功能（类似于使用Github登录一样），然后评论头像显示为qq头像，亦或直接根据qq邮箱获取qq头像
6. [自定义表情](https://waline.js.org/client/emoji.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A1%A8%E6%83%85)目前配置的时候略显麻烦，能否通过只添加cdn就可以实现自定义表情？可以参考[minivaline](https://github.com/MiniValine/hexo-next-minivaline)

**Comment by lizheming** [comment]
1. 现在已登录发布的评论有博主标签，你可以自定义文案，参考 issue https://github.com/lizheming/waline/issues/175
2. 目前提供了默认的深色模式样式，你可以通过自己在 `<body>` 上增加 `class="dark"` 来实现深色模式。
3. 可以加到 TODO 中
4. 评论数显示自行隐藏即可，底部的 `Power by` 字样也可通过配置 `copyRight: false` 或者是样式隐藏。

**Comment by suyin-long** [comment]
> 1. 现在已登录发布的评论有博主标签，你可以自定义文案，参考问题[＃175](https://github.com/lizheming/waline/issues/175)
> 2. 目前提供了替代的深色模式样式，您可以通过自己在`<body>`上增加`class="dark"`来实现深色模式。
> 3. 可以加到TODO中
> 4. 评论数显示自行隐藏即可，底部的`Power by`字样也可通过配置或是样式`copyRight: false`隐藏。

**首先多谢为我解惑**

1. 问题1：已通过在配置文件中添加如下代码解决
    ```yaml
    langMode: {
      admin: '管理员'
    }
    ```
2. 问题2：还是希望可以增加类似于在配置文件中添加如下代码实现
    ```yaml
    dark: true
    ````
3. 问题:4：已通过修改源文件解决
    
![1](https://user-images.githubusercontent.com/49554285/113735838-30a04900-972f-11eb-92c6-ccfcfc983031.png)
还有你说的 `copyRight: false` 选项亲测有用！

**Comment by code004Accepted** [comment]
@suyin-long 如果不登录就显示博主标签，那么人人都可以填你的邮箱冒充你了（

**Comment by jerryc127** [comment]
4 是你主题的问题 不是评论

**Comment by Mister-Hope** [comment]
@lizheming 看这里。。。。这个问题早就有了

**Comment by lizheming** [comment]
@Mister-Hope https://github.com/lizheming/waline/blob/c1c53a1b6b5fe6c3dd64572c693a3c3ec51fb19c/packages/hexo-next/index.js#L20-L23 看起来应该是可以通过配置修改的？

**Comment by Mister-Hope** [comment]
> @Mister-Hope https://github.com/lizheming/waline/blob/c1c53a1b6b5fe6c3dd64572c693a3c3ec51fb19c/packages/hexo-next/index.js#L20-L23 看起来应该是可以通过配置修改的？

虽然我没用过，但是从上面其他人说的来看，默认的标签名似乎是Waline？应该默认成评论吧

**Comment by Mister-Hope** [comment]
1 我们有计划做么? 我个人觉得没啥用.... @lizheming

**Comment by Mister-Hope** [comment]
另外我个人不是很看好3. 理由如下:

ip地址以及其所在位置原则上是用户隐私的一部分,不应强行收集,最起码也要让用户可以有一个选择.但是评论的时候用户选择是否允许显式地址也很怪异. 而且本质上这个东西对整个评论区影响也不大.除非一些特定的跟线下密切相关的活动类网站,否则这个信息是没什么太大帮助的,尤其是在个人博客这一块的大多数形况下.

**Comment by Mister-Hope** [comment]
其他的功能应该都已经完成.

**Comment by lizheming** [comment]
> 1 我们有计划做么? 我个人觉得没啥用.... @lizheming
> 
> 另外这个逻辑如何设计?用户首次或前N次评论是新用户,还是用户注册的前N天是新用户.

暂时无计划支持非博主的个人标签

**Comment by jerryc127** [comment]
ip定位还是算了吧
记录评论者ip
我都觉得是多余了
还要把ip地址显示出来
就没必要了 也是隐私问题

**Comment by Mister-Hope** [comment]
那就可以close了，其他建议都已完成

**Comment by Mister-Hope** [comment]
QQ有一个单独的issue在追踪。
