### ISSUE TITLE
[Bug]: UI Conflict with WordPress

### ISSUE THREAD

**Issue by Suleman-Elahi** [walinejs/waline#1910]
### 问题描述 | Describe the bug

The UI on the main website text area is leaving outside the body.

The option to drag the text are also appears outside the body.

### 问题网站 | Website URL

https://www.ilovefreesoftware.com/28/webware/generate-ux-copies-design-descriptions-headings-free-online-tool.html

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

MySQL

---
### Description of the problem | Describe the bug

The UI on the main website after deploying looks like this:

![image](https://user-images.githubusercontent.com/24384996/228503649-ef79c739-a566-4351-81d7-1a2362f88ca3.png)

The option to drag the text are also appears outside the body.

### Problem Website | Website URL

https://www.ilovefreesoftware.com/28/webware/generate-ux-copies-design-descriptions-headings-free-online-tool.html

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

MySQL

**Comment by Mister-Hope** [comment]
Resolve the style conflicts yourself
