### ISSUE TITLE
[Bug]:  hexo-butterfly获取最新评论的跨域访问的报错 || [Bug]: Hexo-butterfly gets the latest comment cross-domain access error

### ISSUE THREAD

**Issue by musnows** [walinejs/waline#1911]
### 问题描述 | Describe the bug

我在使用hexo 的butterfly主题的时候，获取最近评论出现了跨域访问的报错。我尝试直接访问这个连接，是可以正常显示结果的。博客的页面评论能正常显示，只是无法访问最近评论

![image](https://user-images.githubusercontent.com/87506951/228801716-8e9e0078-8706-49df-8bac-6c0208085644.png)

waline是部署在vercel上的，请问要如何解决这个问题？是butterfly主题的请求方式不对吗

### 问题网站 | Website URL

https://blog.musnow.top/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Description of the problem | Describe the bug

When I was using hexo's butterfly theme, I got a cross-domain access error when getting recent comments. I try to access this connection directly, and the result can be displayed normally. Comments on the blog's page are displayed normally, but recent comments cannot be accessed

![image](https://user-images.githubusercontent.com/87506951/228801716-8e9e0078-8706-49df-8bac-6c0208085644.png)

Waline is deployed on vercel, how to solve this problem? Is the request method of the butterfly theme wrong?

### Problem Website | Website URL

https://blog.musnow.top/

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud (https://leancloud.app)

**Comment by lizheming** [comment]
https://github.com/walinejs/waline/issues/1739
