### ISSUE TITLE
[Bug]: 老版本API的返回数据结构体也变为了{errno, errmsg, data} || [Bug]: The return data structure of the old version API has also changed to {errno, errmsg, data}

### ISSUE THREAD

**Issue by i-abc** [walinejs/waline#1915]
### 问题描述 | Describe the bug

如：[https://walinejs.comment.lithub.cc/article?path=/guide/features/pageview.html](https://walinejs.comment.lithub.cc/article?path=/guide/features/pageview.html)，返回 `{"errno":0,"errmsg":"","data":[{"time":2134}]}`，未能兼容老版本。

所以使用老版本 API 的 `pageview.mjs` 等也出现了错误：

![image](https://user-images.githubusercontent.com/104631897/229342240-43263aad-d89e-47f0-a276-791d3a834606.png)

### 问题网站 | Website URL

https://waline.js.org/guide/features/pageview.html

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Description of the problem | Describe the bug

Such as: [https://walinejs.comment.lithub.cc/article?path=/guide/features/pageview.html](https://walinejs.comment.lithub.cc/article?path=/guide/features/ pageview.html), returns `{"errno":0,"errmsg":"","data":[{"time":2134}]}`, which is not compatible with the old version.

Therefore, `pageview.mjs` using the old version of the API also has errors:

![image](https://user-images.githubusercontent.com/104631897/229342240-43263aad-d89e-47f0-a276-791d3a834606.png)

### Problem Website | Website URL

https://waline.js.org/guide/features/pageview.html

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud (https://leancloud.app)

**Comment by lizheming** [comment]
fixed at https://github.com/walinejs/waline/commit/08bc5047cdca43d042ffb432d90db36b3e6aff24
