### ISSUE TITLE
[Bug]: 文章访问量获取不到，显示 [object Object]

### ISSUE THREAD

**Issue by appotry** [walinejs/waline#1916]
### 问题描述 | Describe the bug

https://waline.js.org/guide/features/pageview.html

个人网站上发现获取不到，去官网看了一下，一样的问题，控制台没有发现报错

### 问题网站 | Website URL

https://waline.17lai.site/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Description of the problem | Describe the bug

https://waline.js.org/guide/features/pageview.html

I found that I couldn’t get it on my personal website, so I went to the official website to check it out. I found the same problem, but no error was found in the console.

### Problem Website | Website URL

https://waline.17lai.site/

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud (https://leancloud.app)

**Comment by lizheming** [comment]
和 #1915 是一个问题，合并到一块关注。
