### ISSUE TITLE
[Bug]: Unable to log in to the management interface

### ISSUE THREAD

**Issue by rockbenben** [walinejs/waline#1921]
### 问题描述 | Describe the bug

The login management interface of Waline@1.28.2 displays an error message indicating incorrect password. After resetting to 1.27.0, the issue was resolved and normal functionality was restored.

### 问题网站 | Website URL

https://waline.newzone.top

### 服务部署在哪里？ | Where your waline deploy?

VPS, VirtualHost

### 数据存储在哪里？| Where your comment data store?

MySQL

**Comment by lizheming** [comment]
I used the same environment locally and did not reproduce this problem. If possible, please provide the environment for reproduction and let me have a look.

**Comment by rockbenben** [comment]
The environment is stored in `/etc/environment`. The database was migrated from Leancloud to MySQL, I am not sure if this is related.

```
MYSQL_DB="waline"
MYSQL_USER="waline"
MYSQL_PASSWORD=""
AUTHOR_EMAIL=""
SITE_NAME="LearnData"
SITE_URL="https://newzone.top"
WEBHOOK=""
SECURE_DOMAINS=""
SMTP_HOST=""
SMTP_PORT=""
SMTP_USER=""
SMTP_PASS=""
TZ="Asia/Shanghai"
```

**Comment by lizheming** [comment]
What I mean is that I need a reproducible page and I will check it out, not environment variables.

**Comment by rockbenben** [comment]
I'm not sure how to provide a reproducible page either. However, I did notice that there were many warning messages when I tested version 1.30.1 today, and I'm not sure if this is related to the login issue.

1.27.0
![image](https://user-images.githubusercontent.com/28252913/232854363-329ad9ee-35dc-4e62-8d11-1f24b88196b6.png)

1.30.1
![image](https://user-images.githubusercontent.com/28252913/232853591-3f0b272f-ef6b-4c69-ae95-f12c4d0f97b9.png)

After unsuccessfully attempting to log in with my account credentials, I tried to log in using my GitHub account, but it still didn't work.

**Comment by lizheming** [comment]
I need you to provide me with a problematic environment for me to actually test it. I can't reproduce this problem myself.
WARNING messages can be ignored without affecting functionality.

**Comment by rockbenben** [comment]
Could it be that the POST request was sent to the wrong URL?
![image](https://user-images.githubusercontent.com/28252913/233485277-27b632f6-f2c1-4e54-b7d4-97611f7987b9.png)

**Comment by rockbenben** [comment]
The issue has been identified and it appears to be a problem with the Nginx configuration settings. It seems that the default reverse proxy deployment provided by the bt panel conflicts with the new version, but using [the official Nginx configuration](https://waline.js.org/guide/deploy/vps.html#nginx-%E9%85%8D%E7%BD%AE) resolves the issue. 

This is similar to issue #1917
