### ISSUE TITLE
[Bug]:  || [Bug]:

### ISSUE THREAD

**Issue by waahah** [walinejs/waline#1937]
### *Fetch comment list failed with 500: can not find service: storage/undefined*

版本：hexo :6.3.0，vercel/node@2.5.10，waline/vercel": "latest"，
地址：https://waahah.xyz，https://waline.waahah.xyz
之前部署可用，最近添加了邮件通知，无法注册登录，无法获取评论

### 问题网站 | Website URL

https://waline.waahah.xyz

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
已经修复了，请更新到 `@waline/vercel@1.30.1`
