### ISSUE TITLE
[Bug]: Turnstile  报错？ || [Bug]: Turnstile reported an error?

### ISSUE THREAD

**Issue by jerryc127** [walinejs/waline#1944]
### 问题描述 | Describe the bug

配置了 Turnstile 
控制台出现报错
![image](https://user-images.githubusercontent.com/16351105/233854296-b6c6f19a-678d-4e70-9def-81a983a704cd.png)

### 问题网站 | Website URL

https://blog.crazywong.com/link/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

MongoDB

---
### Description of the problem | Describe the bug

Turnstiles configured
An error occurred in the console
![image](https://user-images.githubusercontent.com/16351105/233854296-b6c6f19a-678d-4e70-9def-81a983a704cd.png)

### Problem Website | Website URL

https://blog.crazywong.com/link/

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

MongoDB

**Comment by lizheming** [comment]
`@waline/client@2.15.3` 发布了，可以再试试
