### ISSUE TITLE
[Bug]:  || [Bug]:

### ISSUE THREAD

**Issue by XiaoYuer2022** [walinejs/waline#1955]
### 问题描述 | Describe the bug

用docker+MYSQL本地部署waline评论功能的服务器端，docker-compose运行后连接MYSQL出错。报错提示为：`Error: connect ECONNREFUSED 127.0.0.1:3306`，网上查阅资料后对可能的问题逐一检查：MYSQL运行正常，端口3360监视正常，防火墙关闭，使用的docker-compose.yml配置文件如下：

![](https://api.onedrive.com/v1.0/shares/s!An8j80bjmrTdlH5fDgYowkv3iBkB/root/content)

在docker-compose命令运行的截图为：

![](https://api.onedrive.com/v1.0/shares/s!An8j80bjmrTdlH_jdWEtHvQRQd7H/root/content)

### 问题网站 | Website URL

http://127.0.0.1:8360/

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

MySQL

**Comment by lizheming** [comment]
容器里不包含 mysql 服务，需要自己再挂个 mysql。不懂的话自己网上搜一下其他人的教程，不要想当然哈~
