### ISSUE TITLE
[Bug]: 评论插件显示空白 || [Bug]: The comment plugin is blank

### ISSUE THREAD

**Issue by laisc7301** [walinejs/waline#1956]
### 问题描述 | Describe the bug

https://my-git-hub-blog-comment.vercel.app/

评论插件显示空白，不知道是哪里出了问题。

重新配置一个新的也是同样的问题：https://my-git-hub-blog-comment-7301.vercel.app/

### 问题网站 | Website URL

https://laisc7301.github.io/blog/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Description of the problem | Describe the bug

https://my-git-hub-blog-comment.vercel.app/

The comment plugin shows blank, not sure what is wrong.

Reconfiguring a new one is the same problem: https://my-git-hub-blog-comment-7301.vercel.app/

### Problem Website | Website URL

https://laisc7301.github.io/blog/

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
@waline/client 2.15.3 有点问题，没有发布变异后的文件包，更新成 2.15.4 应该就可以了
