### ISSUE TITLE
[Bug]: 回复评论时没有@对方 || [Bug]: There is no @友友 when replying to comments

### ISSUE THREAD

**Issue by 214545666** [walinejs/waline#1959]
### 问题描述 | Describe the bug

回复评论时没有@对方

![截屏2023-05-06 18 48 38](https://user-images.githubusercontent.com/53327400/236619732-49b9a843-04a2-4604-81d2-abe49c902d36.png)
![截屏2023-05-06 18 48 16](https://user-images.githubusercontent.com/53327400/236619745-bd070e71-4bf8-41d3-bee1-b2ab25b7b3f1.png)

自己部署的和官网实例都有这种情况

### 问题网站 | Website URL

https://waline.js.org/guide/get-started/#%E4%BD%BF%E7%94%A8-vercel-%E7%AE%80%E5%8D%95%E5%9C%B0%E9%83%A8%E7%BD%B2-waline-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F

### 服务部署在哪里？ | Where your waline deploy?

Netlify

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Description of the problem | Describe the bug

There is no @友友 when replying to comments

![Screenshot 2023-05-06 18 48 38](https://user-images.githubusercontent.com/53327400/236619732-49b9a843-04a2-4604-81d2-abe49c902d36.png)
![Screenshot 2023-05-06 18 48 16](https://user-images.githubusercontent.com/53327400/236619745-bd070e71-4bf8-41d3-bee1-b2ab25b7b3f1.png)

Both self-deployed and official website instances have this situation

### Problem Website | Website URL

https://waline.js.org/guide/get-started/#%E4%BD%BF%E7%94%A8-vercel-%E7%AE%80%E5%8D%95%E5%9C%B0 %E9%83%A8%E7%BD%B2-waline-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F

### Where is the service deployed? | Where your waline deploy?

Netlify

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by 214545666** [comment]
抱歉，没看到这个pr #1875

**Comment by lizheming** [comment]
@214545666 前两天看到了这个问题，周末了才有空看了下原因，这的确是一个 Bug，已经修复了，可以等下个版本的更新。

#1875 是针对下个版本 Waline 做的一些改造，这个改造对当前版本应该是无影响的。
