### ISSUE TITLE
[Bug]: 邮箱格式检测问题 || [Bug]: Email format detection problem

### ISSUE THREAD

**Issue by alswl** [walinejs/waline#1961]
### 问题描述 | Describe the bug

遇到问题：

> Please confirm your email address.

使用邮箱：my+blog@gmail.com

似乎检查规则有些问题。

### 问题网站 | Website URL

https://blog.alswl.com/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Description of the problem | Describe the bug

Encounter problems:

> Please confirm your email address.

Use email: my+blog@gmail.com

It seems that there is something wrong with the inspection rules.

### Problem Website | Website URL

https://blog.alswl.com/

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by Mister-Hope** [comment]
Related https://datatracker.ietf.org/doc/html/rfc5322#section-3.4.1

So 

```
  "!" / "#" /        ;  characters not including
                       "$" / "%" /        ;  specials.  Used for atoms.
                       "&" / "'" /
                       "*" / "+" /
                       "-" / "/" /
                       "=" / "?" /
                       "^" / "_" /
                       "`" / "{" /
                       "|" / "}" /
                       "~"

```

can be used in email name

PR welcomed

**Comment by alswl** [comment]
I'm not that familiar with front-end, I found the right regular expressions.
https://www.regextester.com/115911 .

```
(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])
```

I tried to put it inside the code, but it introduces some errors that I tried and found I couldn't fix. The error message is:
```
Unexpected control character(s) in regular expression
```
