### ISSUE TITLE
Deta 部署无法注册Waline || Deta deployment cannot register Waline

### ISSUE THREAD

**Issue by xiatianPE** [walinejs/waline#1962]
### 问题描述 | Describe the bug

![Snipaste_2023-05-07_18-31-54](https://user-images.githubusercontent.com/121849812/236672345-67da48ff-bcf1-471e-8489-b267a2c5d6a4.png)

### 问题网站 | Website URL

https://waline-1-i3854234.deta.app/

### 服务部署在哪里？ | Where your waline deploy?

Deta

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Description of the problem | Describe the bug

![Snipaste_2023-05-07_18-31-54](https://user-images.githubusercontent.com/121849812/236672345-67da48ff-bcf1-471e-8489-b267a2c5d6a4.png)

### Problem Website | Website URL

https://waline-1-i3854234.deta.app/

### Where is the service deployed? | Where your waline deploy?

Deta

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by xiatianPE** [comment]
现在只有注册，注册会出现这个：
![236672345-67da48ff-bcf1-471e-8489-b267a2c5d6a4](https://user-images.githubusercontent.com/121849812/236737794-f85f5353-5442-4934-af1d-d5f5964c21f9.png)
第三方也注册不了

**Comment by lizheming** [comment]
@xiatianPE Deta 的自动打包发布应该有点问题，目前发布没有发布到最新的版本。晚点我再看下

**Comment by lizheming** [comment]
可以再升级到 Deta 最新的版本，试了是可以的了。
