### ISSUE TITLE
[Bug]: 评论获取有post和get报错 || [Bug]: There are post and get errors in comment acquisition

### ISSUE THREAD

**Issue by nanbowan323** [walinejs/waline#1974]
### 问题描述 | Describe the bug

<img width="1720" alt="image" src="https://github.com/walinejs/waline/assets/20452341/ca03a7bf-0294-46b4-83e9-1eb895b7f927">

部署方式参考：
https://liubing.me/article/baota/bt-deploy-waline.html#%E5%88%9D%E5%A7%8B%E5%8C%96%E9%A1%B9%E7%9B%AE

部署配置项目：
<img width="973" alt="image" src="https://github.com/walinejs/waline/assets/20452341/a77557be-f13c-4a4e-9156-aaae4982241b">

配置反向代理：
https://www.techgrow.cn/posts/ae18fb85.html#Nginx-%E9%85%8D%E7%BD%AE%E8%B7%A8%E5%9F%9F%E8%AE%BF%E9%97%AE

主题：
butterfly 4.5.1

### 问题网站 | Website URL

https://blog.nanbowan.top/message/

### 服务部署在哪里？ | Where your waline deploy?

Other

### 数据存储在哪里？| Where your comment data store?

MySQL

---
### Description of the problem | Describe the bug

<img width="1720" alt="image" src="https://github.com/walinejs/waline/assets/20452341/ca03a7bf-0294-46b4-83e9-1eb895b7f927">

Deployment method reference:
https://liubing.me/article/baota/bt-deploy-waline.html#%E5%88%9D%E5%A7%8B%E5%8C%96%E9%A1%B9%E7%9B%AE

Deployment configuration project:
<img width="973" alt="image" src="https://github.com/walinejs/waline/assets/20452341/a77557be-f13c-4a4e-9156-aaae4982241b">

Configure reverse proxy:
https://www.techgrow.cn/posts/ae18fb85.html#Nginx-%E9%85%8D%E7%BD%AE%E8%B7%A8%E5%9F%9F%E8%AE%BF%E9 %97%AE

theme:
butterfly 4.5.1

### Problem Website | Website URL

https://blog.nanbowan.top/message/

### Where is the service deployed? | Where your waline deploy?

other

### Where is the data stored? | Where your comment data store?

MySQL

**Comment by lizheming** [comment]
SECURE_DOMAINS 是配置域名，不是网址，直接配置 `blog.nanbowan.top` 即可。

**Comment by Mister-Hope** [comment]
https://waline.js.org/reference/server/env.html#%E5%AE%89%E5%85%A8
