### ISSUE TITLE
[Bug]: forbidden

### ISSUE THREAD

**Issue by felixesintot** [walinejs/waline#1984]
### 问题描述 | Describe the bug

被forbidden搞死了
![image](https://github.com/walinejs/waline/assets/98651799/9319a286-8f25-49c9-8cc3-0c49bc3143a4)
![image](https://github.com/walinejs/waline/assets/98651799/e07fc82f-26ce-417b-b8d5-b8311fba5fa7)

### 问题网站 | Website URL

https://waline.felixesintot.top

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Description of the problem | Describe the bug

Fucked by forbidden
![image](https://github.com/walinejs/waline/assets/98651799/9319a286-8f25-49c9-8cc3-0c49bc3143a4)
![image](https://github.com/walinejs/waline/assets/98651799/e07fc82f-26ce-417b-b8d5-b8311fba5fa7)

### Problem Website | Website URL

https://waline.felixesintot.top

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud (https://leancloud.app)

**Comment by lizheming** [comment]
环境变量需要 RECAPTCHA_V3_KEY 和 RECAPTCHA_V3_SECRET 都要配置，是不是漏了配 KEY 了？

**Comment by felixesintot** [comment]
那官网上为啥没写TXT

**Comment by lizheming** [comment]
官网写了的 https://waline.js.org/reference/server/env.html#%E5%AE%89%E5%85%A8

![image](https://github.com/walinejs/waline/assets/424491/900197e5-b96a-4cb1-8e06-35074c9eb1be)
