### ISSUE TITLE
[Bug]: 从博客首页访问文章后页面滚动条并不是在最顶部，去除底部评论插件Waline后发现正常。 || [Bug]: After accessing the article from the blog homepage, the page scroll bar is not at the top. After removing the bottom comment plug-in Waline, it is found to be normal.

### ISSUE THREAD

**Issue by OrageKK** [walinejs/waline#2001]
### 问题描述 | Describe the bug

从博客首页访问文章后页面滚动条并不是在最顶部，去除底部评论插件Waline后发现正常。
请参考：https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/2814
@Mister-Hope  在2.15.1已修复此问题，最近又复现了，而且本地dev没有问题，只在部署后出现
目前使用waline版本为2.15.5 可访问我部署后的页面验证 https://oragekk.me/

### 问题网站 | Website URL

https://oragekk.me/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Description of the problem | Describe the bug

After accessing the article from the homepage of the blog, the page scroll bar is not at the top. After removing the bottom comment plug-in Waline, it is found to be normal.
Please refer to: https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/2814
@Mister-Hope has fixed this problem in 2.15.1, and it has reappeared recently, and there is no problem with local dev, it only appears after deployment
Currently using waline version 2.15.5, you can visit my post-deployment page verification https://oragekk.me/

### Problem Website | Website URL

https://oragekk.me/

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
看了下对应 issue 的修复 commit https://github.com/vuepress-theme-hope/vuepress-theme-hope/commit/1bf15b866301d805d2d69d728435a6b39a496a43 ，似乎是 vuepress-theme-hope 主题的问题，commit 中 `@waline/client` 的版本并没有修改。建议去 vuepress-theme-hope 中提交此问题 issue。

**Comment by Mister-Hope** [comment]
修复在这https://github.com/walinejs/waline/commit/409b28bd6ec80c9289ff2c76a10f27e519b45dde

**Comment by lizheming** [comment]
> 修复在这https://github.com/walinejs/waline/commit/409b28bd6ec80c9289ff2c76a10f27e519b45dde 。我那个commit明明只升级了依赖
> 
> ---
> The fix is ​​here https://github.com/walinejs/waline/commit/409b28bd6ec80c9289ff2c76a10f27e519b45dde. My commit obviously only upgraded the dependency
> 
 但我并没有在那个版本升级的 commit 里面看到 @waline/client 的升级，所以我以为和 waline 是无关的

**Comment by OrageKK** [comment]
今天又好了，很抱歉，我也不知道什么原因，我准备关闭这个问题，看起来似乎无法复现了
