### ISSUE TITLE
[Bug]: 发布评论提示"undefined [404 GET www.yuanning0818.tk/1.1/classes/Comment]" || [Bug]: Publish comment prompt "undefined [404 GET www.yuanning0818.tk/1.1/classes/Comment]"

### ISSUE THREAD

**Issue by ning0818** [walinejs/waline#2002]
### 问题描述 | Describe the bug

发布评论提示
![image](https://github.com/walinejs/waline/assets/117955401/43fe81b8-1638-4e95-b774-7b7c54b2556b)

![](https://bu.dusays.com/2023/06/08/6481464a30716.png)

### 问题网站 | Website URL

https://liuyan.yuanning0818.tk && https://waline.yuanning0818.tk

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Description of the problem | Describe the bug

post a comment tip
![image](https://github.com/walinejs/waline/assets/117955401/43fe81b8-1638-4e95-b774-7b7c54b2556b)

![](https://bu.dusays.com/2023/06/08/6481464a30716.png)

### Problem Website | Website URL

https://liuyan.yuanning0818.tk && https://waline.yuanning0818.tk

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
LEAN_SERVER 是指 LeanCloud 的域名，不是指你的博客域名，LeanCloud 国际版 Vercel 可以不用配 LEAN_SERVER，国内版需要配一个在 LeanCloud 后台绑定的已备案的域名
