### ISSUE TITLE
[Feature]: 是否能自定义图床 || [Feature]: Can you customize the picture bed

### ISSUE THREAD

**Issue by ning0818** [walinejs/waline#2003]
### 功能概述 | Describe the feature

自定义评论上传图片的图床

---
### Feature Overview | Describe the feature

Customize the picture bed for uploading pictures in comments

**Comment by lizheming** [comment]
https://waline.js.org/cookbook/customize/upload-image.html

**Comment by ning0818** [comment]
> https://waline.js.org/cookbook/customize/upload-image.html

抱歉，没找到。..
