### ISSUE TITLE
[Bug]: 评论通知无反应 || [Bug]: Comment notification does not respond

### ISSUE THREAD

**Issue by xiatianPE** [walinejs/waline#2009]
### 问题描述 | Describe the bug

按照官方文档配置的，发评论没有提醒

### 问题网站 | Website URL

https://waline-1-i3854234.deta.app/

### 服务部署在哪里？ | Where your waline deploy?

Deta

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Description of the problem | Describe the bug

Configured according to the official document, there is no reminder to post a comment

### Problem Website | Website URL

https://waline-1-i3854234.deta.app/

### Where is the service deployed? | Where your waline deploy?

Deta

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
可以在 Deta 里进入应用的 log 查看界面看下服务端的错误日志

**Comment by lizheming** [comment]
close with no long activity.
