### ISSUE TITLE
Vercel基于MongoDB Alias 部署，环境变量需要配置哪些？文档并没有提到！ || Vercel is deployed based on MongoDB Alias, what environment variables need to be configured? The docs don't mention it!

### ISSUE THREAD

**Issue by zhenqicai** [walinejs/waline#2011]
### 问题描述 | Describe the bug

![image](https://github.com/walinejs/waline/assets/20643420/b09eb06d-990b-4225-b91c-2c098173cd8a)

### 问题网站 | Website URL

https://qiucode.cn

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

MongoDB

---
### Description of the problem | Describe the bug

![image](https://github.com/walinejs/waline/assets/20643420/b09eb06d-990b-4225-b91c-2c098173cd8a)

### Problem Website | Website URL

https://qiucode.cn

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

MongoDB

**Comment by lizheming** [comment]
https://waline.js.org/guide/database.html#mongodb 看下文档
