### ISSUE TITLE
[Bug]: 博主回复其他人时自己也会收到邮件通知 || [Bug]: Bloggers will also receive email notifications when they reply to others

### ISSUE THREAD

**Issue by cnmoe** [walinejs/waline#2013]
### 问题描述 | Describe the bug

开启邮件通知的情况下，博主回复其他人的评论时，自己和被回复人都会收到新评论通知。

博主回复时不用再通知博主了吧，只有评论人不是博主时才应该通知博主吧，

### 问题网站 | Website URL

https://yuanhao.moe/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.cn)

---
### Description of the problem | Describe the bug

When email notifications are enabled, when bloggers reply to other people's comments, both themselves and the respondent will receive new comment notifications.

When the blogger replies, there is no need to notify the blogger. Only when the commenter is not the blogger should the blogger be notified, right?

### Problem Website | Website URL

https://yuanhao.moe/

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.cn)

**Comment by lizheming** [comment]
https://github.com/walinejs/waline/blob/main/packages/server/src/service/notify.js#L475

可以检查下发布评论的邮箱，需要和`AUTHOR_EMAIL` 配置的一样，才会被识别成博主评论。

**Comment by cnmoe** [comment]
已解决，谢谢大佬
