### ISSUE TITLE
[Bug]:  || [Bug]:

### ISSUE THREAD

**Issue by kingcwt** [walinejs/waline#2014]
### 问题描述 | Describe the bug

<img width="1147" alt="image" src="https://github.com/walinejs/waline/assets/29888469/680811b1-ff4b-4ae2-959b-93d22bed052f">
Navigator cannot find

### 问题网站 | Website URL

正在开发中

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Description of the problem | Describe the bug

<img width="1147" alt="image" src="https://github.com/walinejs/waline/assets/29888469/680811b1-ff4b-4ae2-959b-93d22bed052f">
Navigator cannot find

### Problem Website | Website URL

in development

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by kingcwt** [comment]
<img width="1279" alt="image" src="https://github.com/walinejs/waline/assets/29888469/89623d11-5014-48da-913b-2ac3768eec58">

**Comment by lizheming** [comment]
我理解这应该是在 SSR 中渲染了 Waline 组件了，应该是要把 Waline 组件放在客户端逻辑中。
VuePress 看下 @Mister-Hope Hopes 老师能不能指导下。

**Comment by Mister-Hope** [comment]
你这action是不是有点问题。我回头看看。

**Comment by kingcwt** [comment]
这个我已经解决了  把import("@waline/client")放在onMounted就行了 这样加载的才是window下的环境 而不是node环境

**Comment by Mister-Hope** [comment]
That's not needed, I am busy but I will look into your issue.

**Comment by Mister-Hope** [comment]
vuepress-plugin-comment2 supports ssr rendering.

**Comment by kingcwt** [comment]
ok
