### ISSUE TITLE
[Feature]: Edge function & KV storge

### ISSUE THREAD

**Issue by lolifamily** [walinejs/waline#2015]
### 功能概述 | Describe the feature

函数支持更快的vercel edge function以及对应的kv storge

---
### Feature Overview | Describe the feature

The function supports faster vercel edge function and corresponding kv storge

**Comment by lizheming** [comment]
1. Edge Functions 受限于 Node 架构原因，短期无法支持，CF workers 也类似
2. Vercel KV 每天只有 3000 请求，算下来每天最多应该只能承接 200 pv 以下的访问，感觉性价比不高 https://vercel.com/docs/storage/vercel-kv/limits

**Comment by lolifamily** [comment]
那能支持一下Vercel的postgres吗？它自带的环境变量名有点不同，如果可以适配新的环境变量也会好些
![image](https://github.com/walinejs/waline/assets/47876607/17178468-4528-4d4e-b869-24634beb0abd)

**Comment by lizheming** [comment]
@lolifamily 这个很早就支持了 https://t.me/walinejs/15481

**Comment by lolifamily** [comment]
可能就是改了
![image](https://github.com/walinejs/waline/assets/47876607/0ca1bade-4108-477d-bb2f-5249d61500b4)
要是我找到一样的变量名就不会提这个issue了

**Comment by lizheming** [comment]
![image](https://github.com/walinejs/waline/assets/424491/213ab469-326f-49c4-bd66-c48e20aab777) 我看我之前创建的是这个环境变量。如果是这样的话先自行配置吧，也不太好做这种适配，说不定后面又变了。等 Vercel 那边正式版稳定下来了再说。
