### ISSUE TITLE
[Feature]: deta部署Waline缺少变量 || [Feature]: Deta deployment Waline missing variables

### ISSUE THREAD

**Issue by xiatianPE** [walinejs/waline#2016]
### 功能概述 | Describe the feature

评论通知缺少：
MAIL_SUBJECT
MAIL_TEMPLATE
MAIL_SUBJECT_ADMIN
MAIL_TEMPLATE_ADMIN
希望添加上去

---
### Feature Overview | Describe the feature

Comment notifications are missing:
MAIL_SUBJECT
MAIL_TEMPLATE
MAIL_SUBJECT_ADMIN
MAIL_TEMPLATE_ADMIN
hope to add

**Comment by lizheming** [comment]
已经增加并发布了新版本了。不过我测试了一下，应该是需要重新安装才会生效新配置。
