### ISSUE TITLE
[Bug]: 页面访问量没更新 || [Bug]: Page views are not updated

### ISSUE THREAD

**Issue by changel** [walinejs/waline#2019]
### 问题描述 | Describe the bug

我在vuepress2中使用waline，部署的时候有使用base配置基础路径，
现象：访问的页面时，后台查询放量的时候会使用带有base基础路径的url去查询，
           但是在update的时候，是通过没有base前缀的url查询出来的id来更新的。

### 问题网站 | Website URL

无

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

MySQL

---
### Description of the problem | Describe the bug

I use waline in vuepress2. When deploying, I use base to configure the base path.
Phenomenon: When accessing the page, the background query will use the url with the base path to query when the volume is heavy.
           But when updating, it is updated through the id queried by the url without the base prefix.

### Problem Website | Website URL

none

### Where is the service deployed? | Where your waline deploy?

Docker

### Where is the data stored? | Where your comment data store?

MySQL

**Comment by Mister-Hope** [comment]
Waline根本不关心你所谓的base，你自己传递的参数不一致不要怪别人，检查你自己API的调用。

**Comment by changel** [comment]
我使用的vuepress-theme-hope主题，不是自己调用的api，抱歉，我可能应该去vuepress-theme-hope中提，是使用这个主题升级到最新版本后出来的问题，以前是正常的。
