### ISSUE TITLE
[建議] 評論管理界面上，回覆的評論能顯示是回覆哪一條評論

### ISSUE THREAD

**Issue by jerryc127** [walinejs/waline#202]
[建議] 評論管理界面上，回覆的評論能顯示是回覆哪一條評論

雖然可以點擊跳轉到blog上去看
但是如果遇到別人回覆的是很舊的評論
會找不到原評論在哪裏

希望評論管理界面，能指明是回覆的哪一條評論

**Comment by appotry** [comment]
同样想要这个， 想valine-admin 里面的 hash id直接跳转到指定的评论id

**Comment by lizheming** [comment]
已通过在客户端增加评论管理曲线解决该问题，请更新到 `@waline/client@2.4.0` 及 `@waline/vercel@1.18.0` 以上版本
