### ISSUE TITLE
[BUG]CloudBase上Waline对同一页面最多只返回100条评论数据

### ISSUE THREAD

**Issue by asforest** [walinejs/waline#203]
**问题描述 | Describe the bug**
Waline对同一页面（指url参数相同时）最多只会返回100条评论数据

我将别的评论系统的数据导入到了CloudBase上的Waline，一共大约160条评论，导入过程一切顺利，但是服务端返回的数据中，评论数量总是返回100，而且返回的评论的页数也对不上。

totalPages返回的值是5，而pageSize是10。5*10也不等于100，我查阅了文档，好像也没有相关的配置选项

![QQ截图20210416233319](https://user-images.githubusercontent.com/28993050/115048637-59cd9000-9f0c-11eb-86ee-a27cfc47a1f2.png)

这是Waline后台的数据，可以确定的确是成功导入了161条数据

![image](https://user-images.githubusercontent.com/28993050/115049240-14f62900-9f0d-11eb-82a1-31fb18c4cc59.png)

**问题网站 | Website URL**
https://hello-cloudbase-9gyv4rta0bd17d6a-1254063044.ap-shanghai.app.tcloudbase.com

**部署方式 | Deploy Type**
- 服务部署在哪里？ | Where your waline deploy?
    - [ ] Vercel
    - [x] CloudBase
    - [ ] Docker 
    - [ ] VPS, Virtual Host
    - [ ] Other
- 数据存储在哪里？| Where your comment data store?
    - [ ] LeanCloud(https://leancloud.app) 
    - [ ] LeanCloud(https://leancloud.cn)
    - [x] CloudBase
    - [ ] MongoDB
    - [ ] MySQL
    - [ ] SQLite
    - [ ] PostgreSQL
    - [ ] Github

**Comment by lizheming** [comment]
这个和 CloudBase 和 LeanCloud 的限制有关，这两个的数据库一次性只支持返回最大100条的数据。而在获取评论数据的时候，为了节省一次数据库操作（能节省数据库读取的额度），我会将当前文章的所有评论数据读取出来，通过判断数组长度返回评论数。所以这两个结合了一下就产生了这个问题了，可能后续需要优化一下。

**Comment by innc11** [comment]
这个主要还是CloudBase的锅，限制老多了，也许后面可以从需要地方开始读取数据库

**Comment by lizheming** [comment]
嗯，我后续想一下怎么优化吧，可以考虑当返回条数 >= 100 的时候我再增加单独请求一下评论条数的操作。

**Comment by Mister-Hope** [comment]
虽然没用过cloudbase，但是看描述这不是跟小程序的云开发是一样的么？可以在云函数里先读总长度然后分次读取一并返回。
