### ISSUE TITLE
[Bug]: GIF 表情搜索按键导致页脚出现空白 || [Bug]: The GIF emoticon search button causes the footer to appear blank

### ISSUE THREAD

**Issue by felixesintot** [walinejs/waline#2036]
### 问题描述 | Describe the bug

<img width="650" alt="startsearch" src="https://github.com/jerryc127/hexo-theme-butterfly/assets/98651799/66081527-d718-47a7-837b-0fb3901b65b4">
<img width="715" alt="endsearch" src="https://github.com/jerryc127/hexo-theme-butterfly/assets/98651799/e9204777-3c59-466e-8f4a-8a11f5eea7f2">
点开“GIF”图标后关闭，页面就变成这样，难看死了o(╥﹏╥)o

### 问题网站 | Website URL

https://felixesintot.top

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Description of the problem | Describe the bug

<img width="650" alt="startsearch" src="https://github.com/jerryc127/hexo-theme-butterfly/assets/98651799/66081527-d718-47a7-837b-0fb3901b65b4">
<img width="715" alt="endsearch" src="https://github.com/jerryc127/hexo-theme-butterfly/assets/98651799/e9204777-3c59-466e-8f4a-8a11f5eea7f2">
Click on the "GIF" icon and close it, the page becomes like this, it's ugly o(╥﹏╥)o

### Problem Website | Website URL

https://felixesintot.top

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud (https://leancloud.app)

**Comment by lizheming** [comment]
建议换个其他主题看一下

**Comment by jerryc127** [comment]
> 建议换个其他主题看一下
> 
> It is recommended to change another theme to see

参考 waline 的 doc
https://waline.js.org/cookbook/reactivity.html#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

![image](https://github.com/walinejs/waline/assets/16351105/67e0435f-3b05-4725-8e20-f0fc9e44f9d7)

打开 gif 后
![image](https://github.com/walinejs/waline/assets/16351105/96335cce-8fa8-40fc-938b-738a7e007843)

关闭 gif

![image](https://github.com/walinejs/waline/assets/16351105/6d62009b-3df4-4487-ae19-9cf14d8b1fd9)

**Comment by so1ve** [comment]
issue标题可以别起这种名字…没必要当inm小鬼，反馈bug还是用描述性的句子好

**Comment by felixesintot** [comment]
> issue标题可以别起这种名字…没必要当inm小鬼，反馈bug还是用描述性的句子好
> 
> The title of the issue can not be named like this... There is no need to be an inm kid, it is better to use descriptive sentences when reporting bugs

您说得对，所以问题可不可以解决一下。

**Comment by felixesintot** [comment]
6
