### ISSUE TITLE
[Bug]: waline.js.org出BUG力 || [Bug]: waline.js.org made a bug

### ISSUE THREAD

**Issue by felixesintot** [walinejs/waline#2041]
### 问题描述 | Describe the bug
点开“GIF”按键前：
![image](https://github.com/walinejs/waline/assets/98651799/ae982b09-7a93-4f1b-8e0e-1f60955f8ac3)
点开“GIF”按键后，注意到滚动条异常变长：
![256387999-8bd43c58-4dc3-4a25-9f69-954db09d2c72](https://github.com/walinejs/waline/assets/98651799/a7a5895f-04a9-4469-ad56-69abbfc1efec)
往下拉滚动条后：
![image](https://github.com/walinejs/waline/assets/98651799/bf4f34b4-301f-4026-9858-ea3e3d0605b2)
关闭“GIF”窗口，这时可以明显发现问题：
![image](https://github.com/walinejs/waline/assets/98651799/9f9df12c-9af7-42bb-bea5-a5ca8af852d3)

### 问题网站 | Website URL

https://waline.js.org

具体的出错页面：https://waline.js.org/guide/features/comment.html#%E6%89%8B%E5%8A%A8%E6%9B%B4%E6%96%B0

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Description of the problem | Describe the bug
Before clicking the "GIF" button:
![image](https://github.com/walinejs/waline/assets/98651799/ae982b09-7a93-4f1b-8e0e-1f60955f8ac3)
After clicking the "GIF" button, I noticed that the scroll bar became abnormally long:
![256387999-8bd43c58-4dc3-4a25-9f69-954db09d2c72](https://github.com/walinejs/waline/assets/98651799/a7a5895f-04a9-4469-ad56-69abbfc1efec)
After scrolling down:
![image](https://github.com/walinejs/waline/assets/98651799/bf4f34b4-301f-4026-9858-ea3e3d0605b2)
Close the "GIF" window, and the problem can be clearly found at this time:
![image](https://github.com/walinejs/waline/assets/98651799/9f9df12c-9af7-42bb-bea5-a5ca8af852d3)

### Problem Website | Website URL

https://waline.js.org

Specific error page: https://waline.js.org/guide/features/comment.html#%E6%89%8B%E5%8A%A8%E6%9B%B4%E6%96%B0

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud (https://leancloud.app)

**Comment by lizheming** [comment]
same as #2036
