### ISSUE TITLE
[BUG] GitHub 存储的评论后台无法显示

### ISSUE THREAD

**Issue by oCoke** [walinejs/waline#205]
**问题描述 | Describe the bug**

我使用 GitHub 存储，前往 GitHub 仓库看到数据已被正确写入文件，前端也可以正常显示，但 `/ui` 后台并没有显示相关的评论。
**问题网站 | Website URL**

**部署方式 | Deploy Type**
- 服务部署在哪里？ | Where your waline deploy?
    - [x] Vercel
    - [ ] CloudBase
    - [ ] Docker 
    - [ ] VPS, Virtual Host
    - [ ] Other
- 数据存储在哪里？| Where your comment data store?
    - [ ] LeanCloud(https://leancloud.app) 
    - [ ] LeanCloud(https://leancloud.cn)
    - [ ] CloudBase
    - [ ] MongoDB
    - [ ] MySQL
    - [ ] SQLite
    - [ ] PostgreSQL
    - [x] Github

**Comment by lizheming** [comment]
目前 Github 存储不建议使用 `/ui` 后台进行管理，建议直接 clone 下来修改 csv 文件比较好… 因为 Github 的本质是通过 Github API 去读取文件，这个最大的问题是会由于 Github API 的频率或者大小问题导致超时等问题。而后台的接口请求比较多，非常容易出现这个问题，目前暂时还没有很好的方法优化

**Comment by lizheming** [comment]
Closes the issue because of long inactivity
