### ISSUE TITLE
[Feature]: 希望能异步发送通知, 提升提交评论的相应速度 || [Feature]: It is hoped that notifications can be sent asynchronously to improve the corresponding speed of submitting comments

### ISSUE THREAD

**Issue by Doradx** [walinejs/waline#2056]
### 功能概述 | Describe the feature

目前提交评论基本需要3-4s的响应时间，查看源码后发现是因为处理post请求时，需要await发送通知的任务。详细如下：
https://github.com/walinejs/waline/blob/826737bb51680a26334d1bb0a388d683674bfcaf/packages/server/src/controller/comment.js#L257-L260
后续是否有可能进行修改优化？
毕竟通知一般需要发送网络请求，并等待回复，太耗时间了。
谢谢！

---
### Feature Overview | Describe the feature

At present, submitting comments basically takes 3-4s response time. After checking the source code, it is found that it is because the task of await sending notifications is required when processing post requests. The details are as follows:
https://github.com/walinejs/waline/blob/826737bb51680a26334d1bb0a388d683674bfcaf/packages/server/src/controller/comment.js#L257-L260
Is it possible to modify and optimize in the future?
After all, notification generally needs to send a network request and wait for a reply, which is too time-consuming.
Thanks!

**Comment by lizheming** [comment]
https://waline.js.org/reference/server/env.html#%E9%AB%98%E7%BA%A7%E9%85%8D%E7%BD%AE 可以使用 WEBHOOK 配置自行实现
