### ISSUE TITLE
[Bug]: Styles breaking

### ISSUE THREAD

**Issue by Mister-Hope** [walinejs/waline#2059]
### 问题描述 | Describe the bug

![image](https://github.com/walinejs/waline/assets/33315834/cc18ee0c-0765-4ebc-a7a1-e5e801529221)

https://caniuse.com/css-media-range-syntax

We are using features which is only supported by Chrome104+ and safari 16.4+. which obeys our browser support declaration in `@waline/client/package.json`.

This is breaking appearance on a lot of devices.

Solution:

Revert 6e9b579cc5e87b1c3f39b9cd6c293ad6797e9788, stylelint config may need an upgrade to ensure we are not outputing synatax that is "too mordern".

### 问题网站 | Website URL

Not related

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by Mister-Hope** [comment]
Busy in real life now, so could you plz handle it? @lizheming 

May need to check out recent lint changes in client style files, and disable those that has similar behavior above.

**Comment by Mister-Hope** [comment]
@lizheming Could you check and fix this?

**Comment by lizheming** [comment]
@Mister-Hope OK

**Comment by Mister-Hope** [comment]
https://github.com/walinejs/waline/commit/d65d6ef89e17f1d434705e4a10f4fc3ecbc75eba
