### ISSUE TITLE
[Bug]: 评论时报错/邮件提醒无效 || [Bug]: Comment error/mail reminder is invalid

### ISSUE THREAD

**Issue by Genkaim** [walinejs/waline#2061]
### 问题描述 | Describe the bug

在提交评论时报错，但是评论成功：
JSON.parse: unexpected character at line 1 column 1 of the JSONdata
还有我正确配置了环境变量（确认了好几次），却没有收到邮件通知提醒（日志里连邮件的那部分都没有）
日志内容：
```
[33m[2023-08-21T09:15:48.168] [15] [WARN][39m - [Deprecated] /comment API will be deprecated in the next major version, please don't use it anymore. If you are using `@waline/client` please upgrade to `@waline/client@3`. For other scenarios, you can use `/api/comment` to replace it.
[36m[2023-08-21T09:15:48.170] [15] [DEBUG][39m - Post Comment Start!
[36m[2023-08-21T09:15:48.170] [15] [DEBUG][39m - Post Comment initial Data: {
  link: '',
  mail: '',
  nick: 'Anonymous',
  pid: undefined,
  rid: undefined,
  ua: 'Mozilla/5.0 (Windows NT 10.0; WOW64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.5666.197 Safari/537.36',
  url: '/',
  comment: '111',
  ip: '13.230.44.65',
  insertedAt: 2023-08-21T09:15:48.170Z,
  user_id: undefined
}
[36m[2023-08-21T09:15:48.172] [15] [DEBUG][39m - Comment IP <ip> check OK!
[36m[2023-08-21T09:15:48.272] [15] [DEBUG][39m - Comment duplicate check OK!
[36m[2023-08-21T09:15:48.572] [15] [DEBUG][39m - Comment post frequency check OK!
[36m[2023-08-21T09:15:48.573] [15] [DEBUG][39m - Comment initial status is approved
[36m[2023-08-21T09:15:48.658] [15] [DEBUG][39m - Comment akismet check result: approved
[36m[2023-08-21T09:15:48.659] [15] [DEBUG][39m - Comment keyword check result: approved
[36m[2023-08-21T09:15:48.659]` [15] [DEBUG][39m - Comment post hooks preSave done!
[36m[2023-08-21T09:15:49.010] [15] [DEBUG][39m - Comment have been added to storage.
```
报错截图：
![](https://raw.gitmirror.com/genkaim/blog_img/main/data/202308211728881.png)
![](https://raw.gitmirror.com/genkaim/blog_img/main/data/202308211729218.png)
环境变量截图：
![](https://raw.gitmirror.com/genkaim/blog_img/main/data/202308211731910.png)

### 问题网站 | Website URL

https://blog-dh0k9nevv-genkaim.vercel.app/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Description of the problem | Describe the bug

An error is reported when submitting a comment, but the comment is successful:
JSON.parse: unexpected character at line 1 column 1 of the JSONdata
Also, I configured the environment variables correctly (confirmed several times), but I did not receive the email notification reminder (there is not even the part of the email in the log)
Log content:
```
[33m[2023-08-21T09:15:48.168] [15] [WARN] [39m - [Deprecated] /comment API will be deprecated in the next major version, please don't use it anymore. If you are using `@waline/client` please upgrade to `@waline/client@3`. For other scenarios, you can use `/api/comment` to replace it.
[36m[2023-08-21T09:15:48.170] [15] [DEBUG] [39m - Post Comment Start!
[36m[2023-08-21T09:15:48.170] [15] [DEBUG] [39m - Post Comment initial Data: {
  link: '',
  mail: '',
  nick: 'Anonymous',
  pid: undefined,
  rid: undefined,
  ua: 'Mozilla/5.0 (Windows NT 10.0; WOW64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.5666.197 Safari/537.36',
  url: '/',
  comment: '111',
  ip: '13.230.44.65',
  insertedAt: 2023-08-21T09:15:48.170Z,
  user_id: undefined
}
[36m[2023-08-21T09:15:48.172] [15] [DEBUG] [39m - Comment IP <ip> check OK!
[36m[2023-08-21T09:15:48.272] [15] [DEBUG] [39m - Comment duplicate check OK!
[36m[2023-08-21T09:15:48.572] [15] [DEBUG] [39m - Comment post frequency check OK!
[36m[2023-08-21T09:15:48.573] [15] [DEBUG] [39m - Comment initial status is approved
[36m[2023-08-21T09:15:48.658] [15] [DEBUG] [39m - Comment akismet check result: approved
[36m[2023-08-21T09:15:48.659] [15] [DEBUG] [39m - Comment keyword check result: approved
[36m[2023-08-21T09:15:48.659]` [15] [DEBUG] [39m - Comment post hooks preSave done!
[36m[2023-08-21T09:15:49.010] [15] [DEBUG] [39m - Comment have been added to storage.
```
Error screenshot:
![](https://raw.gitmirror.com/genkaim/blog_img/main/data/202308211728881.png)
![](https://raw.gitmirror.com/genkaim/blog_img/main/data/202308211729218.png)
Environment variable screenshot:
![](https://raw.gitmirror.com/genkaim/blog_img/main/data/202308211731910.png)

### Problem Website | Website URL

https://blog-dh0k9nevv-genkaim.vercel.app/

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud (https://leancloud.app)

**Comment by lizheming** [comment]
应该是邮件通知服务商那边返回了错误，导致后续逻辑没执行。这种具体的 case 可能需要具体的排查了，不太好做归因，邮件通知这个功能本身是没有问题的。我建议是可以换一些邮件通知服务商试试，或者使用其他通知功能。

**Comment by Genkaim** [comment]
非常感谢，刚才发现只有在博客评论才会发邮件，直接访问域名评论不会发邮件，现在已经解决了🥲
