### ISSUE TITLE
[Feature]: add QmsgHost

### ISSUE THREAD

**Issue by ThatCoders** [walinejs/waline#2075]
### 功能概述 | Describe the feature

Dear walinejs,
  The qmsg service has launched a private deployment, can you reserve the link of qmsg as a variable, let us customize it. [Official reference URL](https://qmsgpvt.zendee.cn/docs/plus/#%E4%BB%80%E4%B9%88%E6%98%AF%E7%A7%81%E6%9C%89%E4%BA%91).
  Thanks.

**Comment by lizheming** [comment]
fixed with #2076
