### ISSUE TITLE
[Feature]: 10分钟邮箱 || [Feature]: 10 minutes email

### ISSUE THREAD

**Issue by felixesintot** [walinejs/waline#2079]
### 功能概述 | Describe the feature

建议添加只能用qq.com与163.com结尾的邮箱注册的功能以防止10分钟邮箱。

同时，建议支持删除与封禁用户，被删除的可再次用相同邮箱登录，被封禁的不行。

---
### Feature Overview | Describe the feature

It is recommended to add the function that only the emails ending in qq.com and 163.com can be registered to prevent 10-minute emails.

At the same time, it is recommended to support deleting and banning users. Deleted users can log in with the same email address again, and banned users cannot.

**Comment by lizheming** [comment]
邮件校验，这个可以自己写插件支持，在中间件中判断是 `POST /user` 的请求的时候，增加邮箱校验的逻辑。
