### ISSUE TITLE
[Feature]: 评论反应保护 || [Feature]: Comment reaction protection

### ISSUE THREAD

**Issue by felixesintot** [walinejs/waline#2080]
### 功能概述 | Describe the feature

被别人用 python 刷点赞了，难受。

能不能为反应也加个 capcha，或者要求必须登录之类的？

---
### Feature Overview | Describe the feature

It's uncomfortable to be praised by others with python.

Can you also add a capcha to the response, or require a login or something?

**Comment by lizheming** [comment]
Reaction 就是为了轻量所以没有加这些东西，这个数字本身也只是一种氛围而已。验证码应该实现不了，如果需要登录的话可以自行写插件实现。
