### ISSUE TITLE
[Bug]: Waline后台导出再重新导入后，`objectId` `pid` `rid`会发生改变，导致@没法跳转至相应id || [Bug]: After Waline background export and re-import, `objectId` `pid` `rid` will change, causing @ to be unable to jump to the corresponding id

### ISSUE THREAD

**Issue by shuibaco** [walinejs/waline#2082]
### 问题描述 | Describe the bug

因为Disqus导出的评论需要手动修改，所以测试了Waline后台的导出导入功能。结果发现同样的内容导入导出后，`objectId` `pid` `rid`会发生改变，虽然这三者同步改变并不影响评论嵌套，但是@评论者的#链接就没法用了。

### 问题网站 | Website URL

https://shuiba.co/about

### 服务部署在哪里？ | Where your waline deploy?

Deta

### 数据存储在哪里？| Where your comment data store?

Deta Base

---
### Problem description | Describe the bug

Because the comments exported by Disqus need to be modified manually, the export and import function of the Waline backend was tested. It turns out that after the same content is imported and exported, `objectId` `pid` `rid` will change. Although the simultaneous changes of these three do not affect the nesting of comments, the # link of @commenter cannot be used.

### Question Website | Website URL

https://shuiba.co/about

### Where is the service deployed? | Where your waline deploy?

Deta

### Where is the data stored? | Where your comment data store?

Deta Base

**Comment by lizheming** [comment]
下个大版本会修改现在的回复逻辑，就不会有这个问题了，可以等后续大版本。

**Comment by SaraKale** [comment]
我最近也是换成Deta Base部署了，迁移过来的评论都可以正常查看，唯独这一篇[文章](https://sarakale.top/blog/posts/24482/)无法显示评论，我在后台看了很久也没找到问题，配置和数据都是以前的没改动，控制台报错如下：
```
Uncaught (in promise) TypeError: Waline.init is not a function
    at a (<anonymous>:1:35)
    at t (<anonymous>:1:838)
```
也加了"status": "approved", 还是无解。
我现在是waline 2.15.8版本，不知道是不是也是objectId、pid、rid问题，我替换了对应pid链接也是不行……百思不得其解，那我也等下个大版本更新？

**Comment by lizheming** [comment]
@SaraKale 因为你这个页面没有加载 Waline 的脚本，所以找不到 Waline 的方法。看起来和使用了 Cloudflare 的 Rocket Loader 有点关系，但我不确定为什么只有这个页面有问题。具体还需要你自己研究下了。
