### ISSUE TITLE
[Bug]: "path can not be blank" error when deploying on Netlify using redirect rule configuration

### ISSUE THREAD

**Issue by Talaxy009** [walinejs/waline#2083]
### 问题描述 | Describe the bug

I have deployed the function on Netlify and to make the url path simple I added a redirect rule to redirect all requests from `/api/*` to `/.netlify/functions/*`. The comments can be loaded successfully through both `/api/comment/comment` and `/.netlify/functions/comment/comment`. The management page cannot be visited through `/api/comment/ui`, but can be visited through `/.netlify/functions/comment/ui`.

Everything is fine when loading comments data:
![image](https://github.com/walinejs/waline/assets/41264828/0f29c540-3771-4a9f-8b86-0bd9e1e2f58b)
![image](https://github.com/walinejs/waline/assets/41264828/8c2bcd74-39f2-4bd1-9dd7-e240f24476b7)

The management page can be visited through `/.netlify/functions/comment/ui`:
![image](https://github.com/walinejs/waline/assets/41264828/f433b068-b014-4d51-82e3-cdfda7fc23e3)
but return "path can not be blank" error when visit `/api/comment/ui`:
![image](https://github.com/walinejs/waline/assets/41264828/1b6de291-9d1c-43e5-93e1-5eb53a6a9389)

### 问题网站 | Website URL

https://www.talaxy.site/

### 服务部署在哪里？ | Where your waline deploy?

Netlify

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
It doesn't support in netlify.
