### ISSUE TITLE
[Bug]:PushPlus 通知无法推送 || [Bug]:PushPlus notification cannot be pushed

### ISSUE THREAD

**Issue by XiHua0522** [walinejs/waline#2085]
### 问题描述 | Describe the bug

PushPlus 通知无法推送
![image](https://github.com/walinejs/waline/assets/98436743/cb391577-0ad3-44f0-85c8-6a337dc49c65)
是我的变量设置有问题吗，我使用的是企业微信的webhook的通知渠道
![image](https://github.com/walinejs/waline/assets/98436743/03d22a55-ac4b-4487-93c7-7d52ebaecff4)
![image](https://github.com/walinejs/waline/assets/98436743/a52ec4e0-fff3-459b-85cb-f7249df03027)
机器人方面按照文档好像不需要额外配置吧？ 

### 问题网站 | Website URL

https://xihua.shop/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

PushPlus notification cannot be pushed
![image](https://github.com/walinejs/waline/assets/98436743/cb391577-0ad3-44f0-85c8-6a337dc49c65)
Is there something wrong with my variable settings? I am using the webhook notification channel of Enterprise WeChat.
![image](https://github.com/walinejs/waline/assets/98436743/03d22a55-ac4b-4487-93c7-7d52ebaecff4)
![image](https://github.com/walinejs/waline/assets/98436743/a52ec4e0-fff3-459b-85cb-f7249df03027)
According to the documentation, it seems that no additional configuration is required for the robot, right?

### Question Website | Website URL

https://xihua.shop/

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by XiHua0522** [comment]
补充：
我同时开启了 邮件通知 和 Server 酱 通知，但是邮箱通知只会在评论被回复时才会通知， 
而Server 酱是能正常通知到的，但是通知内容是乱的
![image](https://github.com/walinejs/waline/assets/98436743/dbb36566-3812-443d-b8b5-178c34733d94)
是通知方式只能选择一种吗？我也尝试过QQ通知，但也是不能接收

**Comment by XiHua0522** [comment]
好像发错地方了💦💦💦💦

**Comment by lizheming** [comment]
1. PushPlus 可能需要你先自行排查下，我目前没有使用这个通知服务
2. 邮箱通知在新邮件的时候也会通知
3. 目前 Server 酱的评论模板和新邮件通知的模板是一套模板，但 Server 酱不支持 HTML 渲染，所以有点问题。你可以尝试修改新邮件通知的模板解决这个问题
