### ISSUE TITLE
[Feature]: 设置指定页面禁止评论 || [Feature]: Set the specified page to prohibit comments.

### ISSUE THREAD

**Issue by Steven-WZH** [walinejs/waline#2092]
### 功能概述 | Describe the feature

有许多人在后台链接评论
![image](https://github.com/walinejs/waline/assets/113268133/e1484abd-9862-4824-9818-c9d5285d2905)
这样会导致整个站点的每个评论区都有这些评论
能否增加后台链接评论区禁止评论的变量

---
### Feature Overview | Describe the feature

There are many people linking and commenting in the background
![image](https://github.com/walinejs/waline/assets/113268133/e1484abd-9862-4824-9818-c9d5285d2905)
This will result in these comments appearing in every comments section throughout the site
Can you add a variable that prohibits comments in the background link comment area?

**Comment by lizheming** [comment]
不太理解问题，什么叫做“后台链接”，以及“整个站点的每个评论区都有这些评论”

**Comment by Steven-WZH** [comment]
抱歉我没有表达清楚。
下面两个链接的评论可以参考
https://waline.stevenw.cc/
https://blog.stevenw.cc/?p=docker-da-jian-walineping-lun-xi-tong

**Comment by lizheming** [comment]
每个页面需要有一个唯一 ID，和评论映射上，这样 Waline 能知道评论从属于哪个页面。Waline 默认使用的是 URL path 来做的唯一参数。 https://blog.stevenw.cc/themes/theme-hao/assets/js/comment/waline.js 你可以修改这个主题文件针对到你的场景进行适配。

具体可以查看文档 https://waline.js.org/reference/client/props.html#path
