### ISSUE TITLE
[Bug]: docker配置了评论邮件通知，但是一直收不到信息，qq 163都试了，密码也是配置的邮箱授权码，求助 || [Bug]: Docker has configured comment email notification, but the message has not been received. I have tried qq 163. The password is also the configured email authorization code. Please help.

### ISSUE THREAD

**Issue by Jehol1983** [walinejs/waline#2094]
### 问题描述 | Describe the bug

docker配置了评论邮件通知，但是一直收不到信息，qq 163都试了，密码也是配置的邮箱授权码，求助

### 问题网站 | Website URL

无

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

Docker has configured comment email notification, but I have not received the message. I have tried qq 163. The password is also the configured email authorization code. Please help.

### Question Website | Website URL

none

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
去 Vercel 后台看下日志有啥问题没有
