### ISSUE TITLE
[Bug]: 关于 auth || [Bug]: About auth

### ISSUE THREAD

**Issue by felixesintot** [walinejs/waline#2097]
### 问题描述 | Describe the bug

现在 https://oauth.lithub.cc 必须翻墙才能上？？

### 问题网站 | Website URL

https://waline.js.org

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

Now, does https://oauth.lithub.cc need to be accessed through the wall? ?

### Question Website | Website URL

https://waline.js.org

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
没有？
![image](https://github.com/walinejs/waline/assets/424491/b601f255-0d08-48e5-a573-2bf58ad2a707)

**Comment by felixesintot** [comment]
这里坐标为福建，已知 cname.vercel-dns.com 在这里上不去，所以能不能改成 A 76.223.126.88一下？

**Comment by felixesintot** [comment]
![image](https://github.com/walinejs/waline/assets/98651799/cfa78fff-aa01-430e-a76f-1068692b027e)

**Comment by lizheming** [comment]
换了
