### ISSUE TITLE
[Bug]: 访问restful服务器报错 401 unauthorized || [Bug]: Error 401 unauthorized when accessing restful server

### ISSUE THREAD

**Issue by xsr2004** [walinejs/waline#2103]
### 问题描述 | Describe the bug

# 访问restful服务器报错 401 unauthorized

![image](https://github.com/walinejs/waline/assets/113783793/918243f2-d6e5-459e-8474-5c818e47f99b)

**若不连梯子则报错 fetch failed**

 **postman测试restful服务器api也报401 unauthorized错误。（连梯子）**

卡了好久了，求大佬解决一下！！谢谢！1
![image](https://github.com/walinejs/waline/assets/113783793/b8770785-0946-4800-ae22-a4bdfcaef4ae)

下面是我的leancloud的接口和我的vercel生成的默认域名
https://s2msivjn.api.lncldglobal.com
https://myblog-beige-pi.vercel.app/

### 问题网站 | Website URL

https://myblog-beige-pi.vercel.app/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

# Error 401 unauthorized when accessing restful server

![image](https://github.com/walinejs/waline/assets/113783793/918243f2-d6e5-459e-8474-5c818e47f99b)

**If the ladder is not connected, an error fetch failed will be reported**

 **Postman also reported a 401 unauthorized error when testing the restful server api. (With ladder)**

I've been stuck for a long time, please help me solve it! ! Thanks! 1
![image](https://github.com/walinejs/waline/assets/113783793/b8770785-0946-4800-ae22-a4bdfcaef4ae)

The following is the interface of my leancloud and the default domain name generated by my vercel
https://s2msivjn.api.lncldglobal.com
https://myblog-beige-pi.vercel.app/

### Question Website | Website URL

https://myblog-beige-pi.vercel.app/

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
环境变量检查下，一般这种是 LeanCloud 相关密钥配置错误导致的，注意前后空格之类的
