### ISSUE TITLE
[Bug]: Register Fail with non https service

### ISSUE THREAD

**Issue by hilaily** [walinejs/waline#2104]
### 问题描述 | Describe the bug

I deployed waline in my vps, and only allowed access by https(http will return 301 to https).
but this request it is always use http protocol(/api/token is also), I don't know why.
<img width="1211" alt="image" src="https://github.com/walinejs/waline/assets/5792904/5f54813d-473e-45fe-9119-b6c964990497">

### 问题网站 | Website URL

https://comment.hulalala.top

### 服务部署在哪里？ | Where your waline deploy?

Self Host

### 数据存储在哪里？| Where your comment data store?

MySQL

**Comment by lizheming** [comment]
https://github.com/orgs/walinejs/discussions/2017
