### ISSUE TITLE
[Bug]: There is empty response body for `/api/comment` in case the number of eligible data items over a certain number

### ISSUE THREAD

**Issue by mengrru** [walinejs/waline#2105]
### 问题描述 | Describe the bug

The request `GET /api/comment?type=list&owner=all&status=approved&keyword=&page=1&lang=en-US` will return an empty response body with status 200 (I have over 100 approved messages):

![image](https://github.com/walinejs/waline/assets/80361883/9908db26-00f9-46ea-a605-824c4d30d79f)

![image](https://github.com/walinejs/waline/assets/80361883/d0ccdcc2-7bc9-4430-9811-9224db4615c5)

When I added a keyword to reduce the number of eligible data items like: `/api/comment?type=list&owner=all&status=approved&keyword=meng&page=1&lang=en-US`, I got the expected result:

![image](https://github.com/walinejs/waline/assets/80361883/898069f8-a59e-470e-a406-9f9c8044e929)

![image](https://github.com/walinejs/waline/assets/80361883/c9404738-b5a7-4a6b-9f72-698fc9e77a25)

### 问题网站 | Website URL

https://comment-backend.vercel.app/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

MongoDB

**Comment by lizheming** [comment]
I can't reproduce your problem at my development environment. Can you reproduce it stably? If so, can you check if there are any error messages in the log panel at the vercel?
![image](https://github.com/walinejs/waline/assets/424491/ed726ced-1ad1-4d9f-8d5f-bfd01fddbbc4)
