### ISSUE TITLE
[Bug]: 使用Vercel和MongoDB部署无法注册 || [Bug]: Unable to register using Vercel and MongoDB deployment

### ISSUE THREAD

**Issue by Akimio521** [walinejs/waline#2106]
### 问题描述 | Describe the bug

使用Vercel和MongoDB部署无法注册，也没办法评论
![无法注册](https://github.com/walinejs/waline/assets/77880495/c2c98c10-7400-46cb-a770-0ff2e6e52262)
MongoDB我是使用https://cloud.mongodb.com免费的数据库，不知道是不是我的环境变量填写有问题
![环境变量](https://github.com/walinejs/waline/assets/77880495/fede4f71-a1ff-4a66-8b96-cea8883ad18c)
把`MONGO_OPT_SSL`改为`false`也依旧无法注册

### 问题网站 | Website URL

https://waline-vercel-woad.vercel.app/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

MongoDB

---
### Problem description | Describe the bug

Unable to register and comment using Vercel and MongoDB deployment
![Unable to register](https://github.com/walinejs/waline/assets/77880495/c2c98c10-7400-46cb-a770-0ff2e6e52262)
For MongoDB, I use the free database https://cloud.mongodb.com. I don’t know if there is something wrong with my environment variables.
![Environment variables](https://github.com/walinejs/waline/assets/77880495/fede4f71-a1ff-4a66-8b96-cea8883ad18c)
Even after changing `MONGO_OPT_SSL` to `false`, I still cannot register.

### Question Website | Website URL

https://waline-vercel-woad.vercel.app/

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

MongoDB

**Comment by lizheming** [comment]
https://waline.js.org/guide/database.html#mongodb 参考下示例配置，HOST 和 PORT 要配置成一个数组字符串

**Comment by Akimio521** [comment]
![image](https://github.com/walinejs/waline/assets/77880495/d8268018-4b7e-4a29-8d18-20e18034f7ec)
参考了多机格式还是不行

**Comment by Big-Cake-jpg** [comment]
不要填写 REPLICA_SET，可以参考我之前发的文章：[将 Waline 从 LeanCloud 迁移至 MongoDB Cloud](https://lihaoyu.cn/posts/migrate-waline-db-to-mongodb)

**Comment by Akimio521** [comment]
> 不要填写 REPLICA_SET，可以参考我之前发的文章：[将 Waline 从 LeanCloud 迁移至 MongoDB Cloud](https://lihaoyu.cn/posts/migrate-waline-db-to-mongodb)
> 
> Do not fill in REPLICA_SET, you can refer to my previous article: [Migrate Waline from LeanCloud to MongoDB Cloud](https://lihaoyu.cn/posts/migrate-waline-db-to-mongodb)

我这么填还是提示无法注册
```
MONGO_DB=Waline
MONGO_USER=xxxx
MONGO_PASSWORD=xxxxx
MONGO_AUTHSOURCE=admin
MONGO_OPT_SSL=true
MONGO_HOST=["ac-mjok8qk-shard-00-00.upxk3ss.mongodb.net","ac-mjok8qk-shard-00-01.upxk3ss.mongodb.net","ac-mjok8qk-shard-00-02.upxk3ss.mongodb.net"]
MONGO_PORT=[27017,27017,27017]
```

**Comment by Akimio521** [comment]
> 不要填写 REPLICA_SET，可以参考我之前发的文章：[将 Waline 从 LeanCloud 迁移至 MongoDB Cloud](https://lihaoyu.cn/posts/migrate-waline-db-to-mongodb)
> 
> ---
> Do not fill in REPLICA_SET, you can refer to my previous article: [Migrate Waline from LeanCloud to MongoDB Cloud](https://lihaoyu.cn/posts/migrate-waline-db-to-mongodb)
> 

我部署成功了，没想到3个host需要对应4个port
