### ISSUE TITLE
[Bug]: File too large! File size limit 128KB

### ISSUE THREAD

**Issue by KnightKilito** [walinejs/waline#2120]
### 问题描述 | Describe the bug

<img width="788" alt="image" src="https://github.com/walinejs/waline/assets/61006533/b07f2f1b-ac4d-4910-bd63-6ae04abb5873">
上传图片或者文本框里粘贴图片会报错
我没有修改过配置呀（我也没找到限制大小的配置），之前都可以上传现在怎么突然限制图片大小了，前端是引入的https://cdn.staticfile.org/waline/2.15.5/，会不会跟这个有关？

### 问题网站 | Website URL

https://moechun.fun/links/

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

<img width="788" alt="image" src="https://github.com/walinejs/waline/assets/61006533/b07f2f1b-ac4d-4910-bd63-6ae04abb5873">
An error will be reported when uploading images or pasting images into text boxes.
I haven't modified the configuration (I haven't found the configuration to limit the size). I could upload it before, but now I suddenly limit the image size. The front-end is introduced at https://cdn.staticfile.org/waline/2.15.5/. Could it be related to this?

### Question Website | Website URL

https://moechun.fun/links/

### Where is the service deployed? | Where your waline deploy?

Docker

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
https://github.com/orgs/walinejs/discussions/1727

**Comment by KnightKilito** [comment]
好叻，我去看教程把评论图片整到图床去吧，base64省事但是确实慢哈哈哈哈
