### ISSUE TITLE
[Bug]: 客户端登录后的默认头像没有遵循服务器配置（问题仍在，详细代码帖出） || [Bug]: The default avatar after client login does not follow the server configuration (the problem is still there, the detailed code will be posted)

### ISSUE THREAD

**Issue by taotecode** [walinejs/waline#2125]
### 问题描述 | Describe the bug

引用之前的issues #1029 

我发现了到今天仍然没有修复这个问题

在管理后台中，头像仍然是固定链接
![image](https://github.com/walinejs/waline/assets/48904825/a3750fe9-26f4-4646-868b-5cddf80ee983)

这是个很低级错误的问题
来自：`packages/admin/src/pages/manage-comments/utils.js`
```js
export function buildAvatar(email = '', avatar = '') {
  if (avatar) {
    return avatar;
  }

  if (typeof email !== 'string') {
    email = '';
  }

  return `https://sdn.geekzu.org/avatar/${md5(email)}?s=40&r=G&d=`;
}
```
![image](https://github.com/walinejs/waline/assets/148311282/eec37288-a081-4276-bd4c-fcefa9e832b5)

@lizheming @cjh0613 

同时我发现这个代码来自 #259 的合并提交中

### 问题网站 | Website URL

https://waline.berf1.cn

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

SQLite

---
### Problem description | Describe the bug

Quoting previous issues #1029

I found this problem and still haven't fixed it to this day

In the admin background, the avatar is still a fixed link
![image](https://github.com/walinejs/waline/assets/48904825/a3750fe9-26f4-4646-868b-5cddf80ee983)

This is a very low-level mistake
From: `packages/admin/src/pages/manage-comments/utils.js`
```js
export function buildAvatar(email = '', avatar = '') {
  if (avatar) {
    return avatar;
  }

  if (typeof email !== 'string') {
    email = '';
  }

  return `https://sdn.geekzu.org/avatar/${md5(email)}?s=40&r=G&d=`;
}
```
![image](https://github.com/walinejs/waline/assets/148311282/eec37288-a081-4276-bd4c-fcefa9e832b5)

@lizheming @cjh0613

At the same time, I found that this code comes from the merge commit of #259

### Question Website | Website URL

https://waline.berf1.cn

### Where is the service deployed? | Where your waline deploy?

Docker

### Where is the data stored? | Where your comment data store?

SQLite

**Comment by lizheming** [comment]
可以抓下列表接口返回的数据，默认评论数据会返回 avatar 字段，前端会优先用 avatar 字段的数据的。

https://github.com/walinejs/waline/blob/main/packages/admin/src/pages/manage-comments/utils.js#L4-L6

https://github.com/walinejs/waline/blob/main/packages/admin/src/pages/manage-comments/index.jsx#L544
