### ISSUE TITLE
[Bug]: 使用暗色主题后评论的显示问题 || [Bug]: Display problem of comments after using dark theme

### ISSUE THREAD

**Issue by charle00001** [walinejs/waline#2127]
### 问题描述 | Describe the bug

使用暗色主题后正常评论无法反色为白色显示，评论无法显示清楚，文字颜色与主题颜色相近。
网站测试链接：
https://charle00001.github.io/posts/387162d6.html
![图片](https://github.com/walinejs/waline/assets/91960736/263d509d-4e37-4e71-9e26-58de1801e8b1)

这是hexo博客next主题的问题，不知能不能在这里反馈？
谢谢。

### 问题网站 | Website URL

https://charle00001.github.io/posts/387162d6.html

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

After using the dark theme, normal comments cannot be displayed in white, comments cannot be displayed clearly, and the text color is similar to the theme color.
Website test link:
https://charle00001.github.io/posts/387162d6.html
![Picture](https://github.com/walinejs/waline/assets/91960736/263d509d-4e37-4e71-9e26-58de1801e8b1)

This is a problem with the next theme of the hexo blog. I wonder if you can give feedback here?
Thanks.

### Question Website | Website URL

https://charle00001.github.io/posts/387162d6.html

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by jerryc127** [comment]
你是不是没有设置这个？
https://waline.js.org/reference/client/props.html#dark

**Comment by Mister-Hope** [comment]
It seems your website is working as expected.
