### ISSUE TITLE
[Bug]: 配置Turnstile报错 || [Bug]: Error reporting when configuring Turnstile

### ISSUE THREAD

**Issue by uuanqin** [walinejs/waline#2128]
### 问题描述 | Describe the bug

服务端Vercel 环境变量已配置TURNSTILE_KEY、TURNSTILE_SECRET。
主题使用Hexo Butterfly主题，已配置turnstileKey选项

提交评论时按钮一直处于加载状态，控制台报错：

![image](https://github.com/walinejs/waline/assets/61202052/7e224020-f163-431c-8d9b-8114f858d8d2)

### 问题网站 | Website URL

~~https://uuanqin.top/pages/building.html~~ 目前暂时恢复原先状态

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

The server-side Vercel environment variables have been configured with TURNSTILE_KEY and TURNSTILE_SECRET.
The theme uses the Hexo Butterfly theme, and the turnstileKey option has been configured

When submitting a comment, the button is always loading and the console reports an error:

![image](https://github.com/walinejs/waline/assets/61202052/7e224020-f163-431c-8d9b-8114f858d8d2)

### Question Website | Website URL

~~https://uuanqin.top/pages/building.html~~ Currently restored to the original state

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
可以提供一个可复现的地址我再 check 下

**Comment by uuanqin** [comment]
感谢回复。问题已解决，更新cdn链接到新版本的waline.js即可。
