### ISSUE TITLE
[Bug]: 更新浏览数量与查询浏览数量参数不一致 || [Bug]: The parameters for updating the number of views and querying the number of views are inconsistent

### ISSUE THREAD

**Issue by sjsmi1e** [walinejs/waline#2146]
### 问题描述 | Describe the bug

 更新浏览数量接口使用的是window.location.pathname参数，会默认url编码，如果网址存在中文，会出现更新和查询不一致的问题，如下图：
请求浏览数量+1
![image](https://github.com/walinejs/waline/assets/34391836/f5f1580f-1b10-449b-b295-212087b43931)
而查询浏览数量参数如下
![image](https://github.com/walinejs/waline/assets/34391836/24048d5b-530f-4c72-9b70-abb0b832dc3f)
当前为了解决这个问题，我暂时的处理方式是每次实例化waline是调用post请求更新一次非编码的参数请求，如下：
![image](https://github.com/walinejs/waline/assets/34391836/d404af53-2b3f-4127-996d-e1ffa48724bd)
希望能有方式解决，不需要每次进行额外的请求了。

### 问题网站 | Website URL

www.sjsmile.cn

### 服务部署在哪里？ | Where your waline deploy?

Other

### 数据存储在哪里？| Where your comment data store?

MySQL

---
### Problem description | Describe the bug

 The interface for updating the number of views uses the window.location.pathname parameter, which will default to URL encoding. If the URL exists in Chinese, there will be an inconsistency problem between update and query, as shown below:
Number of requested views +1
![image](https://github.com/walinejs/waline/assets/34391836/f5f1580f-1b10-449b-b295-212087b43931)
The parameters for querying the number of views are as follows:
![image](https://github.com/walinejs/waline/assets/34391836/24048d5b-530f-4c72-9b70-abb0b832dc3f)
Currently, in order to solve this problem, my temporary approach is to call a post request to update a non-encoded parameter request every time I instantiate Waline, as follows:
![image](https://github.com/walinejs/waline/assets/34391836/d404af53-2b3f-4127-996d-e1ffa48724bd)
I hope there is a way to solve it without making additional requests every time.

### Question Website | Website URL

www.sjsmile.cn

### Where is the service deployed? | Where your waline deploy?

Other

### Where is the data stored? | Where your comment data store?

MySQL

**Comment by lizheming** [comment]
1. 可以设置主题里面获取阅读统计的数据时 path 进行编码
2. 如果认为编码这个问题比较麻烦，可以设置其他的唯一 id，本质上是两边的 id 能对应上即可
3. 本质上这属于主题设置的两个参数没对应上的原因，Waline 的 path 都是可配置的，不属于 Waline 的 Bug 吧，把配置调整正确即可。
