### ISSUE TITLE
[Bug]: 修改用户评论内容会连带修改用户头像、昵称及网址 || [Bug]: Modifying the user's comment content will also modify the user's avatar, nickname and website.

### ISSUE THREAD

**Issue by uuanqin** [walinejs/waline#2163]
### 问题描述 | Describe the bug

比如这时有一位用户评论：
![QQ截图20231128225527](https://github.com/walinejs/waline/assets/61202052/c31a1ae5-aa33-49fc-8fba-17d3717c0967)
管理员登录后，点击编辑按钮进行编辑：
![QQ截图20231128225616](https://github.com/walinejs/waline/assets/61202052/2bec231d-bcaf-444f-ba02-d477ba3eb9f5)
提交，并 **刷新当前页面** 后，该用户的头像、昵称及网址信息改成了管理员的信息。
![QQ截图20231128225701](https://github.com/walinejs/waline/assets/61202052/64b01c1a-c48a-427e-b27f-a3d41ddd1b1d)
后台显示信息：
![image](https://github.com/walinejs/waline/assets/61202052/3981fb1b-7cf0-41cb-a17c-59c56b28edea)

### 问题网站 | Website URL

https://uuanqin.top/pages/building.html

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

For example, a user commented:
![QQ screenshot 20231128225527](https://github.com/walinejs/waline/assets/61202052/c31a1ae5-aa33-49fc-8fba-17d3717c0967)
After the administrator logs in, click the edit button to edit:
![QQ screenshot 20231128225616](https://github.com/walinejs/waline/assets/61202052/2bec231d-bcaf-444f-ba02-d477ba3eb9f5)
After submitting and **refreshing the current page**, the user's avatar, nickname and website information are changed to the administrator's information.
![QQ screenshot 20231128225701](https://github.com/walinejs/waline/assets/61202052/64b01c1a-c48a-427e-b27f-a3d41ddd1b1d)
Information displayed in the background:
![image](https://github.com/walinejs/waline/assets/61202052/3981fb1b-7cf0-41cb-a17c-59c56b28edea)

### Question Website | Website URL

https://uuanqin.top/pages/building.html

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
确认是个 Bug，后面修复一下，先暂时用后台修改吧。
