### ISSUE TITLE
导出文件 umd 移除确认 || Export file umd removal confirmation

### ISSUE THREAD

**Issue by lizheming** [walinejs/waline#2203]
https://github.com/walinejs/waline/blob/2e98f0b3cec34ed771cfebc268798f644539aa6b/packages/client/package.json#L34

是不是需要移除一下，现在应该不产出 umd 文件了吧~ 

https://www.npmjs.com/package/@waline/client/v/3.0.0-alpha.7?activeTab=code

ps. 3.0.0-alpha.6 和 3.0.0-alpha.7 我看 CDN 引入反馈有一些问题，暂时先标记废弃了

---
https://github.com/walinejs/waline/blob/2e98f0b3cec34ed771cfebc268798f644539aa6b/packages/client/package.json#L34

Do you need to remove it? The umd file should not be generated now~

https://www.npmjs.com/package/@waline/client/v/3.0.0-alpha.7?activeTab=code

ps. 3.0.0-alpha.6 and 3.0.0-alpha.7 I think there are some problems with the CDN introduction feedback, so I will mark them as abandoned for the time being

**Comment by Mister-Hope** [comment]
好的今天预答辩，答辩完再看看

**Comment by Mister-Hope** [comment]
waline 的 umd 版本考虑到 scrip 引入问题加回去了，其他的 cjs 和 umd 都去掉了。
