### ISSUE TITLE
[Bug]: Unexpected token 'export'

### ISSUE THREAD

**Issue by yancqS** [walinejs/waline#2204]
### 问题描述 | Describe the bug

When I opened the blog today, I found that the comment system was gone and there was an error message from waline in the console. It was still OK last Friday。
error messag: `Uncaught SyntaxError: Unexpected token 'export' (at waline.min.js:7:154898)`
Thanks

### 问题网站 | Website URL

https://www.up-4ever.site/posts/e823e90e/

### 服务部署在哪里？ | Where your waline deploy?

Self Host

### 数据存储在哪里？| Where your comment data store?

MySQL

**Comment by lizheming** [comment]
3.0 正在尝试使用 ES Module 作为默认导出形式，所以不能使用普通的方式做加载。建议先使用这两个增加版本号限制的地址进行加载。

- https://cdn.jsdelivr.net/npm/@waline/client@2/dist/waline.min.js
- https://cdn.jsdelivr.net/npm/@waline/client@2/dist/waline.min.css

如果是主题自带的逻辑，可以给主题作者提个 issue 添加一下。

**Comment by yancqS** [comment]
> 3.0 正在尝试使用 ES Module 作为默认导出形式，所以不能使用普通的方式做加载。建议先使用这两个增加版本号限制的地址进行加载。
> 
> * https://cdn.jsdelivr.net/npm/@waline/client@2/dist/waline.min.js
> * https://cdn.jsdelivr.net/npm/@waline/client@2/dist/waline.min.css
> 
> 如果是主题自带的逻辑，可以给主题作者提个 issue 添加一下。
> 
> 3.0 is trying to use ES Module as the default export form, so it cannot be loaded in the ordinary way. It is recommended to use these two addresses with increased version number restrictions to load first.
> 
> * https://cdn.jsdelivr.net/npm/@waline/client@2/dist/waline.min.js
> * https://cdn.jsdelivr.net/npm/@waline/client@2/dist/waline.min.css
> 
> If it is the logic that comes with the theme, you can submit an issue to the theme author to add it.

多谢~

**Comment by Ran-Xing** [comment]
环境：hexo butterfly date.space 

求支招，不想开一个新的issues，谢谢

![image](https://github.com/walinejs/waline/assets/73819467/c307f920-cef4-459f-ae3c-850bc30fe5f3)
![image](https://github.com/walinejs/waline/assets/73819467/39d98ac3-b08c-433f-b9c4-c05d3c3ddfd9)
