### ISSUE TITLE
[Bug]: 其他页面 pageview 异常 || [Bug]: Pageview exception on other pages

### ISSUE THREAD

**Issue by BeiyanYunyi** [walinejs/waline#2207]
### 问题描述 | Describe the bug

复现版本为 master 分支 6c9f4f6 。后端与 https://waline.js.org/ 相同。

复现方法为，将 `pnpm client:dev` 的 `http://localhost:5173/pageview.html` 改为如下所示：

```html
<!doctype html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Waline pageview test</title>
  </head>
  <body>
    阅读量: <span id="/" class="waline-pageview-count"></span>
    页面阅读量 1：
    <span
      class="waline-pageview-count"
      data-path="/guide/features/pageview.html"
    ></span
    >页面阅读量 2：<span
      class="waline-pageview-count"
      data-path="/guide/features/i18n.html"
    ></span>
    <script type="module">
      import { pageviewCount } from '../src/entries/pageview.ts';

      pageviewCount({
        serverURL:
          import.meta.env.SERVERURL || 'https://walinejs.comment.lithub.cc',
        path: '/',
      });
    </script>
  </body>
</html>
```

即可见“页面阅读量 1”与“页面阅读量 2”处出现异常。出现异常的原因是在查询其他页面的访问量时，服务端返回值与客户端预期不同。

BeiyanYunyi/sodesu@8208fae 在前端给出了一个可能的缓解或修复措施。然而，我认为服务端的接口同样需要统一。

### 问题网站 | Website URL

https://waline.js.org/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

The reproducible version is master branch 6c9f4f6. The backend is the same as https://waline.js.org/.

The method to reproduce is to change `http://localhost:5173/pageview.html` of `pnpm client:dev` to the following:

```html
<!doctype html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Waline pageview test</title>
  </head>
  <body>
    Reading volume: <span id="/" class="waline-pageview-count"></span>
    Page views 1:
    <span
      class="waline-pageview-count"
      data-path="/guide/features/pageview.html"
    ></span
    >Page views 2:<span
      class="waline-pageview-count"
      data-path="/guide/features/i18n.html"
    ></span>
    <script type="module">
      import { pageviewCount } from '../src/entries/pageview.ts';

      pageviewCount({
        serverURL:
          import.meta.env.SERVERURL || 'https://walinejs.comment.lithub.cc',
        path: '/',
      });
    </script>
  </body>
</html>
```

It can be seen that there are exceptions at "Page Views 1" and "Page Views 2". The reason for the exception is that when querying the visits of other pages, the server return value is different from the client's expectation.

BeiyanYunyi/sodesu@8208fae gives a possible mitigation or fix on the front end. However, I think the server-side interface also needs to be unified.

### Question Website | Website URL

https://waline.js.org/

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
1. pageview 接口之前是有一个返回数据问题，是当请求一条的时候返回的是 `1`，而多条的时候返回的是 `[1,1]` 数组格式。这块在新的版本中已经都统一成了 `{errmsg: '', errno: '', data: [1]}` 结构体了。前提是需要使用 `<serverURL>/api` 新的接口来请求。
2. 我看了下你的 MR https://github.com/BeiyanYunyi/sodesu/commit/8208fae 没有看太明白，我们应该是不会返回`{time: 1}` 这种结构的。这块建议你直接发下请求地址我一块看看。

**Comment by BeiyanYunyi** [comment]
对于“其他页面 pageview”的情况：

`GET https://walinejs.comment.lithub.cc/api/article?path=/guide/features/pageview.html,/guide/features/i18n.html&type=time&lang=zh-CN`

返回值：

```json
{"errno":0,"errmsg":"","data":[{"time":5995},{"time":4844}]}
```

对于“本页面 pageview”的情况：

`POST https://walinejs.comment.lithub.cc/api/article?lang=zh-CN`

返回值：

```json
{"errno":0,"errmsg":"","data":[125849]}
```

两个返回值的 data 格式很显然是不同的。

**Comment by Mister-Hope** [comment]
Any update with this @lizheming, dpes client side code need any changes?

**Comment by Mister-Hope** [comment]
@lizheming 我这两天又羊了，正难受，你看一下这个问题是 @waline/api 写的有问题还是的确需要 refine 一下服务端的 api 吧。

**Comment by lizheming** [comment]
@Mister-Hope 是服务端 API 改造的问题，这个我正在纠结预期的返回格式是什么样子的，确认完之后再统一修改一下。

**Comment by lizheming** [comment]
为了统一 pageview 和 reaction 的返回格式，思考了下，最终统一按照如下结构体进行返回。`@waline/client@v3` 也需要进行下适配，这块我来同步修改一下。

```
type ResponseData = Counter[];

interface Counter {
  time?: number;
  reaction0: number;
  reaction1: number;
}
```

**Comment by FidStyle** [comment]
![image](https://github.com/walinejs/waline/assets/115857087/2a9e516a-5ae9-400c-8851-4313810382d2)
按照文档配置发生error，仍然无法显示
服务端客户端均为latest
@lizheming

**Comment by lizheming** [comment]
@FidStyle 修了，更新到 `@waline/client@3.1.21` 吧
