### ISSUE TITLE
[Feature]: 更好地支持自定义用户系统 || [Feature]: Better Support custom user system

### ISSUE THREAD

**Issue by UriPomer** [walinejs/waline#2208]
### 功能概述 | Describe the feature

目前的用户系统很难自定义扩展，尤其是在本地部署的情况下。官方似乎只对 Vercel 有较好支持，对本地部署没有提供入口函数。也有可能是我没有研究出来，总之我现在完成了 UserModel ，也执行了 module.exports 来导出模块，但我不知道在哪里应用我自定义的模块

---
### Feature Overview | Describe the feature

Current user systems are difficult to customize and extend, especially if deployed locally. The official seems to only have good support for Vercel and does not provide entry functions for local deployment. It's also possible that I haven't researched it. In short, I have completed the UserModel and executed module.exports to export the module, but I don't know where to apply my customized module

**Comment by lizheming** [comment]
https://github.com/walinejs/waline/blob/main/packages/server/vanilla.js#L17 映射到 `/app/config.js` 即可

**Comment by UriPomer** [comment]
感谢回复，我去研究一下
