### ISSUE TITLE
[Bug]: 管理后台无法拉取评论 || [Bug]: The management background cannot pull comments

### ISSUE THREAD

**Issue by Ares-X** [walinejs/waline#2218]
### 问题描述 | Describe the bug

管理员身份登陆后台，点击评论管理，chrome 调试工具记录请求信息
请求地址：
```
/api/comment?type=list&owner=all&status=approved&keyword=&page=1&lang=zh-CN
```
Payload：
```
type=list&owner=all&status=approved&keyword=&page=1&lang=zh-CN
```
响应状态500
Response Data:
```
{"errno":500,"errmsg":"Input data should be a String"}
```
仅Approved类型评论会出现500报错，waiting和spam均正常返回

用户管理也可以正常显示

### 问题网站 | Website URL

https://waline.ares-x.com/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

Log in to the backend as an administrator, click Comment Management, and the chrome debugging tool will record the request information.
Request address:
```
/api/comment?type=list&owner=all&status=approved&keyword=&page=1&lang=zh-CN
```
Payload:
```
type=list&owner=all&status=approved&keyword=&page=1&lang=zh-CN
```
Response status 500
Response Data:
```
{"errno":500,"errmsg":"Input data should be a String"}
```
Only Approved type comments will receive a 500 error, and waiting and spam will return normally.

User management can also be displayed normally

### Question Website | Website URL

https://waline.ares-x.com/

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
官网是同样的部署环境，没办法复现这个问题，你提供下账号登下你后台看下吧。

**Comment by Ares-X** [comment]
approved类型status参数为mine的时候可以正常获取到评论
![image](https://github.com/walinejs/waline/assets/30471149/61421e67-bed4-4079-ba2b-48e48ee48fff)
status参数为all到时候返回
```
{"errno":500,"errmsg":"Input data should be a String"}
```
![image](https://github.com/walinejs/waline/assets/30471149/29ce1b38-35d0-421f-8055-dc0ff069279d)

**Comment by Ares-X** [comment]
vercel后台log
```
[36m[2023-12-24T14:45:23.673] [8] [DEBUG][39m - Post Comment Start!
[36m[2023-12-24T14:45:23.673] [8] [DEBUG][39m - Post Comment initial Data: {
  link: undefined,
  mail: undefined,
  nick: undefined,
  pid: undefined,
  rid: undefined,
  ua: undefined,
  url: undefined,
  comment: undefined,
  ip: '',
  insertedAt: 2023-12-24T14:45:23.673Z,
  user_id: '639ef5a05fee9f4325f95faf'
}
[36m[2023-12-24T14:45:23.674] [8] [DEBUG][39m - Comment post hooks preSave done!
[36m[2023-12-24T14:45:24.029] [8] [DEBUG][39m - Comment have been added to storage.
Error: Input data should be a String
    at MarkdownIt.parse (/var/task/node_modules/markdown-it/lib/index.js:519:11)
    at MarkdownIt.render (/var/task/node_modules/markdown-it/lib/index.js:544:36)
    at /var/task/node_modules/@waline/vercel/src/service/markdown/index.js:61:43
    at formatCmt (/var/task/node_modules/@waline/vercel/src/controller/comment.js:57:21)
    at module.exports.postAction (/var/task/node_modules/@waline/vercel/src/controller/comment.js:239:23)
    at cors (/var/task/node_modules/@koa/cors/index.js:108:16)
    at /var/task/node_modules/@waline/vercel/src/middleware/version.js:5:3
    at /var/task/node_modules/@waline/vercel/src/middleware/prefix-warning.js:27:3
    at Server.<anonymous> (/var/task/___vc/__launcher/helpers-23SL6TQX.js:1:7826)
    at Server.<anonymous> (/var/task/___vc/__launcher/bridge-server-PK2WV7I3.js:5:12379)
```

**Comment by Ares-X** [comment]
查看Leancloud存储数据发现多个所有字段全部为`undefined`的row，删除后管理后台可以正常取到数据

**Comment by lizheming** [comment]
了解，那应该就是空数据导致的 Markdown 渲染失败了，应该是非正常情况，先忽略吧，谢谢反馈。

**Comment by Ares-X** [comment]
![image](https://github.com/walinejs/waline/assets/30471149/2c2bb8b3-3e5f-478c-8f1e-13af0766235b)
```
POST /comment?lang=en
```

该接口并未验证用户输入合法性，POST空json数据会返回

```
{"errno":500,"errmsg":"Input data should be a String"}
```

同时在数据库插入无效数据

![image](https://github.com/walinejs/waline/assets/30471149/6b76374f-ec2c-47f3-85ae-1e2a8c7eadf1)

**Comment by lizheming** [comment]
评论除了评论内容之外是可以都为空的，评论内容之前只做了前台的空判断，没有在服务端做处理，有需要的话欢迎 PR。
