### ISSUE TITLE
[Bug]: 3.0 版本的 @waline/client 的 exports 问题 || [Bug]: Issue with exports of @waline/client in version 3.0

### ISSUE THREAD

**Issue by YieldRay** [walinejs/waline#2230]
### 问题描述 | Describe the bug

版本是 "@waline/client": "^3.0.0-alpha.9"  
目前 package.json 中 exports 字段如下：
```json
"./waline.css": "./dist/waline.css",
```
导致[文档](https://waline.js.org/cookbook/import/project.html)给出的代码无法正确导入
```js
import '@waline/client/dist/waline.css';
```
也许可以再加一个 `./dist/waline.css` 的映射（就像 2.15.8 版本一样）

我在 nextjs 中使用时，build 会报 `ReferenceError: __VUE_PROD_DEVTOOLS__ is not defined` 错误    
这也许是因为 main 字段的 `./dist/slim.js` 构建时[将 vue 作为外部依赖](https://github.com/walinejs/waline/blob/77ad1b487208a18912cf24937b6f4709d3b62ce2/packages/client/rollup.config.ts#L107)而不是一起打包，因此导入这个文件需要就自行定义该常量  

导入 @waline/client/full 版本就不需要定义了，我觉得文档中可以建议非 vue 项目使用 @waline/client/full，或者加一些别的说明

### 问题网站 | Website URL

https://waline.js.org/cookbook/

### 服务部署在哪里？ | Where your waline deploy?

Other

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

The version is "@waline/client": "^3.0.0-alpha.9"
Currently the exports field in package.json is as follows:
```json
"./waline.css": "./dist/waline.css",
```
As a result, the code given in [Document](https://waline.js.org/cookbook/import/project.html) cannot be imported correctly.
```js
import '@waline/client/dist/waline.css';
```
Maybe add another mapping to `./dist/waline.css` (like version 2.15.8)

When I use it in nextjs, the build will report `ReferenceError: __VUE_PROD_DEVTOOLS__ is not defined` error
This may be because the `./dist/slim.js` of the main field is built [with vue as an external dependency](https://github.com/walinejs/waline/blob/77ad1b487208a18912cf24937b6f4709d3b62ce2/packages/client/rollup.config. ts#L107) instead of packaging together, so you need to define this constant yourself when importing this file.

There is no need to define the version that imports @waline/client/full. I think the document can recommend that non-vue projects use @waline/client/full, or add some other instructions.

### Question Website | Website URL

https://waline.js.org/cookbook/

### Where is the service deployed? | Where your waline deploy?

Other

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by Mister-Hope** [comment]
1. For `__VUE_PROD_DEVTOOLS__`, this is a upstream bug or something you should handle yourself.

   The difference depends on Vue teams, that is whether `__VUE_PROD_DEVTOOLS__` should be manually defined when using Vue with pure javascript or users are expecting to add `@vitejs/plugin-vue` or `vue-loader` whenever they use vue. If so do the things above, if not, then it's a Vue bug that Vue doesnot handle the case that this flag is not set.

2. For the dist export, as we are already moving to full ESM with node, there is no need to do so. Exports should be simple as possible, so that users can easily import them.

**Comment by YieldRay** [comment]
> 1. For `__VUE_PROD_DEVTOOLS__`, this is a upstream bug or something you should handle yourself.
>    The difference depends on Vue teams, that is whether `__VUE_PROD_DEVTOOLS__` should be manually defined when using Vue with pure javascript or users are expecting to add `@vitejs/plugin-vue` or `vue-loader` whenever they use vue. If so do the things above, if not, then it's a Vue bug that Vue doesnot handle the case that this flag is not set.
> 2. For the dist export, as we are already moving to full ESM with node, there is no need to do so. Exports should be simple as possible, so that users can easily import them.

It seems to be a upstream bug, upgrade to 3.0.0-alpha.10 and turn off the `webpack.DefinePlugin` will work.
