### ISSUE TITLE
[Feature]: cdnjs 中添加 mjs 文件 || [Feature]: Add mjs file to cdnjs

### ISSUE THREAD

**Issue by yy4382** [walinejs/waline#2234]
### 功能概述 | Describe the feature

现在waline在cdnjs中只包含了js和css 文件，但是实际上需要使用的是mjs文件，希望可以添加

现在unpkg在国内速度很一般，cdnjs中有了mjs文件之后国内的一些cdn就能用了

ref: <https://github.com/cdnjs/packages/blob/master/packages/w/waline.json>

---
### Feature Overview | Describe the feature

Now waline only includes js and css files in cdnjs, but in fact it is the mjs file that needs to be used. I hope it can be added.

Now the speed of unpkg in China is very average. With the mjs file in cdnjs, some domestic CDNs can use it.

ref: <https://github.com/cdnjs/packages/blob/master/packages/w/waline.json>

**Comment by Mister-Hope** [comment]
我们本身有发布esm文件，也许你的意思是这个cd的配置文件需要更新？

**Comment by Mister-Hope** [comment]
我们本身有发布esm文件，也许你的意思是这个cd的配置文件需要更新？

**Comment by yy4382** [comment]
> 我们本身有发布esm文件，也许你的意思是这个cd的配置文件需要更新？
> 
> We have published esm files ourselves. Maybe you mean that the cd configuration file needs to be updated?

是这样，国内大多数cdn站从cdnjs这个站获取内容，然后 cdnjs 目前只包括了waline client的js和css文件，导致国内访问比较快的镜像cdn也都只有js和css文件，而没有mjs文件。

jsdeliver和unpkg好像是直接从npm拿的数据？这方面我也不是很了解。

**Comment by Mister-Hope** [comment]
v3 will be stable very soon, and it's not affected.

If you are interested in, you can send a PR to that repo adding `.mjs` extension.
