### ISSUE TITLE
[Bug]: client-side error in next.js

### ISSUE THREAD

**Issue by BigCoke233** [walinejs/waline#2243]
### 问题描述 | Describe the bug

In Next.js 14 App Router, when using Waline as a React component according to the document (I copied and pasted the exact same code from the document), it works fine in development environment and succeeded in deployment. However, the error occured when trying to visit the page containing Waline comment.

It seems to be a problem with Vue and I have no knowledge of Vue.js, so I just can't figure out why this happens.

![image](https://github.com/walinejs/waline/assets/45323514/b23020fe-5f9e-49e7-a510-4809a6426fce)

### 问题网站 | Website URL

I can't leave this issue in production environment, therefore there's no available website reproducing this problem,

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by BigCoke233** [comment]
I also tried importing waline like this:

```javascript
import { init } from '@waline/client';

import '@waline/client/style';

init({
  el: '#waline',
  // ...
});
```

But the same error persists.

**Comment by Mister-Hope** [comment]
Are you sure you care using Vue3.4.5?

**Comment by Mister-Hope** [comment]
This is obviously not a bug here, for workaround, define the variable to `false`

See https://github.com/walinejs/waline/issues/2230#issuecomment-1879763400 and  https://github.com/walinejs/waline/issues/2230#issuecomment-1879924886
