### ISSUE TITLE
[Feature]: 切换 CDN 加载路径 || [Feature]: Switch CDN Load path

### ISSUE THREAD

**Issue by FreshP0325** [walinejs/waline#2249]
### 功能概述 | Describe the feature

在引用 `waline.js` 和 `waline.css` 时，由于 UNPKG 和 JsDelivr 在中国国内大多被阻断或加载速度慢，有时会选择使用私人维护的镜像服务以加速。但是，在 `waline.js` 文件中引用的 emojis 表情却是 UNPKG 上的资源，譬如：

```javascript
["//unpkg.com/@waline/emojis@1.1.0/weibo"],Vr="en-US",yo=["//unpkg.com/@waline/emojis/tieba/tieba_agree.png","//unpkg.com/@waline/emojis/tieba/tieba_look_down.png","//unpkg.com/@waline/emojis/tieba/tieba_sunglasses.png","//unpkg.com/@waline/emojis/tieba/tieba_pick_nose.png","//unpkg.com/@waline/emojis/tieba/tieba_awkward.png","//unpkg.com/@waline/emojis/tieba/tieba_sleep.png"]
```

绝对路径的引用方式导致 emojis 无法从镜像服务加载，而强制从 UNPKG 加载。

是否可以修改绝对路径 `//unpkg.com/@waline/emojis@version/` 为 `../../../emojis@version/`？

---

When loading `waline.js` and `waline.css` since UNPKG and JsDelivr are mostly blocked or slow to load in China, it is sometimes supposed to use a privately maintained mirror service to speed up. However, the emojis used in the `waline.js` file are still resources on UNPKG, such as:

```javascript
["//unpkg.com/@waline/emojis@1.1.0/weibo"],Vr="en-US",yo=["//unpkg.com/@waline/emojis/tieba/tieba_agree.png","//unpkg.com/@waline/emojis/tieba/tieba_look_down.png","//unpkg.com/@waline/emojis/tieba/tieba_sunglasses.png","//unpkg.com/@waline/emojis/tieba/tieba_pick_nose.png","//unpkg.com/@waline/emojis/tieba/tieba_awkward.png","//unpkg.com/@waline/emojis/tieba/tieba_sleep.png"]
```

The absolute path is referenced in such a way that emojis cannot be correctly loaded from the mirror service, forcing it to be loaded from UNPKG.

May we change the absolute path `//unpkg.com/@waline/emojis@version/` to `../../../emojis@version/`?

---
### Feature Overview | Describe the feature

When referencing `waline.js` and `waline.css`, since UNPKG and JsDelivr are mostly blocked or slow to load in China, privately maintained mirror services are sometimes chosen to speed up the process. However, the emojis referenced in the `waline.js` file are resources on UNPKG, for example:

```javascript
["//unpkg.com/@waline/emojis@1.1.0/weibo"],Vr="en-US",yo=["//unpkg.com/@waline/emojis/tieba/tieba_agree.png" ,"//unpkg.com/@waline/emojis/tieba/tieba_look_down.png","//unpkg.com/@waline/emojis/tieba/tieba_sunglasses.png","//unpkg.com/@waline/emojis /tieba/tieba_pick_nose.png","//unpkg.com/@waline/emojis/tieba/tieba_awkward.png","//unpkg.com/@waline/emojis/tieba/tieba_sleep.png"]
```

The absolute path reference method causes emojis to fail to be loaded from the mirror service, and is forced to be loaded from UNPKG.

Is it possible to modify the absolute path `//unpkg.com/@waline/emojis@version/` to `../../../emojis@version/`?

---

When loading `waline.js` and `waline.css` since UNPKG and JsDelivr are mostly blocked or slow to load in China, it is sometimes supposed to use a privately maintained mirror service to speed up. However, the emojis used in the ` waline.js` file are still resources on UNPKG, such as:

```javascript
["//unpkg.com/@waline/emojis@1.1.0/weibo"],Vr="en-US",yo=["//unpkg.com/@waline/emojis/tieba/tieba_agree.png" ,"//unpkg.com/@waline/emojis/tieba/tieba_look_down.png","//unpkg.com/@waline/emojis/tieba/tieba_sunglasses.png","//unpkg.com/@waline/emojis /tieba/tieba_pick_nose.png","//unpkg.com/@waline/emojis/tieba/tieba_awkward.png","//unpkg.com/@waline/emojis/tieba/tieba_sleep.png"]
```

The absolute path is referenced in such a way that emojis cannot be correctly loaded from the mirror service, forcing it to be loaded from UNPKG.

May we change the absolute path `//unpkg.com/@waline/emojis@version/` to `../../../emojis@version/`?

**Comment by lizheming** [comment]
https://waline.js.org/guide/features/emoji.html
