### ISSUE TITLE
[Feature]: Integrating Waline Comment System with Strapi Account Authentication

### ISSUE THREAD

**Issue by rockbenben** [walinejs/waline#2261]
### 功能概述 | Describe the feature

I am using Strapi v4.17.0 as my content management system and looking to integrate Waline as the commenting system in my project. 

I am curious about the possibility of integrating the Waline comment system with user accounts managed by Strapi. My aim is to allow users to post and manage comments using their accounts registered on Strapi.

**Comment by lizheming** [comment]
https://waline.js.org/cookbook/customize/userdb.html
