### ISSUE TITLE
[Bug]: 间歇性访问速度极其缓慢，建议更换cdn || [Bug]: Intermittent access speed is extremely slow, it is recommended to replace the cdn

### ISSUE THREAD

**Issue by FidStyle** [walinejs/waline#2279]
### 2024.1.22
unpkg cdn间歇性访问速度极慢
![image](https://github.com/walinejs/waline/assets/115857087/a29d99fd-b2f5-47eb-a71b-3a0992ccdfba)

webche的访问速度一直可以
![image](https://github.com/walinejs/waline/assets/115857087/6b746d0e-b622-46e6-b086-4e6f717de23b)

### 之前的记录: [2024.1.17](https://github.com/theme-shoka-x/hexo-theme-shokaX/pull/197#issuecomment-1894966335)

建议更改：
```bash
-  '//unpkg.com/@waline/emojis/tieba/tieba_agree.png',
+ '//npm.webcache.cn/@waline/emojis@1.2.0/tieba/tieba_agree.png',
-  cssUrl: https://unpkg.com/@waline/client@v3/dist/waline.css
+ cssUrl: https://npm.webcache.cn/@waline/client@v3/dist/waline.css
-  libUrl: config.waline.libUrl | default('//unpkg.com/@waline/client@v2/dist/waline.js', true),
+ libUrl: config.waline.libUrl | default('//npm.webcache.cn/@waline/client@v2/dist/waline.js', true),
- <link href='//unpkg.com/@waline/client@v3/dist/waline.css' rel='stylesheet' />
+ <link href='//npm.webcache.cn/@waline/client@v3/dist/waline.css' rel='stylesheet' />
- import { init } from 'https://unpkg.com/@waline/client@v3/dist/waline.js';
+ import { init } from 'https://npm.webcache.cn/@waline/client@v3/dist/waline.js';
- process.env.WALINE_ADMIN_MODULE_ASSET_URL || '//unpkg.com/@waline/admin'
+ process.env.WALINE_ADMIN_MODULE_ASSET_URL || '//npm.webcache.cn/@waline/admin'
```
其中大部分可直接用 npm.webcache.cn 替换 unpkg.com。经测试，部分表情需要使用 jsd.cdn.zzko.cn/npm 反代 jsdelivr，
```bash
- * @default ['//unpkg.com/@waline/emojis@1.1.0/weibo']
+ * @default ['//jsd.cdn.zzko.cn/npm/@waline/emojis@1.1.0/weibo']
```
但是zzko的cdn有限制：参见[公告](https://jsd.cdn.zzko.cn/forum-post/67.html)

我要是想自己改cdn要怎么部署呢（）
希望提供一个好的途径，或者官方源给解决方案直接改了是最好的 : )

### 问题网站 | Website URL

waline.joytion.cn

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### 2024.1.22
unpkg cdn intermittent access extremely slow
![image](https://github.com/walinejs/waline/assets/115857087/a29d99fd-b2f5-47eb-a71b-3a0992ccdfba)

The access speed of webche has always been good
![image](https://github.com/walinejs/waline/assets/115857087/6b746d0e-b622-46e6-b086-4e6f717de23b)

### Previous record: [2024.1.17](https://github.com/theme-shoka-x/hexo-theme-shokaX/pull/197#issuecomment-1894966335)

Suggested changes:
```bash
- '//unpkg.com/@waline/emojis/tieba/tieba_agree.png',
+ '//npm.webcache.cn/@waline/emojis@1.2.0/tieba/tieba_agree.png',
- cssUrl: https://unpkg.com/@waline/client@v3/dist/waline.css
+ cssUrl: https://npm.webcache.cn/@waline/client@v3/dist/waline.css
- libUrl: config.waline.libUrl | default('//unpkg.com/@waline/client@v2/dist/waline.js', true),
+ libUrl: config.waline.libUrl | default('//npm.webcache.cn/@waline/client@v2/dist/waline.js', true),
- <link href='//unpkg.com/@waline/client@v3/dist/waline.css' rel='stylesheet' />
+ <link href='//npm.webcache.cn/@waline/client@v3/dist/waline.css' rel='stylesheet' />
- import { init } from 'https://unpkg.com/@waline/client@v3/dist/waline.js';
+ import { init } from 'https://npm.webcache.cn/@waline/client@v3/dist/waline.js';
- process.env.WALINE_ADMIN_MODULE_ASSET_URL || '//unpkg.com/@waline/admin'
+ process.env.WALINE_ADMIN_MODULE_ASSET_URL || '//npm.webcache.cn/@waline/admin'
```
Most of them can be directly replaced by npm.webcache.cn unpkg.com. After testing, some expressions need to use jsd.cdn.zzko.cn/npm to reverse jsdelivr.
```bash
- * @default ['//unpkg.com/@waline/emojis@1.1.0/weibo']
+ * @default ['//jsd.cdn.zzko.cn/npm/@waline/emojis@1.1.0/weibo']
```
However, zzko’s CDN has limitations: see [Announcement](https://jsd.cdn.zzko.cn/forum-post/67.html)

If I want to change the cdn myself, how should I deploy it? ()
I hope to provide a good way, or it would be best if the official source directly changes the solution :)

### Question Website | Website URL

waline.joytion.cn

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by FidStyle** [comment]
@lizheming

**Comment by lizheming** [comment]
@waline/client 怎么引入，取决于网站自己。你如果不清楚怎么修改，可以去你的主题 GitHub 提个 issue。你贴的+和-的代码，都不是 Waline 的。

**Comment by FidStyle** [comment]
> @waline/client 怎么引入，取决于网站自己。你如果不清楚怎么修改，可以去你的主题 GitHub 提个 issue。你贴的+和-的代码，都不是 Waline 的。
> 
> How to introduce @waline/client depends on the website itself. If you don’t know how to modify it, you can raise an issue on your theme GitHub. The + and - codes you posted are not from Waline.

没有啊，我通过vercel部署没有提供cdn的参数。以上的+和-是@waline/vercel 里找到的，本仓库的/packages/server下都能找到对应的代码，难道是上游的问题？
waline.joytion.cn（vercel部署）会加载`unpkg.com/@waline/client@v3/dist/waline.css`和`unpkg.com/@waline/client@v2/dist/waline.js`，我想更改如何更改。此网站与主题无关

**Comment by FidStyle** [comment]
> > @waline/client 怎么引入，取决于网站自己。你如果不清楚怎么修改，可以去你的主题 GitHub 提个 issue。你贴的+和-的代码，都不是 Waline 的。
> > How to introduce @waline/client depends on the website itself. If you don’t know how to modify it, you can raise an issue on your theme GitHub. The + and - codes you posted are not from Waline.
> 
> 没有啊，我通过vercel部署没有提供cdn的参数。以上的+和-是@waline/vercel 里找到的，本仓库的/packages/server下都能找到对应的代码，难道是上游的问题？ waline.joytion.cn（vercel部署）会加载`unpkg.com/@waline/client@v3/dist/waline.css`和`unpkg.com/@waline/client@v2/dist/waline.js`，我想更改如何更改。此网站与主题无关

因为@waline/vercel使用了unpkg的cdn，我想更改而已。waline本身可能没问题。

**Comment by lizheming** [comment]
Waline 提供的默认页面只是一个用于测试的页面，并不会提供给用户使用，可以忽略。如果有强迫症，可以通过 Vercel 的 rewrites 功能，将 `/` 路由映射到自己的 HTML 文件来自定义处理。

**Comment by FidStyle** [comment]
了解，感谢！
