### ISSUE TITLE
[Bug]: Importing in HTML (Client) Cannot find package @waline/client@v3

### ISSUE THREAD

**Issue by updowncity** [walinejs/waline#2282]
### 问题描述 | Describe the bug

引入HTML時 https://unpkg.com/@waline/client@v3/dist/waline.js 和 https://unpkg.com/@waline/client@v3/dist/waline.css 都無法打開，顯示 `Cannot find package @waline/client@v3`
(但是把v3換成v2就一切正常）

### 问题网站 | Website URL

https://unpkg.com/@waline/client@v3/dist/waline.js

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

When introducing HTML, both https://unpkg.com/@waline/client@v3/dist/waline.js and https://unpkg.com/@waline/client@v3/dist/waline.css cannot be opened, displaying ` Cannot find package @waline/client@v3`
(But if v3 is replaced by v2, everything will be normal)

### Question Website | Website URL

https://unpkg.com/@waline/client@v3/dist/waline.js

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by Mister-Hope** [comment]
For alpha versions they are not accessible via major tag (e.g.: `v3`)

For now it's recommend to use links like `https://unpkg.com/@waline/client@3.0.0-alpha.10/dist/waline.js`.
