### ISSUE TITLE
[Bug]: 登录(可选)按钮在iPhone12-微信上显示异常 || [Bug]: The login (optional) button displays abnormally on iPhone12-WeChat

### ISSUE THREAD

**Issue by witqu** [walinejs/waline#2283]
### 问题描述 | Describe the bug

登录(可选)按钮在iPhone12-微信上显示异常，同样的设备谷歌浏览器、Safari、QQ浏览器、QQ等都支持，图1为微信，图二为谷歌浏览器
![d3d9d49cfcb50ba5829ada40f8870c7](https://github.com/walinejs/waline/assets/7465879/4bf9de48-c45a-4ca6-9637-309ef9547802)
![c356654134a2fad1b02ee9d623bdd7f](https://github.com/walinejs/waline/assets/7465879/e29b184b-0841-4547-b690-6b721a857f6e)

### 问题网站 | Website URL

https://hllfy.shop

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

The login (optional) button displays abnormally on iPhone 12-WeChat. The same device is supported by Google Chrome, Safari, QQ Browser, QQ, etc. Figure 1 shows WeChat and Figure 2 shows Google Chrome.
![d3d9d49cfcb50ba5829ada40f8870c7](https://github.com/walinejs/waline/assets/7465879/4bf9de48-c45a-4ca6-9637-309ef9547802)
![c356654134a2fad1b02ee9d623bdd7f](https://github.com/walinejs/waline/assets/7465879/e29b184b-0841-4547-b690-6b721a857f6e)

### Question Website | Website URL

https://hllfy.shop

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by Mister-Hope** [comment]
I don't think this is something we should fix or handle.
