### ISSUE TITLE
[Feature]: 能主动@人员吗，弹出一个用户列表 || [Feature]: Can you take the initiative to @ people, and a user list will pop up?

### ISSUE THREAD

**Issue by sunnysteam** [walinejs/waline#2284]
### 功能概述 | Describe the feature

能主动@人员吗，弹出一个用户列表

---
### Feature Overview | Describe the feature

Can you take the initiative to @ people, and a user list will pop up

**Comment by lizheming** [comment]
单纯只是这个能力是比较好实现的，但是整体交互考虑下来会比较复杂。

1. 用户列表候选的用户是哪些人，是注册用户，还是当前文章的用户列表，还是所有的用户。不同的范围复杂度不太一样。
2. 增加了这个能力的目的是什么，是需要 @ 之后做通知提醒么。通知提醒又可以分站内和邮件提醒，站内提醒的话暂时还没有这个能力，邮件提醒的话需要考虑最大提醒量等问题规避恶意 @。

可以多沟通沟通大家一块明确需求细节再慢慢落地。

**Comment by sunnysteam** [comment]
想要做一个协同的功能，用户不会太多，然后可以主动@人员来通知该人员来回复，而不是只能回复其他人的消息。我明白如果是用户很多的情况下，这个功能可能没必要，但如果只是一小部分用户使用的情况，还是有这个需求的

**Comment by FrederickBun** [comment]
不好管理，因为不是所有的用户都注册了，而且你要通过什么方式辨别用户，是用户名，还是邮箱？
