### ISSUE TITLE
[Feature]: 提供开关设置评论URL过期时间-SEO || [Feature]: Provides a switch to set the comment URL expiration time-SEO

### ISSUE THREAD

**Issue by Doradx** [walinejs/waline#2285]
### 功能概述 | Describe the feature

# 原因
评论区会被搜索引擎检索，且很多个人站长因为弃坑、卖站跑路等各类原因，可能域名被用作非法用途，链接到此类网站可能存在一定风险。
而人工排除各类链接又过于困难。

# 方案
故添加可选配置项，设置评论者URL过期时间`urlVaildTime (default: 0)`，
- 当访客采用API加载评论列表时，若评论的`createdAt+urlVaildTime<time.now()`，API不返回该条评论者URL信息
- 当登录用户或者管理员采用API加载评论列表时，直接返回全部信息

# 效果
该方案可避免搜索引擎或其它爬虫抓取到评论区古早的评论者URL，减少一些不必要的麻烦。
该特性可作为可选项，默认不开启

---
### Feature Overview | Describe the feature

# reason
The comment area will be retrieved by search engines, and many individual webmasters may have their domain names used for illegal purposes due to various reasons such as abandonment, selling and running away. Linking to such websites may involve certain risks.
It is too difficult to manually exclude various types of links.

# plan
Therefore, an optional configuration item is added to set the commenter URL expiration time `urlVaildTime (default: 0)`.
- When a visitor uses the API to load the comment list, if the comment's `createdAt+urlVaildTime<time.now()`, the API will not return the commenter URL information.
- When the logged-in user or administrator uses the API to load the comment list, all information will be returned directly

# Effect
This solution can prevent search engines or other crawlers from crawling old commenter URLs in the comment area, reducing unnecessary trouble.
This feature is optional and is not enabled by default

**Comment by lizheming** [comment]
有实际的案例吗？没有太明白你的诉求。评论为什么会被搜索引擎检索呀？我们的评论都是动态加载的，应该不会？以及后面的风险描述我也没有看太懂。

**Comment by Doradx** [comment]
# 回复
1. 是会被搜索引擎收录的，形成了外链的效果。例如在google检索`site:4311346.com Dorad`可以看到我在该网站的留言记录。
2. 如果是评论者留的域名用作黄赌毒类的用途，成为不良外链。这一会误导用户，二会招来网警。

# 案例
- http://www.casx.gov.cn/content/2022-04/11/content_12730851.htm
- https://www.cifnews.com/article/133786
- https://zhuanlan.zhihu.com/p/575139990

**Comment by lizheming** [comment]
我们的链接默认都是增加了 nofollow noreferer 处理的，搜索引擎基本不会收到影响。

针对你反馈的这个问题，相比较于增加一个过期时间这种较临时的处理方法，业界更通用的做法，是增加一个跳转中间页，用来提示用户后续链路与原网站无关。

而这个中间页是可以通过 Waline 的插件来实现的，我临时写了一个，感兴趣的话可以试试 https://github.com/walinejs/plugins/blob/master/packages/link-interceptor/README_CN.md
