### ISSUE TITLE
[Bug]: https的页面 请求走的却是http || [Bug]: The request for https page goes through http.

### ISSUE THREAD

**Issue by Cnzw** [walinejs/waline#2286]
### 问题描述 | Describe the bug

用https访问waline登录页面，但是登录请求走的是http的
http没备案给拦截了，只能看着登录页面干瞪眼
![image](https://github.com/walinejs/waline/assets/20514522/033618e8-8a56-46cf-833e-e1715c2320f3)

### 问题网站 | Website URL

https://cnzw.github.io/p/16107.html

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

SQLite

---
### Problem description | Describe the bug

Use https to access the waline login page, but the login request goes through http.
http has not been registered and has been blocked. I can only stare at the login page.
![image](https://github.com/walinejs/waline/assets/20514522/033618e8-8a56-46cf-833e-e1715c2320f3)

### Question Website | Website URL

https://cnzw.github.io/p/16107.html

### Where is the service deployed? | Where your waline deploy?

Docker

### Where is the data stored? | Where your comment data store?

SQLite

**Comment by lizheming** [comment]
https://github.com/orgs/walinejs/discussions/2017
