### ISSUE TITLE
[Bug]: TiDB注册帐号403，但是可以正常使用第三方登陆 || [Bug]: TiDB registered account 403, but third-party login can be used normally

### ISSUE THREAD

**Issue by higoozu** [walinejs/waline#2291]
### 问题描述 | Describe the bug

按照文档正常配置环境变量，功能正常，可以正常评论和显示。
但是，注册帐号会出现403: Forbidden错误，不过可以通过第三方比如GitHub、qq登陆。
我尝试通过第三方登陆后修改密码，使用账号密码登陆提示账号密码错误。
我在TiDB直接写入新的用户数据，登陆也提示账号密码错误。但是使用第三方帐号登录到后台后，能看到添加的用户。
已经添加了安全域名，应该不是安全域名的问题。

### 问题网站 | Website URL

https://blognewcomment.vercel.app/ui/register

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

TiDB

---
### Problem description | Describe the bug

The environment variables are configured normally according to the documentation, the functions are normal, and comments and displays can be made normally.
However, a 403: Forbidden error will appear when registering an account, but you can log in through third parties such as GitHub and qq.
I tried to change my password after logging in through a third party, but when I logged in using my account and password, I was prompted that the account and password were incorrect.
I directly wrote new user data in TiDB, and when logging in, it also prompted an error message about the wrong account and password. However, after logging in to the backend using a third-party account, you can see the added users.
A secure domain name has been added, so it should not be a problem with the secure domain name.

### Question Website | Website URL

https://blognewcomment.vercel.app/ui/register

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

TiDB

**Comment by lizheming** [comment]
是不是设置了 SECURE_DOMAIN 变量

**Comment by higoozu** [comment]
> 是不是设置了 SECURE_DOMAIN 变量

没有，不论是我设置还是删掉这个变量，问题依旧

**Comment by lizheming** [comment]
删除变量后需要重新部署才能生效，确认下是否有重新部署

**Comment by higoozu** [comment]
> 删除变量后需要重新部署才能生效，确认下是否有重新部署
> 
> After deleting the variable, it needs to be redeployed to take effect. Check whether there is redeployment

我检查了下确实已经删除并重新部署了，之前我尝试重新从头部署这个项目，没有安全域名情况下，用leancloud可以正常登陆，但是tidb不行，我重新检查tidb配置，没有问题，而且评论功能也正常，不清楚哪里出了问题

**Comment by lizheming** [comment]
那去 Vercel 后台看下服务端返回的日志吧

**Comment by higoozu** [comment]
> 那去 Vercel 后台看下服务端返回的日志吧
> 
> Then go to the Vercel backend and look at the logs returned by the server

我看了日志找到问题了，我配置了TURNSTILE_SECRET，因为这个问题导致403。我删除这个变量后就可以了。不过登录界面是没有验证码弹出的。

Forbidden
    at Object.throw (/var/task/node_modules/koa/lib/context.js:97:11)
    at module.exports.useRecaptchaOrTurnstileCheck (/var/task/node_modules/@waline/vercel/src/logic/base.js:163:28)
    at module.exports.useCaptchaCheck (/var/task/node_modules/@waline/vercel/src/logic/base.js:139:19)
    at module.exports.postAction (/var/task/node_modules/@waline/vercel/src/logic/user.js:87:17)
    at /var/task/node_modules/think-logic/index.js:51:37
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by lizheming** [comment]
服务端需要配置 TURNSTILE_KEY 后台才会有验证码出现

**Comment by higoozu** [comment]
我重新看了下文档，确实是我看漏了，抱歉
