### ISSUE TITLE
[Bug]: emoji的wl-tabs标签手机端会超出页面宽度，导致网页其他部分错位 || [Bug]: The mobile version of emoji's wl-tabs will exceed the page width, causing other parts of the webpage to be misaligned.

### ISSUE THREAD

**Issue by FidStyle** [walinejs/waline#2295]
## 应该考虑到手机端的自适应问题

![image](https://github.com/walinejs/waline/assets/115857087/a6db1b2b-abbc-4bc1-a34a-fe9591f60a03)

![image](https://github.com/walinejs/waline/assets/115857087/8dcda17d-e6ed-4124-9b4c-52d0864d01db)

### 问题网站 | Website URL

https://shokax.joytion.cn/2024/01/26/test/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
## Should take into account the adaptability issue on the mobile phone

![image](https://github.com/walinejs/waline/assets/115857087/a6db1b2b-abbc-4bc1-a34a-fe9591f60a03)

![image](https://github.com/walinejs/waline/assets/115857087/8dcda17d-e6ed-4124-9b4c-52d0864d01db)

### Question Website | Website URL

https://shokax.joytion.cn/2024/01/26/test/

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by FidStyle** [comment]
@lizheming

**Comment by FidStyle** [comment]
#2296

**Comment by Mister-Hope** [comment]
我当初的设计预想应该是在手机上上面的是你那样做，然后下面是出一个横向的滚动条，类似手机qq的多表情选择。

很久很久之前的版本应该是工作的，我最开始写他的时候，肯定是在移动端上测了的，你看一下什么原因导致他现在溢出。

你去掉的那个css本意上是为了让它出横向的滚动条，而不是像你这样换行。

**Comment by FidStyle** [comment]
![image](https://github.com/walinejs/waline/assets/115857087/28b62f98-be8a-46d1-872f-190bc669a98a)
![image](https://github.com/walinejs/waline/assets/115857087/6d031495-a230-45ce-be45-3db900a305bf)

wl-emoji-popup 这项增加 width:100% 即可解决，无其他影响

#2297

**Comment by FidStyle** [comment]
@Mister-Hope
