### ISSUE TITLE
[Bug]: 时差8小时问题；邮件发送问题 || [Bug]: 8-hour time difference problem; email sending problem

### ISSUE THREAD

**Issue by kdyzm** [walinejs/waline#2302]
### 1. 时差八小时
![image](https://github.com/walinejs/waline/assets/12097910/d7153178-1698-4d92-966b-d9685bfc16aa)
可以看到插入时间和当前日志的打印时间差了八小时，可以看到日志打印时间是正常的，但是插入时间一插入就8小时前
复现地址：https://blog.kdyzm.cn/messageBoard

### 2. 邮件发送

我用docker-compose部署的服务端，配置了环境变量：SENDER_NAME: '一枝梅的博客系统通知' ，但是并没有生效，显示的还是发件人的邮件地址
![image](https://github.com/walinejs/waline/assets/12097910/84c6096e-a1fc-4e14-bbc5-6735483d53a3)

### 问题网站 | Website URL

https://blog.kdyzm.cn/messageBoard

### 服务部署在哪里？ | Where your waline deploy?

Self Host

### 数据存储在哪里？| Where your comment data store?

MySQL

---
### 1. Time difference is eight hours
![image](https://github.com/walinejs/waline/assets/12097910/d7153178-1698-4d92-966b-d9685bfc16aa)
You can see that there is a difference of eight hours between the insertion time and the current log printing time. You can see that the log printing time is normal, but the insertion time is 8 hours ago as soon as it is inserted.
Recurrence address: https://blog.kdyzm.cn/messageBoard

### 2. Send email

I used docker-compose to deploy the server and configured the environment variable: SENDER_NAME: 'Iljimae's blog system notification', but it did not take effect. The sender's email address was still displayed.
![image](https://github.com/walinejs/waline/assets/12097910/84c6096e-a1fc-4e14-bbc5-6735483d53a3)

### Question Website | Website URL

https://blog.kdyzm.cn/messageBoard

### Where is the service deployed? | Where your waline deploy?

Self Host

### Where is the data stored? | Where your comment data store?

MySQL

**Comment by lizheming** [comment]
1. 8 小时问题搜下历史 issue，需要设置下 MySQL 的时区
2. SENDER_NAME 需要看各个邮箱的显示情况，不是所有的都会展示

**Comment by kdyzm** [comment]
> 1. 8 小时问题搜下历史 issue，需要设置下 MySQL 的时区
> 2. SENDER_NAME 需要看各个邮箱的显示情况，不是所有的都会展示
> 
> 1. Search historical issues for the 8-hour issue. You need to set the time zone of MySQL.
> 2. SENDER_NAME needs to check the display status of each mailbox, not all of them will display

我用的qq邮箱，那博客园、京东、淘宝啥的发过来的邮件显示的都是正常的。。。
