### ISSUE TITLE
无法管理评论 || Unable to manage comments

### ISSUE THREAD

**Issue by cmyf122** [walinejs/waline#2309]
### 问题描述 | Describe the bug

添加评论，注册账号以后，自动跳转到个人资料页面了，评论管理页面一闪而过
![8888](https://github.com/walinejs/waline/assets/90293910/1c23891e-4c61-4981-af68-d3859e6a92f3)

### 问题网站 | Website URL

https://cmyf122.github.io/2024/02/06/%E5%BD%92%E5%9B%AD%E7%94%B0%E5%B1%85/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

After adding comments and registering an account, you will automatically jump to the personal profile page, and the comment management page will flash by.
![8888](https://github.com/walinejs/waline/assets/90293910/1c23891e-4c61-4981-af68-d3859e6a92f3)

### Question Website | Website URL

https://cmyf122.github.io/2024/02/06/%E5%BD%92%E5%9B%AD%E7%94%B0%E5%B1%85/

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
第一个注册的用户是管理员，才有权限管理评论，之后注册的用户都是普通用户，无法管理评论。如果需要修改用户的角色，可以进数据库修改下。
