### ISSUE TITLE
[Bug]: vercel:The engine "node" is incompatible with this module. Expected version ">=18". Got "16.20.2"

### ISSUE THREAD

**Issue by JiangJiYue** [walinejs/waline#2312]
### 问题描述 | Describe the bug

<html>
<body>

error @waline/vercel@1.31.8: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.20.2"
07:49:33.831 | error Found incompatible module.
07:49:33.832 | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
07:49:33.860 | Error: Command "yarn install" exited with 1
07:49:37.335

<br class="Apple-interchange-newline">
</body>
</html>

### 问题网站 | Website URL

https://vercel.com/new/clone/hidden?repository-url=https%3A%2F%2Fgithub.com%2Fwalinejs%2Fwaline%2Ftree%2Fmain%2Fexample&deploymentIds=dpl_HDgHy6kxTMFMjXj1rBL5RN4BcL2X

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by YSC-hain** [comment]
我也遇到了这个问题，似乎可以通过修改项目下的 vercel.json 文件来解决？
### 解决步骤
1. 打开你的 GitHub 中 clone 的 waline
2. 删除红线区域原本存在的版本号 
![image](https://github.com/walinejs/waline/assets/58895782/963c99b0-dee8-4498-8f92-1a5ca2d821f0)
  
**注意：我不确定该方法会不会导致其他兼容性问题**

**Comment by lizheming** [comment]
先回退 @waline/vercel 到 1.31.7 的版本，可以正常工作

**Comment by ilovefreesw** [comment]
After changing the Node version to 20.x in the Vercel the error changes to:

```
[11:31:36.915] > Installing Builder: @vercel/node@2.5.10
[11:31:42.105] Installing dependencies...
[11:31:42.120] Yarn requires Node.js 4.0 or higher to be installed.
[11:31:42.124] Error: Command "yarn install" exited with 1
```

**Comment by yzl3014** [comment]
Someone has encountered the same problem, but there is no solution:
https://github.com/orgs/vercel/discussions/5755

**Comment by willow-god** [comment]
我尝试将vercel.json内的node版本修改为：
`"builds": [
    {
      "src": "index.js",
      "use": "@vercel/node@3.0.17"
    }
  ],`
更新成功了，但是后端的测试页面是空的，但是管理页面又可以正常打开，上方更新横幅也消失了，博客内的评论也是正常的，不知道是怎么回事

**Comment by conge** [comment]
我模仿着，将 vercel.json内的node版本修改为： `"builds": [ { "src": "index.js", "use": "@vercel/node@3.0.10" } ],` deploy 成功。

在博客上可以显示评论，发评论。

同样出现后端测试页面空白： https://waline.livingwithfcs.org/

> 我尝试将vercel.json内的node版本修改为： `"builds": [ { "src": "index.js", "use": "@vercel/node@3.0.17" } ],` 更新成功了，但是后端的测试页面是空的，但是管理页面又可以正常打开，上方更新横幅也消失了，博客内的评论也是正常的，不知道是怎么回事
>
