### ISSUE TITLE
[Bug]: Vercell部署报错 || [Bug]: Vercell deployment error

### ISSUE THREAD

**Issue by xlenco** [walinejs/waline#2313]
### 问题描述 | Describe the bug

![PixPin_2024-02-07_16-22-33](https://github.com/walinejs/waline/assets/75837117/15c366e1-fb0b-4c01-a6dd-812f5d6f5abb)
升级node版本可以解决第一个报错，但无法解决第二个

### 问题网站 | Website URL

https://waline.js.org/guide/deploy/vercel.html

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

![PixPin_2024-02-07_16-22-33](https://github.com/walinejs/waline/assets/75837117/15c366e1-fb0b-4c01-a6dd-812f5d6f5abb)
Upgrading the node version can solve the first error, but cannot solve the second one.

### Question Website | Website URL

https://waline.js.org/guide/deploy/vercel.html

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
重新试试

**Comment by lizheming** [comment]
重新按照教程 fork 仓库部署吧

**Comment by LeafYeeXYZ** [comment]
在 `vercel.json` 里，把 `build` 中的对应项修改为 `@vercel/node@latest` 可解决，但是会有新bug，直接访问域名时的 `Waline Example` 通过 `unpkg` 获取的 `waline.css` 和 `waline.js` 报 `Failed to load resource: the server responded with a status of 404 ()` 错误

**Comment by willow-god** [comment]
> 在 `vercel.json` 里，把 `build` 中的对应项修改为 `@vercel/node@latest` 可解决
> 
> 但是会有新bug，直接访问域名时的 `Waline Example` 页面无内容：通过 `unpkg` 获取的 `waline.css` 和 `waline.js` 报 `Failed to load resource: the server responded with a status of 404 ()`

请问这个您解决了吗？我遇见了相同的问题

**Comment by xlenco** [comment]
> > 在 `vercel.json` 里，把 `build` 中的对应项修改为 `@vercel/node@latest` 可解决
> > 但是会有新bug，直接访问域名时的 `Waline Example` 页面无内容：通过 `unpkg` 获取的 `waline.css` 和 `waline.js` 报 `Failed to load resource: the server responded with a status of 404 ()`
> 
> 请问这个您解决了吗？我遇见了相同的问题

从新按教程部署
