### ISSUE TITLE
[Bug]: 3.0 版本后使用 npm 安装失败，提示 Unsupported URL Type "workspace:": workspace:1.0.0-alpha.5

### ISSUE THREAD

**Issue by yy4382** [walinejs/waline#2328]
### 问题描述 | Describe the bug

尝试在一个vue项目中引入waline时
```
$ npm i @waline/client             
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:1.0.0-alpha.5
```

如果使用yarn，会让我选择：
```
? Please choose a version of "@waline/api" from this list: (Use arrow keys)
❯ 1.0.0-alpha.5 
  1.0.0-alpha.4 
  1.0.0-alpha.3 
  1.0.0-alpha.2 
  1.0.0-alpha.1 
  1.0.0-alpha.0 
```

好像是新的 @waline/api 引入的问题？

在本机、docker容器中和GitHub Actions中尝试安装，都失败了，应该不是我环境的问题。

### 问题网站 | Website URL

null

### 服务部署在哪里？ | Where your waline deploy?

Self Host

### 数据存储在哪里？| Where your comment data store?

PostgreSQL

**Comment by lizheming** [comment]
@Mister-Hope 是不是这些依赖应该都放在 devDep 里面？https://github.com/walinejs/waline/blob/main/packages/client/package.json#L84-L92

**Comment by Mister-Hope** [comment]
Nope,.the slim bundle is the default entry on node, so perhaps your workflow are still problematic.

**Comment by lizheming** [comment]
@Mister-Hope 有两种解决办法，一种是将 `@waline/api` 打包进去，这样能保持 `@waline/api` 是跟随仓库最新的；还有一种方案是构建前修改 `package.json` 将其指向到 npm 最新的版本号上。你选一个我再改吧。

**Comment by Mister-Hope** [comment]
原则上使用workspace:* 对于pnpm是没问题的。

**Comment by lizheming** [comment]
@Mister-Hope CI和发布都没有问题，现在是package.json中依赖写的还是workspace，所以导致了在其他项目里安装出错了。这种monorepo项目的依赖内部引用一般对外的产物都是bundle后文件，所以我才提了第一个问题是否是放在devDep的。如果要提供未bundle的版本给node使用的话，要么就是把workspace的依赖bundle进去，要么就是workspace的依赖发包改成非workspace依赖，对应着我说的两个方案。

**Comment by Mister-Hope** [comment]
大哥别犟，我之前特意开了issue。如果你使用 pnpm publish命令发布任何含有workspace 协议的任何包，那么他们会在发布时基于workspace相关依赖的版本自动转换到对应的版本号范围。本质上就是你 CI 发布有问题。

换言之，无论是 dep peerDep 还是 devDep 的依赖，workspace protocal都是没问题，对于本地是 1.0.0 的版本，workspace:* workspace:~ workspace:^ 会自动转换为 "1.0.0" "~1.0.0" 和 "^1.0.0"。

**Comment by lizheming** [comment]
@Mister-Hope 我觉得你可能没听明白我说的话的意思。那就按照你的理解来吧，CI 发布有问题，有两个解决方案，你选择一种，我来修改。

**Comment by Mister-Hope** [comment]
我觉得我充分理解了你要表达的意思，但我不觉得你的观点是对的。

握有大量包含monorepo的项目都在用 pnpm，比如 vuepress/core vuepress/ecosystem vuepress-theme-hope/vuepress-theme-hope mdit-plugins/mdit-plugins 之类的。

1. 包管理器使用要一致，而且像corepack这种东西已经很成熟了，比如 `corepack use npm` 就直接能把当前的项目从任意包管理器换成 npm。我不能理解 pnpm 的项目用 npm publish 的方式来发包，就是这里的workspace的问题。npm不支持 workspace，也自然不需要再 publish 的时候对这种特殊版本做处理。

2. > 这种monorepo项目的依赖内部引用一般对外的产物都是bundle后文件。

   我不能理解这种错误结论是从哪得出来的，所有针对 node 的 monorepo 发包的时候都不会 bundle，做一个需要 CDN 通过浏览器来使用的包在前端才是特例。我上面举的所有例子都没有打包 monorepo 内其他包的行为。就拿这个项目本身的依赖来说，\@typescript-eslint \@commitlint 等包也不是你所说的这么干。

（仅技术性讨论）

**Comment by lizheming** [comment]
@Mister-Hope
1. 包管理器要使用一致，这个是有待商榷的结论，先不说它是不是完全正确的吧。我没有按照你的思路选择 `pnpm publish` 的原因是，市面上暂时没有比较好的集成 `pnpm publish` 的 GitHub Action。而现有的 https://github.com/JS-DevTools/npm-publish 工具比较好的点是能够识别版本号再做发布相关的逻辑，能比较好的根据不同 case 返回发布的状态。综合换工具和适配的成本，我选择了后者适配。
2. 首先，我说的是“一般”，其次，这也不是错误的结论。就你举例的两个案例我都去看了，typescript-eslint 的 workspace 依赖是在 workspaceRoot 的，不存在需要发布的场景。而 commitlint 我没找到它有 workspace 依赖的行为，或者它使用 yarn 的 workspace 的依赖书写规则和 pnpm 不太一样，我没有看到同类的场景可以参考。

按照你说的 pnpm 的行为，我认为你会选择提到的方案二，那我就不多说了按照二来处理吧。

**Comment by lizheming** [comment]
fixed with #2333 please update to  `@waline/client@3.0.1`
