### ISSUE TITLE
[Feature]: Add support for Vietnamese language (vi)

### ISSUE THREAD

**Issue by h4upt** [walinejs/waline#2347]
### 功能概述 | Describe the feature

Hello Waline Admins,

I've noticed that Vietnamese language support is not currently available in the Waline project. As a native Vietnamese speaker, I believe adding support for the Vietnamese language (vi) would greatly benefit the user experience for Vietnamese-speaking users.
[
![2024-02-18_13-58-48](https://github.com/walinejs/waline/assets/16865624/bdf5771b-9676-4de1-a885-1abcaa495107)
](url)
I found the file "vi-VN.ts" at the link "https://github.com/walinejs/waline/blob/main/packages/client/src/config/i18n/vi-VN.ts" that contained the translation for this language.
//////////
import { generateLocale } from './generate.js';

export default generateLocale([
  'Tên',
  'Tên không được nhỏ hơn 3 ký tự.',
  'E-Mail',
  'Vui lòng xác nhập địa chỉ email của bạn.',
  'Website',
  'Tùy chọn',
  'Hãy bình luận có văn hoá!',
  'Chưa có bình luận',
  'Gửi',
  'Thích',
  'Bỏ thích',
  'Trả lời',
  'Hủy bỏ',
  'bình luận',
  'Làm mới',
  'Tải thêm...',
  'Xem trước',
  'Emoji',
  'Tải lên hình ảnh',
  'giây trước',
  'phút trước',
  'giờ trước',
  'ngày trước',
  'Vừa xong',
  'Đang tải lên',
  'Đăng nhập',
  'đăng xuất',
  'Quản trị viên',
  'Dính',
  'từ',
  'Bình luận phải có độ dài giữa $0 và $1 từ!\n Số từ hiện tại: $2',
  'Vô danh',
  'Người lùn',
  'Người tí hon',
  'Thần rừng',
  'Pháp sư',
  'Tiên tộc',
  'Maiar',
  'Ảnh GIF',
  'Tìm kiếm ảnh GIF',
  'thông tin cá nhân',
  'Đã được phê duyệt',
  'Đang chờ đợi',
  'Thư rác',
  'Không dính',
  'lâu đời nhất',
  'muộn nhất',
  'nóng nhất',
  'What do you think?',
]);
//////////
Can the admins take a look and add it? I and Vietnamese users will be very grateful to you. Thank you!

---
### 功能概述 | Describe the features

Hello Waline Admins,

I've noticed that Vietnamese language support is not currently available in the Waline project. As a native Vietnamese speaker, I believe adding support for the Vietnamese language (vi) would greatly benefit the user experience for Vietnamese-speaking users.
[
![2024-02-18_13-58-48](https://github.com/walinejs/waline/assets/16865624/bdf5771b-9676-4de1-a885-1abcaa495107)
](URL)
I found the file "vi-VN.ts" at the link "https://github.com/walinejs/waline/blob/main/packages/client/src/config/i18n/vi-VN.ts" that contains the translation for this language.
//////////
import { generateLocale } from './generate.js';

export default generateLocale([
  'Name',
  'Name cannot be less than 3 characters.',
  'Email',
  'Please enter your email address.',
  'Website',
  'Option',
  'Please comment culturally!',
  'No comments yet',
  'Send',
  'Prefer',
  'Unlike',
  'Reply',
  'Cancel',
  'comment',
  'Refresh',
  'Load more...',
  'Preview',
  'Emoji',
  'Upload image',
  'seconds ago',
  'minute ago',
  'hours ago',
  'yesterday',
  'Just finished',
  'Uploading',
  'Log in',
  'log out',
  'Administrators',
  'Sticky',
  'from',
  'Comment must be between $0 and $1 words in length!\nCurrent word count: $2',
  'Nameless',
  'Shorty',
  'Tiny',
  'Satyr',
  'Magician',
  'Elves',
  'Maiar',
  'GIFs',
  'Search for GIFs',
  'personal information',
  'Approved',
  'Waiting',
  'Spam',
  'Not adhesive',
  'longest life span',
  'latest',
  'hottest',
  'What do you think?',
]);
//////////
Can the admins take a look and add it? I and Vietnamese users will be very grateful to you. Thank you!

**Comment by lizheming** [comment]
`@waline/client@3.1.0` has added support for this language, https://waline.js.org/en/guide/features/i18n.html

**Comment by h4upt** [comment]
Thank you very much for your support.
