### ISSUE TITLE
[Bug]: 我在配置邮箱回复时，使用一个新邮箱模拟游客，当我回复了游客的信息时，自己接收到了邮件，但是游客并没有接收到邮件 || [Bug]: When I configured the email reply, I used a new email address to simulate a visitor. When I replied to the visitor's information, I received the email myself, but the visitor Didn't receive email

### ISSUE THREAD

**Issue by willow-god** [walinejs/waline#2349]
### 问题描述 | Describe the bug

尊敬的开发者，很抱歉打扰一下，我想请教一个问题，我在配置邮箱通知时，使用一个新邮箱模拟游客，当我回复了游客评论的一个问题时，只有我自己的邮箱接收到了邮件，但是游客的邮箱并没有接收到邮件，我知道自己接收到邮件是因为author_email的配置问题，但是我想知道为什么游客无法接收到邮件提醒呢？是我配置问题还是没有这个功能呢？我尝试上网查询资料但是并没有结果，所以来请教一下。感谢开发者

### 问题网站 | Website URL

comment.qyliu.top

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

Dear developer, I'm sorry to bother you. I want to ask a question. When configuring email notifications, I used a new email address to simulate a visitor. When I responded to a question commented by a visitor, only my own email address received the email. However, the visitor's mailbox did not receive the email. I know that the email I received was due to the configuration problem of author_email, but I want to know why the visitor cannot receive the email reminder? Is it a configuration problem on my part or does it not have this function? I tried to search for information online but there was no result, so I came to ask for advice. Thanks to the developer

### Question Website | Website URL

comment.qyliu.top

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
评论回复邮件通知功能是有的，检查下评论状态是不是审核状态，审核状态的回复评论不会给父评论发邮件通知。这块判断条件较多，可以对着这段代码排查 https://github.com/walinejs/waline/blob/main/packages/server/src/service/notify.js#L528-L534

**Comment by willow-god** [comment]
好的，谢谢您，辛苦了
