### ISSUE TITLE
[Feature]: 请问，去除评论框上方的【昵称】【邮箱】【网址】 || [Feature]: Please remove the [nickname] [email] [website] above the comment box.

### ISSUE THREAD

**Issue by nakamiv** [walinejs/waline#2350]
### 功能概述 | Describe the feature

请问有什么方法能去除评论框上方的昵称，邮箱和网址项？
匿名评论一般没什么人会填写，页面上有这三项很累赘，不简洁。特别是移动端。
不代表其他人，只是我的站点用不到这三个框。

我是用vercel 搭建的。有没有办法修改去除这三个选项呢？谢谢
![image](https://github.com/walinejs/waline/assets/12234157/f28b43e9-af11-4150-b736-98e282452676)

---
### Feature Overview | Describe the feature

Is there any way to remove the nickname, email address and website address above the comment box?
Generally few people will fill in anonymous comments. Having these three items on the page is cumbersome and not concise. Especially the mobile version.
I don’t speak for others, but my site doesn’t use these three boxes.

I built it using vercel. Is there any way to modify and remove these three options? Thanks
![image](https://github.com/walinejs/waline/assets/12234157/f28b43e9-af11-4150-b736-98e282452676)

**Comment by lizheming** [comment]
可以自己通过自定义样式隐藏
