### ISSUE TITLE
Reaction 初始数据不展示

### ISSUE THREAD

**Issue by lizheming** [walinejs/waline#2352]
### Discussed in https://github.com/orgs/walinejs/discussions/2351

<div type='discussions-op-text'>

<sup>Originally posted by **nanqic** February 23, 2024</sup>
### Describe the bug | 问题描述

后台看不到 ipv6位置，只看到 v4 的，是 我个人配置的问题吗？

看到文档说文章反映基于 ip，点赞过的，点赞总数怎么显示 0 呢？控制台看到有请求数据

调试 ：tk=123

### Website URL | 问题网站

https://m.ningway.com/search/%E6%89%93%E5%9D%90

### Where your waline deploy? | 服务部署在哪里？

Netlify

### Where your comment data store? | 数据存储在哪里？

LeanCloud(https://leancloud.app)

---
### Describe the bug | Problem description

I can't see the ipv6 location in the background, but only v4. Is it a problem with my personal configuration?

I saw the document saying that the article reflection is based on IP and has been liked. Why does the total number of likes show 0? The console sees request data

Debugging: tk=123

### Website URL | Problem website

https://m.ningway.com/search/%E6%89%93%E5%9D%90

### Where your waline deploy? | Where is the service deployed?

Netlify

### Where your comment data store? | Where is the data stored?

LeanCloud(https://leancloud.app)
</div>

**Comment by panoshu** [comment]
我这里（[https://www.panoshu.top/](https://www.panoshu.top/)）也遇到了这个问题，另外官方文档页面的Reaction也不记录了，刷新后都会清零。

**Comment by lizheming** [comment]
`@waline/client@3.1.3` 已修复
