### ISSUE TITLE
[Bug]: 评论对方后文字不消失，会显示到上方的输入框内 || [Bug]: The text does not disappear after commenting on the other party, and will be displayed in the input box above

### ISSUE THREAD

**Issue by willow-god** [walinejs/waline#2371]
### 问题描述 | Describe the bug

当我回复对方的评论并发送后，除了文字已经发送，输入的文本框的内容没有清空，会显示到上方的主评论框中，请问这个是我个人问题还是？可以解决吗？

![image](https://github.com/walinejs/waline/assets/93815242/47a2fd91-7d9a-4bbe-a642-6a8c79f97550)

### 问题网站 | Website URL

https://www.qyliu.top/comment/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

When I reply to the other party's comment and send it, except that the text has been sent, the content of the input text box is not cleared and will be displayed in the main comment box above. Is this a personal problem of mine? Can it be solved?

![image](https://github.com/walinejs/waline/assets/93815242/47a2fd91-7d9a-4bbe-a642-6a8c79f97550)

### Question Website | Website URL

https://www.qyliu.top/comment/

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by willow-god** [comment]
如上图，我本来已经回复下方的评论，回复后，输入的文字会显示到最顶上输入框中

**Comment by OrageKK** [comment]
+1 我也有这个现象，不是个例

**Comment by MingTechPro** [comment]
我也是这样子，还有登录不会刷新
---
I'm the same way, and the login doesn't refresh

**Comment by OrageKK** [comment]
The value of the key 'WALINE_COMMENT_BOX_EDITOR' is set in **LocalStorage** to the content of the last comment
> 由于在**LocalStorage**中设置了`WALINE_COMMENT_BOX_EDITOR`这个key的值为上次评论的内容导致的

**Comment by MingTechPro** [comment]
> The value of the key 'WALINE_COMMENT_BOX_EDITOR' is set in **LocalStorage** to the content of the last comment
> 
> > 由于在**LocalStorage**中设置了`WALINE_COMMENT_BOX_EDITOR`这个key的值为上次评论的内容导致的

这个有方法解决么

**Comment by OrageKK** [comment]
> > The value of the key 'WALINE_COMMENT_BOX_EDITOR' is set in **LocalStorage** to the content of the last comment
> > > 由于在**LocalStorage**中设置了`WALINE_COMMENT_BOX_EDITOR`这个key的值为上次评论的内容导致的
> 
> 这个有方法解决么

等官方修复呗，或者提个PR
