### ISSUE TITLE
[Bug]: v3版本客户端回复别人评论不会显示@nickname || [Bug]: v3 version client does not display @nickname when replying to other people’s comments

### ISSUE THREAD

**Issue by track23** [walinejs/waline#2377]
### 问题描述 | Describe the bug

回复别人评论时，评论内容不会出现@nickname。
是因为后端1.27.0版本废弃了at和pid字段，需要自己拼接内容吗？没有pid字段被回复人的邮件提醒会不会有问题？

### 问题网站 | Website URL

waline.js.org

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

When replying to other people's comments, @nickname will not appear in the comment content.
Is it because the backend version 1.27.0 has abandoned the at and pid fields, do I need to splice the content myself? Will there be any problem with the email reminder of the person being replied to without the pid field?

### Question Website | Website URL

waline.js.org

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by track23** [comment]
server 版本： 1.31.13
客户端版本：3.1.3

**Comment by cirry** [comment]
v3版本确实没有了@功能，而且邮件提醒也没有了，以前回复的邮件标题是`您在xxx上的评论收到了回复`也变成了`收到了新邮件`，目前看来回复功能是失效了。

**Comment by track23** [comment]
@lizheming 请问这是bug还是feature？

**Comment by track23** [comment]
@lizheming 这个pr不更新吗？现在还是1.31.13
