### ISSUE TITLE
[Bug]: 可以通过域名访问 /ui/login，但是后续的请求地址却是 127.0.0.1，而不是域名 || [Bug]: /ui/login can be accessed through the domain name, but the subsequent request address is 127.0.0.1, not the domain name

### ISSUE THREAD

**Issue by JQiue** [walinejs/waline#2378]
### 问题描述 | Describe the bug

![image](https://github.com/walinejs/waline/assets/45145407/8390d09b-57f5-4832-a62a-9ae29c0aa276)

### 问题网站 | Website URL

没有部署到外网

### 服务部署在哪里？ | Where your waline deploy?

Self Host

### 数据存储在哪里？| Where your comment data store?

MySQL

---
### Problem description | Describe the bug

![image](https://github.com/walinejs/waline/assets/45145407/8390d09b-57f5-4832-a62a-9ae29c0aa276)

### Question Website | Website URL

Not deployed to the external network

### Where is the service deployed? | Where your waline deploy?

Self Host

### Where is the data stored? | Where your comment data store?

MySQL

**Comment by lizheming** [comment]
nginx 里面需要加 `proxy_set_header REMOTE-HOST $remote_addr;`
