### ISSUE TITLE
[Bug]: Waline无法正常显示 || [Bug]: Waline cannot be displayed properly

### ISSUE THREAD

**Issue by CXwudi** [walinejs/waline#2379]
### 问题描述 | Describe the bug

不知道为什么，我用Vercel一键部署的Waline无法正常显示
![image](https://github.com/walinejs/waline/assets/17377423/fc623676-6f50-4ed8-bade-588e4914556b)

### 问题网站 | Website URL

https://blog-waline.mikufancx.cyou/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

I don’t know why, but the Waline I deployed with one click using Vercel cannot be displayed normally.
![image](https://github.com/walinejs/waline/assets/17377423/fc623676-6f50-4ed8-bade-588e4914556b)

### Question Website | Website URL

https://blog-waline.mikufancx.cyou/

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
这个页面的 Waline 配置默认使用的是你的浏览器语言做的展示，可以控制台打印下 `navigator.languages` 截图看一下。另外，截图的页面是 Waline 的 demo 页，不是真实使用的页面，有问题可以忽略。

**Comment by CXwudi** [comment]
显示`en-GB`
![image](https://github.com/walinejs/waline/assets/17377423/ccaefb5d-7a8e-4a80-bc5d-fb1e19ddad91)

这个应该跟美国英语不一样
