### ISSUE TITLE
[Bug]: 评论预览不支持Markdown表情包的预览，提交之后表情可以正常显示 || [Bug]: Comment preview does not support the preview of Markdown emoticon packages. The emoticons can be displayed normally after submission.

### ISSUE THREAD

**Issue by meiMingle** [walinejs/waline#2388]
### 问题描述 | Describe the bug

![image](https://github.com/walinejs/waline/assets/39942874/3a65fd4d-d7ef-485e-97c9-87d141bb0dcc)
![image](https://github.com/walinejs/waline/assets/39942874/33744572-cb12-436b-827d-8b0227ea118a)

### 问题网站 | Website URL

https://meimingle.github.io/2024/03/16/Excel%E5%AF%BC%E5%85%A5%E5%AF%BC%E5%87%BA%E6%96%B9%E6%A1%88%E6%B1%87%E6%80%BB/

### 服务部署在哪里？ | Where your waline deploy?

Deta

### 数据存储在哪里？| Where your comment data store?

PostgreSQL

---
### Problem description | Describe the bug

![image](https://github.com/walinejs/waline/assets/39942874/3a65fd4d-d7ef-485e-97c9-87d141bb0dcc)
![image](https://github.com/walinejs/waline/assets/39942874/33744572-cb12-436b-827d-8b0227ea118a)

### Question Website | Website URL

https://meimingle.github.io/2024/03/16/Excel%E5%AF%BC%E5%85%A5%E5%AF%BC%E5%87%BA%E6%96%B9%E6% A1%88%E6%B1%87%E6%80%BB/

### Where is the service deployed? | Where your waline deploy?

Deta

### Where is the data stored? | Where your comment data store?

PostgreSQL

**Comment by Mister-Hope** [comment]
We are expecting you to read the docs https://waline.js.org/guide/features/syntax.html#%E6%9C%89%E9%99%90%E7%9A%84%E9%A2%84%E8%A7%88%E6%94%AF%E6%8C%81
