### ISSUE TITLE
[Bug]: 将博主邮箱设置为smtp发件邮箱，博主自己发的贴子也会提醒 || [Bug]: Set the blogger’s email address as the SMTP sending email address, and the blogger’s own posts will also be reminded

### ISSUE THREAD

**Issue by im-pzy** [walinejs/waline#2389]
### 问题描述 | Describe the bug

[Bug]: 将博主邮箱设置为smtp发件邮箱，博主自己发的贴子也会提醒

### 问题网站 | Website URL

https://impzy.cn

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

[Bug]: If the blogger’s email is set as the SMTP sending email, the blogger’s own posts will also be reminded

### Question Website | Website URL

https://impzy.cn

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
https://waline.js.org/guide/features/notification.html 搜 `AUTHOR_EMAIL`
