### ISSUE TITLE
[Bug]: nginx代理waline，访问ui后台api报404 || [Bug]: nginx proxy waline, access ui backend api reports 404

### ISSUE THREAD

**Issue by Spacesless** [walinejs/waline#2390]
### 问题现象
独立部署，nginx配置/comment代理到@waline/vercel服务，访问ui后台example.com/comment/ui/login，api报404查看地址为example.com/api/token。
### 问题分析
查看@waline/vercel/src/middleware/dashboard.js源代码：
`window..serverURL = '${ctx.serverURL}/api/'`
发现固定为 serverURL+/api
### 期望
由于/api很多系统都会用这个地址，所以没法添加/api代理到waline，所以期望这些api地址可以自适应，或者通过环境配置，比如：example.com/comment/api/token

### 问题网站 | Website URL

app.timelessq.com

### 服务部署在哪里？ | Where your waline deploy?

Other

### 数据存储在哪里？| Where your comment data store?

MySQL

---
### Problem phenomenon
Independent deployment, nginx configures /comment proxy to @waline/vercel service, accesses the ui backend example.com/comment/ui/login, the api reports 404, and the viewing address is example.com/api/token.
### problem analysis
View @waline/vercel/src/middleware/dashboard.js source code:
`window..serverURL = '${ctx.serverURL}/api/'`
Found that it is fixed to serverURL+/api
### expect
Since many systems use this address for /api, it is not possible to add the /api proxy to waline. Therefore, it is expected that these api addresses can be adaptive or configured through the environment, such as: example.com/comment/api/token

### Question Website | Website URL

app.timelessq.com

### Where is the service deployed? | Where your waline deploy?

Other

### Where is the data stored? | Where your comment data store?

MySQL

**Comment by lizheming** [comment]
`SERVER_URL` 设置这个环境变量为你对应的地址即可。https://github.com/walinejs/waline/blob/main/packages/server/src/config/extend.js#L15-L19
