### ISSUE TITLE
[Feature]:  新增评论通知渠道 ntfy  || [Feature]: Added comment notification channel ntfy

### ISSUE THREAD

**Issue by 0x5c0f** [walinejs/waline#2401]
## 需求: 

希望增加新的评论通知渠道 `ntfy`, 或者增加自定义的`webhook` 。目前我是部署在`vercel`上的，已测试邮件通知，但似乎是无法成功通知的，希望能增加`ntfy`或者自定义的`webhook`,用于解决类似问题. 

## 参考链接:
> https://github.com/binwiederhier/ntfy
> https://ntfy.sh 

---
## need: 

I hope to add a new comment notification channel `ntfy`, or add a custom `webhook`. Currently, I deploy it on `vercel` and have tested the email notification, but it seems that the notification cannot be successful. I hope to add `ntfy` or a customized `webhook` to solve similar problems.

## Reference link:
> https://github.com/binwiederhier/ntfy
> https://ntfy.sh

**Comment by lizheming** [comment]
`WEBHOOK` 看一下这个， https://waline.js.org/reference/server/env.html#%E9%AB%98%E7%BA%A7%E9%85%8D%E7%BD%AE
