### ISSUE TITLE
[Bug]: Disqus 迁移 Waline 评论数据导入失败 || [Bug]: Disqus migration Waline comment data import failed

### ISSUE THREAD

**Issue by leimao** [walinejs/waline#2403]
### 问题描述 | Describe the bug

使用官方的数据转换工具将 Disqus 评论数据转换成 Waline LeanCloud 评论数据，在 Waline 数据管理端导入 Waline LeanCloud 评论数据时报错提示 “import data format not support!“

这个是我的 Disqus 的评论数据
[disqus.txt](https://github.com/walinejs/waline/files/14752017/disqus.txt)

这个是转换后的 Waline LeanCloud 评论数据
[leancloud.json](https://github.com/walinejs/waline/files/14752019/leancloud.json)

### 问题网站 | Website URL

N/A

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

Use the official data conversion tool to convert Disqus comment data into Waline LeanCloud comment data. When importing Waline LeanCloud comment data on the Waline data management terminal, an error message appears "import data format not support!"

This is my Disqus comment data
[disqus.txt](https://github.com/walinejs/waline/files/14752017/disqus.txt)

This is the converted Waline LeanCloud comment data
[leancloud.json](https://github.com/walinejs/waline/files/14752019/leancloud.json)

### Question Website | Website URL

N/A

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
转换后的数据是去 LeanCloud 后台做导入，不是在 Waline 后台，这里需要注意下。Waline 后台的导入导出仅支持 Waline 自己的格式。
