### ISSUE TITLE
[Bug]: 夜间模式下自体是黑色的 || [Bug]: The self is black in night mode

### ISSUE THREAD

**Issue by leimao** [walinejs/waline#2410]
### 问题描述 | Describe the bug

请问这个是预料之中的吗？
![Screenshot from 2024-04-02 20-25-28](https://github.com/walinejs/waline/assets/17606112/7d1ba586-6d9d-4422-9ff0-fd5b35b6bf88)

### 问题网站 | Website URL

N/A

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

Is this expected?
![Screenshot from 2024-04-02 20-25-28](https://github.com/walinejs/waline/assets/17606112/7d1ba586-6d9d-4422-9ff0-fd5b35b6bf88)

### Question Website | Website URL

N/A

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by Mister-Hope** [comment]
link

**Comment by leimao** [comment]
> 提供你的页面链接
> 
> Provide your page link

并没有实际部署。我只是想先确认这个是不是意料之中的。

**Comment by Mister-Hope** [comment]
我们的官网样式是意料之中的
