### ISSUE TITLE
[Bug]: 指定开启暗黑模式没效果 dark:true || [Bug]: Specifying dark mode has no effect dark:true

### ISSUE THREAD

**Issue by kok777** [walinejs/waline#2423]
### 问题描述 | Describe the bug

`<script type="module">
import{init}from"https://npm.onmicrosoft.cn/@waline/client@v3/dist/waline.js";
function loadWaline(){init({el:"#waline",serverURL:"",lang:"en",
dark:true,
requiredMeta:["nick","mail"],wordLimit:["2","1000"],imageUploader:!1,copyright:!1,emoji:["//npm.onmicrosoft.cn/@waline/emojis@1.2.0/qq"]})}"undefined"!=typeof swup?loadWaline():window.addEventListener("DOMContentLoaded",loadWaline)</script>`
见如上代码，因为模板就是纯黑色的没有其他模式，我设置直接开启暗黑模式。但是没效果。

### 问题网站 | Website URL

http

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

`<script type="module">
import{init}from"https://npm.onmicrosoft.cn/@waline/client@v3/dist/waline.js";
function loadWaline(){init({el:"#waline",serverURL:"",lang:"en",
dark: true,
requiredMeta:["nick","mail"],wordLimit:["2","1000"],imageUploader:!1,copyright:!1,emoji:["//npm.onmicrosoft.cn/@waline/emojis @1.2.0/qq"]})}"undefined"!=typeof swup?loadWaline():window.addEventListener("DOMContentLoaded",loadWaline)</script>`
See the code above. Because the template is pure black and has no other modes, I set it to turn on the dark mode directly. But it didn't work.

### Question Website | Website URL

http

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by kok777** [comment]
![1712763719214](https://github.com/walinejs/waline/assets/59135068/2d7799ca-7883-4c96-a1a8-4288bba92818)

**Comment by Mister-Hope** [comment]
needs reproduction
