### ISSUE TITLE
[Bug]: 部署在远程服务器上，直接访问8360端口显示跨域问题，打开科学上网却可以正常访问 || [Bug]: Deployed on a remote server, direct access to port 8360 shows a cross-domain problem, but when scientific Internet access is turned on, access can be normal.

### ISSUE THREAD

**Issue by Zcion202** [walinejs/waline#2428]
### 问题描述 | Describe the bug

**在阿里云的服务器上部署了waline容器，创建的命令如下：**
···
docker run -d --name waline -p 8360:8360 \
  -v /docker/waline/data:/app/data \
  -e MYSQL_HOST="172.17.0.1" \
  -e MYSQL_PORT="3306" \
  -e MYSQL_DB="waline" \
  -e MYSQL_USER="root" \
  -e MYSQL_PASSWORD="123456" \
  --restart always \
  lizheming/waline:latest
···

**正常访问 http://120.24.233.182:8360/ 会出现以下报错：**
[Bug]: Access to script at 'https://unpkg.com/@waline/client@v3/dist/waline.js' from origin 'http://120.24.233.182:8360' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**但开了科学上网后就可以正常访问，想请教下问题出在哪里**

### 问题网站 | Website URL

http://120.24.233.182:8360/

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

MySQL

---
### Problem description | Describe the bug

**The waline container is deployed on the Alibaba Cloud server, and the created command is as follows:**
···
docker run -d --name waline -p 8360:8360 \
  -v /docker/waline/data:/app/data \
  -e MYSQL_HOST="172.17.0.1" \
  -e MYSQL_PORT="3306" \
  -e MYSQL_DB="waline" \
  -e MYSQL_USER="root" \
  -e MYSQL_PASSWORD="123456" \
  --restart always \
  lizheming/waline:latest
···

**Normal access to http://120.24.233.182:8360/ will result in the following error:**
[Bug]: Access to script at 'https://unpkg.com/@waline/client@v3/dist/waline.js' from origin 'http://120.24.233.182:8360' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**But after turning on the scientific Internet, you can access it normally. I would like to ask where the problem lies**

### Question Website | Website URL

http://120.24.233.182:8360/

### Where is the service deployed? | Where your waline deploy?

Docker

### Where is the data stored? | Where your comment data store?

MySQL

**Comment by lizheming** [comment]
1. 这个页面是一个 debug 页面，真正使用不依赖
2. 出现问题的原因是 unpkg.com 的网络问题
