### ISSUE TITLE
[Bug]: cn域名无法加载出评论框以及列表 || [Bug]: cn domain name cannot load the comment box and list

### ISSUE THREAD

**Issue by resetsix** [walinejs/waline#2446]
### 问题描述 | Describe the bug

代码托管：Github
站点部署：Vercel或Cloudflare
问题描述：生产环境通过自定义域名访问时(cn域名)无法加载出waline组件，默认域名正常。本地启动访问也正常。
因为我没有其他的域名，所以无法测试其他域名的情况。

能加载出评论框的站点(默认域名)
```
https://blog-ruby-pi-11.vercel.app/hello-world/
```
一直loading转圈无法加载出评论框的站点(cn域名)
```
https://www.resetsix.cn
```
www替换成blog也行，但效果始终一样。

提示：开了代理，也尝试清除过浏览器缓存。Chrome、Firefox也都用过。

### 问题网站 | Website URL

https://www.resetsix.cn

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

Code hosting: Github
Site deployment: Vercel or Cloudflare
Problem description: When the production environment is accessed through a custom domain name (cn domain name), the waline component cannot be loaded, and the default domain name is normal. Local startup access is also normal.
Because I don't have other domain names, I can't test the situation with other domain names.

A site that can load a comment box (default domain name)
```
https://blog-ruby-pi-11.vercel.app/hello-world/
```
The site (cn domain name) that keeps loading in circles and cannot load the comment box
```
https://www.resetsix.cn
```
You can replace www with blog, but the effect will always be the same.

Tip: Turn on the proxy and try clearing the browser cache. Chrome and Firefox have also been used.

### Question Website | Website URL

https://www.resetsix.cn

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by Mister-Hope** [comment]
https://resetsix.cn/hello-world/ 在这个页面里我并没有看到任何像 Waline 的脚本被加载，也并没有看到任何发送至 Waline 服务器的网络请求。

建议检查自己所使用的主题是不是配置对了
