### ISSUE TITLE
[Bug]: ArticleReaction.vue:99 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'reaction0')

### ISSUE THREAD

**Issue by wish5115** [walinejs/waline#2451]
### 问题描述 | Describe the bug

页面加载时出现以下错误：

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'reaction0')
    at ArticleReaction.vue:99:33
    at Array.map (<anonymous>)
    at f (ArticleReaction.vue:98:32)
(anonymous) @ ArticleReaction.vue:99
f @ ArticleReaction.vue:98
await in f (async)
Pe.immediate @ ArticleReaction.vue:152
ut @ runtime-core.esm-bundler.js:192
Be @ runtime-core.esm-bundler.js:199
w @ runtime-core.esm-bundler.js:1941
Hs @ runtime-core.esm-bundler.js:1979
Pe @ runtime-core.esm-bundler.js:1806
(anonymous) @ ArticleReaction.vue:149
(anonymous) @ runtime-core.esm-bundler.js:2872
ut @ runtime-core.esm-bundler.js:192
Be @ runtime-core.esm-bundler.js:199
Ka.t.__weh.t.__weh @ runtime-core.esm-bundler.js:2852
Os @ runtime-core.esm-bundler.js:367
qt @ runtime-core.esm-bundler.js:6676
mount @ runtime-core.esm-bundler.js:3928
t.mount @ runtime-dom.esm-bundler.js:1501
Od @ init.ts:81
window.initWaline @ (index):18
(anonymous) @ (index):18
Show 13 more frames
Show less

```

### 问题网站 | Website URL

https://wilson.lovestoblog.com/demo/ob_demo/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
问题网站打不开

**Comment by lizheming** [comment]
看起来应该已经没问题了
![image](https://github.com/walinejs/waline/assets/424491/a11cf632-fa12-455b-abef-bcd43ee4a7ea)

**Comment by wish5115** [comment]
> t ArticleReaction.vue:99:33
>     at Array.map (<anonymous>)
>     at f (ArticleReaction.vue:98:32)
> (anonymous) @ ArticleReaction.vue:99

Sorry, I thought you guys were delayed in responding to bug feedback like other projects, so I didn't pay attention, I didn't expect you guys to reply so quickly, sorry!

The problem still exists, I'll re-give you a URL, this site is faster to access and easier for you guys to find the problem, the page loads normally, it's just that when switching documents in the left menu will report an error.

You click on the URL below and refer to my GIF image:

https://wxkj.asia/mynote/

![waline-bugs](https://github.com/walinejs/waline/assets/5248206/d89d381b-fdf4-4f22-88cd-2d55280671c1)

**Comment by wish5115** [comment]
Here resp is an object, not an array, so [0] here is redundant, I think.

<img width="665" alt="Snipaste_2024-05-02_17-07-27" src="https://github.com/walinejs/waline/assets/5248206/c9601796-0db6-4493-9e4c-1ad8b064da49">
