### ISSUE TITLE
[Bug]:  Comment sorting and disabling image upload settings in client don't seem to work.

### ISSUE THREAD

**Issue by ScootRay** [walinejs/waline#2462]
### 问题描述 | Describe the bug

Comment sorting and disabling image upload settings in client don't seem to work.

I have them defined on the client side as:

```
 <script type="module">
    import { init } from 'https://unpkg.com/@waline/client@v3/dist/waline.js';

    init({
      el: '#waline',
      serverURL: 'https://test-comments.vercel.app',
      lang: 'en',
      dark: 'auto',
      login: 'disable',
      WalineCommentSorting: 'oldest',
      WalineImageUploader: 'false',
    });
  </script>

```

lang, dark and login are accepted and working just not the comment/uploading settings. Is there something else I should be doing?

Thanks, looks like a slick comment app!

Ray

### 问题网站 | Website URL

https://private.url

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
1. It's named `commentSorting`, not `WalineCommentSorting`. https://waline.js.org/en/reference/client/props.html#commentsorting
2. It's named `imageUploader`, not `WalineImageUploader`. And the value should be `false`, not `'false'`

**Comment by ScootRay** [comment]
Doh! That’s what I get for not getting much sleep. It’s all good now. Thank you muchly. 

Am loving how elegant and easy Waline is. 

Props!
Ray
