### ISSUE TITLE
[Bug]: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

### ISSUE THREAD

**Issue by wenleiwang** [walinejs/waline#2464]
### 问题描述 | Describe the bug

我使用MYSQL8.0数据库

配置文件都已经编写，表结构也创建

登录报这个错误

![image](https://github.com/walinejs/waline/assets/39472071/f11eb7b0-4e9b-4fdd-9171-501a5dbb7ce4)

查询了一下，貌似是这个问题，但我不知道该怎么解决，求帮助 

https://stackoverflow.com/questions/50093144/mysql-8-0-client-does-not-support-authentication-protocol-requested-by-server

### 问题网站 | Website URL

http://59.110.90.215:8360/

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

MySQL

---
### Problem description | Describe the bug

I use MYSQL8.0 database

The configuration files have been written and the table structure has been created.

This error is reported when logging in

![image](https://github.com/walinejs/waline/assets/39472071/f11eb7b0-4e9b-4fdd-9171-501a5dbb7ce4)

After searching, it seems that this is the problem, but I don’t know how to solve it. Please help.

https://stackoverflow.com/questions/50093144/mysql-8-0-client-does-not-support-authentication-protocol-requested-by-server

### Question Website | Website URL

http://59.110.90.215:8360/

### Where is the service deployed? | Where your waline deploy?

Docker

### Where is the data stored? | Where your comment data store?

MySQL

**Comment by lizheming** [comment]
就是按照你给的参考文档，在 MySQL 里执行下就行。主要是切换下密码的加密格式。

**Comment by wenleiwang** [comment]
```sql
-- 如果您使用多个 MySQL 用户，请确保更新所有从远程（即不是本地主机）连接的用户。就我而言，我还必须使用 '%' 而不是 'localhost'
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'YourRootPassword';
-- or
CREATE USER 'foo'@'%' IDENTIFIED WITH mysql_native_password BY 'bar';
-- then
FLUSH PRIVILEGES;
```


好的，谢谢。
