### ISSUE TITLE
[Bug]:  Error when accessing UI management，TypeError: ww is not a function (admin:9118:162)

### ISSUE THREAD

**Issue by wish5115** [walinejs/waline#2467]
### 问题描述 | Describe the bug

Error when accessing UI management, TypeError: ww is not a function

It was fine before and suddenly I can't access it.

The page opens and goes blank.

The error message is as follows:

```
TypeError: ww is not a function
    at co.extractFromKey (admin:9118:162)
    at co.translate (admin:9143:14)
    at Fr.t (admin:10215:47)
    at o (admin:10210:143)
    at Iw (admin:10432:94)
    at fa (admin:3248:148)
    at Qd (admin:5679:21)
    at Hd (admin:5419:11)
    at Eg (admin:5412:5)
    at eo (admin:5400:7)
pl	@	admin:3619
```

<img width="1135" alt="Snipaste_2024-05-03_00-10-35" src="https://github.com/walinejs/waline/assets/5248206/90ee68d8-2285-4b27-a750-37487d26a9da">

### 问题网站 | Website URL

https://waline.wxkj.asia/ui/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
开隐私模式看下是否正常

**Comment by wish5115** [comment]
隐私模式正常的，为什么？ 以前是好的。

---

Privacy mode is normal. Why? It used to be fine.
