### ISSUE TITLE
[Feature]: GRAVATAR_STR SHA256 支持 || [Feature]: GRAVATAR_STR SHA256 support

### ISSUE THREAD

**Issue by SamuNatsu** [walinejs/waline#2487]
### 功能概述 | Describe the feature

现在 Gravatar API 使用 SHA256 作为邮箱哈希计算，MD5 哈希已经弃用，是否可以在 GRAVATAR_STR 中支持 SHA256 过滤器？

---
### Feature Overview | Describe the feature

Now that Gravatar API uses SHA256 for mailbox hash calculation and MD5 hashing has been deprecated, is it possible to support SHA256 filter in GRAVATAR_STR?

**Comment by lizheming** [comment]
https://waline.js.org/reference/server/config.html#avatarurl-comment 你可以通过 avatarUrl 这个配置自定义函数来实现你的需求，或者也可以提个 PR 在这里添加下 sha256 的支持 https://github.com/walinejs/waline/blob/main/packages/server/src/service/avatar.js#L8，这两种方案都是可以的。
