### ISSUE TITLE
[Bug]: Fail to deploy on Vercel - dist folder missing?

### ISSUE THREAD

**Issue by hirako2000** [walinejs/waline#2498]
### 问题描述 | Describe the bug

Following the steps to deploy on Vercel:
```
Error: No Output Directory named "dist" found after the Build completed. You can configure the Output Directory in your Project Settings.
21:05:38.400 | Learn More: https://vercel.link/missing-public-directory
21:05:40.818
```

<br class="Apple-interchange-newline">

### 问题网站 | Website URL

https://perdu.org

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
是按照 https://waline.js.org/guide/get-started/ 教程来的么，我试了下是正常的，没有复现你这个问题。

**Comment by hirako2000** [comment]
> 是按照 https://waline.js.org/guide/get-started/ 教程来的么，我试了下是正常的，没有复现你这个问题。
> 
> Did you follow the tutorial at https://waline.js.org/guide/get-started/? I tried it and it was normal and did not reproduce your problem.

Yes I followed those steps.

Worth noting: Vercel detects this repo as a Vite project automatically.

**Comment by hirako2000** [comment]
thanks for your help @lizheming  creating the project via this link did work.

So here is the issue, if you create the project via the create project on Vercel, it automatically detect it as a Vite project (due to the vite config file in the repo). This makes Vercel set some default project settings which make the build fail.

Worth showing this on the Getting Started as it is a mystery whether users should override build commands or not.

<img width="851" alt="waline-f - Overview – Vercel 🔊 2024-05-12 18-29-04" src="https://github.com/walinejs/waline/assets/1500712/dedfe9d0-6591-4546-8b1c-db36cc759c17">

**Comment by hirako2000** [comment]
I confirm the build indeed is functional, this issue is not a bug thus can be closed.

**Comment by lizheming** [comment]
Yes, because waline project template is not on the repo's root path, so we can't create project directly with create button at the vercel. That's why I check did you created repo with the official tutorial, and we has a create button to users create project quickly.

![image](https://github.com/walinejs/waline/assets/424491/3866db4f-e611-479a-b597-7afb576cef63)
