### ISSUE TITLE
[Bug]: QQ邮件登陆后后台出现乱码，且发件退件 || [Bug]: After logging in to QQ mail, garbled characters appear in the background and the mail is returned.

### ISSUE THREAD

**Issue by awaae001** [walinejs/waline#2500]
### 问题描述 | Describe the bug

使用QQ登录的用户无法正常获取用户电子邮件
![image](https://github.com/walinejs/waline/assets/108462724/ce4373eb-407f-46a3-95ea-6fdb0d46eadd)

### 问题网站 | Website URL

https://waline.m-c.top/

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

MySQL

---
### Problem description | Describe the bug

Users who log in using QQ cannot obtain user emails normally
![image](https://github.com/walinejs/waline/assets/108462724/ce4373eb-407f-46a3-95ea-6fdb0d46eadd)

### Question Website | Website URL

https://waline.m-c.top/

### Where is the service deployed? | Where your waline deploy?

Docker

### Where is the data stored? | Where your comment data store?

MySQL

**Comment by lizheming** [comment]
用户使用 QQ 登录，由于没有办法获取到 QQ 用户的邮箱信息，所以会在后台根据 UID 伪造一个邮箱名称，用于保持账号系统的全局唯一。
https://github.com/walinejs/waline/blob/main/packages/server/src/controller/oauth.js#L78-L80

这种用户，后台代码有做判断，是不会给它发邮件通知的。
https://github.com/walinejs/waline/blob/main/packages/server/src/service/notify.js#L523-L530

**Comment by awaae001** [comment]
> 用户使用 QQ 登录，由于没有办法获取到 QQ 用户的邮箱信息，所以会在后台根据 UID 伪造一个邮箱名称，用于保持账号系统的全局唯一。 https://github.com/walinejs/waline/blob/main/packages/server/src/controller/oauth.js#L78-L80
> 
> 这种用户，后台代码有做判断，是不会给它发邮件通知的。 https://github.com/walinejs/waline/blob/main/packages/server/src/service/notify.js#L523-L530
> 
> Users log in using QQ. Since there is no way to obtain the QQ user's email information, an email name will be forged based on the UID in the background to maintain the global uniqueness of the account system. https://github.com/walinejs/waline/blob/main/packages/server/src/controller/oauth.js#L78-L80
> 
> For this kind of user, the background code will make a judgment and will not send them an email notification. https://github.com/walinejs/waline/blob/main/packages/server/src/service/notify.js#L523-L530

那该如何让它可以获取到电子邮件？

**Comment by lizheming** [comment]
QQ 登录用户无法获取到电子邮件地址，这是 QQ 那边的限制，没有办法。
