### ISSUE TITLE
[Feature]: 能支持从环境变量指定端口吗 || [Feature]: Can the port be specified from the environment variable?

### ISSUE THREAD

**Issue by lijc210** [walinejs/waline#2508]
### 功能概述 | Describe the feature

因为要从 docker 启动，在腾讯云函数环境下，应用必须要以 9000 端口启动

---
### Feature Overview | Describe the feature

Because it needs to be started from docker, in the Tencent Cloud function environment, the application must be started with port 9000

**Comment by lizheming** [comment]
你是怎么启动的呀，Docker 不是可以映射端口么？

**Comment by lijc210** [comment]
腾讯云函数的镜像部署，需要应用本身使用 9000，所以需要waline支持从环境变量指定端口

**Comment by lizheming** [comment]
如果是直接用 `docker run` 命令启动的话可以使用 `docker run lizheming/waline --entrypoint 9000` 来自定义端口，如果不是的话暂时没有办法。建议去腾讯那边提下工单，强制使用 9000 听起来也是比较奇怪的设定。

**Comment by lijc210** [comment]
![1716168834762](https://github.com/walinejs/waline/assets/10651081/5cd22fe2-b560-4c6f-b0e0-e32a17c27808)

腾讯云函数镜像部署确实要求这个，是挺奇怪，不过docker 应用支持从环境变量指定端口也很常见

**Comment by lizheming** [comment]
Docker 应用支持从环境变量指定端口这个需求不太常见的，主要是因为 Docker 应用最终暴露的端口可以自己做映射，所以基本不会管应用内的端口。建议你再和腾讯那边提下工单。

**Comment by Ran-Xing** [comment]
其实不需要用docker的，我仓库有一份example，你可以参考下

**Comment by Ran-Xing** [comment]
@lizheming 我这个仓库能上咋的文档那哥哥

https://github.com/Ran-Xing/Waline-tencent-scf

readme写了，但是没上传

顺便问下，加端口号就能自定义端口了吗？
