### ISSUE TITLE
[Bug]: Prior submitted comment isn't clearing from comment form

### ISSUE THREAD

**Issue by ScootRay** [walinejs/waline#2521]
### 问题描述 | Describe the bug

Hi, after submitting a comment on a post, the comment doesn't clear out of the form in subsequent submissions. I.e. it keeps the name, website, and email as proper but it also includes the original submitted comment in the box so I have to manually clear it each time. 

How can I fix this? 

Thank you!
Ray

### 问题网站 | Website URL

https://noggin.alongtheray.com/about

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
same problem as https://github.com/walinejs/waline/issues/2371. it's a bug for waline, we'll fix it in later version, thx for reporting it~

**Comment by ScootRay** [comment]
Ah gotcha. Apologies for that - tried searching but only in English. 

Thank you as always,
Ray

**Comment by ScootRay** [comment]
Ah gotcha. Apologies for that - tried searching but only in English. 

Thank you as always,
Ray

**Comment by lizheming** [comment]
It desn't matter. Although we have translate all issue actions to english automatically, it still have some difficult for non chinese user. So if you have any problem with waline, don't hesitate, just post a new issue! I'll give a reply asap. We really hope you can like waline.

**Comment by ScootRay** [comment]
Am loving it so far! I've already told other Blot.im users to try it. 

Thanks again,
Ray
