### ISSUE TITLE
[Bug]: 使用 zeabur 部署后评论/登录后台会提示：Not initialized

### ISSUE THREAD

**Issue by LenChou95** [walinejs/waline#2529]
### 问题描述 | Describe the bug

使用 zeabur 部署后评论/登录后台会提示：Not initialized

### 问题网站 | Website URL

https://waline.imzl.com/

### 服务部署在哪里？ | Where your waline deploy?

Zeabur

### 数据存储在哪里？| Where your comment data store?

MongoDB

**Comment by LenChou95** [comment]
参考的是该文档操作：https://waline.js.org/guide/deploy/zeabur.html

**Comment by LenChou95** [comment]
> 浏览器不识别walin.min.js里的 export
> 
> The browser does not recognize export

请问该如何解决？

**Comment by chjiyun** [comment]
用waline.umd.min.js

**Comment by LenChou95** [comment]
用 zeabur 模版部署改不了这个，是不是可以考虑更新 https://waline.js.org/guide/deploy/zeabur.html

**Comment by LenChou95** [comment]
![CleanShot 2024-06-03 at 07 02 26@2x](https://github.com/walinejs/waline/assets/3508855/3d2c52d2-c4b3-4208-a1b4-c2207e8a70c0)
![CleanShot 2024-06-03 at 07 03 07](https://github.com/walinejs/waline/assets/3508855/3b3ec26e-9920-43cc-9ff9-d8cc7f51c7fa)

调整后打开博客页面，评论部分直接为空

**Comment by lizheming** [comment]
zeabur 修改了环境变量名称，已重新适配，可以重新走下流程再试试。
