### ISSUE TITLE
[Feature]: 1. 建议把邮件提示这个功能做成可以在后台修改的样式 2. 优化一下图片上传 || [Feature]: 1. It is recommended that the email reminder function be made into a style that can be modified in the background 2. Optimize image uploading

### ISSUE THREAD

**Issue by FrederickBun** [walinejs/waline#2554]
### 1. 邮件
邮件上传功能一直都有，但是不够全面，希望在后台添加邮件编辑框（支持HTML）
### 2. 图片
图片上传可以支持自定义图床等，更方便一些

---
### 1. Email
The email upload function has always been available, but it is not comprehensive enough. I hope to add an email editing box in the background (supports HTML)
### 2. Pictures
Image upload can support custom image beds, etc., which is more convenient

**Comment by FrederickBun** [comment]
其实何止是这些功能需要在后台添加，其实所有需要靠yaml文件去完成的配置都可以展现在管理面板中，就像twikoo一样方便，也对代码小白比较友好。所以希望作者能够重视这个问题

**Comment by FrederickBun** [comment]
此issue与 #2553 联合发表，希望作者能够在用户在前端交互方面能够有更好的体验

**Comment by lizheming** [comment]
1. 我们适配的都是一些免费的 Serverless 数据库场景，这些场景对读取次数有免费额度要求。使用环境变量的方式，能降低数据库读取次数。
2. 邮件模板编辑，这个其实可以找一些第三方在线服务使用，官方暂时可能还没有精力加这个
3. 图片上传是可以自定义图床的 https://waline.js.org/cookbook/customize/upload-image.html

**Comment by FrederickBun** [comment]
那就希望你们能把文档写的更详细些，要不然简短文字加代码真的看着吃力

**Comment by lizheming** [comment]
这个没问题的。不过不同的人有不同的视角，文档已经尽我自己所能详细了。如果觉得有不详细的地方，可以提 issue 单独再咨询后帮忙补充到文档中
