### ISSUE TITLE
[Bug]: 评论区登录后，头像显示错乱的问题 || [Bug]: After logging in to the comment area, the avatar is displayed incorrectly

### ISSUE THREAD

**Issue by pydaxing** [walinejs/waline#2565]
### 问题描述 | Describe the bug

评论区登录后，头像显示错乱的问题，这是什么原因导致的

![20240618152520](https://github.com/walinejs/waline/assets/129026999/86808ff8-6a68-4c33-b928-8eee75a59aca)

### 问题网站 | Website URL

https://lengm.cn

### 服务部署在哪里？ | Where your waline deploy?

Netlify

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

After logging in to the comment area, the avatar is displayed incorrectly. What is the reason for this?

![20240618152520](https://github.com/walinejs/waline/assets/129026999/86808ff8-6a68-4c33-b928-8eee75a59aca)

### Question Website | Website URL

https://lengm.cn

### Where is the service deployed? | Where your waline deploy?

Netlify

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
![image](https://github.com/walinejs/waline/assets/424491/b4e39fc6-8150-4145-9a37-c5975ba4c113) 自己网站的样式覆盖自己处理下。
