### ISSUE TITLE
[Bug]: 最新版未在登录完成后刷新 || [Bug]: The latest version is not refreshed after the login is completed.

### ISSUE THREAD

**Issue by felixesintot** [walinejs/waline#2582]
### 问题描述 | Describe the bug

以前都很正常，更新完了以后，刚登陆管理账号变成这样：
![image](https://github.com/walinejs/waline/assets/98651799/98e2b84b-0a67-4d57-ad75-337dd64457d4)
刷新整个页面才会变成这样：
![image](https://github.com/walinejs/waline/assets/98651799/7a05cc07-c022-462c-9eae-ec6f07661390)

### 问题网站 | Website URL

https://waline.felixesintot.top/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

It used to be normal. After the update, when I first log in to manage the account, it looks like this:
![image](https://github.com/walinejs/waline/assets/98651799/98e2b84b-0a67-4d57-ad75-337dd64457d4)
Refresh the entire page and it will look like this:
![image](https://github.com/walinejs/waline/assets/98651799/7a05cc07-c022-462c-9eae-ec6f07661390)

### Question Website | Website URL

https://waline.felixesintot.top/

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
#2422 很早就反馈过了，这个不是一个必现的问题，我们还在跟进中，可以关注下 2422 issue，这个 issue 我先关闭了。
