### ISSUE TITLE
[Bug]: 导入TiDB 的 SQL 数据只有 wl_Users 数据表 || [Bug]: The SQL data imported into TiDB is only the wl_Users data table

### ISSUE THREAD

**Issue by AkarinLiu** [walinejs/waline#2585]
### 问题描述 | Describe the bug

复制 TiDB 的 SQL 脚本后，导入只有 wl_Users 数据表，其他的数据表没有创建成功。

### 问题网站 | Website URL

https://tidbcloud.com/console/clusters/10072868295899316623/sqleditor?orgId=1372813089209232624&projectId=1372813089454550142

### 服务部署在哪里？ | Where your waline deploy?

Other

### 数据存储在哪里？| Where your comment data store?

TiDB

---
### Problem description | Describe the bug

After copying the TiDB SQL script, only the wl_Users data table was imported, and other data tables were not created successfully.

### Question Website | Website URL

https://tidbcloud.com/console/clusters/10072868295899316623/sqleditor?orgId=1372813089209232624&projectId=1372813089454550142

### Where is the service deployed? | Where your waline deploy?

Other

### Where is the data stored? | Where your comment data store?

TiDB

**Comment by lizheming** [comment]
TiDB 的 SQL 执行只能执行光标所在的当前行，所以你需要按行执行下才行。

**Comment by AkarinLiu** [comment]
现在可以了，我全选代码后就行。

邮件来自 Outlook for Windows
________________________________
发件人: Austin Lee ***@***.***>
发送时间: 2024年6月27日 18:58
收件人: walinejs/waline ***@***.***>
抄送: 阿卡林刘 ***@***.***>; Author ***@***.***>
主题: Re: [walinejs/waline] [Bug]: 导入TiDB 的 SQL 数据只有 wl_Users 数据表 || [Bug]: The SQL data imported into TiDB is only the wl_Users data table (Issue #2585)


TiDB 的 SQL 执行只能执行光标所在的当前行，所以你需要按行执行下才行。

________________________________

TiDB's SQL execution can only execute the current row where the cursor is located, so you need to execute it row by row.

―
