### ISSUE TITLE
[Bug]: Waline2.5.18前端无法显示评论信息，评论数统计插件显示为0 || [Bug]: Waline2.5.18 front-end cannot display comment information, and the comment number statistics plug-in displays 0

### ISSUE THREAD

**Issue by elkan1788** [walinejs/waline#2591]
### 问题描述 | Describe the bug

在收到用户的评论后，访问管理后台是可以正常查看到评论信息，但在页面前端却不能正常显示。F12查看了后台waline请求路径，发现都是正常的200响应。

1.后台评论显示
![后台管理](https://github.com/walinejs/waline/assets/1217096/7cd5b9b3-08fe-41d5-a2f5-fcb77f7f2de4)

2.评论插件显示
![评论插件](https://github.com/walinejs/waline/assets/1217096/7bb6f0d6-f5c4-4e6a-b67f-85193485010b)

3.评论内容显示
![评论内容](https://github.com/walinejs/waline/assets/1217096/3547837e-0566-4563-8cee-f454c0136473)

### 问题网站 | Website URL

https://lisenhui.cn/tech/how-to-restart-wsl2.html

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

After receiving the user's comments, the comment information can be viewed normally when accessing the management backend, but it cannot be displayed normally on the front end of the page. F12 checked the background waline request path and found that they were all normal 200 responses.

1. Backstage comment display
![Backend management](https://github.com/walinejs/waline/assets/1217096/7cd5b9b3-08fe-41d5-a2f5-fcb77f7f2de4)

2. Comment plug-in display
![Comment plug-in](https://github.com/walinejs/waline/assets/1217096/7bb6f0d6-f5c4-4e6a-b67f-85193485010b)

3. Comment content display
![Comment content](https://github.com/walinejs/waline/assets/1217096/3547837e-0566-4563-8cee-f454c0136473)

### Question Website | Website URL

https://lisenhui.cn/tech/how-to-restart-wsl2.html

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by elkan1788** [comment]
感觉和这个关系不影响不大，使用API工具调试获取都是正常的，就是在站点中调用会出现这样的问题。
![image](https://github.com/walinejs/waline/assets/1217096/780e696c-4d05-4adb-90fb-8da2b1567617)

现有个点更奇怪，就是明明把那些测试的数据都删除了，结果还是在页面中会出现，切换为浏览器隐身模式也还是一样，这里现就只有2条评论。
![image](https://github.com/walinejs/waline/assets/1217096/22cafa3e-1cc7-4102-8a58-ac3ffd482765)
![image](https://github.com/walinejs/waline/assets/1217096/31882fe3-762a-4298-ad9d-54985757b16c)
![image](https://github.com/walinejs/waline/assets/1217096/3ddbec73-c645-486b-90af-a84fb173bfa5)

**Comment by lizheming** [comment]
应该就是编码的问题，如果你自己处理不了建议换一个唯一字段吧，不要用 pathname

**Comment by elkan1788** [comment]
处理是可以处理的，只是可以明确和编码应该没有问题，因为在后台就只找到2条记录(直接使用路径的wsl2作为关键检索)，但为何上面会显示出来6条评论数据呢？
![leancloud comment](https://github.com/walinejs/waline/assets/1217096/c6ed250d-11b0-44c2-8c7c-49167182f6dc)

**Comment by lizheming** [comment]
用这个`%2Ftech%2Fhow-to-restart-wsl2.html`值再搜索下

**Comment by elkan1788** [comment]
试过的，没有找搜索到数据。另外也观察到页面的浏览次数统计是正常的，这也是使用url做唯一处理的吧。
![image](https://github.com/walinejs/waline/assets/1217096/5d85a3eb-87c3-4b6a-bcea-29c364f65826)

直接搜索 %2F 也是没有找到相关的数据
![image](https://github.com/walinejs/waline/assets/1217096/9ec66ccc-a608-4447-8277-bf95f51875b6)

**Comment by lizheming** [comment]
要不你导出一份数据发我邮箱吧，我查下问题看看

**Comment by elkan1788** [comment]
已导出发送到你的QQ邮箱，劳烦帮忙看看，谢谢。

**Comment by lizheming** [comment]
你是不是自己换了什么数据库自己忘记掉了，我看你页面上展示的内容，在你发我导出的文件里，根本搜不到啊。

<img width="1791" alt="image" src="https://github.com/walinejs/waline/assets/424491/940eb4ab-a8e2-4760-9c37-88be87aabecb">
<img width="1789" alt="image" src="https://github.com/walinejs/waline/assets/424491/1b921c4c-b4f6-40ef-9e64-d1a075d1a9eb">

而且从你的截图里看评论列表也很奇怪，一会儿是问有没有收到邮件通知的评论，一会儿是讨论 CDN 屏蔽的评论。这两个都对应着一个页面，但是数据又不一样。

**Comment by elkan1788** [comment]
没有换数据库哦，一直就是使用的leancloud数据存储方式。之前发的那些测试评论已经删除了，只保留了网友有关于CDN屏蔽的讨论。所以这个`how-to-restart-wsl2.html`页面只有2条记录。

![comments](https://private-user-images.githubusercontent.com/1217096/345258330-c6ed250d-11b0-44c2-8c7c-49167182f6dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNDIxNzEsIm5iZiI6MTcyMDE0MTg3MSwicGF0aCI6Ii8xMjE3MDk2LzM0NTI1ODMzMC1jNmVkMjUwZC0xMWIwLTQ0YzItOGM3Yy00OTE2NzE4MmY2ZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDVUMDExMTExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGMxMGE5MjY0OWMxZDI0NzYzYTY2ZTc4YTI4MjcxNjk2OWY4NThkOWE2NzMyMTVhZTgzZWY3YzAzOTNmNjc0ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gXOP2mU0AlTXnscwYgaosSRl2rbvq3ugb_e0BCKqvx0)

自己也测试了好久，似乎和缓存有关系啦，用新的设备访问确实是看不出问题来的。😂

**Comment by lizheming** [comment]
1. 接口的数据，和缓存没有关系应该。这个得需要你自己排查下，给我的数据和线上有问题的数据不一致，这块我没办法继续跟进排查。
2. 登录的问题我好像发现点问题，你的网站域名是不是设置了什么未知 referrer 跳转屏蔽的逻辑，目前看第三方登录相关的都会因为这个跪掉。

**Comment by elkan1788** [comment]
好的，谢谢**Austin**大神，后续我再观察一下。

**Comment by elkan1788** [comment]
@lizheming  有什么办法在count和comment请求时，在URL后面添加个自定义参数呢？比如ts=1720159903

**Comment by lizheming** [comment]
可以自己自定义客户端实现。

**Comment by elkan1788** [comment]
有没可参考的案例学习下，在手册上似乎没有找到这部分的说明，谢谢。

**Comment by lizheming** [comment]
你这个是比较定制化的功能了，需要自己研究下了。

**Comment by elkan1788** [comment]
好的，回头了解一下。

**Comment by lizheming** [comment]
目前来看，这个 issue 应该和你做了 CDN 缓存有点关系。如果是你把接口做了 CDN 化的话。个人建议你增加下 postSave 的钩子，发布评论后调 CDN 的接口清空缓存，应该也可以的。

**Comment by elkan1788** [comment]
也不清楚具体什么情况，如果说是CDN缓存的话，那文章浏览次数统计应该也是会触发才是，但它又是正常的。就只是评论内容相关的接口有缓存现象，所以有点懵圈。
