### ISSUE TITLE
[Bug]: 名字，邮件，和网页部分显示undefined，右下角有白色和绿色框但无文字 || [Bug]: The name, email, and web page parts are displayed as undefined. There are white and green boxes in the lower right corner but no text.

### ISSUE THREAD

**Issue by carrieeex** [walinejs/waline#2596]
### 问题描述 | Describe the bug

按照官网步骤deploy完以后点开url预览，发现各项名字都undefined，右下角登陆什么的也没显示，如下图：
<img width="825" alt="Screenshot 2024-07-05 at 8 25 11 PM" src="https://github.com/walinejs/waline/assets/59303880/f199738c-a3ec-44b8-b388-19109a71a56f">

### 问题网站 | Website URL

https://carrieeex.github.io/2022/02/20/hello-world/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

After deploying according to the official website steps, click on the URL preview and find that all the names are undefined, and nothing about login is displayed in the lower right corner, as shown below:
<img width="825" alt="Screenshot 2024-07-05 at 8 25 11PM" src="https://github.com/walinejs/waline/assets/59303880/f199738c-a3ec-44b8-b388-19109a71a56f ">

### Question Website | Website URL

https://carrieeex.github.io/2022/02/20/hello-world/

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
https://github.com/walinejs/waline/issues/2379 应该和这个是一个问题，上周已修复。可以等下一个版本发布，再次之前你可以通过手动设置语言来规避这个问题。

**Comment by carrieeex** [comment]
好的，谢谢！我先换成twikoo了😂
