### ISSUE TITLE
[Bug]: 邮件通知无法生效 || [Bug]: Email notification cannot take effect

### ISSUE THREAD

**Issue by cjqts** [walinejs/waline#2617]
### 问题描述 | Describe the bug

邮件通知无法生效
![image](https://github.com/user-attachments/assets/463a0f37-d2e7-4e95-93f0-36f629d097e8)
配置如图
![image](https://github.com/user-attachments/assets/272b4d19-60fb-44d2-9aef-acd057fbce90)
日志如图
![image](https://github.com/user-attachments/assets/1d54aa7b-0740-4ae2-ad1e-2eff90df9026)

### 问题网站 | Website URL

dimzone.cn & waline.dimzone.cn

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

Email notification cannot take effect
![image](https://github.com/user-attachments/assets/463a0f37-d2e7-4e95-93f0-36f629d097e8)
The configuration is as shown in the figure
![image](https://github.com/user-attachments/assets/272b4d19-60fb-44d2-9aef-acd057fbce90)
The log is as shown in the figure
![image](https://github.com/user-attachments/assets/1d54aa7b-0740-4ae2-ad1e-2eff90df9026)

### Question Website | Website URL

dimzone.cn & waline.dimzone.cn

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
邮件通知的问题可以自行排查下。

需要注意，如果是用 AUTHOR_EMAIL 去做评论的话，或者如果回复的评论是 AUTHOR_EMAIL 的评论的话，都是没有新评论通知的。

剩下的就是你需要看下发布评论时后台的 `/comment` 那个接口的日志，查看详细的邮件通知服务返回的信息。
