### ISSUE TITLE
[Bug]: 邮件通知不生效 || [Bug]: Email notification does not take effect

### ISSUE THREAD

**Issue by ilusymon** [walinejs/waline#2618]
### 问题描述 | Describe the bug

配置如下：
![image](https://github.com/user-attachments/assets/c0703330-0e2a-48e8-a5a9-070cd800e8db)

日志如下：
![image](https://github.com/user-attachments/assets/9d72a87c-c802-49fe-a868-89827e3a6563)

### 问题网站 | Website URL

https://waline.nsyue.com/

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

MySQL

---
### Problem description | Describe the bug

The configuration is as follows:
![image](https://github.com/user-attachments/assets/c0703330-0e2a-48e8-a5a9-070cd800e8db)

The log is as follows:
![image](https://github.com/user-attachments/assets/9d72a87c-c802-49fe-a868-89827e3a6563)

### Question Website | Website URL

https://waline.nsyue.com/

### Where is the service deployed? | Where your waline deploy?

Docker

### Where is the data stored? | Where your comment data store?

MySQL

**Comment by lizheming** [comment]
可以换个其他的邮箱服务试试，初步看了下没什么问题
