### ISSUE TITLE
[Bug]: 快速点击 like 导致数据异常 || [Bug]: Clicking like quickly causes data anomaly

### ISSUE THREAD

**Issue by Raincarnator** [walinejs/waline#2626]
### 问题描述 | Describe the bug

快速点击评论的 like 按钮会导致一次性点多个赞或扣多个赞，在前端甚至会产生负数。需要加个锁。

### 问题网站 | Website URL

blog.reincarnatey.net

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

Quickly clicking the like button of a comment will result in multiple likes or deductions at once, and may even produce a negative number on the front end. Need to add a lock.

### Question Website | Website URL

blog.reincarnatey.net

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
点赞和文章反应，以及浏览量等纯计数的能力，预期就是给网站增加氛围的，所以当时没有想做的很重，就是一个单纯的计数就好了。你说的这些问题其实都是已知的，暂时不打算通过锁的方式去修复。目前应该是增加了一个前端接口请求中点击无效的操作（不确定有没有）去规避下这个问题。另外就是很多 serverless 的数据库也没有锁的能力~
