### ISSUE TITLE
[Feature]: Disable base64 image upload

### ISSUE THREAD

**Issue by zhuozhiyongde** [walinejs/waline#2633]
### 功能概述 | Describe the feature

如题，希望允许禁用直接图片上传，但是允许 md 语法的外链图床。

base64 上传图片比较容易占满免费的数据库额度，个人觉得不太合适。

---
### Feature Overview | Describe the feature

As the title states, I hope to allow direct image uploading to be disabled, but allow external link image beds with md syntax.

It is easier to upload images to base64 to fill up the free database quota, but I personally think it is not suitable.

**Comment by track23** [comment]
```js
const waline = init({
  imageUploader: false,
})
```

**Comment by zhuozhiyongde** [comment]
草 我的问题，抱歉，没认真看文档
