### ISSUE TITLE
[Bug]: 连接mysql8.4客户端异常 || [Bug]: Exception when connecting to mysql8.4 client

### ISSUE THREAD

**Issue by wxywizard** [walinejs/waline#2640]
## 连接mysql8.4客户端异常
![CleanShot 2024-08-01 at 18 17 48@2x](https://github.com/user-attachments/assets/cd259774-0308-4527-b441-7113337b18ad)
希望升级下客户端

### 问题网站 | Website URL

https://togowill.com

### 服务部署在哪里？ | Where your waline deploy?

Self Host

### 数据存储在哪里？| Where your comment data store?

MySQL

---
## Abnormal connection to mysql8.4 client
![CleanShot 2024-08-01 at 18 17 48@2x](https://github.com/user-attachments/assets/cd259774-0308-4527-b441-7113337b18ad)
Hope to upgrade the client

### Question Website | Website URL

https://togowill.com

### Where is the service deployed? | Where your waline deploy?

Self Host

### Where is the data stored? | Where your comment data store?

MySQL

**Comment by lizheming** [comment]
https://github.com/walinejs/waline/issues/2119

**Comment by lizheming** [comment]
https://github.com/thinkjs/thinkjs/issues/1354 我们使用的底层框架还不支持这块，底层框架使用的场景比较多，不太好贸然更换底层连接器。之后我们按照你的建议处理下。
