### ISSUE TITLE
[Bug]: 在vercel部署后，注册时显示500: Not initialized || [Bug]: After vercel deployment, 500: Not initialized is displayed during registration.

### ISSUE THREAD

**Issue by YunFeng86** [walinejs/waline#2653]
### 问题描述 | Describe the bug

<img width="1274" alt="2024-08-08 121246" src="https://github.com/user-attachments/assets/8fec5d08-5cbb-4914-afe7-2e062ef16375">
<img width="155" alt="image" src="https://github.com/user-attachments/assets/58036d07-0df7-447c-9318-6c8b66ae84b0">

### 问题网站 | Website URL

https://walien-e7.yfblog.site/ui/register

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

<img width="1274" alt="2024-08-08 121246" src="https://github.com/user-attachments/assets/8fec5d08-5cbb-4914-afe7-2e062ef16375">
<img width="155" alt="image" src="https://github.com/user-attachments/assets/58036d07-0df7-447c-9318-6c8b66ae84b0">

### Question Website | Website URL

https://walien-e7.yfblog.site/ui/register

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
环境变量配置了之后需要重新部署一下，你重新部署下再看看。

**Comment by YunFeng86** [comment]
已重新部署，但仍在注册时报错：500: Not initialized

**Comment by lizheming** [comment]
名字写错了
![image](https://github.com/user-attachments/assets/70cf40c7-86fe-45e1-ab94-0afceda4065f)
