### ISSUE TITLE
[Feature]: 数据库导入的sql文件添加索引优化 || [Feature]: Add index optimization to the sql file imported from the database

### ISSUE THREAD

**Issue by axiaoxin** [walinejs/waline#2665]
### 功能概述 | Describe the feature

看了一下日志，有很多查询貌似都没有索引。
数据量大了以后性能会有影响，计数表和评论表里面url字段可以加前缀索引，或者做成固定长度的hash然后见唯一索引（需要改代码逻辑）

---
### Feature Overview | Describe the feature

After looking at the logs, it seems that many queries are not indexed.
Performance will be affected when the amount of data is large. The URL field in the count table and comment table can be added with a prefix index, or it can be made into a fixed-length hash and then used as a unique index (the code logic needs to be changed)

**Comment by axiaoxin** [comment]
另外，在保存url的时候还应该先对url的结构做一个标准化，比如在集成了Google搜索的页面上：

https://my-domain.com/page/#gsc.tab=0 和 https://my-domain.com/page/ 其实是同一个页面

这种会导致同一个页面有时候有评论，有时候又没有评论

**Comment by lizheming** [comment]
是个不错的建议，也欢迎 PR 呀~

**Comment by lizheming** [comment]
https://github.com/walinejs/waline/pull/2803 已处理
