### ISSUE TITLE
[建议] css分离或者自定义css开关

### ISSUE THREAD

**Issue by MaxChang3** [walinejs/waline#268]
新版更新后css样式有些改动，之前一直通过引用外部css的方式覆盖样式来达到自定义样式的效果，于是失效了。
不知道有没有打算分离出css文件或者加一个自定义css的开关呢

**Comment by lizheming** [comment]
可以，之后修改下打包脚本增加一下吧

**Comment by Mister-Hope** [comment]
- 新版CSS重构的目的就是使现有的CSS更容易做配置。

- 捆绑CSS主要是考虑到cdn引入的简便性。



的确可以做一个js和CSS分离的版本，不过我觉得没有必要。因为样式重构很大概率会伴随着HTML结构的一些微调。

调整自己维护的一套CSS适配当前结构付出的成本很多情况可能会大于在原有的基础上使用更高权重的选择器自行覆盖。

**Comment by Mister-Hope** [comment]
@lizheming  

RFC here. I totally disagree we need this feature. Here are some points:

- Nearly no `important!` selector is used in style, so people can easily overide them or unset them (`xxx: unset`)

- A set of css variables is provided to take better control of the appearance. 

- The generated dom is uneditable which means users can only adjust some of the appearance with the layout unchanged. Which means there are no great meanings for users to totaly rewrite one themselves.

- DOM structures may changed when shiping new features. And in that way, a fully custom version can be hard to migrate comparing with a small version overiding the current CSS.

- One CDN link is definitely better than two

  > From download number between CDN and npm we can find out most people are using CDN, and this may break them
  > Though it has a possiable solution: generating two output in dist with a new split css one

**Comment by Mister-Hope** [comment]
Added in V1 beta
