### ISSUE TITLE
[Bug]: 强制登录在用户前端界面显示上出现问题 || [Bug]: Forced login causes problems in user front-end interface display

### ISSUE THREAD

**Issue by FrederickBun** [walinejs/waline#2680]
### 问题描述 | Describe the bug

本人Waline试用deta部署，在Login这一个环境变量设置了force。强制登录确实启用了但在用户界面上出现了问题

###### 环境变量配置：

<img width="777" alt="image" src="https://github.com/user-attachments/assets/400617e9-b18a-4dbe-ab47-0d95b8613b64">

###### Waline展示出的效果：

<img width="843" alt="image" src="https://github.com/user-attachments/assets/0d09a51a-6e4a-40b3-99bd-955b89285581">

###### 未登录发送评论展示出的效果

<img width="1340" alt="Screenshot 2024-08-22 at 10 27 35 PM" src="https://github.com/user-attachments/assets/529a2b4e-9897-4ef2-8def-a2c9d5a8798b">

在所有使用本评论的站点都是这样的，下方提供服务端地址，图片展示为下方地址的评论

然后登录过后是没有任何问题的

### 问题网站 | Website URL

https://comment.setbun.com/

### 服务部署在哪里？ | Where your waline deploy?

Deta

### 数据存储在哪里？| Where your comment data store?

Deta Base

---
### Problem description | Describe the bug

I tried deta deployment in Waline and set force in the Login environment variable. Forced login is indeed enabled but there is a problem with the user interface

###### Environment variable configuration:

<img width="777" alt="image" src="https://github.com/user-attachments/assets/400617e9-b18a-4dbe-ab47-0d95b8613b64">

###### The effect shown by Waline:

<img width="843" alt="image" src="https://github.com/user-attachments/assets/0d09a51a-6e4a-40b3-99bd-955b89285581">

###### The effect of sending comments without logging in

<img width="1340" alt="Screenshot 2024-08-22 at 10 27 35PM" src="https://github.com/user-attachments/assets/529a2b4e-9897-4ef2-8def-a2c9d5a8798b">

This is the case on all sites that use this comment. The server address is provided below, and the picture shows the comment at the address below.

Then after logging in, there will be no problems.

### Question Website | Website URL

https://comment.setbun.com/

### Where is the service deployed? | Where your waline deploy?

Deta

### Where is the data stored? | Where your comment data store?

Deta Base

**Comment by lizheming** [comment]
https://waline.js.org/reference/client/props.html#login 强制登录前后端都需要配置下，前端需要配置下隐藏直接登录的按钮。

**Comment by FrederickBun** [comment]
好的（官方建议有精力的话适配一下谢谢）
