### ISSUE TITLE
[Bug]: 人机验证会成为刷评论的原因 || [Bug]: Human-machine verification will become the reason for brushing comments

### ISSUE THREAD

**Issue by FrederickBun** [walinejs/waline#2681]
### 问题描述 | Describe the bug

本人在捣鼓自己评论的时候，发现了这样的现象：

<img width="1216" alt="image" src="https://github.com/user-attachments/assets/e3b76529-34cf-4764-b708-9a702ddffb8c">

因为Waline按 Command/Control + Enter 会发送，而又人机验证的时候就会按几次有几个人机验证，而此时输入框还有内容，所以每一次人机验证完成都会带内容发送，一次完成这些人机验证之后将会发送很多消息从而达到刷屏

https://github.com/user-attachments/assets/8f7c7696-40a6-401a-9cc5-ff856aac6afd

后台就会出现这样的惨状

建议修复为人机验证完成前不允许发送过多消息

如果没有人机验证，那么也有可能因为卡顿而导致刷屏（差不多意思，只是说那个刷的少些）

> [!NOTE]
> 本人仅在自己的Waline上实验，未对其他用户造成攻击

> [!WARNING]
> 在BUG修复前，请熊孩子不要捣乱

### 问题网站 | Website URL

https://comment.setbun.com/

### 服务部署在哪里？ | Where your waline deploy?

Deta

### 数据存储在哪里？| Where your comment data store?

Deta Base

---
### Problem description | Describe the bug

When I was tinkering with my comments, I discovered this phenomenon:

<img width="1216" alt="image" src="https://github.com/user-attachments/assets/e3b76529-34cf-4764-b708-9a702ddffb8c">

Because Waline presses Command/Control + Enter to send, and during human-computer verification, it will press several times for several human-computer verifications. At this time, the input box still has content, so every time the human-computer verification is completed, the content will be sent. After completing these human-machine verifications at once, many messages will be sent to achieve a refreshed screen.

https://github.com/user-attachments/assets/8f7c7696-40a6-401a-9cc5-ff856aac6afd

There will be such a tragic situation in the background

It is recommended to fix the problem of not allowing too many messages to be sent before human-machine verification is completed.

If there is no human-machine verification, it is possible that the screen will be refreshed due to lag (similar to the same meaning, it just means that the refresh rate is less)

> [!NOTE]
> I only experimented on my own Waline and did not cause any attacks on other users.

> [!WARNING]
> Please don’t cause trouble until the bug is fixed.

### Question Website | Website URL

https://comment.setbun.com/

### Where is the service deployed? | Where your waline deploy?

Deta

### Where is the data stored? | Where your comment data store?

Deta Base

**Comment by lizheming** [comment]
尝试了下，应该属于评论发送过程中的防止重复发送的问题，后续优化下这块。

**Comment by jeremy0519** [comment]
不是有IPQPS吗？
