### ISSUE TITLE
[Bug]: 点击登录后，俺的头像溢出了 || [Bug]: After clicking to log in, my avatar overflowed

### ISSUE THREAD

**Issue by Tasselmi** [walinejs/waline#2698]
### 问题描述 | Describe the bug

**问题1：如图所示，点击登录后，头像就溢出了。我也不知道发生了啥。** 

![Screenshot from 2024-09-01 18-16-30](https://github.com/user-attachments/assets/2fc0fa4e-964d-4752-b468-af9ff0721349)

**问题2：如图所示，刚发表后，发表日期显示的是 1970年1月1日，这个显然是不对的。** 

![73969599](https://github.com/user-attachments/assets/37e0156e-6ec1-4a21-8d54-43fd68037869)

### 问题网站 | Website URL

https://scalapie.com/2024/08/31/%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8B%E9%83%A8%E7%BD%B2%E4%B8%AA%E4%BA%BA%E7%BD%91%E7%AB%99%E4%B8%8A%E7%BA%BF%E4%B9%8B7/

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

PostgreSQL

---
### Problem description | Describe the bug

**Question 1: As shown in the picture, after clicking to log in, the avatar overflows. I don't know what happened either. **

![Screenshot from 2024-09-01 18-16-30](https://github.com/user-attachments/assets/2fc0fa4e-964d-4752-b468-af9ff0721349)

**Question 2: As shown in the picture, after the publication, the publication date was January 1, 1970. This is obviously incorrect. **

![73969599](https://github.com/user-attachments/assets/37e0156e-6ec1-4a21-8d54-43fd68037869)

### Question Website | Website URL

https://scalapie.com/2024/08/31/%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8B%E9%83%A8%E7%BD%B2 %E4%B8%AA%E4%BA%BA%E7%BD%91%E7%AB%99%E4%B8%8A%E7%BA%BF%E4%B9%8B7/

### Where is the service deployed? | Where your waline deploy?

Docker

### Where is the data stored? | Where your comment data store?

PostgreSQL

**Comment by lizheming** [comment]
1. `.post-container img` 你的主题有个样式冲突
2. 发布后的时间问题，晚点有空处理下

**Comment by Tasselmi** [comment]
好的 大佬。谢谢你。第一个冲突我已经通过加入下面的代码解决掉了：
```css
.post-container #waline img {
  margin: 0;
}
```

发布时间的问题你这边修复好后在本帖里面通知我声啊。感恩。
