### ISSUE TITLE
[Bug]: pageview功能无法正常工作 || [Bug]: pageview function does not work properly

### ISSUE THREAD

**Issue by Tasselmi** [walinejs/waline#2702]
### 问题描述 | Describe the bug

按照官网指引进行了pageview在html页面的配置。然后有的页面能正常工作，有的页面无法正常工作。然后自己找了半天也不知道问题出在哪儿。

在这里是正常工作的：[https://scalapie.com/about/](https://scalapie.com/about/)
但是在下面给的博文的正文页面又是不能工作的。

**注： pageview统计显示在页面的底部**

### 问题网站 | Website URL

https://scalapie.com/2024/08/31/%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8B%E9%83%A8%E7%BD%B2%E4%B8%AA%E4%BA%BA%E7%BD%91%E7%AB%99%E4%B8%8A%E7%BA%BF%E4%B9%8B7/

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

PostgreSQL

---
### Problem description | Describe the bug

According to the official website guidelines, the pageview is configured on the html page. Then some pages can work normally, and some pages cannot work properly. Then I searched for a long time and didn't know where the problem was.

It works fine here: [https://scalapie.com/about/](https://scalapie.com/about/)
But the text page of the blog post given below does not work.

**Note: Pageview statistics are displayed at the bottom of the page**

### Question Website | Website URL

https://scalapie.com/2024/08/31/%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8B%E9%83%A8%E7%BD%B2 %E4%B8%AA%E4%BA%BA%E7%BD%91%E7%AB%99%E4%B8%8A%E7%BA%BF%E4%B9%8B7/

### Where is the service deployed? | Where your waline deploy?

Docker

### Where is the data stored? | Where your comment data store?

PostgreSQL

**Comment by lizheming** [comment]
中文编码的问题，所有获取浏览数的地方传入 path 的话要做一次 URL 编码。建议如果搞不明白的，可以把 URL 换成英文，或者换一个其他的唯一字串做 path 即可。

**Comment by Tasselmi** [comment]
> 中文编码的问题，所有获取浏览数的地方传入 path 的话要做一次 URL 编码。建议如果搞不明白的，可以把 URL 换成英文，或者换一个其他的唯一字串做 path 即可。
> 
> The problem with Chinese encoding is that if the path is passed in to all places where the number of views is obtained, URL encoding must be performed. It is recommended that if you don't understand it, you can change the URL to English, or use another unique string as path.

我讲path进行了url encode转换，还是不灵啊。目前都是显示0浏览

**Comment by lizheming** [comment]
`/2024/08/31/%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8B%E9%83%A8%E7%BD%B2%E4%B8%AA%E4%BA%BA%E7%BD%91%E7%AB%99%E4%B8%8A%E7%BA%BF%E4%B9%8B7/` 默认的 path 用的是 `location.pathname`，值的格式是这个，你和这个对齐吧。目前看还是有问题的。

**Comment by Tasselmi** [comment]
搞定，谢啦。又搞定一个重要的功能咯。流量统计搞定咯。
