### ISSUE TITLE
[Bug]: Double-clicking the like button triggers a double operation

### ISSUE THREAD

**Issue by miruchigawa** [walinejs/waline#2710]
### 问题描述 | Describe the bug

I tried testing it on my website, but I encountered an issue where it spams likes or unlikes, causing a double increase or decrease, especially during loading.
![IMG_20240909_112417](https://github.com/user-attachments/assets/ba14739f-17a9-4a1c-bb9c-ddd81501d811)

### 问题网站 | Website URL

https://www.miwudev.xyz

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
got it, I'll check it later
