### ISSUE TITLE
[Bug]: 无法正常使用第三方登录 || [Bug]: Unable to use third-party login normally

### ISSUE THREAD

**Issue by xiatianPE** [walinejs/waline#2741]
### 问题描述 | Describe the bug

不知道何时起，我的评论系统无法通过第三方登录，只有邮箱登录才正常
![Screenshot_20241003_152200](https://github.com/user-attachments/assets/7ad5ec11-0f3f-4fe2-841b-9a59d4622627)

### 问题网站 | Website URL

https://gorgeous-pavlova-d7b2a1.netlify.app/.netlify/functions/comment

### 服务部署在哪里？ | Where your waline deploy?

Netlify

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

I don’t know when, but my comment system cannot be logged in through a third party. It can only be logged in via email.
![Screenshot_20241003_152200](https://github.com/user-attachments/assets/7ad5ec11-0f3f-4fe2-841b-9a59d4622627)

### Question Website | Website URL

https://gorgeous-pavlova-d7b2a1.netlify.app/.netlify/functions/comment

### Where is the service deployed? | Where your waline deploy?

Netlify

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by nirvana6** [comment]
I have the same problem. 

Waline is deployed in vercel, and the db is internatonal leancloud.

**Comment by sysfox** [comment]
@xiatianPE 这玩意儿现在需要自建
https://waline.js.org/reference/server/env.html#%E9%AB%98%E7%BA%A7%E9%85%8D%E7%BD%AE

**Comment by sysfox** [comment]
@xiatianPE 原有的默认oauth服务可能已闭服

**Comment by lizheming** [comment]
那段时间域名解析有点问题，目前已经恢复正常
