### ISSUE TITLE
[BUG] CloudBace 版管理后台不能用

### ISSUE THREAD

**Issue by eallion** [walinejs/waline#277]
**问题描述 | Describe the bug**

CloudBace 版管理后台一直打不开。

**问题网站 | Website URL**

<https://tcb.eallion.com/ui> 
// 在早期版本可以打开……（因为成功注册过。）但是一直很少用后台，最近才发现不能打开。

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [x] CloudBase
- 数据存储在哪里？| Where your comment data store?
  - [x] CloudBase

**Comment by lizheming** [comment]
你去 CloudBase 那边反馈一下吧，这个看起来像是命中到了云存储服务了。个人感觉是 Host 可能发生了变化。官方 DEMO 从 CloudBase 后台拿到的 [地址](https://waline-2gm7vu3aae9513e2-1252157872.ap-shanghai.service.tcloudbase.com/waline/ui) 是可以登录的，但是之前贴在 Github 上的 [地址](https://waline-2gm7vu3aae9513e2-1252157872.tcloudbaseapp.com/ui/) 好像是不行，看起来也像是命中到了云存储找不到文件。

**Comment by eallion** [comment]
<https://eallion-8gkunp4re49bae66-1251347414.ap-shanghai.app.tcloudbase.com/waline/ui/>
这个是原始地址。
![Snipaste_2021-05-22_12-46-47](https://user-images.githubusercontent.com/1698841/119214758-c9323300-bafb-11eb-9748-51c776c925f0.png)

**Comment by L-cw** [comment]
> https://eallion-8gkunp4re49bae66-1251347414.ap-shanghai.app.tcloudbase.com/waline/ui/
> 这个是原始地址。

是不是在这个环境里部署了其他的应用？

**Comment by eallion** [comment]
> 是不是在这个环境里部署了其他的应用？

是的。

**Comment by L-cw** [comment]
> > 是不是在这个环境里部署了其他的应用？
> 
> 是的。

那可能是你的别的应用把 `waline/ui` 当做参数解析了，我之前在环境里部署了一个 rsshub 的应用，也总是有这种重定向，你可以对你环境的其他应用排查下😂

我现在卸载了 rsshub ，但还是有影响，不过直接访问登录链接还是可以进去后台的

**Comment by eallion** [comment]
@L-cw 可能不全是这个原因，开过新环境测试过。

**Comment by L-cw** [comment]
> @L-cw 可能不全是这个原因，开过新环境测试过。

新环境也是一模一样的报错么，新环境的话要注意下是否有免费额度，没有免费额度也没买资源包的话应该也是用不了的😂

**Comment by Mister-Hope** [comment]
此问题印象中有相关PR进行修复。
