### ISSUE TITLE
[Bug]: 导入Twikoo评论时出错 || [Bug]: Error importing Twikoo comments

### ISSUE THREAD

**Issue by sysfox** [walinejs/waline#2776]
### 问题描述 | Describe the bug

使用官方工具转化Twikoo评论后，得到csv文件(已确认目标框选择正确)
在后台导入时，提示: `JSON Parse error: Unexpected identifier "id"`
目标数据库: PostgreSQL

### 问题网站 | Website URL

https://waline.trfox.top

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

PostgreSQL

---
### Problem description | Describe the bug

After using the official tool to convert Twikoo comments, the csv file was obtained (it was confirmed that the target box was selected correctly)
When importing in the background, the prompt: `JSON Parse error: Unexpected identifier "id"`
Target database: PostgreSQL

### Question Website | Website URL

https://waline.trfox.top

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

PostgreSQL

**Comment by lizheming** [comment]
受限于工具实现先后关系，官方的后台暂时还只支持后台导出的内容导入，如果是其他系统的导入，pg 的话需要直接进 pg 数据库中导入官方工具转换出来的 csv 文件
