### ISSUE TITLE
[Bug]: 博客评论报Load failed错误 || [Bug]: Blog comments reported Load failed error

### ISSUE THREAD

**Issue by ayly2341** [walinejs/waline#2786]
### 问题描述 | Describe the bug

我是按操作手册部署的，不过没有绑定域名，发表评论时报了Load failed错误

### 问题网站 | Website URL

lyay23.github.io

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

I deployed according to the operation manual, but the domain name was not bound. When I posted a comment, I received a Load failed error.

### Question Website | Website URL

lyay23.github.io

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
试了下应该是已经好了，我这边可以正常pi评论
![image](https://github.com/user-attachments/assets/d2638e2f-1229-460a-ac52-a88543479a36)
