### ISSUE TITLE
[Feature] Version mark

### ISSUE THREAD

**Issue by Mister-Hope** [walinejs/waline#279]
- Add a new api on server. Which will return Version number.
- Client: request server version on startup, and warn if incompatible. Then add it in footer.

**Comment by lizheming** [comment]
How about add a response header `waline-version` in every waline api response?

**Comment by Mister-Hope** [comment]
That's better.

**Comment by lizheming** [comment]
`@waline/vercel@1.1.0` add response header `x-waline-version` to export server version.
