### ISSUE TITLE
[Bug]: 部分已登录用户邮箱显示为UID || [Bug]: Some logged-in users’ email addresses are displayed as UIDs

### ISSUE THREAD

**Issue by XiHua0522** [walinejs/waline#2813]
### 问题描述 | Describe the bug

![fe12a65575df10c2f84a06196503a0a](https://github.com/user-attachments/assets/f4f555c1-3200-4923-8bb3-7bbf027d613a)
![ffbb9ffa3dca833cddabcf43b1b763f](https://github.com/user-attachments/assets/b0483f67-a24b-4894-8bd1-9917ebd646fe)

如图，在后台查看评论时发现一些已登录用户的邮箱账号会显示为UID开头的链接，请问这情况是否会影响对方的邮箱通知？

### 问题网站 | Website URL

https://xihua.shop/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

---
### Problem description | Describe the bug

![fe12a65575df10c2f84a06196503a0a](https://github.com/user-attachments/assets/f4f555c1-3200-4923-8bb3-7bbf027d613a)
![ffbb9ffa3dca833cddabcf43b1b763f](https://github.com/user-attachments/assets/b0483f67-a24b-4894-8bd1-9917ebd646fe)

As shown in the picture, when checking the comments in the background, I found that the email accounts of some logged-in users will be displayed as links starting with UID. Will this affect the other party's email notification?

### Question Website | Website URL

https://xihua.shop/

### Where is the service deployed? | Where your waline deploy?

Vercel (Default)

### Where is the data stored? | Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
这个是正常的，通过 QQ 登录的用户，无法获取到邮箱等关键信息，所以用 uid 伪造了一个邮箱地址入库了。

**Comment by XiHua0522** [comment]
> 这个是正常的，通过 QQ 登录的用户，无法获取到邮箱等关键信息，所以用 uid 伪造了一个邮箱地址入库了。
> 
> This is normal. Users who log in through QQ cannot obtain key information such as email addresses, so they use uid to forge an email address and store it in the database.这很正常。通过QQ登录的用户无法获取电子邮件地址等关键信息，因此他们使用uid伪造电子邮件地址并将其存储在数据库中。

原来如此，不影响通知的话就没事了，感谢回答~

**Comment by lizheming** [comment]
通过 QQ 登录的用户，应该是没办法收到邮件通知的
