### ISSUE TITLE
[Feature]: AI-powered comment moderation

### ISSUE THREAD

**Issue by wuyilingwei** [walinejs/waline#2839]
### 功能概述 | Describe the feature

Users can define the AI ​​service port and system prompt words. When receiving comments, the server will review them and automatically pass the review. The API format is chatgpt (currently the most widely used)

**Comment by lizheming** [comment]
https://github.com/zhullyb/waline-plugin-llm-reviewer

**Comment by wuyilingwei** [comment]
Thanks, this project has a little problem, but it works after fixing it. 
I suggest that newcomers read issue #1 before configuring it. I pointed out the problem of its default configuration.

**Comment by lizheming** [comment]
I see you have had some communication in that issue zhullyb/waline-plugin-llm-reviewer#1. I think there should be no problem after your PR is merged. I will close this issue.
