### ISSUE TITLE
[Bug]: https+ip 请求登录时存在无法登录问题 || [Bug]: There is a problem of being unable to log in when requesting login via https+ip

### ISSUE THREAD

**Issue by brightChenGit** [walinejs/waline#2869]
### 问题描述 | Describe the bug

项目时独立部署的，采用https+ip形式请求，后续发现，评论登录用qq第三方登录失败，发现问题是window.serverURL 本来是https的请求变成了http的请求导致的

### 问题网站 | Website URL

http://43.139.91.254:8084/message/

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

SQLite

---
### Problem description | Describe the bug

The project was deployed independently and requested in the form of https+ip. Later, it was discovered that the third-party login using qq to log in for comments failed. The problem was found to be caused by window.serverURL, which was originally an https request and became an http request.

### Question Website | Website URL

http://43.139.91.254:8084/message/

### Where is the service deployed? | Where your waline deploy?

Docker

### Where is the data stored? | Where your comment data store?

SQLite

**Comment by brightChenGit** [comment]
![1734579524632](https://github.com/user-attachments/assets/152490a7-346e-4df2-a813-0beb2cd1e1a7)

**Comment by brightChenGit** [comment]
![1734579524632](https://github.com/user-attachments/assets/84ba30f5-56d1-4f81-b0b0-28ee990a068b)

**Comment by lizheming** [comment]
https://github.com/orgs/walinejs/discussions/2290
