### ISSUE TITLE
[BUG]1.0.0-beta2和3，首页报Option 'el' is invalid!错误

### ISSUE THREAD

**Issue by tyadan** [walinejs/waline#287]
**问题描述 | Describe the bug**

使用最新的1.0.0-beta3，在首页js报错，提示Option 'el' is invalid!
使用0.17.0没有问题，印象中使用1.0.0-beta0和1好像也是正常的
在文章详情页面一切正常
<img width="1432" alt="Snipaste_2021-05-27_17-43-00" src="https://user-images.githubusercontent.com/13864360/119804808-45b97d00-bf13-11eb-8dfd-3cfaca87473e.png">

**问题网站 | Website URL**

jayshao.com

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?

  - [ ] Docker

- 数据存储在哪里？| Where your comment data store?

  - [ ] LeanCloud(https://leancloud.cn)

**Comment by tyadan** [comment]
博客使用Hexo，主题为 Next Theme，使用@Waline/hexo-next引入 Waline

**Comment by Mister-Hope** [comment]
你的el控制台打一下看看？

**Comment by Mister-Hope** [comment]
@lizheming hexo这里传入的是HTML Element么？🧐

**Comment by lizheming** [comment]
@Mister-Hope https://github.com/walinejs/waline/blob/main/packages/hexo-next/index.js#L39-L44 插件会注入 `#waline-comemnts` 的 DOM，然后 Waline 这边会直接配对应的选择器 https://github.com/walinejs/waline/blob/main/packages/hexo-next/waline.njk#L4

**Comment by Mister-Hope** [comment]
那我支持一下，因为目前waline文档写的是只支持选择器，我重写的时候也是这么来的

**Comment by lizheming** [comment]
> 那我支持一下，因为目前waline文档写的是只支持选择器，我重写的时候也是这么来的

嗯？Hexo Next 插件里传的是选择器的诶~

**Comment by tyadan** [comment]
不好意思我前端比较小白

不过奇怪的是只有首页会报这个错误，文章详情页面都是正常的

**Comment by Mister-Hope** [comment]
我问个问题，首页有评论么？

> 不好意思我前端比较小白
> 
> 不过奇怪的是只有首页会报这个错误，文章详情页面都是正常的

没关系我还没用过hexo，vuepress党一枚

**Comment by tyadan** [comment]
> 我问个问题，首页有评论么？ @tyadan
> 
> > 不好意思我前端比较小白
> > 不过奇怪的是只有首页会报这个错误，文章详情页面都是正常的
> 
> 没关系我还没用过hexo，vuepress党一枚

首页没有评论，只获取文章阅读数量

**Comment by Mister-Hope** [comment]
如果首页没有评论的话，就要看@lizheming对没对首页做特殊处理了。如果没有的话，首页找不到评论选择器报这个错就是正常的。

**Comment by Mister-Hope** [comment]
0.x 版本是会静默掉这个错误的，我在 V1把这个错误打到了控制台作为error

**Comment by tyadan** [comment]
其实还有一个小bug
在Valine里面，针对非文章页面，是不会统计访问数量的
但是目前不论首页、分类页面、存档页面等，全部都发起并统计了访问数量
这个其实可以做个判断

**Comment by lizheming** [comment]
> 0.x 版本是会静默掉这个错误的，我在 V1把这个错误打到了控制台作为error

0.x 我是考虑到了这种只需要阅读数场景的，所以在没有 DOM 的情况下不会做评论框的初始化


> 其实还有一个小bug
> 在Valine里面，针对非文章页面，是不会统计访问数量的
> 但是目前不论首页、分类页面、存档页面等，全部都发起并统计了访问数量
> 这个其实可以做个判断

非文章这个定义实在是太主观了。如果你觉得你只想要在文章页做统计的话，可以选择修改下配置的逻辑，只在文章页的时候设置 `visitor: true` 就可以了。

**Comment by tyadan** [comment]
> > 0.x 版本是会静默掉这个错误的，我在 V1把这个错误打到了控制台作为error
> 
> 0.x 我是考虑到了这种只需要阅读数场景的，所以在没有 DOM 的情况下不会做评论框的初始化
> 
> > 其实还有一个小bug
> > 在Valine里面，针对非文章页面，是不会统计访问数量的
> > 但是目前不论首页、分类页面、存档页面等，全部都发起并统计了访问数量
> > 这个其实可以做个判断
> 
> 非文章这个定义实在是太主观了。如果你觉得你只想要在文章页做统计的话，可以选择修改下配置的逻辑，只在文章页的时候设置 `visitor: true` 就可以了。

请教下，如何分不同页面类型来进行配置呀？

**Comment by Mister-Hope** [comment]
> > 0.x 版本是会静默掉这个错误的，我在 V1把这个错误打到了控制台作为error
> 
> 0.x 我是考虑到了这种只需要阅读数场景的，所以在没有 DOM 的情况下不会做评论框的初始化

这个倒是一个问题，我考虑一下，之前没细想。

因为对 SPA进行了兼容 实例上有方法，也就是可以


```js
// in `/` route
const waline = Walien({
  serverURL: 'https://example.com',
});

// after some time, route has changed to `/a.html`

waline.update(); // now waline will start clear the comment and show a loading state
// after some time, the counter and comments will be all updated

waline.update({ lang: 'en' }); // this will make waline refresh and display in english
```

所以我才在控制台打出这个错误，不过的确可以优化一下，我后续加一个判断吧，如果没传递el这个参数不渲染评论框。

**Comment by Mister-Hope** [comment]
> > 0.x 版本是会静默掉这个错误的，我在 V1把这个错误打到了控制台作为error
> 
> 0.x 我是考虑到了这种只需要阅读数场景的，所以在没有 DOM 的情况下不会做评论框的初始化

这个倒是一个问题，我考虑一下，之前没细想。

因为对 SPA进行了兼容 实例上有方法，也就是可以


```js
// in `/` route
const waline = Walien({
  serverURL: 'https://example.com',
});

// after some time, route has changed to `/a.html`

waline.update(); // now waline will start clear the comment and show a loading state
// after some time, the counter and comments will be all updated

waline.update({ lang: 'en' }); // this will make waline refresh and display in english
```

所以我才在控制台打出这个错误，不过的确可以优化一下，我后续加一个判断吧，如果没传递el这个参数不渲染评论框。

**Comment by lizheming** [comment]
> > > 0.x 版本是会静默掉这个错误的，我在 V1把这个错误打到了控制台作为error
> 
> > 
> 
> > 0.x 我是考虑到了这种只需要阅读数场景的，所以在没有 DOM 的情况下不会做评论框的初始化
> 
> > 
> 
> > > 其实还有一个小bug
> 
> > > 在Valine里面，针对非文章页面，是不会统计访问数量的
> 
> > > 但是目前不论首页、分类页面、存档页面等，全部都发起并统计了访问数量
> 
> > > 这个其实可以做个判断
> 
> > 
> 
> > 非文章这个定义实在是太主观了。如果你觉得你只想要在文章页做统计的话，可以选择修改下配置的逻辑，只在文章页的时候设置 `visitor: true` 就可以了。
> 
> 
> 
> 请教下，如何分不同页面类型来进行配置呀？

你自己根据当前页的 pathname 判断下？不过要写点代码了，可能对新手不是很友好，2333

**Comment by Mister-Hope** [comment]
我正好就占用你的issue 多说两句 @tyadan 

@lizheming 我刚才又想了一下，添加了spa之后，原来的调用方式就有点问题了。visitor和comment两个counter实际上和 Waline 本体的评论逻辑是分离的。

我目前支持支持到的有:

**Comment by Mister-Hope** [comment]
在这种情况下所有的相关请求是用同一个signal控制的，但是如果路径不变直接update，原则上不应该更新评论，但是两个counter应该被取消，然后重新触发(因为用户可能在同一页进行了分页的翻页想要拉新的评论数浏览量？)。代码逻辑上可能要改不少？

**Comment by Mister-Hope** [comment]
beta4应该已经修复

**Comment by tyadan** [comment]
> beta4应该已经修复

我今天看了下线上更新到1.0.1了，还是报错哎
我的博客地址是jayshao.com，可以再看下？

**Comment by Mister-Hope** [comment]
> > beta4应该已经修复
> 
> 我今天看了下线上更新到1.0.1了，还是报错哎
> 我的博客地址是jayshao.com，可以再看下？

更新到1.1.0吧

**Comment by yczheng0** [comment]
大佬好，我目前使用hexo 6.0.0，主题Next 8.10.1，通过插件@waline/hexo-next （2.0.6）引入 waline 1.6.0，在首页会报warning Option 'el' do not match any domElement! 看起来应该是这个issue的延续，请问现在有对首页特殊处理的方案吗？谢谢。
