### ISSUE TITLE
[建议] 希望能添加邮箱屏蔽的功能

### ISSUE THREAD

**Issue by lewky** [walinejs/waline#293]
因为本人站点被一个搞空包快递单号的广告哥盯上了，他一直用同一个邮箱来发垃圾评论的，虽然屏蔽了他的关键词，但有时候他会用逗号之类的隔开关键词，这样就没办法自动屏蔽他的垃圾评论了。。

**Comment by lewky** [comment]
他ip换的也很勤快，靠ip屏蔽也不靠谱

**Comment by lewky** [comment]
98562953@qq.com
这是他用的邮箱，不知道有没有其他兄弟也被他盯上了

**Comment by CCKNBC** [comment]
@lewky 建议关闭评论🙃

**Comment by Mister-Hope** [comment]
邮箱是可以随意填的，即使开发出这个功能，他搞你也没办法。建议开启评论审核。

**Comment by lewky** [comment]
> @lewky 建议关闭评论🙃

这也太因噎废食了吧

**Comment by lewky** [comment]
> 邮箱是可以随意填的，即使开发出这个功能，他搞你也没办法。建议开启评论审核。
> 
> 另外他换一个ip建议你多屏蔽一个ip。他总不能成天换ip。

他可能是用的脚本一次性在大量站点上发的垃圾评论，所以一直用的同一个用户名和邮箱，所以我才想着直接屏蔽邮箱

**Comment by Mister-Hope** [comment]
我们会通过支持#289来改善你的状态。

**Comment by lewky** [comment]
好的，谢谢了

**Comment by Mister-Hope** [comment]
不过目前的有效建议是开启评论审核，辛苦一下及时通过正常用户的评论。

**Comment by Mister-Hope** [comment]
哦对我忘了，你可以看一下文档中的评论hook，通过hook对其有效进行屏蔽。

**Comment by lewky** [comment]
好的，十分感谢！

**Comment by cjh0613** [comment]
也可以使用单字关键词，手动恢复误判的
