### ISSUE TITLE
[BUG] 评论管理后台表情包过大

### ISSUE THREAD

**Issue by oCoke** [walinejs/waline#295]
**问题描述 | Describe the bug**

评论管理后台表情包过大。

![image](https://user-images.githubusercontent.com/71591824/120265687-16b85800-c2d3-11eb-8819-19c78c33e743.png)

**问题网站 | Website URL**

`{serverURL}/ui`

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [x] Vercel
  - [ ] CloudBase
  - [ ] Docker
  - [ ] VPS, Virtual Host
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [x] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [ ] CloudBase
  - [ ] MongoDB
  - [ ] MySQL
  - [ ] SQLite
  - [ ] PostgreSQL
  - [ ] GitHub

**Comment by Mister-Hope** [comment]
I will release a new version later today
