### ISSUE TITLE
[BUG] 后台管理评论在Safari浏览器下评论时间显示不正常

### ISSUE THREAD

**Issue by lei2rock** [walinejs/waline#297]
**问题描述 | Describe the bug**

后台管理评论在Safari浏览器下评论时间显示不正常

![Snipaste_2021-06-01_21-19-05](https://user-images.githubusercontent.com/19180725/120331813-bfd96f80-c320-11eb-8d1a-ebe1dfb5d9bf.png)

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [ ] Vercel
  - [ ] CloudBase
  - [x] Docker
  - [ ] VPS, Virtual Host
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [ ] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [ ] CloudBase
  - [ ] MongoDB
  - [x] MySQL
  - [ ] SQLite
  - [ ] PostgreSQL
  - [ ] GitHub

**Comment by lizheming** [comment]
应该已经做兼容处理了，你看一下。
