### ISSUE TITLE
[BUG] 報 Option 'el' is invalid!

### ISSUE THREAD

**Issue by TszHong0411** [walinejs/waline#299]
**问题描述 | Describe the bug**

console 報 Option 'el' is invalid!
框架: Hexo
主題: Butterfly
![](https://cdn.jsdelivr.net/gh/tszhong0411/image/issue/waline_issue1.png)

**问题网站 | Website URL**
[https://tszhong.top](https://tszhong.top)

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [x] Vercel
  - [ ] CloudBase
  - [ ] Docker
  - [ ] VPS, Virtual Host
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [x] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [ ] CloudBase
  - [ ] MongoDB
  - [ ] MySQL
  - [ ] SQLite
  - [ ] PostgreSQL
  - [ ] GitHub

**Comment by CCKNBC** [comment]
@TszHong0411 请升级主题版本至 3.8.0-b2

**Comment by TszHong0411** [comment]
> @TszHong0411 请升级主题版本至 3.8.0-b2

好的，非常感謝！
