### ISSUE TITLE
[BUG] GitHub 登录后评论 头像在手动刷新前无法显示

### ISSUE THREAD

**Issue by akuraito** [walinejs/waline#300]
**问题描述 | Describe the bug**

GitHub 登录后进行评论，评论框处的头像可以正常显示，而具体评论处的头像无法显示，此时头像链接为：https://avatar.75cdn.workers.dev/?url=https%3A%2F%2Favatar.75cdn.workers.dev%2F%3Furl%3Dhttps%253A%252F%252Favatars.githubusercontent.com%252Fu%252F51032369%253Fv%253D4
刷新网站后显示正常

**问题网站 | Website URL**

https://waline.js.org/

![image](https://user-images.githubusercontent.com/51032369/120625609-76aa2c80-c494-11eb-9395-6e4b999f941a.png)

**Comment by TszHong0411** [comment]
我也是

**Comment by lizheming** [comment]
`@waline/vercel@0.24.1` 已修复该问题，可以升级再试一下
