### ISSUE TITLE
[咨询]非docker环境独立部署如何配置数据库连接

### ISSUE THREAD

**Issue by skadiD** [walinejs/waline#301]
在服务器内直接使用独立部署运行vanilla.js,访问:8360时提示Not initialized

**Comment by Mister-Hope** [comment]
请检查你的数据库的帐号密码，另外你必须要先完成注册成为admin账户。

**Comment by skadiD** [comment]
我是使用的sqlite,请问相关的路径地址应该在哪里配置

**Comment by Mister-Hope** [comment]
请通过文章提及的环境变量配置，另外类似问题请移步 dicussion。

如果你不知道如何在自己的服务器设置环境变量，请尝试必应或者谷歌搜索。
