### ISSUE TITLE
[BUG] 評論中的 emoji 無法顯示

### ISSUE THREAD

**Issue by TszHong0411** [walinejs/waline#302]
**问题描述 | Describe the bug**

評論後變成 `<p><img ... ></p>`
![](https://cdn.jsdelivr.net/gh/tszhong0411/image/issue/waline_issue2.png)
**问题网站 | Website URL**

[https://tszhong.top/contact/](https://tszhong.top/contact/)

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [x] Vercel
  - [ ] CloudBase
  - [ ] Docker
  - [ ] VPS, Virtual Host
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [x] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [ ] CloudBase
  - [ ] MongoDB
  - [ ] MySQL
  - [ ] SQLite
  - [ ] PostgreSQL
  - [ ] GitHub

**Comment by Mister-Hope** [comment]
See pin issue
