### ISSUE TITLE
[BUG]Client1.2.2 Vercel 头像无法正确显示

### ISSUE THREAD

**Issue by hackedbyxx** [walinejs/waline#303]
缺少CDN地址，是相对路径。0.16.2之前的老版本正常
[地址](https://findxx.cn/2021/06/04/hello-world/)

**Comment by lizheming** [comment]
我看是你这边用 avatarCDN 配置把 CDN 地址置空了，如果你不用这个配置的话可以把它注释了再看一下。

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/121108114-bd54a980-c83b-11eb-8a06-ed7ec01c73fd.png)

Invalid config, check what you are doing
