### ISSUE TITLE
[建议]表情弹窗改为非模态比较合适？

### ISSUE THREAD

**Issue by tsq456** [walinejs/waline#304]
**问题描述 | Describe the bug**
当前打开表情弹窗后，需要再次点击表情图标才能关闭，但是实际上这个完全没必要，点击空白处或其他相应区域就关闭表情弹窗，体验会更好。

建议优化。

另，为什么现在发布表情后，是生成一段<img>标签的HTML代码。

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [X] Vercel
  - [ ] CloudBase
  - [ ] Docker
  - [ ] VPS, Virtual Host
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [x] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [ ] CloudBase
  - [ ] MongoDB
  - [ ] MySQL
  - [ ] SQLite
  - [ ] PostgreSQL
  - [ ] GitHub

**Comment by Mister-Hope** [comment]
Please see pin issue. Your advice is recorded and will be published as an enhancment.

**Comment by MaxChang3** [comment]
旧版本的waline(0.15)中我使用
```javascript
$("body").click(function (event) {
if (event.target.parentNode.parentNode.className != "vcol vcol-40 vctrl text-right") {
    if (document.getElementsByClassName("vicon vemoji-btn actived")[0] != undefined)
        document.getElementsByClassName("vicon vemoji-btn actived")[0].click();
    }
});
```
绑定了这一事件实现了你所说的效果，确实是有必要的。

In the waline of older version(0.15), I use the code above bind an event to close the emoji box when you click the area out of the box;

**Comment by Mister-Hope** [comment]
Published in v1.2.4
