### ISSUE TITLE
[BUG]后台评论链接错误 Backstage Comments URLs Error

### ISSUE THREAD

**Issue by YiHui-Liu** [walinejs/waline#306]
**问题描述 | Describe the bug**
填写评论信息时，如果网址未指定协议（如填写`foolishfox.cn`），那么后台评论管理的链接就会出错
When filling in the comment information, if the URL does not specify the protocol (such as filled with `foolishfox.cn`), then the URL of the back-end comment manage page will be wrong:
![image](https://user-images.githubusercontent.com/30190271/121394759-40811700-c984-11eb-86ef-24f3b2597426.png)

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [x] VPS, Virtual Host
- 数据存储在哪里？| Where your comment data store?
  - [x] MySQL

**备注 | Remarks**
服务端链接为二级目录：`/waline/ui`
URL of server is the secondary directory: `/waline/ui`

**Comment by Mister-Hope** [comment]
Please provide more details or check what you are expressing.

- Link field in comment box should be working when without protocol prefix. (`https://` as default)
- users don't need and can't actually login to see the comment manage page.

**Comment by YiHui-Liu** [comment]
每一条的评论的昵称是一个指向填写的URL的超链接，如果该URL没有指定协议，那么在后台的链接地址将会出错，但是前端展示没有问题，如下图所示：
![](https://user-images.githubusercontent.com/30190271/121394759-40811700-c984-11eb-86ef-24f3b2597426.png)
已经测试，无论服务端URL是否为二级目录，都会出现该问题
<hr />
The nickname of each comment is a hyperlink which the destination address is the URL. If the URL does not specify the protocol, then the link address in the background will be wrong, and the front-end display will be no problem, as shown in the following picture:

![](https://user-images.githubusercontent.com/30190271/121394759-40811700-c984-11eb-86ef-24f3b2597426.png)
It has been tested, regardless of whether the server URL is a secondary directory, the problem may occur
