### ISSUE TITLE
[BUG] 博客首页加载报错 Option 'el' is invalid!

### ISSUE THREAD

**Issue by clay-world** [walinejs/waline#308]
**问题描述 | Describe the bug**

使用最新的 Waline Client v1.2.3，首页加载报错，提示 Option 'el' is invalid!，Hexo 主题是 NexT 8.5

**问题网站 | Website URL**

- https://www.techgrow.cn

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [ ] Vercel
  - [ ] CloudBase
  - [x] Docker
  - [ ] VPS, Virtual Host
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [ ] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [ ] CloudBase
  - [ ] MongoDB
  - [x] MySQL
  - [ ] SQLite
  - [ ] PostgreSQL
  - [ ] GitHub

**Comment by Mister-Hope** [comment]
This  is expected if you don't have a comment box in homepage while you still provide a el.

Just an error msg.

**Comment by Mister-Hope** [comment]
@lizheming Could you try to remove the el option when visiting home page in the official plugin?

**Comment by lizheming** [comment]
@Mister-Hope I think add `try...catch` at here is better than handle it outside of client script.

https://github.com/walinejs/waline/blob/main/packages/client/src/index.ts#L61-L63

```
try {
  const root = document.querySelector<HTMLElement>(el);
  return root || null;
} catch() {
  return null;
}
```

**Comment by Mister-Hope** [comment]
No need, the error log is logged by me with purpose.

I just want to warn the user their options is not correct.

**Comment by lizheming** [comment]
I think that's better to use `console.warn()` instead of `console.error()` if you just want to notice user.

**Comment by Mister-Hope** [comment]
Warning instead of error will be logged in v1.3.0+
