### ISSUE TITLE
腾讯云一键部署链接提示无配置

### ISSUE THREAD

**Issue by L-cw** [walinejs/waline#375]
![image](https://user-images.githubusercontent.com/23190216/123215676-53a2f380-d4fb-11eb-8b4b-5e8cedb9b240.png)

点击 [文档](https://waline.js.org/guide/server/cloudbase.html) 中的一键部署地址后跳转腾讯云，但在部署的时候报错，记得之前有在评论里提示新的部署链接，但是现在找不到那条评论了，麻烦更新下文档吧

**Comment by lizheming** [comment]
https://console.cloud.tencent.com/tcb/env/index?action=CreateAndDeployCloudBaseProject&appUrl=https%3A%2F%2Fgithub.com%2Fwalinejs%2Ftcb-starter&branch=master&appName=waline

你试一下这个地址？

**Comment by L-cw** [comment]
> https://console.cloud.tencent.com/tcb/env/index?action=CreateAndDeployCloudBaseProject&appUrl=https%3A%2F%2Fgithub.com%2Fwalinejs%2Ftcb-starter&branch=master&appName=waline
> 
> 你试一下这个地址？

感谢！这个是好用的。
