### ISSUE TITLE
[BUG] 邮件内的 `@username` 部分无法被正确的打开

### ISSUE THREAD

**Issue by akuraito** [walinejs/waline#408]
**问题描述 | Describe the bug**

当游客收到评论时，邮件通知中 `@username` 部分内容为 `<a class="at" href="#000000000000000000000000">@username</a>`  这个链接无法打开正确的网页。

When the guest received a mail, the `@username` part is a link like  `<a class="at" href="#000000000000000000000000">@username</a>` , and it won't open the correct page.

**Comment by lizheming** [comment]
这个影响不大，暂时不处理了~
