### ISSUE TITLE
[BUG]迁移功能不能使用

### ISSUE THREAD

**Issue by xiyizhou** [walinejs/waline#409]
**问题描述 |  leancloud 数据无法迁移到 cloudbase **

从 leancloud 导出数据 https://download-us.leancloud.cn/export/a1avdg2moWVzKKfrgeIIQp0e-MdYXbMMI-export0vaDyw6z2235289001363510.tar.gz

使用官方转换工具https://waline.js.org/migration/valine.html#%E8%BF%81%E7%A7%BB%E8%87%B3-cloudbase，  
点击“迁移没反应”。
手工复制转换的数据，导入 cloudbase 提示错误。
`将 “tmp-1625884225531-Users.0.json” 导入到 “Users” 失败。Error: Unexpected token # at position 0 文档地址： https://mp.weixin.qq.com/debug/wxadoc/dev/wxcloud/guide/database/import.html
`

**问题网站 | Website URL**

https://inote.xyz

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?

  - [ ] CloudBase

- 数据存储在哪里？| Where your comment data store?

  - [ ] CloudBase

**Comment by lizheming** [comment]
迁移助手目前仅支持 Valine/Disqus/Twikoo/Typecho/Artalk/Commento 之类的外部数据转入到 Waline 中，暂不支持 Waline 本身的迁移

**Comment by xiyizhou** [comment]
好的

**Comment by xiyizhou** [comment]
从 leancloud →设置→数据储存→结构化数据→选择对应 comment counter →将查询结构保存为 CSV
