### ISSUE TITLE
[BUG] Error: read ECONNRESET

### ISSUE THREAD

**Issue by TszHong0411** [walinejs/waline#411]
**问题描述 | Describe the bug**

評論時彈出以下錯誤並且用戶無法接收郵件通知，我的Telegram也無法接收通知

![issue](https://cdn.jsdelivr.net/gh/tszhong0411/image/issue/waline_issue3.png)

**问题网站 | Website URL**

[https://tszhong.top](https://tszhong.top)

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [x] Vercel
  - [ ] CloudBase
  - [ ] Docker
  - [ ] VPS, Virtual Host
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [x] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [ ] CloudBase
  - [ ] MongoDB
  - [ ] MySQL
  - [ ] SQLite
  - [ ] PostgreSQL
  - [ ] GitHub

**Comment by lizheming** [comment]
我测试了一条，是没有问题的呢。`ECONNRESET` 这个错误应该是网络问题，请自行检查下 `https://waline.tszhong.top/` 的访问情况

**Comment by TszHong0411** [comment]
> 我测试了一条，是没有问题的呢。`ECONNRESET` 这个错误应该是网络问题，请自行检查下 `https://waline.tszhong.top/` 的访问情况

有时会出现，有时候不会

**Comment by TszHong0411** [comment]
可以了，感謝回覆！可能我的網絡真的有問題
