### ISSUE TITLE
[BUG] vercel部署后端Mongodb数据库连接失败

### ISSUE THREAD

**Issue by OnlyFor** [walinejs/waline#412]
部署在 vercel 上，后端使用 MongoDB，但是好像连不上 mongodb？

我的mongodb链接是这样(免费版没有replicaSet)：
mongodb+srv://<username>:<password>@cluster0.rxr1g.mongodb.net/myFirstDatabase?retryWrites=true&w=majority

然后配置的时候我按教程改成了这样：
MONGO_HOST=["cluster0-shard-00-00.rxr1g.mongodb.net","cluster0-shard-00-01.rxr1g.mongodb.net","cluster0-shard-00-02.rxr1g.mongodb.net"]
MONGO_PORT=[27017,27017,27017]
MONGO_DB=waline
MONGO_USER=waline
MONGO_PASSWORD=xxxx
MONGO_AUTHSOURCE=admin
MONGO_OPT_SSL=true

然后管理后台ui/register打开注册时失败，看日志好像是连接失败，报错内容如下：

[POST] /user
12:25:36:69
Function Status:None
Edge Status:504
Duration:10012.46 ms
Init Duration: N/A
Memory Used:274 MB
ID:q7dm6-1626150336676-e00d3490df82
User Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0
ne:IrAMkr0H5hKoSdDI@cluster0-shard-00-00.rxr1g.mongodb.net:27017,cluster0-shard-00-01.rxr1g.mongodb.net:27017,cluster0-shard-00-02.rxr1g.mongodb.net:27017/waline?replicaSet=&authSource=admin&ssl=true[2021-07-13T04:25:37.198] [5] [INFO] - mongodb://waline:xxxx@cluster0-shard-00-00.rxr1g.mongodb.net:27017,cluster0-shard-00-01.rxr1g.mongodb.net:27017,cluster0-shard-00-02.rxr1g.mongodb.net:27017/waline?replicaSet=&authSource=admin&ssl=true[2021-07-13T04:25:37.199] [5] [INFO] - mongodb://waline:IrAMkr0H5hKoSdDI@cluster0-shard-00-00.rxr1g.mongodb.net:27017,cluster0-shard-00-01.rxr1g.mongodb.net:27017,cluster0-shard-00-02.rxr1g.mongodb.net:27017/waline?replicaSet=&authSource=admin&ssl=true[2021-07-13T04:25:37.199] [5] [INFO] - mongodb://waline:xxxx@cluster0-shard-00-00.rxr1g.mongodb.net:27017,cluster0-shard-00-01.rxr1g.mongodb.net:27017,cluster0-shard-00-02.rxr1g.mongodb.net:27017/waline?replicaSet=&authSource=admin&ssl=true[2021-07-13T04:25:37.199] [5] [INFO] - mongodb://waline:IrAMkr0H5hKoSdDI@cluster0-shard-00-00.rxr1g.mongodb.net:27017,cluster0-shard-00-01.rxr1g.mongodb.net:27017,cluster0-shard-00-02.rxr1g.mongodb.net:27017/waline?replicaSet=&authSource=admin&ssl=true[2021-07-13T04:25:37.199] [5] [INFO] - mongodb://waline:xxxx@cluster0-shard-00-00.rxr1g.mongodb.net:27017,cluster0-shard-00-01.rxr1g.mongodb.net:27017,cluster0-shard-00-02.rxr1g.mongodb.net:27017/waline?replicaSet=&authSource=admin&ssl=true

建议能不能直接改成环境变量MONGODB_URL入参整一个url？

**Comment by lizheming** [comment]
你是用的 mongodb.com 官方的 MongoDB 服务吗？

**Comment by OnlyFor** [comment]
> 
> 
> 你是用的 mongodb.com 官方的 MongoDB 服务吗？

是的，就是上限512M那个，而且这个官方给的链接：
mongodb+srv://usr:psw@cluster0.rxr1g.mongodb.net/myFirstDatabase?retryWrites=true&w=majority

我在别的同样使用vercel和mongodb的项目中是能正确部署使用的（比如https://github.com/electerious/Ackee这个项目就可以）

**Comment by lizheming** [comment]
<kbd>connect</kbd> - <kbd>connect your application</kbd> - Node.js + 2.2.12 or later 
你这么选后把下面的连接 url 拆一下应该就可以了。目前用的底层 Mongo 的操作库应该不支持字符串的连接地址，之后我再研究一下。

![image](https://user-images.githubusercontent.com/424491/125450260-9ca29521-7c7c-449d-bf4f-b7af994af48e.png)
![image](https://user-images.githubusercontent.com/424491/125450287-4f4c8d8d-c3c1-4b99-9341-89924c1ab8e0.png)

**Comment by OnlyFor** [comment]
好的，谢谢
