### ISSUE TITLE
无法注册[BUG]

### ISSUE THREAD

**Issue by yucho123987** [walinejs/waline#414]
**问题描述 | Describe the bug**

无法注册管理员，提示注册失败。初始化时没配置环境变量，还出现了好几个报错，后来配置了环境变量，但注册时出现错误，服务端首页评论时提示未初始化。
**问题网站 | Website URL**

https://blog-comments-git-main-yucho123987.vercel.app/ui/register
**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [x] Vercel
  - [ ] CloudBase
  - [ ] Docker
  - [ ] VPS, Virtual Host
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [x] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [ ] CloudBase
  - [ ] MongoDB
  - [ ] MySQL
  - [ ] SQLite
  - [ ] PostgreSQL
  - [ ] GitHub

**Comment by lizheming** [comment]
Vercel 修改了环境变量之后需要重新部署一下才能生效，请确认一下是否有重新部署。

**Comment by yucho123987** [comment]
@lizheming 如何重新部署？

**Comment by lizheming** [comment]
![image](https://user-images.githubusercontent.com/424491/125706708-c82638bf-2b41-4304-b375-9bafac9f4792.png)

**Comment by yucho123987** [comment]
@lizheming 谢谢，已经解决问题
