### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nanbowan323** [walinejs/waline#420]
**问题描述 | Describe the bug**
我利用hexo再GitHub上搭建的博客，使用waline插件后出现无法注册的情况

**问题网站 | Website URL**
https://waline-43zgu1rvf-nanbowan.vercel.app/ui/register

**部署方式 | Deploy Type**
根据文档提供的教程。

- 服务部署在哪里？ | Where your waline deploy?
 Vercel

- 数据存储在哪里？| Where your comment data store?
 LeanCloud(https://leancloud.app)

**Comment by Mister-Hope** [comment]
请配置环境变量。

**Comment by nanbowan323** [comment]
请问下这个环境变量在哪里配置是hexo的_config.yml文件还是什么。实在抱歉，小白一个。

**Comment by Mister-Hope** [comment]
你不是说你看过快速上手了么？

**Comment by nanbowan323** [comment]
> 你不是说你看过快速上手了么？

教程上没有环境变量这个说法，所以我想问的是，你说的环境变量指的是哪一步，我好截图给你对应的内容。

**Comment by Mister-Hope** [comment]
![Screenshot_20210717-185256.jpg](https://user-images.githubusercontent.com/33315834/126034651-c3c2cc96-a9b0-4c6b-8dd4-747179d3b0ab.jpg)![Screenshot_20210717-185252.jpg](https://user-images.githubusercontent.com/33315834/126034653-c766e521-ae06-4661-8eaa-1e4dde10aec0.jpg)

**Comment by nanbowan323** [comment]
![image](https://user-images.githubusercontent.com/20452341/126035923-cac10f37-fd49-46ae-927d-6e678ebdfafe.png)
是这个吗？

**Comment by CCKNBC** [comment]
@nanbowan323 加油哦💪

**Comment by Mister-Hope** [comment]
是的，请在此核对它是否正确，同时检查你是否使用的leancloud国际版。如果是国内版你需要设置LEAN_SERVER。

**Comment by nanbowan323** [comment]
重启过后成功了，是没重启的原因，抱歉
