### ISSUE TITLE
[BUG]是否可以添加验证码功能？

### ISSUE THREAD

**Issue by windskyxb** [walinejs/waline#424]
**问题描述 | Describe the bug**
从7月18号开始被机器人刷评，截至19号已有400多评论。Akismet检测结果为Approved；关键词检测结果为Approved请问是否可以添加评论验证码？

![网页捕获_19-7-2021_101341_waline-beige.vercel.app.jpeg](https://i.loli.net/2021/07/19/13V4vTSQbNWEk9K.jpg)

![网页捕获_19-7-2021_101238_zhouhua.vercel.app.jpeg](https://i.loli.net/2021/07/19/eZ29ptHNYxgdCiz.jpg)

**问题网站 | Website URL**
https://zhouhua.vercel.app/2021/07/04/%E6%84%9F%E6%83%B3/

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [x] Vercel
  - [ ] CloudBase
  - [ ] Docker
  - [ ] VPS, Virtual Host
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [x] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [ ] CloudBase
  - [ ] MongoDB
  - [ ] MySQL
  - [ ] SQLite
  - [ ] PostgreSQL
  - [ ] GitHub

**Comment by lizheming** [comment]
暂时没有添加验证码的计划。可以先把评论审核开启，消息通知关闭处理一下。

**Comment by windskyxb** [comment]
> 
> 
> 暂时没有添加验证码的计划。可以先把评论审核开启，消息通知关闭处理一下。

评论审核指的是

**Comment by windskyxb** [comment]
> 
> 
> 暂时没有添加验证码的计划。可以先把评论审核开启，消息通知关闭处理一下。

好的，感谢回复

**Comment by Mister-Hope** [comment]
我们提供了钩子，你可以从昵称、内容或者后缀下手。自行识别出这些垃圾评论直接丢弃。

**Comment by windskyxb** [comment]
> 
> 
> 暂时没有添加验证码的计划。可以先把评论审核开启，消息通知关闭处理一下。

评论审核是将COMMENT_AUDIT设置为true吗？

**Comment by lizheming** [comment]
是的
