### ISSUE TITLE
关于 Waline 的一些疑问

### ISSUE THREAD

**Issue by oCoke** [walinejs/waline#425]
近期我的 Waline 评论系统被刷评论了，对 Waline 有些疑问：

### 字数限制只在前端？

前端有字数限制的配置，但似乎可以通过 API 提交，此设置项防君子不防小人？

### 强制登录只在前端？

前端有强制登录的限制，但似乎可以通过 API 提交，并且不是所有的组件都强制登录，如果有攻击时，并不能很好的防护。

建议：后端可配置强制登录，所有前端发送的未登录的评论都拒绝。

**Comment by oCoke** [comment]
![image](https://user-images.githubusercontent.com/71591824/126156974-b6691214-74af-48e9-970a-55cff9e11439.png)
![image](https://user-images.githubusercontent.com/71591824/126156989-f8c6b179-30bb-4f82-b6c8-b73e369b5ec2.png)

**Comment by Mister-Hope** [comment]
所有在前端的配置显然都只能防前端，不过近期版本会加入后端的强防护

**Comment by lizheming** [comment]
强制登录目前服务端增加了 `LOGIN=force` 的环境变量，可以在接口层限制登录评论功能了。
