### ISSUE TITLE
[建议]提供多语言切换按钮，或者提供多语言自动匹配教程

### ISSUE THREAD

**Issue by zane-ng** [walinejs/waline#428]
[#145](https://github.com/walinejs/waline/issues/145) 提到了 Hexo 插件自动匹配页面语言，但其中的讨论最终似乎并没有明确如何设置，同时未必适用于其他前端（如 Hugo）。

Waline 的 [i18n](https://waline.js.org/en/guide/client/i18n.html) 页面也没有提及有关 Waline 语言自动匹配网页语言的信息，然而该页面的 Waline 评论界面语言自动匹配页面语言。

所以想首先请教一下，如何实现 Waline 界面语言与网页语言自动匹配？
如果当前版本 Waline 已具备此特性，是否可将相关信息添加到 Waline 的使用手册当中？

另外，如果自动匹配语言难以实现，是否可以添加一个手动语言切换按钮？初步考虑可以类似 emoji 菜单按钮，只是点击后菜单直接显示相应语言名称（如：EN, EN-US, 汉, 漢, 日）。

感谢！

**Comment by Mister-Hope** [comment]
老实说，我没看懂你要什么。

你可以自行保存walineInstance并用update方法更新lang或者locale以切换多语言。

waline不关心也不需要知道页面是什么语言，你应该自动传入正确的语言给waline，在spa应用中，在切换页面时更新语言也应该是用户或者主题的工作。

**Comment by Mister-Hope** [comment]
如果你想看具体实现，不妨到docs文件夹下看看官网是怎么添加waline并自动适配语言的。

**Comment by Mister-Hope** [comment]
如果您还有其他疑问，或者上述解答没有帮到您，欢迎继续具体阐述您的问题。

**Comment by zane-ng** [comment]
首先，谢谢你的回复。

我原帖只是想问：1）Wanline 现版本是否能够自动适配语言？如果可以，怎么实现，并且是否可以将实现方法写入官网教程？2）如果无法自动适配语言，是否可以相关功能或者提供切换语言的按钮，由评论者手动切换？

你提到：

> 你可以自行保存 walineInstance 并用 update 方法更新 lang 或者 locale 以切换多语言。
>
> waline 不关心也不需要知道页面是什么语言，你应该自动传入正确的语言给 waline，在 spa 应用中，在切换页面时更新语言也应该是用户或者主题的工作。
> 
> 如果你说的是 Waline 自动读取 html 上的蓝 lang attr 自适应，可以考虑添加，但是只是初始化的时候读一下，spa 应用中仍需要你自己处理逻辑。（location.pathname 没有监听器)

以上信息在 [Waline 官网手册「多语言支持」](https://waline.js.org/guide/client/i18n.html) 中均没有提到。

如果说官网已经实现自动适配，同时用户或者开发者可以到 docs 文件夹下查看官网如何实现自动适配，

那么请问是否可以把官网自动适配的案例直接写入官网手册「多语言支持」章节中？

我不是专业开发者，缺乏很多编程知识。很多 Waline 现在或者未来的用户（比如个人博客）可能也不是。我在官网使用关键字「适配」或者「适应」也无法搜索到相关信息。在官网教程直接提供案例会方便所有人，也避免像我一样只能来提问。相较之下，暗黑模式的自适应则有明确说明，所以可以直接按照教程配置。

谢谢。

**Comment by Mister-Hope** [comment]
首先语言的匹配压根就是编程式的，换而言之，整个UI 的显示文字由 lang 选项和 locale 选项共同配置，这个我想我们在文档中应该是说明白了的。

也就是你应该在初始化的时候自行传入合适的配置。

至于再切换页面的过程中分两种情况：

- 如果你是很简单的网站，每个页面独立，你应该在每个页面的加载过程中重新初始化 Waline，并自行传入合适的配置。

   > 所以我觉得这里不需要单独在多语言提一下重新初始化要传，所有选项都是这样要重新传。

- 如果你在使用 SPA，通过 history.pushState 替换路由，同时类似 Vue 之类的框架会复用整个 Waline dom 的话:

    由于浏览器的特性，这种跳转没有办法在无副作用的情况下监听，所以这意味着你需要手动调用 `walineInstance.update()` 通知 Waline 你切换了页面，并让 Waline 拉取并显示新路径下的评论。在这一过程中，你应该在前后语言不一致的情况下，传入新的 lang 和 locale 更新新的语言。

   > SPA 下的这些限制，以及 `update` 函数在 SPA 章节里有讲，也就是这里 lang 和 locale 跟其他参数配置一样，需要你在切换路由时自己手动去更新相关的参数。我个人也认为没必要单独讲。

---

另外关于自适应语言这个问题: 即使 Waline 想要自适应语言，用户(比如你) 必须显式的将页面的语言代码放置在网页的指定标签的 lang 属性上，这样 waline 才有可能可以读取当前页面的语言。而你既然必须显式这样做，你就完全可以在当前页面将这个语言直接传递 Waline 里，而不是让它试图去爬 html body 等标签的 lang 属性。

> 如果你想的是插件能够真的”自适应“页面语言，那显然是过于异想天开了，暂不提网页的具体 dom 结构是未知的，就算 Waline 拿到正文，除非藏文、阿拉伯语、片假名这种特殊的表象文字还可以被识别，Waline 如何识别页面是英语、意大利语、德语还是葡萄牙语？

**Comment by Mister-Hope** [comment]
总结一下，如果你试图在主题中或者自己的博客嵌入 Waline，Waline 没法知道当前页面是什么语言，所以这需要你自己添加当前页面的语言，或者读取所用框架的多语言配置，然后识别出当前页面的语言告诉 Waline。

如果你在使用一个嵌入了 Waline 的主题，而没办法自动适配多语言，请你联系主题作者，允许在每个页面中单独覆盖全局默认的 Waline 参数功能。

**Comment by zane-ng** [comment]
谢谢。
