### ISSUE TITLE
[BUG] 使用 Cloudflare 后 IP 不正确

### ISSUE THREAD

**Issue by oCoke** [walinejs/waline#429]
**问题描述 | Describe the bug**

我使用 Cloudflare CDN 后，所有的 IP 都变成了 Cloudflare 节点的 IP，无法正常记录用户 IP。

**问题网站 | Website URL**

![](https://bu.dusays.com/2021/07/20/76cd2cab166ba.png)

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [x] Vercel
  - [ ] CloudBase
  - [ ] Docker
  - [ ] VPS, Virtual Host
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [x] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [ ] CloudBase
  - [ ] MongoDB
  - [ ] MySQL
  - [ ] SQLite
  - [ ] PostgreSQL
  - [ ] GitHub

**Comment by karuboniru** [comment]
Similar problem https://github.com/walinejs/waline/discussions/405

Solved by self-hosting, maybe vercel is removing or changing some headers needed to record client ips.

**Comment by lizheming** [comment]
Maybe cf changes proxy header like @karuboniru  mentioned in #405. Please try to replace your `index.js` server file with folllowing code, and tell me if it works. Thank you.

```
// index.js
const Application = require('@waline/vercel');

Application({
  async postSave(comment) {
    // do what ever you want after save comment
  },
});
think.app.proxyIpHeader = 'CF-Connecting-IP';
```

**Comment by bennyxguo** [comment]
> Maybe cf changes proxy header like @karuboniru mentioned in #405. Please try to replace your `index.js` server file with folllowing code, and tell me if it works. Thank you.
> 
> ```
> // index.js
> const Application = require('@waline/vercel');
> 
> Application({
>   async postSave(comment) {
>     // do what ever you want after save comment
>   },
> });
> think.app.proxyIpHeader = 'CF-Connecting-IP';
> ```

This method is working for me on Vecel! Thanks!

**Comment by Ayx03** [comment]
Missing `module.exports = `, should be:

```javascript
// index.js
const Application = require('@waline/vercel');

module.exports = Application({
  async postSave(comment) {
    // do what ever you want after save comment
  },
});
think.app.proxyIpHeader = 'CF-Connecting-IP';
```
