### ISSUE TITLE
希望加强防御措施

### ISSUE THREAD

**Issue by wxydejoy** [walinejs/waline#430]
**问题描述 | Describe the bug**

![image](https://user-images.githubusercontent.com/81625961/126262590-8185e4de-94d8-4816-bab7-67b567b35176.png)

**问题网站 | Website URL**

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [x] Vercel

- 数据存储在哪里？| Where your comment data store?
  - [x] LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
1. 可以开启审核关闭通知忽略这些垃圾评论
2. 可以升级到最新版开启登录才允许评论功能。确保服务端更新到最新版本 0.26.0，然后增加 `LOGIN=force` 环境变量，同时博客 Waline 客户端增加 `login=force` 的配置用于隐藏匿名输入框。

**Comment by lewky** [comment]
这两天我也遇到这个了。。

**Comment by lewky** [comment]
> 1. 可以开启审核关闭通知忽略这些垃圾评论
> 2. 可以升级到最新版开启登录才允许评论功能。确保服务端更新到最新版本 0.26.0，然后增加 `LOGIN=force` 环境变量，同时博客 Waline 客户端增加 `login=force` 的配置用于隐藏匿名输入框。

为什么我在vercel那边配置了COMMENT_AUDIT=true后，评论审核发布功能依然不生效，评论还是可以不经过审核就直接发布出去了，已经重启过服务端了。

**Comment by Mister-Hope** [comment]
> > 1. 可以开启审核关闭通知忽略这些垃圾评论
> > 2. 可以升级到最新版开启登录才允许评论功能。确保服务端更新到最新版本 0.26.0，然后增加 `LOGIN=force` 环境变量，同时博客 Waline 客户端增加 `login=force` 的配置用于隐藏匿名输入框。
> 
> 为什么我在vercel那边配置了COMMENT_AUDIT=true后，评论审核发布功能依然不生效，评论还是可以不经过审核就直接发布出去了，已经重启过服务端了。

其他人也有遇到，建议删除旧的 deploy 环境

**Comment by lewky** [comment]
> > > 1. 可以开启审核关闭通知忽略这些垃圾评论
> > > 2. 可以升级到最新版开启登录才允许评论功能。确保服务端更新到最新版本 0.26.0，然后增加 `LOGIN=force` 环境变量，同时博客 Waline 客户端增加 `login=force` 的配置用于隐藏匿名输入框。
> > 
> > 
> > 为什么我在vercel那边配置了COMMENT_AUDIT=true后，评论审核发布功能依然不生效，评论还是可以不经过审核就直接发布出去了，已经重启过服务端了。
> 
> 其他人也有遇到，建议删除旧的 deploy 环境，并确保你没有用 build cache，经检查我们的代码是没有问题的，问题可能发生在攻击者仍在访问旧的示例。目前我们也没有很好的调试方法。

vercel的build cache要怎么禁止呢？我在Build Logs里有看到 Uploading build cache 之类的log

**Comment by oCoke** [comment]
> vercel的build cache要怎么禁止呢？我在Build Logs里有看到 Uploading build cache 之类的log

在更新环境变量后需要重新部署，在重新部署时会有 Build Cache 的选项，不选就好了。

**Comment by Mister-Hope** [comment]
因为该issue的实际问题已经解决，所以计划关闭😀
