### ISSUE TITLE
[BUG]无法显示已存在的评论

### ISSUE THREAD

**Issue by Nofated095** [walinejs/waline#432]
**问题描述 | Describe the bug**

在评论完成之后，刷新页面无法显示已经存在评论（即使不刷新也都没有），但是评论在Leancloud中已经被储存在数据库中
**问题网站 | Website URL**

https://blog-waline-comment.vercel.app

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [-] Vercel
  - [ ] CloudBase
  - [ ] Docker
  - [ ] VPS, Virtual Host
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [-] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [ ] CloudBase
  - [ ] MongoDB
  - [ ] MySQL
  - [ ] SQLite
  - [ ] PostgreSQL
  - [ ] GitHub

**Comment by lizheming** [comment]
后台看一下评论应该是进待审核或者垃圾评论里了。

**Comment by Nofated095** [comment]
后台中显示的两个评论都是已经通过审核的，但是仍然没有显示

**Comment by lizheming** [comment]
提供一下地址我们看一下

**Comment by Nofated095** [comment]
https://blog-waline-comment.vercel.app/

**Comment by lizheming** [comment]
需要你的博客地址

**Comment by Nofated095** [comment]
数据库已经存在两个评论

**Comment by Nofated095** [comment]
博客中还没有实装

**Comment by Nofated095** [comment]
是因为没有实装的问题么

**Comment by lizheming** [comment]
![image](https://user-images.githubusercontent.com/424491/126582903-f025e794-bedb-490d-ab87-000150f3d029.png)
是这两条么

**Comment by Nofated095** [comment]
是的

**Comment by Nofated095** [comment]
![Uploading E7D3C6AD-78AB-4835-B512-5C1254C169D8.png…]()
