### ISSUE TITLE
[建议]希望能支持本地自定义用户头像

### ISSUE THREAD

**Issue by AkariLiu** [walinejs/waline#440]
考虑到Gratavar不是每个人都能访问，所以希望能直接在用户资料里面自定义头像。

**Comment by lizheming** [comment]
官方可能暂时还不会考虑这件事，主要是 Gravatar 在不同的评论系统之间都有很不错的通用性，对用户来说还是比较友好的。当然如果有同学愿意帮忙实现这个特性的话我们也是非常乐意的。

**Comment by LiuDarkShaoYe** [comment]
但是不同地区的访问情况天差地别，所以可能有部分地区无法访问Gravatar。

**Comment by lizheming** [comment]
头像的话目前通过国内镜像代理的方式还可以接受，官网的话那就只能各凭本事了。这个需求可以做，如果你有想法的话欢迎提 PR 呀~

**Comment by leirock** [comment]
我觉得本地自定义头像是挺好的，可以不需要做成需要用户登录+上传头像的形式。因为我毕竟倾向于让读者可以不需要注册就评论，这里提供一个免注册评论的情况下头像显示想法：

- 简化一下，就提供大概10个默认的头像，填写评论的时候，填写昵称、邮箱、网址后，还可以从这几个默认头像中选择其中一个作为显示的头像，这样也避免了用 Gravatar 头像的时候有些人没有给邮箱设置头像的问题，管理员也不需要考虑上传头像的审核、存储问题。

- 当然也可以用外部图床的方式来自定义头像（就像现在评论框上传图片到图床一样），然后cookies会存储一下头像链接（就像存储昵称、邮箱一样）。

**Comment by Lfhsheng** [comment]
QQ倒是可以

**Comment by lizheming** [comment]
`@waline/vercel@1.11.0`增加了头像修改功能，登录后在后台资料页点击头像，会出现地址输入框，填写一个头像地址后会更新为你的头像。

**Comment by EamonNKU** [comment]
目前的头像代理貌似需要翻墙
