### ISSUE TITLE
[BUG]未被验证的用户依旧能发表评论 | Unverified users can still post comments

### ISSUE THREAD

**Issue by akuraito** [walinejs/waline#443]
**问题描述 | Describe the bug**

未被验证的用户依旧能发表评论 | Unverified users can still post comments

当用户使用任意邮箱注册后，无需点击验证链接也可登录并发表评论。

**问题网站 | Website URL**

https://comment.404gle.cn/
[![fFtoge.gif](https://z3.ax1x.com/2021/08/03/fFtoge.gif)](https://imgtu.com/i/fFtoge)

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [*] Vercel

- 数据存储在哪里？| Where your comment data store?
  - [*] LeanCloud(https://leancloud.app)

**Comment by Mister-Hope** [comment]
图片链接损坏。另外未提供任何复现思路。
![image](https://user-images.githubusercontent.com/33315834/128118579-99ed0697-b388-4971-b396-6c68162ee4b4.png)

**Comment by lizheming** [comment]
@Mister-Hope 这个我看到了已经，我之后跟进一下吧。

**Comment by akuraito** [comment]
> 图片链接损坏。另外未提供任何复现思路。
> ![image](https://user-images.githubusercontent.com/33315834/128118579-99ed0697-b388-4971-b396-6c68162ee4b4.png)

图片过大而无法加载，请尝试右键直接打开图片或链接
https://z3.ax1x.com/2021/08/03/fFtoge.gif

**Comment by lizheming** [comment]
该 Bug 已修复，请升级服务端至 `@waline/vercel@0.26.2`。感谢反馈！
