### ISSUE TITLE
[BUG] 无法评论 SQLITE_CONSTRAINT: NOT NULL constraint failed: wl_Comment.status

### ISSUE THREAD

**Issue by yiyungent** [walinejs/waline#449]
**问题描述 | Describe the bug**

登录后，无法评论

![image](https://user-images.githubusercontent.com/16939388/128223017-77117010-1e6a-4f05-bf10-866072f5e1fc.png)

> PS: 发现无法保持评论的登录状态的，每次到一个新文章页，都需要重新登录

**问题网站 | Website URL**

- https://moeci.com/posts/supervisor-notebook/

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [ ] Vercel
  - [ ] CloudBase
  - [x] Docker
  - [ ] VPS, Virtual Host
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [ ] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [ ] CloudBase
  - [ ] MongoDB
  - [ ] MySQL
  - [x] SQLite
  - [ ] PostgreSQL
  - [ ] GitHub

**Comment by lizheming** [comment]
测试贵站是可以评论的，如果问题解决请帮忙关闭下 Issue，谢谢啦~ 
PS. 使用账密登录勾选保持登录是可以记住登录的

**Comment by yiyungent** [comment]
> 测试贵站是可以评论的，如果问题解决请帮忙关闭下 Issue，谢谢啦~
> PS. 使用账密登录勾选保持登录是可以记住登录的

发现了，用第一个注册的管理员账号，无法评论

邮箱: i@moeci.com
密码: 123456789

**Comment by lizheming** [comment]
@yiyungent 感谢反馈，我在本地已可以复现。晚上再处理下这个问题

**Comment by lizheming** [comment]
你好 @waline/vercel@0.26.3 已修复该问题，请升级后在试试，感谢反馈。
