### ISSUE TITLE
[BUG] 注册成功后登录后台不显示评论

### ISSUE THREAD

**Issue by hotarugali** [walinejs/waline#450]
**问题描述 | Describe the bug**

按照文档将 waline 服务端成功部署到 vercel 上，但注册登录评论后台发现并没有显示出已有的评论，而且只有 `profile` 页面。并且初次注册成功后，使用 `<url.app>/ui` 访问网址会一直重定向跳转。
 
![image](https://user-images.githubusercontent.com/32862896/128243030-a3a1668d-a665-40c1-9283-6000b0c443c1.png)

**问题网站 | Website URL**

[https://waline-one-beta.vercel.app/ui](https://waline-one-beta.vercel.app/ui)

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [x] Vercel
  - [ ] CloudBase
  - [ ] Docker
  - [ ] VPS, Virtual Host
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [x] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [ ] CloudBase
  - [ ] MongoDB
  - [ ] MySQL
  - [ ] SQLite
  - [ ] PostgreSQL
  - [ ] GitHub

**Comment by Mister-Hope** [comment]
请检查leancloud的user数据库，并检查你的帐号type是不是admin

**Comment by BlueHeart0621** [comment]
可以了，感谢！

**Comment by drinktea1a** [comment]
hello，大佬，使用非管理员的邮箱注册后登录ui，一直被redirect到/ui/地址，不知道是什么原因。

**Comment by lizheming** [comment]
@drinktea1a 非管理员没有首页的访问权限，只有 profile 页面的权限
