### ISSUE TITLE
非登录评论添加验证码

### ISSUE THREAD

**Issue by hydrogenoxide-user** [walinejs/waline#453]
**问题描述 | Describe the bug**

就今天被一直刷乱码评论，一秒一个，反垃圾过滤根本招架不住。以后是否有计划添加验证码功能？
**问题网站 | Website URL**

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [ ] Vercel
  - [ ] CloudBase
  - [ ] Docker
  - [ *] VPS, Virtual Host
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [* ] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [ ] CloudBase
  - [ ] MongoDB
  - [ ] MySQL
  - [ ] SQLite
  - [ ] PostgreSQL
  - [ ] GitHub

**Comment by Lfhsheng** [comment]
可以搞一个人机验证
![2022-01-15-10-26-01](https://user-images.githubusercontent.com/74490140/149605514-a4917001-e088-49c7-a051-5d8afc935b50.png)
通过在按钮内移动鼠标来进行人机验证
检测到是手机的话就搞点击验证

**Comment by appotry** [comment]
第三方人机验证应该可以实现， 腾讯人机验证有过滤恶意评论功能。流量小的免费，个人使用免费版完全够用

**Comment by lizheming** [comment]
@appotry 有相关文档么，我看腾讯的验证码说的是2w次免费？

**Comment by appotry** [comment]
@lizheming  官方文档 https://cloud.tencent.com/document/product/1110/36841

费用说明 https://cloud.tencent.com/document/product/1110/36337

现在才免费2万次，7天。  记得我当时申请的，可以免费半年，越来越扣了

**Comment by LxnChan** [comment]
我觉得加个Google reCaptcha就行，让用户把Key和地址丢在data里面

**Comment by qystudio0** [comment]
hcaptcha真的没必要，慢死

**Comment by Mister-Hope** [comment]
显然不是

**Comment by lrhtony** [comment]
> Google reCAPTCHA 国内是可以正常使用的吗？

将引用的js地址`www.google.com`换成`www.recaptcha.net`可以在大陆地区加载，但注册和数据查看还得到google上去

**Comment by LxnChan** [comment]
> Google reCAPTCHA 国内是可以正常使用的吗？

 换个域名就能在国内用

**Comment by LxnChan** [comment]
> hcaptcha真的没必要，慢死

+1

> 极验：https://www.geetest.com/Sensebot
vaptcha：https://www.vaptcha.com/
腾讯T-Sec：https://cloud.tencent.com/product/captcha
reCAPTCHA：https://www.google.com/recaptcha/about/
hcaptcha：https://www.hcaptcha.com/

Geetest是收费的吧

**Comment by qystudio0** [comment]
> 显然不是

似乎我没有影响，以为我的其他项目正常，(深圳移动)

**Comment by w0oo** [comment]
> > hcaptcha真的没必要，慢死
> 
> +1
> 
> > 极验：https://www.geetest.com/Sensebot
> > vaptcha：https://www.vaptcha.com/
> > 腾讯T-Sec：https://cloud.tencent.com/product/captcha
> > reCAPTCHA：https://www.google.com/recaptcha/about/
> > hcaptcha：https://www.hcaptcha.com/
> 
> Geetest是收费的吧

Geetest免费额度500次

**Comment by Lfhsheng** [comment]
> 可以搞一个人机验证 ![2022-01-15-10-26-01](https://user-images.githubusercontent.com/74490140/149605514-a4917001-e088-49c7-a051-5d8afc935b50.png) 通过在按钮内移动鼠标来进行人机验证 检测到是手机的话就搞点击验证

类似于这样的可以免费哦（

**Comment by Lfhsheng** [comment]
> > 可以搞一个人机验证 ![2022-01-15-10-26-01](https://user-images.githubusercontent.com/74490140/149605514-a4917001-e088-49c7-a051-5d8afc935b50.png) 通过在按钮内移动鼠标来进行人机验证 检测到是手机的话就搞点击验证
> 
> 类似于这样的可以免费哦（

不过不知道有没有bug🌚

**Comment by lbroot** [comment]
支持

**Comment by so1ve** [comment]
没必要

**Comment by StarWEB890** [comment]
补充一个Luosimao：https://luosimao.com/

**Comment by qystudio0** [comment]
确实谷歌的v3可以做的无感验证，换个链接就可以做的正常访问

**Comment by qystudio0** [comment]
确实谷歌的v3可以做的无感验证，换个链接就可以做的正常访问

**Comment by appotry** [comment]
搞一个简单的加减乘除计算验证测试？ 

还利用程序生成背景噪音影响OCR，甚至不用管OCR图片识别突破就能拦截90%以上违规刷评论了

**Comment by qystudio0** [comment]
emmm使用无感验证不是更好吗

**Comment by lizheming** [comment]
最新版已添加了 reCAPTCHA v3 的支持，食用方法：
1. 确保 `@waline/client` >= 2.10.0 以及 `@waline/vercel` >= 1.22.0（后台前端版本是 `@waline/admin` >= 0.20.0 不需要手动操作）
2. 去 <https://www.google.com/recaptcha/> 申请网站密钥和服务端密钥
3. 前端 `@waline/client` 配置 `recaptchaV3Key` 为网站密钥
4. 服务端 `@waline/vercel` 配置 `RECAPTCHA_V3_KEY` 为网站密钥，`RECAPTCHA_V3_SECRET` 为服务端密钥（此处网站密钥是给后台使用的）
