### ISSUE TITLE
[BUG] TCB 表情包转义问题

### ISSUE THREAD

**Issue by JaxsonWang** [walinejs/waline#454]
**问题描述 | Describe the bug**

和置顶表情包转义问题一样。确保服务端程序是最新版的。

后来咨询下腾讯云工程师，猜测是规则被修改了，是否需要更新依赖指定版本或者修改工程师反馈的建议？

<img width="770" alt="iShot2021-08-06 21 19 15" src="https://user-images.githubusercontent.com/16836692/128516390-6881bdf4-6ae8-44ce-baf0-0a1257fc5a40.png">

**问题网站 | Website URL**

无

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [ ] Vercel
  - [x] CloudBase
  - [ ] Docker
  - [ ] VPS, Virtual Host
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [ ] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [x] CloudBase
  - [ ] MongoDB
  - [ ] MySQL
  - [ ] SQLite
  - [ ] PostgreSQL
  - [ ] GitHub

**Comment by lizheming** [comment]
你好，已经按照沟通内容改成 latest 了，请重新尝试一下

**Comment by JaxsonWang** [comment]
感谢修复，测试没有问题了，表情功能正常。
