### ISSUE TITLE
[建议]建议增加对cravatar的支持

### ISSUE THREAD

**Issue by WhitemuTeam** [walinejs/waline#479]
Cravatar 是 Gravatar 在中国的完美替代方案，用户可以上传他们的头像至Cravatar，同时也完美兼容Gravatar的API接口，适用于无法访问Gravatar的全体中国用户，尽管在讨论区已经谈及此建议

**Comment by lizheming** [comment]
https://github.com/walinejs/waline/discussions/464 discussion 中的方案不能满足吗？

**Comment by WhitemuTeam** [comment]
> #464 discussion 中的方案不能满足吗？

不是人人都有这个功夫和时间更改opinion，况且Waline管理界面仍使用的是Gravatar头像

**Comment by Mister-Hope** [comment]
> > #464 discussion 中的方案不能满足吗？
> 
> 不是人人都有这个功夫和时间更改opinion，


也不是每个Waline用户都是中国人

> 况且Waline管理界面仍使用的是Gravatar头像

@lizheming 我觉得可以加个选项支持一下。

**Comment by Mister-Hope** [comment]
Libravatar 已经成为 client 和 server 的默认选项。由于 cravatar 和 gravatar 接口相同，现有逻辑也不需要调整，可自行配置。

另外如果没有功夫和时间更改option的话，推荐不用评论，更省事儿。
