### ISSUE TITLE
[BUG]配置邮件通知成功后，无法定位到评论所在的具体文章

### ISSUE THREAD

**Issue by nanchaoke** [walinejs/waline#480]
![image](https://user-images.githubusercontent.com/70080368/130355745-7c385cd8-b67b-4c89-b702-9a2e600881f4.png)

“查看回复的完整內容” 中不包含链接，无法点击跳转到具体的文章页。
这是什么原因？

**Comment by lizheming** [comment]
https://github.com/walinejs/waline/blob/main/packages/server/src/service/notify.js#L48 这是邮件模板中链接的拼接方式，可以看一下各个参数全不全 `SITE_URL` 有没有配等。

**Comment by nanchaoke** [comment]
> https://github.com/walinejs/waline/blob/main/packages/server/src/service/notify.js#L48 这是邮件模板中链接的拼接方式，可以看一下各个参数全不全 `SITE_URL` 有没有配等。

谢谢！已经解决，url 没有写协议部分，直接上的域名，所以出问题了。
