### ISSUE TITLE
[BUG] IPQPS 不起作用

### ISSUE THREAD

**Issue by cxplay** [walinejs/waline#482]
**问题描述 | Describe the bug**

Vercel 环境配置 IPQPS 值为 "0", 依旧提示评论过快
![image](https://user-images.githubusercontent.com/62034099/130479233-e63974f7-432e-459a-a100-4e57a1d8adb1.png)

![image](https://user-images.githubusercontent.com/62034099/130479175-d1ee4710-5f5e-4826-b1e1-8c59c5b3c858.png)

**问题网站 | Website URL**

https://comment.cxplay.org/

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [x] Vercel
  - [ ] CloudBase
  - [ ] Docker
  - [ ] VPS, Virtual Host
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [ ] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [ ] CloudBase
  - [ ] MongoDB
  - [x] MySQL
  - [ ] SQLite
  - [ ] PostgreSQL
  - [ ] GitHub

**Comment by lizheming** [comment]
环境变量修改之后需要重新部署一下

**Comment by cxplay** [comment]
重新部署过了, 还是这样的

**Comment by lizheming** [comment]
服务端版本是最新的吗？

**Comment by cxplay** [comment]
![image](https://user-images.githubusercontent.com/62034099/130580751-de792970-2f84-4009-bf0f-a1c810394c8d.png)

**Comment by Mister-Hope** [comment]
代码上似乎看不出问题.....

https://github.com/walinejs/waline/blob/84e1543356369a952c4f3ae433dcc078064b8be0/packages/server/src/controller/comment.js#L286-L297

本地复现使用 leancloud也一切正常，我翻了一下 MySQL 的代码，发现调用的 thinkJS 的内部逻辑... @lizheming 有空的时候看看那边的逻辑？

**Comment by lizheming** [comment]
本地我测试了功能是 OK 的。你检查一下你的 MySQL 配置的时区对不对，确认下是不是时区的问题。

**Comment by cxplay** [comment]
好的👌

**Comment by cxplay** [comment]
![image](https://user-images.githubusercontent.com/62034099/130640454-a228aced-fd18-416c-9b4f-1a697a870f8b.png)
![image](https://user-images.githubusercontent.com/62034099/130640720-1f6c38b8-5ad3-4408-b1b9-8ae19a2a2f83.png)
---
![image](https://user-images.githubusercontent.com/62034099/130640474-388313b9-3552-433d-8f32-ec57b143f9ce.png)
![image](https://user-images.githubusercontent.com/62034099/130641038-1a7d4bd0-c83a-4fff-9cc2-d7d9af62ee61.png)
---
目前使用的 MySQL 中的是同步 SYSTEM 时间

**Comment by lizheming** [comment]
你看看存储数据里的 `insertedAt` 字段的时间对不对

**Comment by cxplay** [comment]
![image](https://user-images.githubusercontent.com/62034099/130642286-14f11e5c-dd9f-4dc8-ad76-1b14c7821e59.png)

刚发了一条当前时间的评论, 是正确的

**Comment by lizheming** [comment]
那应该是 Vercel 那边的时区不正确了… 上后台看看打印日志搜一下 insertedAt 关键字。或者你可以设置 IPQPS=-28800 看看还有没有问题确认一下……

**Comment by cxplay** [comment]
好的

**Comment by cxplay** [comment]
![image](https://user-images.githubusercontent.com/62034099/130643461-2adfc2a9-f968-4c25-a163-0229fc0ee945.png)

Vercel 这里的 insertedAt 时间对不上了...

**Comment by lizheming** [comment]
我记得 issue 里有说 vercel 时区设置的，好像是 TZ 环境变量，不过不是非常确定，可以试试。不行的话你就直接配 IPQPS 为负数吧，效果是一样的。

**Comment by cxplay** [comment]
好的我再试试负数 IPQOS

**Comment by cxplay** [comment]
负数 IPQPS 似乎起效了, 连续评论也没有被禁止了.
![image](https://user-images.githubusercontent.com/62034099/130644390-0aa4911f-89cb-4003-ad14-068483567c14.png)

**Comment by Mister-Hope** [comment]
Emm, 我感觉这里我们是不是可以再做点处理啥的？统一使用 UTC 判断不就没有时区问题了么？@lizheming

**Comment by lizheming** [comment]
目前是使用时间戳处理的，字符串做比较多有不便。

**Comment by terwer** [comment]
设置成负数也不行。我是阿里云国内版，用的rds

![image](https://user-images.githubusercontent.com/3259282/231630484-dcf784ce-f400-4405-8b72-3c39639d7ea9.png)
![image](https://user-images.githubusercontent.com/3259282/231630508-2bae4436-ac1f-4016-b749-292704656461.png)
![image](https://user-images.githubusercontent.com/3259282/231630573-4b03a053-4ee2-4a2f-aa2b-e431b632f3b3.png)
![image](https://user-images.githubusercontent.com/3259282/231630632-4e9dae0d-8676-4465-9419-37f5100ce64a.png)

**Comment by lizheming** [comment]
@terwer 设置成 -28800 试试，非常大概率还是时区问题，除了校验数据库时区还需要校验服务器时区。

**Comment by terwer** [comment]
可以了，非常感谢！
再次感谢作者提供的这个好用的评论系统！
