### ISSUE TITLE
建议增加限制字符数的功能

### ISSUE THREAD

**Issue by zj713300** [walinejs/waline#489]
如题，为数据库的健壮性考虑。

**Comment by Mister-Hope** [comment]
那样的话，这个限制数据应该设置在server侧，不然client还是可以强行提交。

**Comment by lizheming** [comment]
这个暂时不加了吧，除了关系型数据库有这个问题，似乎 NoSQL 这块没有这种限制。如果不做限制的话，长评论会由于超过 SQL 限制插入失败从而导致接口报错。所以影响其实还好。

**Comment by zj713300** [comment]
qwq，我就是SQL用户，那好叭……

**Comment by Mister-Hope** [comment]
还是在这里说一下现有情况下大致的解决思路吧。

（万一哪天再来为大仙炸用户数据库玩🌚）

server提供了强大的钩子，如果你的确有相关考虑不希望用户甚至攻击者直接通过接口传入大量数据，你可以在 preCommit hook对用户发来的评论进行检测，超过一定长度直接返回，并给出相应的 errMsg

**Comment by Mister-Hope** [comment]
所以换而言之，@zj713300 你可以用现有的配置实现这个功能。
