### ISSUE TITLE
[Enhance] Change `comment?type=count` api

### ISSUE THREAD

**Issue by Mister-Hope** [walinejs/waline#502]
Now the api return `number` with single path and `number[]` with mutiple path, suggesting changing to  `number[]` consistently.

Cuz we are not sure how many comment element are on the page, we always assume there are mutiple elements in coding. So it should be more reasonable, confortable and consistent to return an array all the time.

All v1 versions are compatable with this change.

**Comment by lizheming** [comment]
count api return `number` and `number[]` just for difference scene. And the break change need other client compatible for it, I think we can keep it right now.
