### ISSUE TITLE
部署到自己服务器上遇到的问题

### ISSUE THREAD

**Issue by ZHANG-0317** [walinejs/waline#510]
**问题描述 | Describe the bug**

![image](https://user-images.githubusercontent.com/72189547/131221324-d74a22d0-67c1-4169-84a2-2f7be851b21c.png)
准备将服务端部署到自己的云服务器，但是在执行上面命令时，报错：
![image](https://user-images.githubusercontent.com/72189547/131221359-7778634a-aa23-4f7e-b72b-f43e8f1cf7b8.png)
![image](https://user-images.githubusercontent.com/72189547/131221382-e90f5b9a-1433-40c6-9b28-c3eb304fdcc5.png)

查遍全网也没有合适的解决方式，望解答

**Comment by lizheming** [comment]
sqlite 的安装依赖网络，如果不使用 sqlite 模块的可以忽略该错误。如果需要使用的话请 Google 搜索”sqlite npm 安装“，这里给一下解决方案
```
npm config set node_sqlite3_binary_host_mirror=http://npm.taobao.org/mirrors/
npm install sqlite3
```
另外，如果不是 JS 开发同学的话还是建议你使用 Docker 方式部署，对依赖的问题会少一点。

第二章截图请先看一下相关 issue https://github.com/walinejs/waline/search?q=Not+initialized&type=issues

**Comment by Mister-Hope** [comment]
Closed as all the issue has been answered and not recent activity
