### ISSUE TITLE
[BUG]邮件通知失效

### ISSUE THREAD

**Issue by xiyizhou** [walinejs/waline#518]
**问题描述 | Describe the bug**

刚设置时，邮件通知测试是正常的。
后面就不管用了
**问题网站 | Website URL**

 https://inote.xyz

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?

  - [ ] CloudBase

- 数据存储在哪里？| Where your comment data store?
  - [ ] CloudBase
- SMTP
  - [ ] Gmail

**Comment by lizheming** [comment]
可以进 CloudBase 看看发布评论时候的日志~

**Comment by JaxsonWang** [comment]
@lizheming 我和他一样环境，一开始确实是好好的，后来升级版本就莫名其妙失效了，日志如下：

```json
{
    "msg": "\"\\u001b[36m[2021-09-03T05:45:13.927] [8] [DEBUG]\\u001b[39m - Post Comment initial Data: {\\n link: '',\\n mail: '',\\n nick: '测试测试',\\n pid: undefined,\\n rid: undefined,\\n ua: 'Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1',\\n url: '/vue3-second-submission-of-ref-syntactic-sugar-experience/',\\n ip: '49.82.136.76',\\n insertedAt: 2021-09-03T05:45:13.906Z,\\n comment: '<p>感谢分享</p>\\\\n',\\n user_id: undefined\\n}\"",
    "level": "log",
    "src": "app",
    "requestId": "610d1063-0c79-11ec-9a42-22b532234c9c",
    "function": "main",
    "timestamp": "1630647913929097"
}
```

---

```json
{
    "msg": "\"\\u001b[36m[2021-09-03T05:44:21.192] [8] [DEBUG]\\u001b[39m - Post Comment initial Data: {\\n link: '',\\n mail: '',\\n nick: '测试测试',\\n pid: undefined,\\n rid: undefined,\\n ua: 'Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Mobile/15E148 Safari/604.1',\\n url: '/vue3-second-submission-of-ref-syntactic-sugar-experience/',\\n ip: '49.82.136.76',\\n insertedAt: 2021-09-03T05:44:21.173Z,\\n comment: '<p>感谢分享</p>\\\\n',\\n user_id: undefined\\n}\"",
    "level": "log",
    "src": "app",
    "requestId": "60446ff5-0c79-11ec-aa4a-129dd0f7e4d8",
    "function": "main",
    "timestamp": "1630647861194829"
}
```

**Comment by Meow-2** [comment]
配置完成后收不到邮件，重新尝试过几次依旧无法成功。
- 问题站点：https://fly.meow-2.com
- 服务部署：Vercel
- 数据存储：learncloud国际版
- SMTP：outlook，
log如下：
>[2021-09-03T18:50:25.051] [9] [DEBUG] - Post Comment Start!
[2021-09-03T18:50:25.098] [9] [DEBUG] - Post Comment initial Data: {
  link: '',
  mail: '',
  nick: 'ping',
  pid: undefined,
  rid: undefined,
  ua: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36 Edg/92.0.902.84',
  url: '/post/hello-world.html',
  ip: '8.45.151.235',
  insertedAt: 2021-09-03T18:50:25.054Z,
  comment: '<p>sadfsdafasdxzcv</p>\n',
  user_id: undefined
}
[2021-09-03T18:50:25.101] [9] [DEBUG] - Comment IP 8.45.151.235 check OK!
[2021-09-03T18:50:25.381] [9] [DEBUG] - Comment duplicate check OK!
[2021-09-03T18:50:25.659] [9] [DEBUG] - Comment post frequence check OK!
[2021-09-03T18:50:25.660] [9] [DEBUG] - Comment initial status is approved
[2021-09-03T18:50:25.725] [9] [DEBUG] - Comment akismet check result: approved
[2021-09-03T18:50:25.726] [9] [DEBUG] - Comment keyword check result: approved
[2021-09-03T18:50:25.726] [9] [DEBUG] - Comment post hooks preSave done!
[2021-09-03T18:50:25.992] [9] [DEBUG] - Comment have been added to storage.
Mail send fail: [Error: 139784256632704:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
] {
  library: 'SSL routines',
  function: 'ssl3_get_record',
  reason: 'wrong version number',
  code: 'ESOCKET',
  command: 'CONN'
}
[2021-09-03T18:50:26.033] [9] [DEBUG] - Comment notify done!
[2021-09-03T18:50:26.033] [9] [DEBUG] - Comment post hooks postSave done!
