### ISSUE TITLE
GitHub 登录后无法显示头像，在文档中评论会被自动删除

### ISSUE THREAD

**Issue by zywvvd** [walinejs/waline#523]
### Discussed in https://github.com/walinejs/waline/discussions/522

<div type='discussions-op-text'>

<sup>Originally posted by **zywvvd** September  3, 2021</sup>
GitHub 登录后无法显示头像
![](https://photos.zywvvd.com/win11-mt/20210903143246.png)
在文档中评论会被自动删除
文档链接：https://waline.js.org/guide/client/avatar.html#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9
![](https://photos.zywvvd.com/win11-mt/20210903143333.png)
然后再刷新就没了
![](https://photos.zywvvd.com/win11-mt/20210903143401.png)</div>

**Comment by lizheming** [comment]
`@waline/vercel@0.26.8` 已修复该问题，感谢反馈。
