### ISSUE TITLE
[BUG] 使用Safari 13浏览器访问时接口报错的调试过程

### ISSUE THREAD

**Issue by HiKarry** [walinejs/waline#531]
之前我在Safari 13浏览器使用waline时发现获取评论列表的接口出错了，访问了：
```
http://localhost:9000/undefined/comment?path=undefined&pageSize=undefined&page=1
```

最近我在本地运行了waline，大概找到了bug产生的原因，下面说一下查找bug的过程以供参考。

首先在js代码里搜索关键字`comment`，找到了请求评论列表的代码，可以发现传进来的变量基本为`undefined`：

![image](https://user-images.githubusercontent.com/39751742/132312050-52799a6b-9d04-4dd0-b585-5ac7679bfc90.png)

在代码调用堆栈往回找，发现有些变量是通过`...config.value`传进来的：

![image](https://user-images.githubusercontent.com/39751742/132312627-b6d43927-9fef-47a6-b000-e5da4ef3a1a7.png)

在控制台打印一下结果，发现使用`...`操作符得到的是空字典：

```
> config.value
Proxy {el: "#waline", serverURL: "http://localhost:9090", path: "/", lang: "zh-CN", locale: Object, …}

> {...config.value}
{}
```

而在Chrome浏览器打印结果，得到的字典是有值的：
```
> config.value
Proxy {el: '#waline', serverURL: 'http://localhost:9090', path: '/', lang: 'zh-CN', locale: {…}, …}

> {...config.value}
{el: '#waline', serverURL: 'http://localhost:9090', path: '/', lang: 'zh-CN', locale: Proxy, …}
```

猜想Safari浏览器使用`...`语法会有问题，但是测试了以下语句又是正常的：
```
> var object = new Object();
  object.path = "xxx";
  console.log({...object});
{path: "xxx"}
```

所以，问题很可能出在`config.value`身上，`config.value`的类型是`Proxy`，在网上搜了一下发现是`Vue`的类，猜想对这个类进行`...`操作可能有问题。

而在调试的过程中，我发现`config`还有一个`_rawValue`的属性，应该是`value`的原始数据：

![image](https://user-images.githubusercontent.com/39751742/132316059-7248d64b-2d52-48d2-befc-e4fe4addc0c9.png)

打印一下结果，发现字典有值了：
```
> {...config._rawValue}
{el: "#waline", serverURL: "http://localhost:9090", path: "/", lang: "zh-CN", locale: Proxy, …}
```

然后我修改了一下`Waline.vue`文件里这个方法：
```
      fetchCommentList({
        ...config._rawValue,
        page: pageNumber,
        signal,
      })
```

刷新网页后，请求评论的接口正常了：
```
http://localhost:9090/comment?path=%2F&pageSize=10&page=1
```

在Chrome试了一下也是OK的。

但是我没学过`Vue`，所以不知道这样修改会不会有问题，还是有更好的修改方法？

**Comment by Mister-Hope** [comment]
这。。。。怎么兼容啥的再说，但本质上我觉得这应该属于safari的bug。Proxy可以使用spread运算符，取其真实的值

**Comment by HiKarry** [comment]
我测试了一下：

**Comment by HiKarry** [comment]
我测试了一下，`Object.assign`可以获取到值：
```
> Object.assign({}, config.value)
{el: "#waline", serverURL: "http://localhost:9090", path: "/", lang: "zh-CN", locale: Proxy, …}
```

代码这样改可以正常请求数据：
``` js
      fetchCommentList({
        ...Object.assign({}, config.value),
        page: pageNumber,
        signal,
      })
```

搜了一下代码，用到`...`操作符的代码有这么多，不过不知道哪些是`Proxy`类型的：
``` js
src/composables/config.ts
24:    options = { ...options, ...newOptions };

src/Waline.vue
101:        ...Object.assign({}, config.value),
108:          data.value.push(...resp.data);

src/utils/emoji.ts
52:        ...emojiInfo,

src/utils/config.ts
73:  ...more
93:      ...$locale,
94:      ...(typeof locale === 'object' ? locale : {}),
122:    ...more,

src/components/CommentBox.vue
533:        setUserInfo({ ...userInfo.value, ...data });
```

**Comment by Mister-Hope** [comment]
好的感谢，回头我更正一下

**Comment by Mister-Hope** [comment]
A little bit busy these days, but I will try to fix this tonight.

**Comment by HiKarry** [comment]
Thanks.

**Comment by Mister-Hope** [comment]
A PR is created, but I can not test if it's working. ( It should work though)
