### ISSUE TITLE
[BUG] has been blocked by CORS policy: No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by XRSec** [walinejs/waline#542]
很抱歉我来打扰你们了

[博客](https://blog.zygd.site/) [评论系统](https://waline.zygd.site/comment?count=6&type=recent) 
在 leancloud 中 设置 安全域名已经绑定了我的博客 和 我的评论 但是目前文档里是没有要求绑定的

具体报错
```ini
Access to fetch at 'https://waline.zygd.site//comment?type=recent&count=6' from origin 'https://blog.zygd.site' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
vercel + leancloud 国际版 hexo 主题是 hexo-butterfly

目前是首页获取 最近评论异常，看样子是说cors 问题，但是不晓得是啥问题 

需要我做些什么直接告诉我就好
可能明天 回复的有点晚，不好意思！

**Comment by lizheming** [comment]
severURL 配置最后的斜线去掉，https://waline.zygd.site 就可以了

**Comment by Mister-Hope** [comment]
我印象中，这个配置是会处理的啊 @lizheming 

https://github.com/walinejs/waline/blob/63b3b6e0e41c73dd146f83b9e8a3a1486fa97c09/packages/client/src/utils/config.ts#L89

所以为什么还是会在1.3.4引发这个问题....

**Comment by XRSec** [comment]
谢谢大牛们，已经解决了，太强了
