### ISSUE TITLE
[BUG]iOS Safari 无法获取评论

### ISSUE THREAD

**Issue by icedtangerine7** [walinejs/waline#547]
**问题描述 | Describe the bug**
使用ios13.4.1系统的safari访问含有评论的博客页面，显示还没有评论，而pc端（firefox和chrome）和android 7.1（模拟器）自带浏览器访问该页面可以正常显示评论。
safari可以发出评论，但是刷新页面后仍会显示没有评论。而safari确实发出了评论（在pc端可见）
![image](https://user-images.githubusercontent.com/25699126/133068643-356c144c-594b-4541-8645-4df2397314d9.png)
![image](https://user-images.githubusercontent.com/25699126/133068594-afa89337-4e9d-457b-b13e-02778134e839.png)

**问题网站 | Website URL**
https://moe233.net/2021/06/18/blog%E6%9B%B4%E6%96%B0%E7%BB%B4%E6%8A%A4%E8%AE%B0%E5%BD%95/

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [x] Vercel
  - [ ] CloudBase
  - [ ] Docker
  - [ ] VPS, Virtual Host
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [x] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [ ] CloudBase
  - [ ] MongoDB
  - [ ] MySQL
  - [ ] SQLite
  - [ ] PostgreSQL
  - [ ] GitHub

**Comment by Mister-Hope** [comment]
Same as #531 , will be tracked there.
