### ISSUE TITLE
请教一下评论邮箱通知的问题

### ISSUE THREAD

**Issue by EmptyDreams** [walinejs/waline#551]
在发布评论后，`vercel`后台确时看到了内容，并且显示：`Notification mail send success: undefined` * 2。
我不知道这个是正常的输出还是不正常的输出，但是实际上我并没有收到邮件。
我的配置如下：
![QQ截图20210918144117](https://user-images.githubusercontent.com/44894906/133879124-d0f39dbd-6aa6-495f-b8e2-41de3949eefe.jpg)

**Comment by lizheming** [comment]
这个日志只能表示在 Waline 端邮箱配置没有问题，可以正常发送出去。但是邮件是否能正常收到取决于许多因素，有可能进垃圾邮件了，也有可能被邮件服务商的防火墙拦截了，这些都是有可能的。
你可以检查下垃圾箱，如果垃圾箱里也没有的话，可以多换几个邮箱服务试试。

**Comment by EmptyDreams** [comment]
> 这个日志只能表示在 Waline 端邮箱配置没有问题，可以正常发送出去。但是邮件是否能正常收到取决于许多因素，有可能进垃圾邮件了，也有可能被邮件服务商的防火墙拦截了，这些都是有可能的。
> 你可以检查下垃圾箱，如果垃圾箱里也没有的话，可以多换几个邮箱服务试试。

但是我这边在邮箱里面没有看到发件信息是怎么回事？

**Comment by lizheming** [comment]
那也有可能是发送邮件的服务商有问题？你换下试试吧。具体什么问题我也不清楚

**Comment by Mister-Hope** [comment]
请见 https://github.com/walinejs/waline/issues/483#issuecomment-904545195

我们这里使用的是外部依赖，而且 waline 这边的逻辑很简单，只要你正确配置了环境变量，waline就可以正确调起 nodemailer 。

所以你的问题可能出现在发送邮件的邮件提供商或者 nodemailer 本身 (可能性很小，因为 nodemailer 出现问题的话，控制台会出现它抛出的错误)

**Comment by xiyizhou** [comment]
需要添加博主邮箱环境变量 AUTHOR_EMAIL 才能收到邮件。

**Comment by EmptyDreams** [comment]
> 需要添加博主邮箱环境变量 AUTHOR_EMAIL ，当博客有新评论时，博主才能收到邮件。

我尝试添加了这个变量，依然没有收到邮件（我没有用我的邮箱评论

**Comment by Mantyke** [comment]
> > 需要添加博主邮箱环境变量 AUTHOR_EMAIL ，当博客有新评论时，博主才能收到邮件。
> 
> 我尝试添加了这个变量，依然没有收到邮件（我没有用我的邮箱评论

请问你现在解决了吗？我也遇到类似的问题

**Comment by Mister-Hope** [comment]
由于并未收到所需答复(如描述自己是哪个邮件服务商，其他邮件服务商是否正常等)，故关闭此 issue。
