### ISSUE TITLE
请求添加cloudflare workers或pages 的部署方式

### ISSUE THREAD

**Issue by 6oh** [walinejs/waline#572]
vercel经常会打不开，在某些地方也不行

**Comment by Mister-Hope** [comment]
你的pages指的是什么pages？

**Comment by lizheming** [comment]
cf workers 之前调研过，它的本质是支持 JavaScript 不是 Node.js，所以目前 Waline 的架构适配上不是特别友好，要做的话感觉只能重新写个服务端了，这样维护成本比较高。
可以试试国内的腾讯云云开发，或者自己独立部署，速度上都会有好转。

**Comment by Mister-Hope** [comment]
另外老实说，全国范围内，我不觉得cf worker会比vercel强太多。

http://mping.chinaz.com/Ping/SpeedTest/?host=vercel.app

http://mping.chinaz.com/Ping/SpeedTest/?host=workers.dev

由于worker有限制，而且是per request而不是持久化

> Up to 10ms CPU time per request

我个人觉得很难支持它。如果你的确觉得cf worker有更好的访问性你可以用它建一个反代代理你的vercel应用

**Comment by CXwudi** [comment]
抱歉时隔两年我挖坟了，题主提到了两个部署方式，worker和page，答主说了worker不行，但page是不是可行的，因为[cloudflare page](https://pages.cloudflare.com/)的功能跟vercel真的是太像了

**Comment by lizheming** [comment]
cf pages 是静态文件服务，不支持动态服务
