### ISSUE TITLE
是否能够支持在非登录情况下无法使用博主身份回复？

### ISSUE THREAD

**Issue by chen8945** [walinejs/waline#582]
非登录状态下使用博主邮箱回复虽然不会出现博主标识，但依旧可能存在有人恶意填写博主邮箱进行回复，所以是否能够禁止在非登录状态下填写博主邮箱进行回复

**Comment by Mister-Hope** [comment]
既然都已经没有博主标识了，就已经说明此评论不是博主。所以你的点在哪里？

如果你不想让别人冒名，不光是博主，任何人都可能冒充你的任何注册用户，你就应该直接把它关了。

如果这只是你的特殊需求，请自行使用hook，拒绝掉为登录用户填写博主邮箱评论。

总之，我不认为这是一个我们需要支持的东西。

**Comment by Mister-Hope** [comment]
如果你觉得你需要一个禁止使用已注册用户邮箱的功能，我觉得可以支持，cc @lizheming 


但是严格说来，waline不会泄漏用户邮箱。所以只要你不主动公布，应该不会有人恰好猜到。

**Comment by lizheming** [comment]
这两个都可以通过现有的钩子来实现，具体示例如下。由于感觉需求量不是很大，暂时就先不加入到代码中了，如果有需要可以执行配置实现。

```js
const Waline = require('@waline/vercel');

module.exports = Waline({
  async preSave(comment) {
    const isLogin = !think.isEmpty(this.ctx.state.userInfo);
    // 未登录不允许使用博主邮箱评论
    if(!isLogin && comment.mail === process.env.AUTHOR_MAIL) {
      return { errmsg: '这不是你的邮箱吧!' };
    }
    
    // 未登录不允许使用已注册额的用户邮箱
    const userModel = this.service(
      `storage/${this.config('storage')}`,
       'Users'
     );
    const user = await userModel.where({mail: comment.mail}).select();
    if(!isLogin && !think.Empty(user)) {
       return { errmsg: '未知错误' };
    }
  },
});
```

其中后面这个方案需要注意，不要暴露说邮箱已被注册的错误文案，防止被直接遍历库。

**Comment by chen8945** [comment]
> 这两个都可以通过现有的钩子来实现，具体示例如下。由于感觉需求量不是很大，暂时就先不加入到代码中了，如果有需要可以自行配置实现。
> 
> ```js
> const Waline = require('@waline/vercel');
> 
> module.exports = Waline({
>   async preSave(comment) {
>     const isLogin = !think.isEmpty(this.ctx.state.userInfo);
>     // 未登录不允许使用博主邮箱评论
>     if(!isLogin && comment.mail === process.env.AUTHOR_MAIL) {
>       return { errmsg: '这不是你的邮箱吧!' };
>     }
>     
>     // 未登录不允许使用已注册额的用户邮箱
>     const userModel = this.service(
>       `storage/${this.config('storage')}`,
>        'Users'
>      );
>     const user = await userModel.where({mail: comment.mail}).select();
>     if(!isLogin && !think.Empty(user)) {
>        return { errmsg: '未知错误' };
>     }
>   },
> });
> ```
> 
> 其中后面这个方案需要注意，不要暴露说邮箱已被注册的错误文案，防止被直接遍历库。

好的，谢谢两位的指导与帮助
