### ISSUE TITLE
关于 AVATAR_PROXY

### ISSUE THREAD

**Issue by jerryc127** [walinejs/waline#607]
新版本的 AVATAR_PROXY 是反代
那怎么设置 默认的头像 
我看 https://wiki.libravatar.org/api/ 是支持设置默认头像的
那是否考虑添加一个配置

如果设置了 avatar， 会变回旧的形式

**Comment by lizheming** [comment]
你好，现在增加了 `GRAVATAR_STR` 环境变量可以支持你自定义输出头像地址参数了可以按照下面这个配置试一下

`https://seccdn.libravatar.org/gravatarproxy/{{mail|md5}}?s=80`
