### ISSUE TITLE
hexo next 插件貌似无法记住登录状态。

### ISSUE THREAD

**Issue by wxsms** [walinejs/waline#624]
**问题描述 | Describe the bug**

如题，页面刷新一下就又变成未登录了。

**问题网站 | Website URL**

https://wxsm.space/

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [x] Vercel
  - [ ] Deta
  - [ ] CloudBase
  - [ ] Docker
  - [ ] VPS, Virtual Host
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [x] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [ ] CloudBase
  - [ ] MongoDB
  - [ ] MySQL
  - [ ] SQLite
  - [ ] PostgreSQL
  - [ ] GitHub

**Comment by yiyungent** [comment]
好耶，来一个和我一样的，我还以为就我有这问题，
登录后（勾选自动登录），然后刷新一下评论页面，就需要重新登录了，不过只要勾选了自动登录，那么只需要点击一下登录即可

https://moeci.com/posts/2021/11/github-action-readme/

**Comment by lizheming** [comment]
我看新版本应该刷新是已经 OK 了的，可以再 check 下
