### ISSUE TITLE
[功能需求] 是否可以增加为访客评论时，添加访客标识

### ISSUE THREAD

**Issue by itwxe** [walinejs/waline#625]
是否可以增加为访客评论时，和管理员一样为访客添加访客标识。

**Comment by Mister-Hope** [comment]
> 我目前的想法是给所有登录用户头像后面加一个微博、微信认证的那种标。

Is this ok for you? @itwxe

**Comment by itwxe** [comment]
> > 我目前的想法是给所有登录用户头像后面加一个微博、微信认证的那种标。
> 
> Is this ok for you? @itwxe

可以呀，我就是觉得没有一点标识太单调了，有标识好区分一点，最好和管理员标识的配色不一样，有点区分度

**Comment by akuraito** [comment]
1. ![image](https://user-images.githubusercontent.com/51032369/139814097-7b148625-e1d3-4c7d-8dc6-4cd96267a1e1.png)
昵称和此标记之间希望能增加空格，或置于头像右下角处如：
![image](https://user-images.githubusercontent.com/51032369/139814467-51f1140c-215d-4d87-b9a1-af379c8beb92.png)

2. 此标记能支持 `--waline-theme-color` 和 `--waline-active-color`

**Comment by akuraito** [comment]
管理员标记与登录标记是否可以合二为一，使用不同的标记以区分管理员、登录用户、GitHub 登录用户以及将来更多的登录选项。

**Comment by Mister-Hope** [comment]
我并没有想到，以不同方式登录的登录用户对其他人有什么区别。你看其他用户只是能看一个头像、昵称和网址。而这个头像和昵称打哪来的，无论对普通用户还是对管理员的大部分情景**应该都没有任何区别**。所以我同样反对添加多个图标。

另外那个管理员标签，是可以自定义的，没准有人还喜欢给自己加个什么“第一帅比”之类的标签，所以我觉得留着挺好的，你觉得呢？

关于那个主题色的问题，我再详说一下，你可以自己加个样式改一下，而默认的话，如果有人使用了红橙黄的主题色看起来会非常乖（我还真试了一下）

关于这个标签问题，@lizheming，我觉得如果管理后台支持给登录用户设置专属标签也许是个挺不错的功能，尤其对于个人博客来说对于生活中的熟人小伙伴之类的。

**Comment by akuraito** [comment]
也许是我的表述有问题，这不是请求**同时**实现置于右下角、跟随主题色、合二为一这几个特性，置于右下角的图标跟随主题色听起来就不靠谱。

我关心的仅是 `verified-icon` 在西文昵称后的视觉居中以及昵称之后的后缀过多过长的问题，尤其是管理员标识本身已经表示了登录这一状态。我的想法是在现有的管理员标识上进行改造以区分管理员、登录评论用户和访客，而置于头像右下角只是我认为不错的一种实现。自定义管理员标识自然需要不同的实现方式。

手动更改样式可以接受。

红橙黄挺好的 :-)

有个开关就更好了。

**Comment by lizheming** [comment]
请问这个 issue 是否已经解决？

**Comment by YiHui-Liu** [comment]
> 关于这个标签问题，@lizheming，我觉得如果管理后台支持给登录用户设置专属标签也许是个挺不错的功能，尤其对于个人博客来说对于生活中的熟人小伙伴之类的。

支持这一点

**Comment by lizheming** [comment]
@YiHui-Liu 专属标签功能已添加，另外新版还增加了等级标签
