### ISSUE TITLE
建议增加一个刷新按钮点击重新加载评论内容

### ISSUE THREAD

**Issue by real-nicholas** [walinejs/waline#626]
由于网络因素，很多时候无法显示评论的内容，可以加个刷新按钮吗？避免频繁F5的方式刷新页面来达到目的。

**Comment by real-nicholas** [comment]
你好！
据我观察，vercel 的评论服务（https://xxxxxx.vercel.app/）在国内一些地区访问延迟可能比较大。
测试过几十次吧，一般能访问通的情况下，时间大于1秒。访问不通的情况下，一般在800毫秒左右就超时或直接断掉连接了，浏览器提示：
Failed to load resource:
An SSL error has occurred and a secure connection to the server cannot be made.


下面是浏览器请求截图：

这是我本地的log，如图：
<img width="1169" alt="Screenshot 2021-10-30 at 14 10 15" src="https://user-images.githubusercontent.com/29486126/139522823-c2f83f07-0c55-4d33-a98b-528a4af4de2b.png">
<img width="1169" alt="Screenshot 2021-10-30 at 14 10 24" src="https://user-images.githubusercontent.com/29486126/139522825-3f0def5b-a6b4-414d-b345-61581d019495.png">

这是别人网站的log，如图：
<img width="1169" alt="Screenshot 2021-10-30 at 14 14 10" src="https://user-images.githubusercontent.com/29486126/139522857-347f8414-f6b9-4fd4-ad86-f33e2ad7b15b.png">


以上的网络请求中，都没有直接显示出HTTP的状态。
我的环境：mac OS 11.6，Safari：Version 15.0 (16612.1.29.41.4, 16612)
以上操作没有挂代理。

**Comment by Mister-Hope** [comment]
我先试试能不能在本地模拟这个错误吧，看看这个错误发生后我走到那个逻辑里去了。

**Comment by Mister-Hope** [comment]
我的意思就是我不太确定这个错误，我是不是应该额外加一个catch块才能捕获错误，还是仍然走then，但json返回null或者undefined之类的东西。我回去需要查一下在测试一下所有浏览器是否一致

**Comment by Mister-Hope** [comment]
cc @lizheming May need some help here

**Comment by real-nicholas** [comment]
好的，我不懂前端。
你看看吧。

**Comment by lizheming** [comment]
@Mister-Hope `An SSL error has occurred and a secure connection to the server cannot be made.` 这个错误应该是 SSL 握手错误，还没有进入接口逻辑层，会直接抛到 catch 处的

**Comment by Mister-Hope** [comment]
好，那我回头补个catch
