### ISSUE TITLE
[BUG] 手机版上点击“回复”图标无反应

### ISSUE THREAD

**Issue by real-nicholas** [walinejs/waline#627]
**手机版上点击 “回复” 图标无反应**

1、一级评论，如果是访客发布，则可以回复；如果是网站博主发布，则不可回复；
2、二级评论，如果是访客发布的也不一定可以回复；如果是网站博主发布，则不可回复；

**问题网站**
https://risehere.net/friends/
注意：这不是我的网站，我随便找了一个。

我的环境：
PC端：
mac OS 11.6
Safari Version 15.0 (16612.1.29.41.4, 16612)

手机：
三星S9，自带的三星浏览器，Version 15.0.5.10

**Comment by Mister-Hope** [comment]
![Screenshot_20211030-144416.jpg](https://user-images.githubusercontent.com/33315834/139523418-167b1b81-6ee5-487f-8907-7f0cb22ca098.jpg)

无法复现，建议搭配截图

**Comment by real-nicholas** [comment]
请问你是什么手机浏览器？

**Comment by Mister-Hope** [comment]
Chrome 95。

我需要的是网络日志和控制台截图。主要是有没有脚本错误，网络请求是否发出，返回的是什么。

**Comment by Mister-Hope** [comment]
另外我需要提醒你，默认的ip频率是60秒，也就是你短时间二次评论是无效的。

而且你也汇报过网络问题，所以请先调查一下你是否触发了ip频率限制，以及是否评论的网络请求没有成功。

**Comment by real-nicholas** [comment]
确定没有触发IP频率限制。

**Comment by Mister-Hope** [comment]
好的，有空的时候还请提供其他信息

**Comment by Mister-Hope** [comment]
我仍无法复现这个问题，有时间提供网络日志以及控制台截图么？

**Comment by real-nicholas** [comment]
我给两张截图吧：

这张是一级评论，点击右侧 “回复” 图标后，弹出了评论框，可以输入文字进行回复：
![Screenshot_20211031-213440_Samsung Internet.jpg](https://user-images.githubusercontent.com/29486126/139586580-006c0f3f-e41d-46f6-9d54-1543092c2b79.jpg)

这张是二级评论，点击右侧 “回复” 图标后，**无法弹出评论框**，画红圈的是二级评论：
![20211031_213759.jpg](https://user-images.githubusercontent.com/29486126/139586660-7ae0d493-9cdf-467c-9aed-d7c664acaefa.jpg)

网络日志我暂时无法提供。

**Comment by Mister-Hope** [comment]
![Screenshot_20211031-220733](https://user-images.githubusercontent.com/33315834/139587624-128bd9b5-4862-4980-80bf-caa6669ebf12.jpg)

**Comment by Mister-Hope** [comment]
![Screenshot_20211031-220728](https://user-images.githubusercontent.com/33315834/139587636-7a50099c-c55c-48c5-95e5-27664ee7e1ca.jpg)
 Working as expected

**Comment by real-nicholas** [comment]
Well, it doesn't work on my phone, Samsung Internet Explorer.

**Comment by real-nicholas** [comment]
Have you ever been tried on iOS, or anyone else ?

**Comment by Mister-Hope** [comment]
Still working as expwcted, ios13.7

![50463d01af5f27a9.png](https://user-images.githubusercontent.com/33315834/139588879-23bdf5ab-8dd3-4cca-aee6-32ebd0bdd883.png)![-124b8813eb52475e.png](https://user-images.githubusercontent.com/33315834/139588880-d961c814-46a0-4b2e-9781-475df7b8f08c.png)

**Comment by Mister-Hope** [comment]
![56917c34eb19e4f5.jpg](https://user-images.githubusercontent.com/33315834/139588993-fd8594bc-5daf-4c44-a264-02db032fcc98.jpg)
![-1c2116e243d202a1.jpg](https://user-images.githubusercontent.com/33315834/139588998-dbb8ec61-1dac-4b3c-a7a9-158b5db6f27e.jpg)

Still working as expected on ipados 15.1

**Comment by Mister-Hope** [comment]
Your information is required for me to start investigation. Please provide it when you have time.

**Comment by Mister-Hope** [comment]
I think your samsung browser based on chromium, if so you may get it's version by opening `chrome://version`. If you are using a very old device, that browser may be dropped in browerslist, and polyfill code is not injected for size consideration

**Comment by Mister-Hope** [comment]
This is what we supported:

```
and_chr 94
and_ff 92
and_qq 10.4
and_uc 12.12
android 94
chrome 95
chrome 94
chrome 93
chrome 92
chrome 91
chrome 90
chrome 89
chrome 88
chrome 87
chrome 86
chrome 85
chrome 84
chrome 83
chrome 81
chrome 80
chrome 79
edge 95
edge 94
edge 93
edge 92
edge 91
edge 90
edge 89
edge 88
edge 87
edge 86
edge 85
edge 84
edge 83
edge 81
edge 80
edge 79
firefox 93
firefox 92
firefox 91
firefox 90
firefox 89
firefox 88
firefox 87
firefox 86
firefox 85
firefox 84
firefox 83
firefox 82
firefox 81
firefox 80
firefox 79
firefox 78
firefox 77
firefox 76
firefox 75
firefox 74
firefox 73
firefox 72
firefox 71
ios_saf 15
ios_saf 14.5-14.8
ios_saf 14.0-14.4
ios_saf 13.4-13.7
ios_saf 13.3
ios_saf 12.2-12.5
op_mob 64
opera 80
opera 79
opera 78
opera 77
opera 76
opera 75
opera 74
opera 73
opera 72
opera 71
opera 70
opera 69
opera 68
opera 67
opera 66
opera 65
safari 15
safari 14.1
safari 14
safari 13.1
samsung 15.0
samsung 14.0
samsung 13.0
samsung 12.0
samsung 11.1-11.2
```

Our minium requirement is samsung browser 11.1, so please check that.

**Comment by real-nicholas** [comment]
我上报该 issue 时，三星手机浏览器版本 Version 15.0.5.10

今天我升级到 Version 15.0.6.3

问题依旧存在。

**Comment by Mister-Hope** [comment]
你能在你的手机上装一个Chrome看看Chrome是否正常么？我周围没人在用三星，所以我没法借一个体验一下，也不能拿回家插电脑进行调试。换句话说我没有在本地使用三星浏览器的条件。

如果你方便的话，你可以试着把浏览器打包一下发到 mister-hope@outlook.com，我安装一下试试，但我觉得它可能会依赖与三星账户之类的应用，没法在非三星手机上运行。

**Comment by Mister-Hope** [comment]
就这个手机上点击回复图标无反应的问题，目前是只有你在汇报....

**Comment by real-nicholas** [comment]
我下载了Chrome，录个屏。与三星的对比，一样的重现。只能回复一级评论，二级评论只能回复最后的那条匿名的（应该是你昨天测试时发表的吧）。

录屏文件过大，这里上传不了。

要不你有空了找个三星S9手机试试吧，S9是2018年的三星旗舰机。后面出了S10 S20 等。

**Comment by Mister-Hope** [comment]
你在pc上可以复现么？

**Comment by Mister-Hope** [comment]
Chrome不同设备应该表现一致，由于无法复现、暂无其他人汇报这个问题，且长时间未得到回应，故关闭。
