### ISSUE TITLE
[BUG] v1.4.0 使用遇到的问题

### ISSUE THREAD

**Issue by real-nicholas** [walinejs/waline#636]
**v1.4.0 使用遇到的问题**

部署方式：Vercel + LeanCloud
测试地址：https://waline-comment-api.vercel.app
环境：mac OS 11.6
Safari：Version 15.1 (16612.2.9.1.30, 16612)
网络环境：有挂代理（不挂代理我没法访问）

**具体过程描述：**

1. 匿名 或 不匿名，在写好评论内容后，点击 “提交”。然后有5～8秒的等待时间，“提交” 按钮此时显示转圈等待。
2. 接下来，浏览器弹出提示：“The string did not match the expected pattern.” ，这时用户不解，接着用户继续点击 “提交” 按钮，浏览器提示：“Duplicate Content”。
3. 用户以 F5 的方式重新加载页面，这时才显示出了用户刚才的发表的评论内容。
4. 接下来，博主登录，博主回复用户，浏览器弹出提示：“The string did not match the expected pattern.”。博主尝试重复点击 “提交”，同样的，浏览器弹出提示：“The string did not match the expected pattern.”。博主重试三次“提交”后无果。选择以 F5 的方式重新加载页面，这时才显示出了博主刚才回复用户的评论内容。
5. 博主 和 用户 都没有收到邮件通知（已经在 Vercel 中配置了邮件的相关环境变量）
6. 用户即使填写了 昵称 和 邮箱，下方的头像傍边显示的仍然是 “匿名”。

**以上过程如下图：**
<img width="832" alt="Screenshot 2021-11-01 at 15 18 32" src="https://user-images.githubusercontent.com/29486126/139638095-a50eabfe-6b67-4944-8e98-37374142dbf6.png">

<img width="832" alt="Screenshot 2021-11-01 at 15 18 50" src="https://user-images.githubusercontent.com/29486126/139638120-6270af6d-d8a7-415f-a784-1c2c09aa5f70.png">

<img width="832" alt="Screenshot 2021-11-01 at 15 19 11" src="https://user-images.githubusercontent.com/29486126/139638152-8c932942-8dd6-4f2f-b209-774e633dc6e2.png">

<img width="832" alt="Screenshot 2021-11-01 at 15 31 13" src="https://user-images.githubusercontent.com/29486126/139638196-3e117f41-d57b-4106-a951-aa3875461e7b.png">

<img width="832" alt="Screenshot 2021-11-01 at 15 31 34" src="https://user-images.githubusercontent.com/29486126/139638212-191425c2-f4d0-415a-b822-62d8e4b35fc6.png">

<img width="843" alt="Screenshot 2021-11-01 at 15 32 50" src="https://user-images.githubusercontent.com/29486126/139638237-86673597-99c3-46a8-8418-612fbb62cc8a.png">

请用我提供的服务地址 测试 你是否能复现。

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/139640388-280cb9ac-bac7-401d-9b5d-2bbc4a630b80.png)
我这边显示你服务端有问题

**Comment by Mister-Hope** [comment]
请检查你的服务器配置，如果你不介意的话，请自行尝试 https://waline.vercel.app/。官网评论链接在我这边一切正常。

**Comment by Mister-Hope** [comment]
如果你不介意的话，重开一个leancloud数据库，完整的走一遍“快速上手”里的流程，确保你服务端不会出现错误。

> ![bug](https://user-images.githubusercontent.com/29486126/139638212-191425c2-f4d0-415a-b822-62d8e4b35fc6.png)

上面这个图片的错误完全是服务器给出的。

**Comment by Mister-Hope** [comment]
cc @lizheming 可能需要检查一下服务器侧最近的更改会不会导致类似的问题。 我认为这个问题不在客户端处。

**Comment by real-nicholas** [comment]
我今天就是 重新把 Vercel 和 LeanCloud 两个服务都全部干掉了，才重新新建的项目！
这是我录的屏，我这里没有问题：

https://user-images.githubusercontent.com/29486126/139641608-858c8c90-6d5d-4775-8e88-ca3af0a50201.mov

**Comment by Mister-Hope** [comment]
> ![image](https://user-images.githubusercontent.com/33315834/139640388-280cb9ac-bac7-401d-9b5d-2bbc4a630b80.png)
> 我这边显示你服务端有问题

这是我发送评论后服务端的相应。

**Comment by real-nicholas** [comment]
这是我在 https://waline.vercel.app 测试截图：
我填写了昵称，但是还是现实“匿名”
<img width="635" alt="Screenshot 2021-11-01 at 16 18 56" src="https://user-images.githubusercontent.com/29486126/139642566-8b2289c7-3f5d-491f-91a7-1deb93132b0f.png">

评论显示：
<img width="281" alt="Screenshot 2021-11-01 at 16 19 25" src="https://user-images.githubusercontent.com/29486126/139642604-86140f8a-47c7-4fee-ada4-39a085b89512.png">

**Comment by real-nicholas** [comment]
> > ![image](https://user-images.githubusercontent.com/33315834/139640388-280cb9ac-bac7-401d-9b5d-2bbc4a630b80.png)
> > 我这边显示你服务端有问题
> 
> 这是我发送评论后服务端的相应。并不是说我打不开你的服务端html主页。

这是哪个服务？ LeanCloud 还是 Vercel？

**Comment by Mister-Hope** [comment]
> 这是我在 https://waline.vercel.app 测试截图： 我填写了昵称，但是还是现实“匿名” <img alt="Screenshot 2021-11-01 at 16 18 56" width="635" src="https://user-images.githubusercontent.com/29486126/139642566-8b2289c7-3f5d-491f-91a7-1deb93132b0f.png">
> 
> 评论显示： <img alt="Screenshot 2021-11-01 at 16 19 25" width="281" src="https://user-images.githubusercontent.com/29486126/139642604-86140f8a-47c7-4fee-ada4-39a085b89512.png">

这个问题1.5.1修了

**Comment by real-nicholas** [comment]
我今天刚看到更新的 v1.4.0

这么快就1.5了。。。

**Comment by Mister-Hope** [comment]
因为更新了两个新功能，可以自定义高亮和数学公式渲染。所以从1.3提了两次。

**Comment by Mister-Hope** [comment]
服务端用的CDN有更新延迟，官网已经更新到最新版本的client，你可以在官网进行测试。

**Comment by Mister-Hope** [comment]
> > > ![image](https://user-images.githubusercontent.com/33315834/139640388-280cb9ac-bac7-401d-9b5d-2bbc4a630b80.png)
> > > 我这边显示你服务端有问题
> > 
> > 
> > 这是我发送评论后服务端的相应。并不是说我打不开你的服务端html主页。
> 
> 这是哪个服务？ LeanCloud 还是 Vercel？

当然是Vercel,用户访问vercel的对应api，而vercel上的服务端负责和leancloud通信。
