### ISSUE TITLE
[BUG] 服务端代码高亮失效

### ISSUE THREAD

**Issue by Eumeryx** [walinejs/waline#638]
**问题描述 | Describe the bug**

使用官网的例子，服务端返回的代码块中没有高亮。

![Screenshot_20211102_165512](https://user-images.githubusercontent.com/78412663/139816822-810a0045-7091-48d4-8c2f-1fda2b1d6971.png)

**问题网站 | Website URL**

官网即可复现。

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [x] Vercel
  - [ ] Deta
  - [ ] CloudBase
  - [ ] Docker
  - [ ] VPS, Virtual Host
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [x] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [ ] CloudBase
  - [ ] MongoDB
  - [ ] MySQL
  - [ ] SQLite
  - [ ] PostgreSQL
  - [ ] GitHub

**Comment by Mister-Hope** [comment]
Please give us what you inputed.
![Screenshot_20211102-175816.jpg](https://user-images.githubusercontent.com/33315834/139825693-efbfa980-d8c0-446b-90da-968d773ad385.jpg)

**Comment by Eumeryx** [comment]
> Please give us what you inputed.

```
```
/** @deprecated Use `Prism.plugins.fileHighlight.highlight` instead. */
Prism.fileHighlight = function () {
  if (!logged) {
    console.warn(
      'Prism.fileHighlight is deprecated. Use `Prism.plugins.fileHighlight.highlight` instead.'
    );
    logged = true;
  }
  Prism.plugins.fileHighlight.highlight.apply(this, arguments);
};
```
```

![Screenshot_2021-11-02-18-09-52-947_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/78412663/139827550-4f710dd8-629f-46ba-a1cd-14342575d0bd.jpg)

**Comment by Mister-Hope** [comment]
Please think about why GitHub also choose not to highlight your code but choose to highlight mine. :) 

```js
/** @deprecated Use `Prism.plugins.fileHighlight.highlight` instead. */
Prism.fileHighlight = function () {
  if (!logged) {
    console.warn(
      'Prism.fileHighlight is deprecated. Use `Prism.plugins.fileHighlight.highlight` instead.'
    );
    logged = true;
  }
  Prism.plugins.fileHighlight.highlight.apply(this, arguments);
};
```

**Comment by Eumeryx** [comment]
> Please think about why GitHub also choose not to highlight your code but choose to highlight mine. :) 
> 

但客户端的预览会高亮显示我的输入，服务端却不会高亮，行为不一致。

![Screenshot_2021-11-02-18-28-32-444_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/78412663/139830304-a05ecb99-4185-44eb-a59b-4428fd240093.jpg)

**Comment by Mister-Hope** [comment]
https://waline.js.org/guide/client/syntax.html#%E5%8F%97%E9%99%90%E7%9A%84%E9%A2%84%E8%A7%88%E5%8A%9F%E8%83%BD

It would be nice if you can read docs carefully.😋
