### ISSUE TITLE
希望能支持Waline数据迁移

### ISSUE THREAD

**Issue by lizheming** [walinejs/waline#655]
### Discussed in https://github.com/walinejs/waline/discussions/653

<div type='discussions-op-text'>

<sup>Originally posted by **dyxang** November 11, 2021</sup>
我原本是直接Valine 直接迁移到Waline的，我现在尝试从Leancloud迁出到如elephantsql这样的网站。
于是我尝试了两种方法：

1. 直接使用Leancloud里面的数据存储> 数据导出 导出为jsonline> json > csv 然后尝试导入 postgresql
2. Leancloud 结构化数据 >全选class为comment的所有查询结果 >查询结果保存为 csv

两者都会得到`ERROR:  extra data after last expected column`的报错。请问就现阶段有没有可能方便地把Waline数据从Leancloud迁移到别的地方，比如Supabase或elephant的这种地方……其实这折腾的初衷就是觉得Leancloud国际版太慢了（账号不实名网站不备案），看elephant这种有香港的服务器……</div>

**Comment by 63e** [comment]
这个挺好
