### ISSUE TITLE
[Feature Request] An environment variable to disable notification to blog owner when others post a comment

### ISSUE THREAD

**Issue by mengrru** [walinejs/waline#687]
## 功能简述

用户可以通过配置一个环境变量来关闭新评论邮件通知（但不关闭评论者收到回复的通知）

## 原因

```
// waline/packages/server/src/controller/comment.js
    if (comment.status !== 'spam') {
      const notify = this.service('notify');
      await notify.run({ ...resp, rawComment: comment }, parrentComment);
    }
```
如上方代码所示，在等待通知服务执行完毕返回后前端才能收到评论成功（或失败）的信息，继而用户得到相关反馈（按钮变绿、评论区刷新显示新评论，或得到失败弹窗）。但发送邮件在某些场景下耗时会很长，比如我当前在使用outlook进行邮件发送，关闭和打开邮件通知用户感受到的速度差异明显。所以希望提供关闭发送根评论时对博客所有者的提醒的功能，以（部分地）提高用户体验。除此之外，在博主的角度仍有对该功能的需求，有些博主也许不希望一有新评论就收到通知（因为可以直接去后台查看新评论），但同时又希望评论者被回复时可以收到通知。

## 建议

由于 `notify.run` 已经实现了这个功能：

```
async run(comment, parent, disableAuthorNotify = false) {
 if (!isAuthorComment && !disableAuthorNotify) {
      // ...
    }
}
```

所以基于不大动代码结构但可以临时解决问题的前提，可以添加一个环境变量，比如 DISABLE_AUTHOR_NOTIFY，并在 postAction 的 `notify.run` 的调用处使用这个环境变量：

```
// waline/packages/server/src/controller/comment.js
    if (comment.status !== 'spam') {
      const notify = this.service('notify');
      await notify.run({ ...resp, rawComment: comment }, parrentComment, process.env.DISABLE_AUTHOR_NOTIFY);
    }
```

但从根本上讲，通知是否发送成功不影响用户发送评论是否成功，所以可否考虑不等待通知返回？

**Comment by lizheming** [comment]
Vercel 在请求结束后就会关闭环境，所以没办法做到后台发送先返回内容。不过前几日有用户反馈 Twikoo 把邮件通知抽离成了接口，在服务中调用接口触发，这样似乎可以做到不等待。准备参考优化下试试。

**Comment by mengrru** [comment]
@lizheming 辛苦了！那届时是否仍可以添加一个这样的环境变量呢？基于我在主楼中提出的第二点理由：在博主的角度仍有对该功能的需求，有些博主也许不希望一有新评论就收到通知（因为可以直接去后台查看新评论），但同时又希望评论者被回复时可以收到通知。
