### ISSUE TITLE
[BUG]配置安全域名无法加载评论

### ISSUE THREAD

**Issue by lfhsheng** [walinejs/waline#714]
### 问题描述

根据[官网](https://waline.js.org/reference/server.html#%E4%B8%BB%E8%A6%81%E9%85%8D%E7%BD%AE)配置安全域名后无法加载评论

### 部署方式

**服务部署在哪里？ | Where your waline deploy?**

  - [ ] Vercel

**数据存储在哪里？| Where your comment data store?**

  - [ ] LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
提供下地址看一下

**Comment by lfhsheng** [comment]
你可以自己试一试，地址我明天搞😯
