### ISSUE TITLE
[BUG]头像问题

### ISSUE THREAD

**Issue by Fgaoxing** [walinejs/waline#724]
应该为https://sdn.geekzu.org/avatar/565ada82edc2f01e7cf2bd95b31f19fd ，而不是https://sdn.geekzu.org/avatar/#https://sdn.geekzu.org/avatar/565ada82edc2f01e7cf2bd95b31f19fd

**Comment by Fgaoxing** [comment]
https://www.libravatar.org/avatar/565ada82edc2f01e7cf2bd95b31f19fd

**Comment by Fgaoxing** [comment]
直接访问速度不慢https://www.libravatar.org/avatar/565ada82edc2f01e7cf2bd95b31f19fd

**Comment by lizheming** [comment]
升级到最新版后再看一下，我们默认已经不是 geekzu 了

**Comment by Fgaoxing** [comment]
好

**Comment by Fgaoxing** [comment]
怎么更新？

**Comment by Fgaoxing** [comment]
部署到vercel上的

**Comment by CCKNBC** [comment]
@Fgaoxing 看文档

**Comment by Fgaoxing** [comment]
https://avatar.75cdn.workers.dev/?url=https%3A%2F%2Fseccdn.libravatar.org%2Favatar%2Fafc42a27ef5d331e0a4ecb50945b85c3也不好使，可以直接到https://www.libravatar.org/avatar/565ada82edc2f01e7cf2bd95b31f19fd

**Comment by lizheming** [comment]
看下文档 https://waline.js.org/reference/server.html#%E4%B8%BB%E8%A6%81%E9%85%8D%E7%BD%AE AVATAR_PROXY 配一下

**Comment by Fgaoxing** [comment]
我的哈希码是565ada82edc2f01e7cf2bd95b31f19fd，而头像是afc42a27ef5d331e0a4ecb50945b85c3

**Comment by Fgaoxing** [comment]
帮帮我把

**Comment by lizheming** [comment]
提供下地址，我去看一下，你现在说的这些我都没办法帮你解决问题。

**Comment by Fgaoxing** [comment]
https://waline.yt-blog.top/

**Comment by Fgaoxing** [comment]
邮箱：Fgaoxing0206@163.com
头像：https://www.libravatar.org/avatar/565ada82edc2f01e7cf2bd95b31f19fd

**Comment by Fgaoxing** [comment]
问题出在哈希码不一致，导致无法加载头像

**Comment by lizheming** [comment]
邮箱用小写吧，默认没有做小写的转换，如果有需要的话可以自定义配置 GRAVATAR_STR 为 `https://seccdn.libravatar.org/avatar/{{mail|lower|md5}}` 配置见文档 https://waline.js.org/reference/server.html#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F

**Comment by Fgaoxing** [comment]
我的哈希码大小写是一样的

**Comment by Fgaoxing** [comment]
我试试别的邮箱吧

**Comment by Fgaoxing** [comment]
admin@yt-blog.top 不能用

**Comment by Fgaoxing** [comment]
应该加个判断邮箱商自动改为小写，比可以在登陆后更改邮箱

**Comment by Fgaoxing** [comment]
小写好用了
