### ISSUE TITLE
[BUG] 头像代理问题

### ISSUE THREAD

**Issue by a1262344305** [walinejs/waline#727]
**问题描述 | Describe the bug**

头像代理在博客里面没有用，在服务端的 Example 上倒是正常的，自己博客没有。

**问题网站 | Website URL**

服务端的 Example: https://waline-vercel.009898.xyz/
博客: https://009898.xyz/post/hello-gridea/

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - Vercel
- 数据存储在哪里？| Where your comment data store?
  - PostgreSQL

**Comment by a1262344305** [comment]
找到问题了。。。
博客 Html 引入时，我修改了默认头像
avatar: 'mp',
然后头像代理就不生效了

**Comment by a1262344305** [comment]
有点疑问，现在前段 avatar 弃用了
怎么设置默认头像 ，需要设置神秘人(一个灰白头像)

**Comment by fuzhibin** [comment]
我在hexo博客butterfly主题内使用时，其他人的我看到可以更具QQ邮箱自动识别头像，而我的却没有出现，一直是在客户端配置的默认类型，有知道原因出在哪里的吗？

**Comment by lizheming** [comment]
@a1262344305 
https://waline.js.org/reference/server.html#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F 根据文档，把 `GRAVATAR_STR` 配置为 `https://seccdn.libravatar.org/avatar/{{mail|md5}}?d=mm` 试一下，libravatar 的 API 可参见 https://wiki.libravatar.org/api/

@fuzhibin 请查看这个 issue  https://github.com/walinejs/waline/issues/532
