### ISSUE TITLE
[BUG]關於速率限制無法關閉的問題

### ISSUE THREAD

**Issue by ArsFy** [walinejs/waline#737]
**问题描述 | Describe the bug**

設定 IPQPS=0 還是會出現限制警告
![image](https://user-images.githubusercontent.com/93700457/147864497-e72dbe74-47a5-43ff-b5b3-2e06abfa14e3.png)
![image](https://user-images.githubusercontent.com/93700457/147864537-05c229b2-6bb0-4304-a61f-4654b0b125a4.png)

**问题网站 | Website URL**

https://waline.noyteam.online/

**部署方式 | Deploy Type**

- 服务部署在哪里？ | Where your waline deploy?
  - [ ] Vercel
  - [ ] Deta
  - [ ] CloudBase
  - [ ] Docker
  - [x] VPS, Virtual Host
  - [ ] Deta
  - [ ] InspireCloud
  - [ ] Other
- 数据存储在哪里？| Where your comment data store?
  - [ ] LeanCloud(https://leancloud.app)
  - [ ] LeanCloud(https://leancloud.cn)
  - [ ] CloudBase
  - [ ] MongoDB
  - [x] MySQL
  - [ ] SQLite
  - [ ] PostgreSQL
  - [ ] GitHub
  - [ ] Deta Base
  - [ ] InspireCloud

**Comment by lizheming** [comment]
设置成 `-28800` 试试？有可能是服务器的时区问题

**Comment by Mister-Hope** [comment]
我个人认为这里应该可以当成一个bug。。。。。我觉得我们完全可以预先判断process.env上的原始值，如果是0直接做特殊处理。

**Comment by lizheming** [comment]
时区有问题最终存储的数据也是会有问题的

**Comment by Mister-Hope** [comment]
不，我的意思是直接检测，为0直接吧判断跳过去不行么

**Comment by lizheming** [comment]
这个不做特别处理，因为环境正常这个就不会有问题，环境有问题其它的功能也是有问题的

**Comment by Mister-Hope** [comment]
emmm，你引的issue里我引了相关代码，你是直接取了ipqps然后直接去拿了结果，看看有没有在相关时间内有评论，这样诸如这类的时区问题，你这一步可能会拿到在ipqps外额外包含时区差的时间内的评论，我的意思是，如果ipqps为0，我们直接放弃获取并判断这一步。

上述的思路不能解决此类问题么？

**Comment by lizheming** [comment]
可以，但是没有必要，如果环境正常不需要做这种特别逻辑的判断，功能就是正常的。

**Comment by Mister-Hope** [comment]
正如我在那个issue所建议的用isostring来存储时间，我觉得这里没有环境正常不正常一说。

我服务器用utc和用本地时间，我觉得不存在哪个不正常的说法，但是现在这套逻辑，如果我保持数据库不变，而迁移了waline service，在这两个时间切换，一定会造成问题吧？我还没仔细看waline表现正常是需要在utc还是在本地时间。🧐

**Comment by Mister-Hope** [comment]
换言之，waline应该是直接在自己的时区上创建时间戳的（或者是基于客户端？not sure），而我认为标准的做法是转换到utc来存储时间戳。整个服务不应该受到服务端、客户端所在时区的影响才对。

**Comment by ArsFy** [comment]
不只是時區問題（伺服器位於HK，UTC+8，我的也位於HK，UTC+8），環境是 AliCloud Ubuntu Server
不過這個問題不應該受時區限制，我認為應該使用同一時間戳判斷...
（我自己的解決方案是自己寫了一個評論組件，以後應該不會再用Waline了）
