### ISSUE TITLE
[Feature] 客户端能否增加一个自动预览的参数设置？

### ISSUE THREAD

**Issue by iDvel** [walinejs/waline#752]
**功能概述 | Describe the feature**

就是不用再点一下了，用户输入之后就自动打开预览功能。
我个人觉得那个图标表达的意思不是很到位，不如文字的「预览」「Preview」来得明白。

**Comment by iDvel** [comment]
？？？
我就是按着模板来的啊，模板也只有一行字和一个注释呀
？？？

**Comment by lizheming** [comment]
@iDvel 这块有点问题，目前没有针对 Feature 的 issue 做特别处理，之后我优化一下。

**Comment by Mister-Hope** [comment]
Workaround:

```js
Waline.init({
  // ...
});

document.querySelector('.wl-actions').lastChild.click()
```
