### ISSUE TITLE
[Feature]: 请求添加二步验证

### ISSUE THREAD

**Issue by 63e** [walinejs/waline#769]
### 功能概述 | Describe the feature

比如简单的邮箱验证

----------------------------------
(为什么会有这个想法？  因为我的管理账户被撞库，然后就没有然后了)

**Comment by lizheming** [comment]
嗯，这个其实是安全问题，需要加一下，比较正常的是登录应该加验证码

**Comment by eallion** [comment]
❓

**Comment by 63e** [comment]
# 新年快乐！
--------------------
催更了催更了

**Comment by 63e** [comment]
> 嗯，这个其实是安全问题，需要加一下，比较正常的是登录应该加验证码

# 对我的想法就是这样子

**Comment by AkariLiu** [comment]
@lizheming 能不能新增人机验证功能

**Comment by lizheming** [comment]
@AkariLiu 嗯，其实这个和验证码是一回事
