### ISSUE TITLE
[Bug]: 管理页面不会读取GRAVATAR_STR配置

### ISSUE THREAD

**Issue by ZvonimirSun** [walinejs/waline#775]
### 问题描述 | Describe the bug

如题，后端管理页面不会读取`GRAVATAR_STR `环境变量，仍然会使用`sdn.geekzu.org`域名加载头像。

### 问题网站 | Website URL

https://wl.iszy.xyz/ui

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

PostgreSQL

**Comment by nitezs** [comment]
应该设置 `GRAVATAR_STR` 吧，比如 `GRAVATAR_STR=https://cravatar.cn/avatar/{{mail|md5}}?d=monsterid`

**Comment by ZvonimirSun** [comment]
哦对，搞错了，就是不读取GRAVATAR_STR，客户端展示的是有的，后端评论管理的界面没读。

**Comment by lizheming** [comment]
`@waline/vercel@1.6.1` 已修复，更新到最新版即可，感谢反馈。
