### ISSUE TITLE
[Feature]: 希望管理页面加载的@waline/admin地址可配

### ISSUE THREAD

**Issue by ZvonimirSun** [walinejs/waline#776]
### 功能概述 | Describe the feature

鉴于jsdelivr失去了国内的备案，使用体验不比从前，希望可以支持自定义配置此地址。

**Comment by lizheming** [comment]
这个问题我需要再考虑一下，因为后期会使用云游君开发的新后台作为管理 https://github.com/walinejs/waline/issues/552 我看看是直接换了还是说暂时先兼容处理一下。

**Comment by lizheming** [comment]
暂时先增加了个 `WALINE_ADMIN_MODULE_ASSET_URL` 环境变量临时处理了下，后续再想怎么更好的处理一下吧。
