### ISSUE TITLE
[Bug]:  邮件标题里的 `SITE_NAME` 里的引号被自动转义了

### ISSUE THREAD

**Issue by iDvel** [walinejs/waline#786]
### 问题描述 | Describe the bug

比如 `XXX's Blog` 会显示为 `XXX&#39;s Blog`。
邮件标题显示不正常，下面是正常的。

![2022-01-30-000250](https://user-images.githubusercontent.com/14658234/151686495-0c3d40ec-20a1-4fdf-8ec7-fe740b90eba4.png)

### 问题网站 | Website URL

https://dvel.me

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
感谢反馈，已修复，请等待下个版本的更新。目前你也可以通过 `MAIL_SUBJECT` 变量直接定义邮件标题来解决，例如：

```
MAIL_SUBJECT=Devel's Blog 上有新评论了
```
