### ISSUE TITLE
jsdelivr速度问题

### ISSUE THREAD

**Issue by nitezs** [walinejs/waline#800]
### 问题描述 | Describe the bug

自从jsdelivr国内节点关闭之后，jsdelivr国内访问速度慢得离谱。如果清除浏览器全部缓存进入waline评论页面，要等待十几秒的jsdelivr资源。作者可以考虑增加一个参数来设置静态资源走本地吗？

### 问题网站 | Website URL

https://www.nite07.com/comments/

### 服务部署在哪里？ | Where your waline deploy?

VPS, VirtualHost

### 数据存储在哪里？| Where your comment data store?

SQLite

**Comment by lizheming** [comment]
博客前台的 CDN 地址你根据你自己的需要自己配置即可，我看了下你的博客应该是使用的 Butterfly 主题，它可以在 `_config.yml` 中配置 https://github.com/jerryc127/hexo-theme-butterfly/blob/dev/_config.yml#L847

**Comment by nitezs** [comment]
> 博客前台的 CDN 地址你根据你自己的需要自己配置即可，我看了下你的博客应该是使用的 Butterfly 主题，它可以在 `_config.yml` 中配置 https://github.com/jerryc127/hexo-theme-butterfly/blob/dev/_config.yml#L847

感谢，问题解决了
