### ISSUE TITLE
[feature]: 

### ISSUE THREAD

**Issue by TipsyDr** [walinejs/waline#807]
### 问题描述 | Describe the bug

您好，为什么我使用的 volantis主题  配置我们的评论是不是默认转换成base64 呢

### 问题网站 | Website URL

https://volantis.js.org/v5/theme-settings/?keyword=%E5%9B%BE%E5%BA%8A

### 服务部署在哪里？ | Where your waline deploy?

Other

### 数据存储在哪里？| Where your comment data store?

GitHub

**Comment by lizheming** [comment]
@TipsyDr 辛苦重新组织下语言，这话我怎么都看不太明白…

目前我们有 base64 相关的地方是图片上传，其它的地方都没有使用到 base64。图片上传可以通过客户端的 https://waline.js.org/reference/client.html#uploadimage uploadImage 方法自定义

ps. 原来真的有人在用 GitHub 方式存储呀……

**Comment by lizheming** [comment]
relate discussion https://github.com/walinejs/waline/discussions/811
