### ISSUE TITLE
[Bug]: 评论一直显示 loading，无法加载

### ISSUE THREAD

**Issue by ryan4yin** [walinejs/waline#820]
### 问题描述 | Describe the bug

评论一直显示 loading，无法加载

控制台有报错：

```
TypeError: Cannot read properties of null (reading 'insertBefore')
    at insert (Waline.min.js:1:65194)
    at z (Waline.min.js:1:44489)
    at C (Waline.min.js:1:43741)
    at w (Waline.min.js:1:43327)
    at ue.fn (Waline.min.js:1:49932)
    at ue.run (Waline.min.js:1:25553)
    at P (Waline.min.js:1:50224)
    at $ (Waline.min.js:1:48477)
    at j (Waline.min.js:1:46431)
    at w (Waline.min.js:1:43352)
```

相关 issue: 

- https://github.com/walinejs/waline/issues/794

### 问题网站 | Website URL

https://thiscute.world/about/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by ryan4yin** [comment]
我测试发现如下配置会报错，可能是跟我主题的 js 有什么冲突？

```javascript
            Waline({
              el: '#waline',
              serverURL: 'waline-comment.thiscute.world',
              visitor: 'true',
              dark: 'auto',
              avatar: 'hide',
              requiredMeta: ["nick","mail"],
              wordLimit:  1500 ,
            });
```

但是添加个 160ms 的 timeout 就 work 了：

```javascript

                const config = {
                    el: '#waline',
                    serverURL: 'waline-comment.thiscute.world',
                    visitor: 'true',
                    dark: 'auto',
                    avatar: 'hide',
                    requiredMeta: ["nick","mail"],  
                    wordLimit:  1500 ,
                };
                setTimeout(function() {
                    Waline(config);
                }, 160);
```

我临时在站点上加了个 timeout 恢复了正常...

**Comment by Mister-Hope** [comment]
你需要确定当你调用 Waline 的时候， Waline 能找到 dom 挂载，并且你的主题不会修改其挂载的 dom （比如用刷新过的数据重新渲染 dom）

你的解决方案很符合出现上述问题的情况，这种情况下就只能自己去解决了。这不是我们的锅。

**Comment by alexhua** [comment]
> 你需要确定当你调用 Waline 的时候， Waline 能找到 dom 挂载，并且你的主题在其挂载途中以及初始化后不会修改其挂载的 dom （比如用刷新过的数据重新渲染 dom）
> 
> 你的解决方案很符合出现上述问题的情况，这种情况下就只能自己去解决了。这不是我们的锅。

为了提高代码的鲁棒性和友好度，最好给个错误提示，要不然看到代码报错，直觉是Waline的问题。

另外楼上用`setTimeout`不太保险， ```window.onload = () => Waline.init(config);``` 更好一点。
