### ISSUE TITLE
[Feature]: 希望评论支持渲染web component 用户自定义原生组件  

### ISSUE THREAD

**Issue by 2383155523** [walinejs/waline#829]
### 功能概述 | Describe the feature

可以在Waline 的配置项里添加一个可信任的标签白名单 选项，什么标签可以渲染什么标签不可渲染

**Comment by lizheming** [comment]
Waline 使用了 DOMPurify 进行 HTML 的转义，具体的逻辑在这里： https://github.com/walinejs/waline/blob/main/packages/server/src/service/markdown/xss.js#L31-L34 

DOMPurify 我看了下是支持 ALLOW_TAG 设置白名单的：https://github.com/cure53/DOMPurify

可以考虑在这块增加一个 `think.config('domPurify')` 配置的读取，然后对配置进行一下合并。

**Comment by 2383155523** [comment]
本人技术太菜，还望作者大大 闲暇之时帮忙实现一下吧！ 辛苦了！

**Comment by lizheming** [comment]
增加了 domPurify 的配置，我没有测过，具体你自己试试吧。

```
// index.js
const Waline = require('@waline/vercel'); 
module.exports = Waline({
  domPurify: {
     ALLOW_TAG: ['xxx']
  }
});
```

**Comment by 2383155523** [comment]
好的，感谢作者大大
