### ISSUE TITLE
[Bug]: 时间错误

### ISSUE THREAD

**Issue by XILEJ** [walinejs/waline#833]
### 问题描述 | Describe the bug

服务端：[ailway](https://railway-starter.up.railway.app/)
储存方式：[github](https://github.com/XILEJ/alist-railway)
ailway的postgreSQL
每次一刷新时间就会变成8小时，在刷新变7小时，多平台都一样。
![](https://gitee.com/looking-for-the-first-self/Picture/raw/master/img/VeryCapture_20220226185736.gif)

### 问题网站 | Website URL

https://railway-starter.up.railway.app/

### 服务部署在哪里？ | Where your waline deploy?

Railway.app

### 数据存储在哪里？| Where your comment data store?

PostgreSQL

**Comment by lizheming** [comment]
修改下表结构试一下

```SQL
ALTER TABLE wl_Comment
  ALTER COLUMN insertedAt
  SET DATA TYPE timestamp with time zone;
```

**Comment by XILEJ** [comment]
在哪里修改呀？
