### ISSUE TITLE
[Bug]: waline无法评论

### ISSUE THREAD

**Issue by coderzhw** [walinejs/waline#838]
### 问题描述 | Describe the bug

我按照waline文档集成了，但是发现无发评论，貌似是跨域问题还是啥的，有空帮我看看呢，麻烦了，不晓得咋回事，我的博客地址是：https://blog.codage.info/
大佬有空帮忙看看咋回事呢

### 问题网站 | Website URL

https://blog.codage.info/

### 服务部署在哪里？ | Where your waline deploy?

CloudBase

### 数据存储在哪里？| Where your comment data store?

CloudBase

**Comment by lizheming** [comment]
安全配置里添加下你的博客域名

![image](https://user-images.githubusercontent.com/424491/155988338-3eec1e32-0adf-42e8-8de8-5ac92e970007.png)

**Comment by coderzhw** [comment]
解决了，多谢解惑
