### ISSUE TITLE
[Bug]: 企微微信接收到的消息中的评论内容没有了表情

### ISSUE THREAD

**Issue by Sdky** [walinejs/waline#839]
### 问题描述 | Describe the bug

评论通知使用企微微信时，接收到的消息中的评论内容没有了表情。

![image](https://user-images.githubusercontent.com/29597396/156022706-28e94d5e-9ceb-47f5-96d8-c97198fcf3b1.png)

![image](https://user-images.githubusercontent.com/29597396/156023085-8dc10727-9699-49df-989e-f276f82b5886.png)

### 问题网站 | Website URL

https://sdky.gitee.io/1%20Java%20SE/50%20%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84%E4%B8%8E%E7%AE%97%E6%B3%95.html

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
通知卡片只能显示纯文本

**Comment by Sdky** [comment]
> 通知卡片只能显示纯文本

我看企业微信文档里写，图文消息（mpnews）里的 content 是支持html标签的，可以改用图文消息（mpnews）么？
https://developer.work.weixin.qq.com/document/path/90236#%E5%9B%BE%E6%96%87%E6%B6%88%E6%81%AF%EF%BC%88mpnews%EF%BC%89

**Comment by lizheming** [comment]
这个是 PR 添加的，我没有使用这个功能，有需要的话欢迎 PR 修改。也可以自己通过 postSave 钩子实现自定义消息通知。

**Comment by qianfanguojin** [comment]
> > 通知卡片只能显示纯文本
> 
> 我看企业微信文档里写，图文消息（mpnews）里的 content 是支持html标签的，可以改用图文消息（mpnews）么？ https://developer.work.weixin.qq.com/document/path/90236#%E5%9B%BE%E6%96%87%E6%B6%88%E6%81%AF%EF%BC%88mpnews%EF%BC%89

通知的模板已经采用的是 mpnews 了，具体在源码中也可以看到：https://github.com/walinejs/waline/blob/579c8cfd83cb620309988f7abdb30386896d4306/packages/server/src/service/notify.js#L143-L148

**Comment by Sdky** [comment]
> 

好像是这里的问题
https://github.com/walinejs/waline/blob/579c8cfd83cb620309988f7abdb30386896d4306/packages/server/src/service/notify.js#L103

![image](https://user-images.githubusercontent.com/29597396/157082327-bd24c6f9-7301-47a9-a2aa-f883ce91f107.png)

**Comment by qianfanguojin** [comment]
> > > > 通知卡片只能显示纯文本
> > > 
> > > 
> > > 我看企业微信文档里写，图文消息（mpnews）里的 content 是支持html标签的，可以改用图文消息（mpnews）么？ https://developer.work.weixin.qq.com/document/path/90236#%E5%9B%BE%E6%96%87%E6%B6%88%E6%81%AF%EF%BC%88mpnews%EF%BC%89
> > 
> > 
> > 通知的模板已经采用的是 mpnews 了，具体在源码中也可以看到：
> > https://github.com/walinejs/waline/blob/579c8cfd83cb620309988f7abdb30386896d4306/packages/server/src/service/notify.js#L143-L148
> 
> 好像是这里的问题
> 
> https://github.com/walinejs/waline/blob/579c8cfd83cb620309988f7abdb30386896d4306/packages/server/src/service/notify.js#L103
> 
> ![image](https://user-images.githubusercontent.com/29597396/157082327-bd24c6f9-7301-47a9-a2aa-f883ce91f107.png)

嗯，已经定位到问题的地方了，我正在尝试解决

**Comment by qianfanguojin** [comment]
> > > > 通知卡片只能显示纯文本
> > > 
> > > 
> > > 我看企业微信文档里写，图文消息（mpnews）里的 content 是支持html标签的，可以改用图文消息（mpnews）么？ https://developer.work.weixin.qq.com/document/path/90236#%E5%9B%BE%E6%96%87%E6%B6%88%E6%81%AF%EF%BC%88mpnews%EF%BC%89
> > 
> > 
> > 通知的模板已经采用的是 mpnews 了，具体在源码中也可以看到：
> > https://github.com/walinejs/waline/blob/579c8cfd83cb620309988f7abdb30386896d4306/packages/server/src/service/notify.js#L143-L148
> 
> 好像是这里的问题
> 
> https://github.com/walinejs/waline/blob/579c8cfd83cb620309988f7abdb30386896d4306/packages/server/src/service/notify.js#L103
> 
> ![image](https://user-images.githubusercontent.com/29597396/157082327-bd24c6f9-7301-47a9-a2aa-f883ce91f107.png)
