### ISSUE TITLE
[Bug]: 使用 hexo-theme-yun 的 pjax 后 SPA 支持失效

### ISSUE THREAD

**Issue by Big-Cake-jpg** [walinejs/waline#856]
### 问题描述 | Describe the bug

主题作者已经确认是 Waline 的锅，不知何时修复

### 问题网站 | Website URL

https://bigcake.cakemc.top

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by Mister-Hope** [comment]
锅是从哪个issue扣过来的，相关issue或者讨论在哪？

据我所知 Pjax 是所谓 ajax + pushState，而浏览器的地址栏无法被监听，而且即使这样Waline也没有义务监听导航栏。主题有义务以新 url 调用 WalineInstanceUpdate，所以最好把你和主题作者的讨论或者相关issue丢在这里。

**Comment by lizheming** [comment]
https://github.com/YunYouJun/hexo-theme-yun/issues/256 应该是这个讨论，但其实也没有讨论，我在群里问下云游君 @Mister-Hope

**Comment by lizheming** [comment]
啊，我知道了，估计题主会错意了，云游君应该说的是「等把 Waline 问题修复了发新版本」，可能题主理解成了等 Waline 把问题修复了发新版本……
