### ISSUE TITLE
[Bug]: 使用Akismet垃圾评论测试，Akismet识别为垃圾信息，但收到邮件通知。

### ISSUE THREAD

**Issue by aaro-n** [walinejs/waline#857]
### 问题描述 | Describe the bug

重现方式

1. 部署在Vercel，配置邮件通知并且配置**AUTHOR_EMAIL**为xx@gmail.com
2. 打开[xxx.vercel.app](https://xxx.vercel.app/)
3. 按照[Akismet](https://docs.akismet.com/getting-started/confirm/)测试要求填写昵称，邮件地址和内容
4. 点击提交，能看到刚刚提交的信息，刷新下刚刚信息消失（识别为垃圾信息），同时xx@gmail.com收到邮件通知（邮件通知可能有延迟）

想法
当配置**AUTHOR_EMAIL**时，应先检测是否为垃圾信息，再发邮件通知

### 问题网站 | Website URL

https://xxx.vercel.app

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

MongoDB

**Comment by lizheming** [comment]
是不是开启了评论审核功能了？评论有通过，审核，垃圾三种状态，隐藏还有可能是进审核了，可以进后台查看一下。代码里明确判断了非 spam 才会走通知逻辑 https://github.com/walinejs/waline/blob/main/packages/server/src/controller/comment.js#L426-L429，所以不会有你说的这个问题的哈。
