### ISSUE TITLE
[Bug]: 非管理员用户访问管理评论页面(/ui)，页面无限循环跳转

### ISSUE THREAD

**Issue by ZvonimirSun** [walinejs/waline#869]
### 问题描述 | Describe the bug

如题，非管理员用户访问管理评论页面(/ui)，会出现403跳转回登录界面，但因为已经登录，且redirect为/ui，所以会无限循环。应该在非管理员用户访问未授权页面时，路由到/ui/profile。

### 问题网站 | Website URL

https://wl.iszy.xyz

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

PostgreSQL

**Comment by lizheming** [comment]
这个算是个 Feature？因为普通用户不会有直接在后台登录的场景，在前台评论框登录是正常的，我理解。
