### ISSUE TITLE
[Bug]: Gravatar头像cdn墙内失效

### ISSUE THREAD

**Issue by DomeenoH** [walinejs/waline#876]
### 问题描述 | Describe the bug

目前的头像用的workers好像没法直接访问了，我是江苏电信
![](https://avatar.75cdn.workers.dev/?url=https%3A%2F%2Fseccdn.libravatar.org%2Favatar%2F9253a8706191997e78aaedd11fd1dd2a)

要不要考虑一下使用cravatar之类的服务作为替代？

### 问题网站 | Website URL

https://waline.js.org/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
可以自行通过 AVATAR_PROXY 关闭，也可以 https://github.com/walinejs/porter 自行部署。
