### ISSUE TITLE
[Feature]: 希望评论管理页面可从管理员个人主页获取主页地址

### ISSUE THREAD

**Issue by 5ime** [walinejs/waline#881]
### 功能概述 | Describe the feature

目前为止: `*.vercel.app/评论页`
希望变为: `管理员个人主页/评论页`
方便直接跳转到用户评论页面

`/ui`

![image](https://user-images.githubusercontent.com/31686695/160766550-ccd9fc15-7f56-4d1b-88c9-6e9dadfaefd8.png)

`ui/profile`

![image](https://user-images.githubusercontent.com/31686695/160766627-3d53b745-b221-4cc3-a44d-1292710cd675.png)

**Comment by lizheming** [comment]
配置一下 SITE_URL 环境变量就可以了哈，你试一下 https://github.com/walinejs/waline/blob/main/packages/server/src/middleware/dashboard.js#L13
