### ISSUE TITLE
[Feature]: 能不能有一个评论点赞的功能

### ISSUE THREAD

**Issue by holmofy** [walinejs/waline#882]
### 功能概述 | Describe the feature

<img width="661" alt="image" src="https://user-images.githubusercontent.com/19494806/160800064-5170e02e-abad-4904-b89b-5b20c34dd04e.png">

**Comment by lizheming** [comment]
可以有，你希望这个点赞功能是需要登录还是不需要登录呢？

**Comment by Mister-Hope** [comment]
Any plan for this feature? Am I supposed to support this in v2?

**Comment by lizheming** [comment]
@Mister-Hope That's sound great, I'm also waiting v2 to done to implement it.
