### ISSUE TITLE
[Bug]:valine迁移的评论无法正常显示 

### ISSUE THREAD

**Issue by wyxogo** [walinejs/waline#893]
### 问题描述 | Describe the bug

从valine迁移后的评论无法正常显示，一直在加载中，下图
![image](https://user-images.githubusercontent.com/61509470/161548635-eb711831-4ef6-4566-a6fc-25a29d0a746c.png)

### 问题网站 | Website URL

https://blog.aimoon.top/comments/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by ethan-enhe** [comment]
> ### 问题描述 | Describe the bug
> 从valine迁移后的评论无法正常显示，一直在加载中，下图 ![image](https://user-images.githubusercontent.com/61509470/161548635-eb711831-4ef6-4566-a6fc-25a29d0a746c.png)
> 
> ### 问题网站 | Website URL
> https://blog.aimoon.top/comments/
> 
> ### 服务部署在哪里？ | Where your waline deploy?
> Vercel (Default)
> 
> ### 数据存储在哪里？| Where your comment data store?
> LeanCloud(https://leancloud.app)

我昨天也碰到了这个问题，您可以试试把katex的渲染代码改成只渲染博文的element，而不要渲染评论区，应该就好了。

比如如下这样

```html
<link href="//cdn.bootcdn.net/ajax/libs/KaTeX/0.13.3/katex.min.css" rel="stylesheet">
<script src="//cdn.bootcdn.net/ajax/libs/KaTeX/0.13.3/katex.min.js"></script>
<script src="//cdn.bootcdn.net/ajax/libs/KaTeX/0.13.3/contrib/auto-render.min.js"></script>
<script>
    window.onload= function() {
            renderMathInElement(document.getElementsByClassName("post-container")[0],{
                    delimiters: [
                            {left: "$$", right: "$$", display: true},
                            {left: "\\[", right: "\\]", display: true},
                            {left: "$", right: "$", display: false},
                            {left: "\\(", right: "\\)", display: false}
                        ]
                });
        };
</script>

```

**Comment by wyxogo** [comment]
好的感谢感谢
