### ISSUE TITLE
[Bug]: QQ提醒使用默认模板部分信息损失

### ISSUE THREAD

**Issue by wyxogo** [walinejs/waline#896]
### 问题描述 | Describe the bug

使用QQ提醒功能，使用配置模板，无法收到提醒
若不配置模板（即使用默认配置）部分信息不完全

无站点链接 ({{site.postUrl}})

如下
![image](https://user-images.githubusercontent.com/61509470/161714766-e2c42f80-ef97-4e29-8c20-df392e7661fa.png)

### 问题网站 | Website URL

https://blog.aimoon.top/comments/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
qmsg 酱针对包含链接的内容会有非法提示发送失败，所以专门针对 qmsg 酱过滤了链接内容，是 feature 不是 bug 呢。
https://github.com/walinejs/waline/blob/main/packages/server/src/service/notify.js#L176
