### ISSUE TITLE
[Bug]: Hexo NexT主题首页Warning: Option 'el' do not match any domElement!

### ISSUE THREAD

**Issue by yczheng0** [walinejs/waline#905]
### 问题描述 | Describe the bug

Hexo: 6.0
NexT:  8.10.1
@waline/hexo-next: 2.0.6
waline: 1.6.0

访问首页出现警告：Option 'el' do not match any domElement!

首页没有启用评论，无法与el绑定，但是启用评论计数需要初始化waline，二者有一定程度冲突。

### 问题网站 | Website URL

https://blog.yczheng.top/

### 服务部署在哪里？ | Where your waline deploy?

Deta

### 数据存储在哪里？| Where your comment data store?

Deta Base

**Comment by lizheming** [comment]
黃色的提示可以忽略，我看你的評論功能都是正常的，關閉這個 issue 了。
