### ISSUE TITLE
[Bug]: 在Vercel部署后注册账号会报错

### ISSUE THREAD

**Issue by AkariLiu** [walinejs/waline#912]
### 问题描述 | Describe the bug

通过新用户注册入口注册没响应，Github登录提示“504 Gateway_Timeout”。
![image](https://user-images.githubusercontent.com/58081491/162620651-d06438ae-7966-4c37-bfc2-56f2bc06dfb4.png)

之后我在网络上搜索注意到Vercel对免费用户是有限制的，如下：
![image](https://user-images.githubusercontent.com/58081491/162620696-67dd8b0d-1814-48dc-8040-9f4ff122f1f2.png)
> PS：这个中文不是官方的，是我使用Microsoft Edge自带的翻译工具。

Vercel环境变量配置如下：
![image](https://user-images.githubusercontent.com/58081491/162620960-e75f9f15-9538-4180-94ee-778eaeb52c3c.png)
----
![image](https://user-images.githubusercontent.com/58081491/162621008-942f3d6b-0326-4699-9bd4-03752656fa9f.png)
> PS：为了保障自己的隐私安全，会对敏感部分进行打码，敬请谅解！

### 问题网站 | Website URL

https://comment.akariliu.vercel.app

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

SQLite

**Comment by lizheming** [comment]
Vercel 不支持持久化存储，不能使用 SQLite 存储服务，可以换成其它存储服务。
