### ISSUE TITLE
[Bug]: waline不能用GitHub登录

### ISSUE THREAD

**Issue by weaving-dreams** [walinejs/waline#922]
### 问题描述 | Describe the bug

我用腾讯云部署的waline评论区不能用GitHub登录
![1](https://user-images.githubusercontent.com/100774247/162877245-ecb72e35-262d-40bd-a4e4-b5f02f396465.png)

### 问题网站 | Website URL

https://weaving-dreams.github.io/

### 服务部署在哪里？ | Where your waline deploy?

CloudBase

### 数据存储在哪里？| Where your comment data store?

CloudBase

**Comment by lizheming** [comment]
你增加一个 `/` 子路径的解析应该就可以了

![image](https://user-images.githubusercontent.com/424491/163220374-3eadc9f5-cdaf-4089-ba43-ebcb150b6d23.png)
