### ISSUE TITLE
[Feature]: 对更复杂的 dark theme 的支持

### ISSUE THREAD

**Issue by NichtsHsu** [walinejs/waline#934]
### 功能概述 | Describe the feature

目前 Waline 支持两种独立的 dark theme 模式，一种是 auto，会在 head 的最后添加：

```html
<style>@media (prefers-color-scheme: dark) { WALINE_CSS }</style>
```

一种是用户自定义 selector，例如 `html[data-theme="dark"]`, 会在 head 最后添加：

```html
<style>html[data-theme="dark"] { WALINE_CSS }</style>
```

有部分博客模板支持更为复杂的 dark theme 模式：如果使用者不设置主题样式，则会根据设备主题自适应；如果使用者设置了 theme，则使用所设置的 theme。也就是说存在三种状态，当 `html:not(data-theme)` 时，根据 `prefers-color-scheme` 决定 light 还是 dark，当 `html[data-theme="light"]` 或 `html[data-theme="dark"]` 时选择对应的 theme。

Waline 仅靠 selector 无法适配这类模式，我这边只能通过 js 强行将 `document.getElementsByTagName("head")[0].lastChild` 复制为两个 style，一个设置为 `@media (prefers-color-scheme: dark) { html:not(data-theme) { WALINE_CSS  }}` 一个设置为 `html[data-theme="dark"] { WALINE_CSS }`。

**Comment by Mister-Hope** [comment]
这是主题的适配工作，根据你的描述，我不认为这是一个很好的设计思路。

你可以参考一下vuepress默认主题或者我开发的vuepress-theme-hope来看一下它们的逻辑。

如果你说的使用者指的是博主，那么这个模板应该只注入所需样式，而不是另外两个从来不会使用的样式。

如果你说的使用者是访问者，那我也想不到既然已经需要用js去写data-theme，为什么不在自动的时候也做判断去写而是直接把这个属性拿掉，两段样式可以搞定非得要用三段样式。

总之我认为，并没有一个很强的理由，必须增加一个奇怪的auto选择器或者甚至同时添加light dark auto选择器。所以我的倾向是不予支持。

当然不是我一个人的项目，你可以听听@lizheming 怎么说。

**Comment by lizheming** [comment]
`@media (prefers-color-scheme: dark) { html:not(data-theme) { WALINE_CSS }}` 我似乎没有看太明白为什么会有这种情况，因为你说「如果使用者不设置主题样式，则会根据设备主题自适应」，那此时应该就没有 `html[data-theme]` 的场景我理解，所以 `html:not(data-theme)` 我理解其实就没有必要。

所以还是两种情况 `@media (prefers-color-scheme: dark) { html { WALINE_CSS } }` 和 `html[data-theme="dark"] { WALINE_CSS }`，这应该是可以通过配置解决的。

由于主题的暗黑模式 Selector 各异，所以单纯靠 Waline 本身就能完美契合主题是不太可能的。所以我们期望是不同的场景可以通过配置支持。目前你的场景，可以在主题切换的时候通过切换配置来实现的。

1. 当系统跟随的时候设置 `dark=auto`
2. 当用户手动设置的时候配置 `dark=html[data-theme]`

**Comment by Mister-Hope** [comment]
或者直白点说，css侧只有浅色和深色主题，浅色深色自动三种模式只是逻辑上的，应该在js侧控制而不是直接把三种形式丢到css里去。
