### ISSUE TITLE
Example 里面提供的前端页面只是用来做测试使用的，目前暂时不支持配置

### ISSUE THREAD

**Issue by elkan1788** [walinejs/waline#938]
Example 里面提供的前端页面只是用来做测试使用的，目前暂时不支持配置

_Originally posted by @lizheming in https://github.com/walinejs/waline/discussions/930#discussioncomment-2589423_

**Comment by lizheming** [comment]
你是什么需求需要支持 Example 的前端示例支持配置？

**Comment by elkan1788** [comment]
> 你是什么需求需要支持 Example 的前端示例支持配置？

考虑到 LeanCloud 的空间占用问题，现 Waline 默认的图片上传采用的是 Base64 码 字节占用太大，所以想在 Example 中也支持关闭图片上传，避免一些可能的恶意测试发生，谢谢。

**Comment by lizheming** [comment]
直接把 `/` 指向 404 吧，参考 https://github.com/walinejs/waline/issues/858

**Comment by elkan1788** [comment]
> 直接把 `/` 指向 404 吧，参考 #858

感觉重定向的做法似乎不能解决，另外这样重定向配置，不会影响服务端功能的正常使用吗？

**Comment by lizheming** [comment]
页面都看不到了，为啥解决不了。如果要在服务端处理，可以自己在 `preSave()` 钩子里写逻辑处理。重定向是严格路径匹配的，不会影响。
