### ISSUE TITLE
[Bug]: InsertedAt  does not exist问题再现

### ISSUE THREAD

**Issue by ZvonimirSun** [walinejs/waline#939]
### 问题描述 | Describe the bug

<img width="592" alt="image" src="https://user-images.githubusercontent.com/22871764/163948706-61749266-16bc-4e02-a16b-b31da4328f40.png">

### 问题网站 | Website URL

https://wl.iszy.xyz/

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

PostgreSQL

**Comment by ZvonimirSun** [comment]
退回 sha256:af6dcef2f7d93130f3a84156801cfed5750963ed196e8ef7b7ecce75aee02efe 版本后，恢复正常。也就是上一次构建

**Comment by IssacsChien** [comment]
我也遇到了
