### ISSUE TITLE
[Bug]: 首页所有文章的阅读统计无法获取

### ISSUE THREAD

**Issue by YiHui-Liu** [walinejs/waline#956]
### 问题描述 | Describe the bug

首页无法获取当前所有文章的阅读次数，V1是可以的

### 问题网站 | Website URL

https://foolishfox.cn/

### 服务部署在哪里？ | Where your waline deploy?

Other

### 数据存储在哪里？| Where your comment data store?

MySQL

**Comment by YiHui-Liu** [comment]
首页的`el`已经设置为`null`

**Comment by Mister-Hope** [comment]
我看你自己似乎已经修了?

**Comment by Mister-Hope** [comment]
而且现在新版 api，你可以在 visitor 选项里传入自己需要的选择器。

我看没什么问题，我就直接关了。

**Comment by YiHui-Liu** [comment]
> 

原本的老CDN是没问题的，但是版本是`1.x.x`；我目前显示的不是单篇文章的统计，而是`/`路径的统计

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/164985176-da5f8b3b-11b5-4fd9-8a8f-27bc6cb23ede.png)

把上面的id挪到选择器那里，或者在选择器加 data-path

**Comment by Mister-Hope** [comment]
我个人认为data-path应该就行了，选择器是可能因主题异的，但如果你需要显示其他页面的数量，你是一定要进行额外操作去指定哪个路径的，这个时候你直接按照预设定位成data-path即可。我暂时没有体会到自定义它的需求在哪。
