### ISSUE TITLE
[Bug]: 使用 hexo next 插件无法实现客户端从 v1.6.0 迁移到 v2

### ISSUE THREAD

**Issue by leirock** [walinejs/waline#963]
### 问题描述 | Describe the bug

使用 Waline 的 [Hexo Next 插件](https://www.npmjs.com/package/@waline/hexo-next)，设置中引入 jsdelivr 的 v1.6.0 [waline.min.js](https://cdn.jsdelivr.net/npm/@waline/client@1.6.0/dist/Waline.min.js)，可以正常显示。

但是引入 v2 版本的 [waline.min.js](https://cdn.jsdelivr.net/npm/@waline/client@2.0.2/dist/waline.min.js) 后，浏览器报错

```
Unhandled Promise Rejection: TypeError: Object is not a constructor (evaluating 'new Waline(CONFIG.waline)')
```

版本：Hexo v5.4.2, NexT v8.11.0

Hexo 的设置如下：

```
# Waline
# For more information: https://waline.js.org
waline:
  enable: true
  libUrl: https://cdn.jsdelivr.net/npm/@waline/client@2.0.2/dist/waline.min.js
  serverURL: https://cmt.pinlyu.com # Waline server address url
  login: disable
  meta: [nick, mail, link] # Custom comment header
  requiredMeta: [nick, mail] # Set required fields: [nick] | [nick, mail]
  pageSize: 5 # Pagination size
  visitor: false # Article reading statistic
  comment_count: true  # If false, comment count will only be displayed in post page, not in home page
  copyright: false
  dark: auto
  emoji:  [
    #'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/weibo',
    #'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/bilibili',
    #'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/tw-emoji',
    #'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/qq',
  ]
  locale:
    placeholder: 在这里分享你的想法！评论通过审核才会显示，回复通过邮件提醒，评论规范详见《网站政策》。 # Comment box placeholder
    admin: 站长
    nick: 昵称*
    mail: 邮箱*
    link: 网址
```

### 问题网站 | Website URL

https://pinlyu.com/guestbook/  （未部署v2的客户端）

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

SQLite

**Comment by lizheming** [comment]
可以先配置 `libUrl=https://cdn.jsdelivr.net/npm/@waline/client@1/dist/Waline.min.js` 保证下功能正常，晚些时间我再看一下这个问题。

**Comment by Mister-Hope** [comment]
配置 libUrl=https://cdn.jsdelivr.net/npm/@waline/client 应该也是可以的

**Comment by leirock** [comment]
> 可以先配置 `libUrl=https://cdn.jsdelivr.net/npm/@waline/client@1/dist/Waline.min.js` 保证下功能正常，晚些时间我再看一下这个问题。

目前配置的 v1 版本是正常的，我就是测试一下能否正常升级到 v2。目前看插件这块适配还是有点问题的，我在 PR 那里也提供了测试的情况。

**Comment by leirock** [comment]
> 配置 libUrl=https://cdn.jsdelivr.net/npm/@waline/client 应该也是可以的

如果只配置这个，评论可以正常加载，但是无论是主页还是文章页 post-meta 都不能加载评论统计数字（阅读统计没有测试），但是评论区可以统计评论数。浏览器对此没有特别的报错提示。
