### ISSUE TITLE
[Bug]: 2.0.3 遇到一些问题

### ISSUE THREAD

**Issue by jerryc127** [walinejs/waline#970]
### 问题描述 | Describe the bug

2.0.3 评论能显示 但是一直在发起 emoji fetch
![YV2_1`_CWW_5LD`249%5FLH](https://user-images.githubusercontent.com/16351105/165503669-8cf2dc74-e0a9-48c1-b83f-b68acc6d5564.png)

我有一个 messageboard 页面 直接显示跨域问题 评论没显示
![9F1BMD2O0OWOQUL@P_P@GH](https://user-images.githubusercontent.com/16351105/165503702-810ca84c-0731-4455-8c43-da001344cd95.png)

看dev tool的网络 一直fetch info.json
![image](https://user-images.githubusercontent.com/16351105/165503807-cf970c0f-0e52-4d2b-922c-ae66a03e121a.png)

### 问题网站 | Website URL

https://btftest.vercel.app/messageboard

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by Mister-Hope** [comment]
今天晚些时候搞，正在挣扎 https://github.com/vuepress-theme-hope/vuepress-theme-hope/pull/1717

**Comment by appotry** [comment]
![](https://s2.loli.net/2022/04/27/Wy2bqsT6GFgaPX3.png)
不知道是不是同一个bug 填写了4个 emoji cdn，变成这样，有3个emoji edn失败

```
emoji: [ 
        'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/weibo',
        'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/bilibili',
        'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/qq',
        'https://cdn.jsdelivr.net/gh/walinejs/emojis@1.0.0/tieba',
      ],
```
