### ISSUE TITLE
[Bug]: 一个页面获取不到评论

### ISSUE THREAD

**Issue by jerryc127** [walinejs/waline#972]
### 问题描述 | Describe the bug

网站的一个页面本地测试获取不到评论 ( 可以评论）
报错为
![image](https://user-images.githubusercontent.com/16351105/165769871-ce93baf8-0653-4ff0-8c29-ac9ee42c46ed.png)

但是其他页面正常
评论数 最新评论都能获取到数据

### 问题网站 | Website URL

https://btftest.vercel.app/messageboard/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by lizheming** [comment]
看起来应该是评论比较多超时了，大概有多少条评论知道吗？

**Comment by jerryc127** [comment]
> 看起来应该是评论比较多超时了，大概有多少条评论知道吗？

3971

**Comment by Mister-Hope** [comment]
评论太多的话，个人建议是把服务端和数据库放在一起

**Comment by jerryc127** [comment]
我好像记得 1 系列好像能正常显示

**Comment by Mister-Hope** [comment]
兄弟，这东西跟前端版本一点关系都没有，啥版本也是相同的参数请求服务器。服务器自己超时跟前段有什么关系.....

**Comment by lizheming** [comment]
`@waline/vercel@1.13.6` 可以再试一下。

之前因为一次评论数据获取中有多次数据库异步请求，考虑到大部分评论都比较少这种请求有点划不来所以做了优化，每次都获取所有的评论，这样只需要一次请求就能完成。但是因为 LeanCloud 的限制，一次最多返回 100 条数据，超过这个数据的话需要再继续请求获取。当数据量大的情况，使用这种优化获取全部评论反而是得不偿失了，所以会造成你的这种超时的现象。
