### ISSUE TITLE
[Bug]: 表情包加载错误

### ISSUE THREAD

**Issue by leirock** [walinejs/waline#976]
### 问题描述 | Describe the bug

**1. 设置表情包**

```yml
  emoji:
    - //unpkg.com/@waline/emojis@1.0.1/weibo/info.json
    - //unpkg.com/@waline/emojis@1.0.1/bilibili/info.json
 ```

实际加载情况：

清除缓存后刷新，无法加载表情包
<img width="805" alt="image" src="https://user-images.githubusercontent.com/19180725/165939696-6ce92306-d717-44dc-a82a-980a11293662.png">

**2. 设置表情包**

```yml
  emoji:
    - //unpkg.com/@waline/emojis@1.0.1/weibo/
    - //unpkg.com/@waline/emojis@1.0.1/bilibili/
 ```

实际加载情况：

清除缓存后刷新，重复加载表情包（更新客户端版本到 2.0.6 后已经不再加载 jsdelivr）
<img width="569" alt="iShot_2022-04-29_19 53 54" src="https://user-images.githubusercontent.com/19180725/165939854-e16b6a97-016f-4d35-8134-5dbd3fcd2c93.png">
<img width="751" alt="iShot_2022-04-29_19 54 05" src="https://user-images.githubusercontent.com/19180725/165939868-61bbcbbf-ae7a-486e-bfd6-09cf1b8d5ea8.png">

版本：
- hexo-next 插件 v3.0.0-rc.1
- 客户端 v2.0.6
```yml
  libUrl: https://unpkg.com/@waline/client@2.0.6/dist/waline.js
  cssUrl: https://unpkg.com/@waline/client@2.0.6/dist/waline.css
```

### 问题网站 | Website URL

https://leirock.github.io/blog/about/  （设置的表情包是第一种情况，源码见 https://github.com/leirock/blog ）

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

SQLite

**Comment by leirock** [comment]
@Mister-Hope 另外再来一个 feature request。

我希望关闭表情包的使用，直接隐藏掉，所以设置了 `emoji: []` 以及 CSS `.wl-action[title="表情"] { display:none }`。

 但是这样仍然会加载插件里默认（`default.yaml`）的表情包路径（报错同上述情况一），设置 `emoji: [""]` 也不行。

见 https://pinlyu.com/guestbook/

**Comment by tufu9441** [comment]
我似乎也遇到了同样的问题，从无痕浏览窗口第一次开启网页时能正常加载不同表情，刷新一下之后便会显示三组重复的。我也是删除了最后的info.json，不然实际加载链接会多出一个/info.json。

**Comment by Mister-Hope** [comment]
Will fix this very soon.

**Comment by Mister-Hope** [comment]
Fixed in 2.0.7
