### ISSUE TITLE
[Bug]: 在个人档案页面绑定Github账号时出404错误

### ISSUE THREAD

**Issue by Neal0408** [walinejs/waline#978]
### 问题描述 | Describe the bug

在评论系统点进头像进到个人档案页面
<img width="288" alt="image" src="https://user-images.githubusercontent.com/37592164/166087740-e679cf58-c07d-4479-abff-94e280dfc3b4.png">
之后想要绑定Github账号，Github授权结束后跳转到了
<img width="427" alt="image" src="https://user-images.githubusercontent.com/37592164/166087757-2ec1957e-bdb1-4867-a85d-55272fa8f27f.png">
显示```
{"errno":404,"errmsg":"url `/o/oauth` not found."}```。我这边是刚给博客添加的waline，不知道是因为什么原因导致的。
好像是oauth认证相关的东西，然后在自己Github授权界面确认了一下waline的授权，发现也是正常授权的。
<img width="348" alt="image" src="https://user-images.githubusercontent.com/37592164/166087836-d69e77f1-f36e-4725-a8c7-3226694ca54f.png">

### 问题网站 | Website URL

https://warmwinter.ml

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

GitHub

**Comment by lizheming** [comment]
可以先设置 `SERVER_URL` 环境变量为 `https://blog-waline-eight.vercel.app` 规避一下，之后我看一下
