### ISSUE TITLE
[Feature]: 能不能弄个评论置顶的功能

### ISSUE THREAD

**Issue by holmofy** [walinejs/waline#979]
### 功能概述 | Describe the feature

能不能弄个类似于bilibili中评论置顶的功能，有一些优质的评论，期望能让更多人看到
<img width="982" alt="image" src="https://user-images.githubusercontent.com/19494806/166147296-c0cb1c60-c3e3-4456-94bd-a310696da52c.png">

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/166147791-8063c4cd-2198-49a5-b75d-957e92fe85ac.png)

请你告诉我这是什么？
