### ISSUE TITLE
添加一个IP归属地显示

### ISSUE THREAD

**Issue by qystudio0** [walinejs/waline#989]
### 功能概述 | Describe the feature

由于国家出台了神奇的规定，我们有木有必要跟风添加一个呢

**Comment by lizheming** [comment]
已增加，可以更新到 `@waline/vercel@1.16.0`, `@waline/client@2.2.0` 体验一下，默认开启，不想使用的话可以使用 `DISABLE_REGION` 关闭。

**Comment by ma-wenqian** [comment]
想问一下，为什么我开启了还是不显示ip位置呀

**Comment by lizheming** [comment]
@ma-wenqian 有添加 `DISABLE_REGION` 么，这个是关闭 IP 归属地的功能的开关，配置了会不展示

**Comment by lizheming** [comment]
@ma-wenqian 去掉应该就有了

**Comment by iDvel** [comment]
@lizheming 请问如何正确地关闭这个功能呢？
我在 Vercel 中添加环境变量 `DISABLE_REGION`，然后重新部署应该就可以了吧。
试过留空或者写上 `true`，好像都不行，还是显示 IP 归属地。

**Comment by iDvel** [comment]
> @lizheming 请问如何正确地关闭这个功能呢？ 我在 Vercel 中添加环境变量 `DISABLE_REGION`，然后重新部署应该就可以了吧。 试过留空或者写上 `true`，好像都不行，还是显示 IP 归属地。

呃，我知道啦，管理员默认就是显示的，不登录、隐私窗口或换个浏览器是正常的。
