### ISSUE TITLE
[Bug]: `AVATAR_PROXY` 设置后前端崩溃

### ISSUE THREAD

**Issue by edgexyz** [walinejs/waline#990]
### 问题描述 | Describe the bug

因为 `workers.dev` 域名国内存在间歇性 sni 阻断的情况，我打算利用自己的域名 `libravatar.icesh.me` 对项目组提供的 `avatar.75cdn.workers.dev` 进行反代。

反代域名测试成功，但是在 Vercel 上设置 environment variable `AVATAR_PROXY` 后 deploy log 显示成功，deployment error log 报错 `undefined	ERROR	TypeError: Cannot read property 'split' of undefined`，删除 `AVATAR_PROXY` 后恢复正常

### 问题网站 | Website URL

comments.icesh.me

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by edgexyz** [comment]
看了一下源码，怀疑是 [config.js](https://github.com/walinejs/waline/blob/14d31e01bb7116b3bd927ecb432270cd9b5d93ac/packages/server/src/config/config.js) 里没有将 `AVATAR_PROXY` 用单引号包裹起来？

```
let avatarProxy = 'https://avatar.75cdn.workers.dev/';
if (AVATAR_PROXY) {
  avatarProxy = !isFalse(AVATAR_PROXY) ? AVATAR_PROXY : '';
}
```

**Comment by edgexyz** [comment]
vercel environment variable 设置为：
`NAME: AVATAR_PROXY`
VALUE 设置为带单引号 `'libravatar.icesh.me'` 和不带的形式均构建失败

**Comment by lizheming** [comment]
@edgexyz 剛才有個發版有點小問題，剛發了 1.15.1 的版本你更新下在看一下。另外 `AVATAR_PROXY` 需要帶 `https://` 前綴

**Comment by edgexyz** [comment]
问题解决了，非常感谢。
