### ISSUE TITLE
[Bug]: 配置emoji后，默认的unpkg的weibo emoji仍然会出现

### ISSUE THREAD

**Issue by tyadan** [walinejs/waline#995]
### 问题描述 | Describe the bug

在配置项目里面配置好emoji后，默认的unpkg的weibo emoji仍然会出现，例如我当前的状态，配置了自己的weibo，然后客户端展示了两个weibo的emoji
![telegram-cloud-photo-size-5-6310078403126080662-y](https://user-images.githubusercontent.com/13864360/166632620-1ab2702d-a4b7-4bec-9f8a-b6e006663b99.jpg)
![telegram-cloud-photo-size-5-6310078403126080663-y](https://user-images.githubusercontent.com/13864360/166632632-7c31d91f-eebc-4a54-9a5f-40f3e1d88a4d.jpg)

### 问题网站 | Website URL

https://jayshao.com/use-waline-system/

### 服务部署在哪里？ | Where your waline deploy?

Docker

### 数据存储在哪里？| Where your comment data store?

MySQL

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/166633632-09176b19-3b29-460b-bc13-9242cd6059c0.png)

可能是 next 合并配置的时候实际处理和我想的不大一样。

**Comment by Mister-Hope** [comment]
你使用3.0.1 看看。
