### ISSUE TITLE
继https://github.com/walinejs/waline/commit/bd43fc5343aa241f44b21f0a1faf9fdab0a43f37

### ISSUE THREAD

**Issue by Fgaoxing** [walinejs/waline#998]
### 问题描述 | Describe the bug

见https://github.com/walinejs/waline/commit/bd43fc5343aa241f44b21f0a1faf9fdab0a43f37

### 问题网站 | Website URL

https://waline.yt-blog.top/ui/

### 服务部署在哪里？ | Where your waline deploy?

Vercel (Default)

### 数据存储在哪里？| Where your comment data store?

LeanCloud(https://leancloud.app)

**Comment by Fgaoxing** [comment]
@lizheming

**Comment by lizheming** [comment]
已确认更新到最新版不会有问题

**Comment by Fgaoxing** [comment]
@lizheming 怎么更新?

**Comment by lizheming** [comment]
@Fgaoxing https://github.com/walinejs/waline/commit/bd43fc5343aa241f44b21f0a1faf9fdab0a43f37#commitcomment-72845071
